// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AppendErrorInput struct {
	CardID     *string  `json:"cardId,omitempty"`
	Expected   string   `json:"expected"`
	Transcript string   `json:"transcript"`
	Wrong      []string `json:"wrong"`
}

type AppendErrorPayload struct {
	Ok    bool        `json:"ok"`
	Entry *ErrorEntry `json:"entry,omitempty"`
	Error *UserError  `json:"error,omitempty"`
}

type AppendThieuPayload struct {
	Ok      bool          `json:"ok"`
	Session *ThieuSession `json:"session,omitempty"`
	Error   *UserError    `json:"error,omitempty"`
}

type Bookmark struct {
	ID string `json:"id"`
	// Khoá định danh cho sync — mọi type khác cũng có, client dùng để nhận ra row đã có trên máy peer.
	GUID  string `json:"guid"`
	Title string `json:"title"`
	// null = bookmark không có link (ghi chú tự nhớ chẳng có link nào). Xoá link dùng `clearUrl` chứ không gửi chuỗi rỗng.
	URL  *string `json:"url,omitempty"`
	Note string  `json:"note"`
	// Tag dạng CSV thô như lưu trong DB. Dùng `tagList` nếu cần mảng đã tách.
	Tags string `json:"tags"`
	// Tag đã tách thành mảng. Rỗng khi cột rỗng (không phải [""]); luôn hạ chữ thường + trim.
	TagList   []string       `json:"tagList"`
	Status    BookmarkStatus `json:"status"`
	CreatedAt string         `json:"createdAt"`
	UpdatedAt string         `json:"updatedAt"`
}

type BookmarkInput struct {
	Title string  `json:"title"`
	URL   *string `json:"url,omitempty"`
	Note  *string `json:"note,omitempty"`
	// Tag: trim + hạ chữ thường + bỏ trùng, tối đa 10 tag × 40 ký tự. Tag chứa dấu phẩy bị từ chối (dấu phẩy là ký tự phân cách của cột CSV).
	Tags []string `json:"tags,omitempty"`
	// null = TO_READ.
	Status *BookmarkStatus `json:"status,omitempty"`
}

// PATCH. `url` rỗng KHÔNG phải "xoá link" — dùng `clearUrl`, vì `url: String` không phân biệt được absent với null.
type BookmarkPatch struct {
	Title    *string  `json:"title,omitempty"`
	URL      *string  `json:"url,omitempty"`
	Note     *string  `json:"note,omitempty"`
	Tags     []string `json:"tags,omitempty"`
	ClearURL *bool    `json:"clearUrl,omitempty"`
}

type Card struct {
	ID     string `json:"id"`
	GUID   string `json:"guid"`
	DeckID string `json:"deckId"`
	Front  string `json:"front"`
	Back   string `json:"back"`
	Pinyin string `json:"pinyin"`
	// Hết hạn ôn, RFC3339. Thẻ chưa từng ôn có state = NEW nên vẫn vào hàng đợi dù due_at ở tương lai.
	DueAt      string  `json:"dueAt"`
	Stability  float64 `json:"stability"`
	Difficulty float64 `json:"difficulty"`
	Reps       int     `json:"reps"`
	Lapses     int     `json:"lapses"`
	// NEW | LEARNING | REVIEW — suy ra từ reps/lapses, KHÔNG chỉnh sửa tay được.
	State     string `json:"state"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	// Thanh điệu đã chấm (nội dung "ni3" → "ní"), null = chưa chấm.
	Tone     *string `json:"tone,omitempty"`
	Ipa      *string `json:"ipa,omitempty"`
	Stress   *string `json:"stress,omitempty"`
	AudioURL *string `json:"audioURL,omitempty"`
}

// Số lần sai của 1 thẻ + mặt trước/sau để client hiện gợi ý ôn lại mà không phải gọi thêm 1 query.
type CardErrorCount struct {
	CardID string `json:"cardId"`
	Front  string `json:"front"`
	Back   string `json:"back"`
	Errors int    `json:"errors"`
}

type CardInput struct {
	Front  string `json:"front"`
	Back   string `json:"back"`
	Pinyin string `json:"pinyin"`
}

// PATCH phân biệt "không gửi field" với "gửi giá trị đó".
type CardPatch struct {
	Front  *string `json:"front,omitempty"`
	Back   *string `json:"back,omitempty"`
	Pinyin *string `json:"pinyin,omitempty"`
}

// 1 từ của câu đã tách. Quy tắc cố ý đơn giản: KHÔNG phân giải từ đa nghĩa hay ngữ cảnh cụm từ (xem `domain/content.SplitChunks`).
type Chunk struct {
	Text string    `json:"text"`
	Kind ChunkKind `json:"kind"`
}

type ChunkPayload struct {
	Ok     bool       `json:"ok"`
	Chunks []Chunk    `json:"chunks"`
	Error  *UserError `json:"error,omitempty"`
}

// 1 dòng log xung đột. Merge đã TỰ chọn người thắng — UI chỉ XEM, không có nút resolve tay vì sửa tay sẽ phá hội tụ 2 máy.
type Conflict struct {
	GUID       string `json:"guid"`
	Table      string `json:"table"`
	Field      string `json:"field"`
	Local      string `json:"local"`
	Incoming   string `json:"incoming"`
	Winner     string `json:"winner"`
	Detail     string `json:"detail"`
	ResolvedAt string `json:"resolvedAt"`
}

type CreateBookmarkPayload struct {
	Ok       bool       `json:"ok"`
	Bookmark *Bookmark  `json:"bookmark,omitempty"`
	Error    *UserError `json:"error,omitempty"`
}

type CreateCardPayload struct {
	Ok    bool       `json:"ok"`
	Card  *Card      `json:"card,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type CreateDeckPayload struct {
	Ok    bool       `json:"ok"`
	Deck  *Deck      `json:"deck,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type CreateMilestonePayload struct {
	Ok        bool       `json:"ok"`
	Milestone *Milestone `json:"milestone,omitempty"`
	Error     *UserError `json:"error,omitempty"`
}

type CreatePathPayload struct {
	Ok    bool       `json:"ok"`
	Path  *Path      `json:"path,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type CreateResourcePayload struct {
	Ok       bool       `json:"ok"`
	Resource *Resource  `json:"resource,omitempty"`
	Error    *UserError `json:"error,omitempty"`
}

type CreateStagePayload struct {
	Ok    bool       `json:"ok"`
	Stage *Stage     `json:"stage,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type CreateTopicPayload struct {
	Ok    bool       `json:"ok"`
	Topic *Topic     `json:"topic,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type Deck struct {
	ID        string `json:"id"`
	GUID      string `json:"guid"`
	Name      string `json:"name"`
	Lang      string `json:"lang"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

// Thông tin deck rút gọn cho nút "vào /review" — cần TÊN thật, không phải id.
type DeckRef struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Lang string `json:"lang"`
}

type DeleteBookmarkPayload struct {
	Ok    bool       `json:"ok"`
	Error *UserError `json:"error,omitempty"`
}

type DeleteCardPayload struct {
	Ok    bool       `json:"ok"`
	Error *UserError `json:"error,omitempty"`
}

type DeleteDeckPayload struct {
	Ok    bool       `json:"ok"`
	Error *UserError `json:"error,omitempty"`
}

type DeleteMilestonePayload struct {
	Ok    bool       `json:"ok"`
	Error *UserError `json:"error,omitempty"`
}

type DeletePathPayload struct {
	Ok    bool       `json:"ok"`
	Error *UserError `json:"error,omitempty"`
}

type DeleteResourcePayload struct {
	Ok    bool       `json:"ok"`
	Error *UserError `json:"error,omitempty"`
}

type DeleteStagePayload struct {
	Ok    bool       `json:"ok"`
	Error *UserError `json:"error,omitempty"`
}

type DeleteTopicPayload struct {
	Ok    bool       `json:"ok"`
	Error *UserError `json:"error,omitempty"`
}

type DictEntry struct {
	Hanzi  string `json:"hanzi"`
	Pinyin string `json:"pinyin"`
	Nghia  string `json:"nghia"`
}

type DictEntryInput struct {
	Hanzi  string `json:"hanzi"`
	Pinyin string `json:"pinyin"`
	Nghia  string `json:"nghia"`
}

type DiffInput struct {
	Sample     string `json:"sample"`
	Transcript string `json:"transcript"`
}

type DiffPayload struct {
	Ok     bool        `json:"ok"`
	Result *DiffResult `json:"result,omitempty"`
	Error  *UserError  `json:"error,omitempty"`
}

// Kết quả chấm 1 lần ghi âm.
type DiffResult struct {
	// Bản ĐÃ chuẩn hoá phồn→giản, đúng bằng thứ đã so. Không chuẩn hoá thì Whisper trả 學習 còn deck mẫu dùng 学习 → chấm sai oan dù đọc đúng.
	Transcript string      `json:"transcript"`
	Diff       []DiffToken `json:"diff"`
	Wrong      []string    `json:"wrong"`
	Score      float64     `json:"score"`
}

// 1 từ sau khi so transcript với câu mẫu. Cặp thiếu+thừa liền kề được gộp thành `WRONG` với text dạng "the→a" (đọc dễ hơn 2 mảnh rời).
type DiffToken struct {
	Text   string     `json:"text"`
	Status WordStatus `json:"status"`
}

type EnglishEntry struct {
	Lang    string `json:"lang"`
	Term    string `json:"term"`
	Reading string `json:"reading"`
	Gloss   string `json:"gloss"`
}

// Báo cáo seed tiếng Anh (3 số, giữ nguyên v1).
type EnglishSeedResult struct {
	EnDict     int `json:"enDict"`
	PvoAdded   int `json:"pvoAdded"`
	TmrndAdded int `json:"tmrndAdded"`
}

type ErrorEntry struct {
	ID string `json:"id"`
	// null = lỗi luyện tự do, không gắn thẻ.
	CardID     *string  `json:"cardId,omitempty"`
	Expected   string   `json:"expected"`
	Transcript string   `json:"transcript"`
	Wrong      []string `json:"wrong"`
	CreatedAt  string   `json:"createdAt"`
}

type GradeTonePayload struct {
	Ok    bool       `json:"ok"`
	Grade *ToneGrade `json:"grade,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type ImportHSKInput struct {
	// Mặc định HSK1 (giữ hành vi v1).
	Level *string `json:"level,omitempty"`
	// Rỗng = trùng `level`. Deck KHÁC level bị từ chối 400: khoá hợp nhất là (deck_id, front), đổi tên deck cho cùng 1 level sẽ nhân đôi mọi thẻ khi merge.
	Deck *string `json:"deck,omitempty"`
}

type ImportHSKPayload struct {
	Ok     bool          `json:"ok"`
	Result *ImportResult `json:"result,omitempty"`
	Error  *UserError    `json:"error,omitempty"`
}

// Báo cáo import HSK — 5 trường giữ nguyên như endpoint v1.
type ImportResult struct {
	DeckID     string `json:"deckId"`
	Deck       string `json:"deck"`
	Level      string `json:"level"`
	CardsAdded int    `json:"cardsAdded"`
	CardsTotal int    `json:"cardsTotal"`
	DictAdded  int    `json:"dictAdded"`
}

// Toạ độ node trên canvas bản đồ.
type MapPoint struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type MarkErrorResolvedPayload struct {
	Ok bool `json:"ok"`
	// ID của note đánh dấu mới (sổ lỗi append-only, không xoá note gốc).
	NoteID string     `json:"noteId"`
	Error  *UserError `json:"error,omitempty"`
}

type MergeResult struct {
	Ok        bool       `json:"ok"`
	Merged    *Merged    `json:"merged"`
	Conflicts []Conflict `json:"conflicts"`
	// Cảnh báo KHÔNG chặn merge (clock skew). Chỉ cảnh báo, không tự sửa giờ — sửa giờ máy là việc của user.
	Warnings   []string   `json:"warnings"`
	LastSyncAt string     `json:"lastSyncAt"`
	Error      *UserError `json:"error,omitempty"`
}

// Số lượng row đã ghi theo bảng. `decks`/`cards` chỉ kể row thật sự ghi — insert bị Postgres bỏ vì UNIQUE được tính vào `conflicts`, KHÔNG vào đây (xem `application/sync` `addSkipped`).
type Merged struct {
	Decks             int `json:"decks"`
	Cards             int `json:"cards"`
	Reviews           int `json:"reviews"`
	Notes             int `json:"notes"`
	RoadmapPaths      int `json:"roadmapPaths"`
	RoadmapStages     int `json:"roadmapStages"`
	RoadmapMilestones int `json:"roadmapMilestones"`
	RoadmapTopics     int `json:"roadmapTopics"`
	RoadmapResources  int `json:"roadmapResources"`
	RoadmapBookmarks  int `json:"roadmapBookmarks"`
}

type Milestone struct {
	ID        string `json:"id"`
	GUID      string `json:"guid"`
	StageID   string `json:"stageId"`
	Text      string `json:"text"`
	Position  int    `json:"position"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type MilestoneInput struct {
	Text     string `json:"text"`
	Position *int   `json:"position,omitempty"`
}

type MilestonePatch struct {
	Text     *string `json:"text,omitempty"`
	Position *int    `json:"position,omitempty"`
}

type Mutation struct {
}

type PathInput struct {
	// [a-z0-9-], 1..64. Trùng → 409.
	Slug     string  `json:"slug"`
	Title    string  `json:"title"`
	Overview *string `json:"overview,omitempty"`
	// Rỗng = "zh". User tạo path thì nhận chuỗi tự do tối đa 16 ký tự (vd "vi").
	Language *string `json:"language,omitempty"`
}

// PATCH. Không có `slug`: slug là natural key của seed, đổi nó khiến seed tạo path trùng ở lần boot sau.
type PathPatch struct {
	Title    *string `json:"title,omitempty"`
	Overview *string `json:"overview,omitempty"`
	Language *string `json:"language,omitempty"`
}

type PathProgressPayload struct {
	Ok       bool       `json:"ok"`
	Progress *Progress  `json:"progress,omitempty"`
	Error    *UserError `json:"error,omitempty"`
}

// 1 dòng của list path, kèm tiến độ rút gọn (UI hiện "2/25 · 8%" ngay trong danh sách).
type PathSummary struct {
	Path    *Path            `json:"path"`
	Summary *ProgressSummary `json:"summary"`
}

// Tiến độ 1 path. `percent` CHỈ tính topic bắt buộc — node optional không nằm trong mẫu số (A1).
type Progress struct {
	Stages           int     `json:"stages"`
	TopicsTotal      int     `json:"topicsTotal"`
	TopicsRequired   int     `json:"topicsRequired"`
	TopicsOptional   int     `json:"topicsOptional"`
	TopicsDone       int     `json:"topicsDone"`
	TopicsInProgress int     `json:"topicsInProgress"`
	TopicsLocked     int     `json:"topicsLocked"`
	Percent          int     `json:"percent"`
	LastCompletedAt  *string `json:"lastCompletedAt,omitempty"`
	// Số node bắt buộc hoàn thành trong [since, now). 0 khi không truyền `since`.
	CompletedInRange int `json:"completedInRange"`
}

// Tiến độ roadmap trong 1 khoảng — nuôi biểu đồ tuần/tháng (A1).
type ProgressResult struct {
	// Mốc bắt đầu YYYY-MM-DD, chuẩn hoá từ đầu vào.
	Since string `json:"since"`
	// Số node `roadmap_topics` đang ở trạng thái xong tính từ `since`. KHÔNG phải "đã hoàn thành rồi bỏ sau" — cùng hệ nghĩa với `progress?since=`.
	Completed int `json:"completed"`
}

type ProgressResultPayload struct {
	Ok     bool            `json:"ok"`
	Result *ProgressResult `json:"result,omitempty"`
	Error  *UserError      `json:"error,omitempty"`
}

type ProgressSummary struct {
	Stages           int `json:"stages"`
	TopicsTotal      int `json:"topicsTotal"`
	TopicsRequired   int `json:"topicsRequired"`
	TopicsDone       int `json:"topicsDone"`
	TopicsInProgress int `json:"topicsInProgress"`
	Percent          int `json:"percent"`
}

type Query struct {
}

type ReaderArticle struct {
	ID     string `json:"id"`
	Level  string `json:"level"`
	Lang   string `json:"lang"`
	Title  string `json:"title"`
	Text   string `json:"text"`
	Source string `json:"source"`
}

type RecordReviewPayload struct {
	Ok     bool          `json:"ok"`
	Review *ReviewResult `json:"review,omitempty"`
	Error  *UserError    `json:"error,omitempty"`
}

type Resource struct {
	ID      string `json:"id"`
	GUID    string `json:"guid"`
	TopicID string `json:"topicId"`
	Title   string `json:"title"`
	// null = tài liệu không có link. Xoá link dùng `clearUrl` chứ không gửi chuỗi rỗng.
	URL       *string      `json:"url,omitempty"`
	Kind      ResourceKind `json:"kind"`
	Note      string       `json:"note"`
	Position  int          `json:"position"`
	CreatedAt string       `json:"createdAt"`
	UpdatedAt string       `json:"updatedAt"`
}

type ResourceInput struct {
	Title string  `json:"title"`
	URL   *string `json:"url,omitempty"`
	// Rỗng = tài liệu không phân loại. Ngoài whitelist 9 kind bị từ chối 400.
	Kind     *ResourceKind `json:"kind,omitempty"`
	Note     *string       `json:"note,omitempty"`
	Position *int          `json:"position,omitempty"`
}

// PATCH. URL rỗng KHÔNG phải "xoá link" — dùng `clearUrl`, vì `url: String` không phân biệt được absent với null.
type ResourcePatch struct {
	Title    *string       `json:"title,omitempty"`
	URL      *string       `json:"url,omitempty"`
	Kind     *ResourceKind `json:"kind,omitempty"`
	Note     *string       `json:"note,omitempty"`
	Position *int          `json:"position,omitempty"`
	ClearURL *bool         `json:"clearUrl,omitempty"`
}

type ReviewInput struct {
	CardID string `json:"cardId"`
	// Thang 1-4 đóng băng ở v1 (1 = Again, 4 = Good). 0 và 5 là khoảng trống thật, không nhận.
	Grade int `json:"grade"`
}

// Kết quả chấm điểm 1 thẻ — trả cho client để hiện "lần sau ôn sau 3 ngày" mà không tự tính lại.
type ReviewResult struct {
	CardID       string  `json:"cardId"`
	DueAt        string  `json:"dueAt"`
	IntervalDays int     `json:"intervalDays"`
	Stability    float64 `json:"stability"`
	Difficulty   float64 `json:"difficulty"`
	Reps         int     `json:"reps"`
	// true = lịch rơi về bảng fallback 1-3-7-14-30 vì reps < 3; false = đang dùng FSRS-lite.
	Fallback bool `json:"fallback"`
}

type SeedEnglishPayload struct {
	Ok     bool               `json:"ok"`
	Result *EnglishSeedResult `json:"result,omitempty"`
	Error  *UserError         `json:"error,omitempty"`
}

type SetBookmarkStatusPayload struct {
	Ok       bool       `json:"ok"`
	Bookmark *Bookmark  `json:"bookmark,omitempty"`
	Error    *UserError `json:"error,omitempty"`
}

type SetCardTonePayload struct {
	Ok    bool       `json:"ok"`
	Card  *Card      `json:"card,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type SetStageStatusPayload struct {
	Ok    bool       `json:"ok"`
	Stage *Stage     `json:"stage,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type SetTonePayload struct {
	Ok     bool       `json:"ok"`
	CardID string     `json:"cardId"`
	Tone   *string    `json:"tone,omitempty"`
	Error  *UserError `json:"error,omitempty"`
}

type SetTopicStatusPayload struct {
	Ok    bool       `json:"ok"`
	Topic *Topic     `json:"topic,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

// Tiến độ shadowing hiện tại của 1 thẻ. Chưa luyện lần nào trả vòng 0 / rate 1.0 / mốc rỗng — KHÔNG phải 404 (UI luôn cần 1 giá trị để hiển thị).
type ShadowProgress struct {
	CardID string `json:"cardId"`
	// Số vòng TÍCH LUỸ do CLIENT đếm; server không tự +1 để 1 request retry không nhảy 2 vòng.
	Loops int `json:"loops"`
	// Tỉ lệ tốc độ nói, đã qua `domain/practice.NormalizeRate` (0 → 1.0; ngoài [0.5, 1.5] là 400).
	Rate      float64 `json:"rate"`
	UpdatedAt string  `json:"updatedAt"`
}

type ShadowProgressInput struct {
	CardID string  `json:"cardId"`
	Loops  int     `json:"loops"`
	Rate   float64 `json:"rate"`
}

type ShadowProgressPayload struct {
	Ok       bool            `json:"ok"`
	Progress *ShadowProgress `json:"progress,omitempty"`
	Error    *UserError      `json:"error,omitempty"`
}

type StageInput struct {
	Slug  string  `json:"slug"`
	Title string  `json:"title"`
	Goal  *string `json:"goal,omitempty"`
	// null = max+1, giữ hành vi v1 (thêm node liên tiếp không phải tự đếm).
	Position      *int    `json:"position,omitempty"`
	DurationWeeks *int    `json:"durationWeeks,omitempty"`
	Status        *Status `json:"status,omitempty"`
	DeckID        *string `json:"deckId,omitempty"`
	// Rỗng = lấy DEFAULT của cột (plain/up).
	Terrain   *Terrain   `json:"terrain,omitempty"`
	Direction *Direction `json:"direction,omitempty"`
}

// PATCH. `terrain`/`direction` null = KHÔNG đụng — PATCH phân biệt "không gửi" với "gửi rỗng" (rỗng sẽ ra DEFAULT).
type StagePatch struct {
	Title         *string    `json:"title,omitempty"`
	Goal          *string    `json:"goal,omitempty"`
	Position      *int       `json:"position,omitempty"`
	DurationWeeks *int       `json:"durationWeeks,omitempty"`
	DeckID        *string    `json:"deckId,omitempty"`
	Terrain       *Terrain   `json:"terrain,omitempty"`
	Direction     *Direction `json:"direction,omitempty"`
}

// Số liệu dashboard cho 1 cửa sổ. `done`/`total` là alias deprecated của `doneWindow`/`totalAll` — giữ vì UI v1 đang đọc tên cũ.
type Stats struct {
	// week (7 ngày) | month (30 ngày). Rỗng = week.
	Range string `json:"range"`
	Days  int    `json:"days"`
	// @deprecated dùng `doneWindow`.
	Done int `json:"done"`
	// @deprecated dùng `totalAll`.
	Total int `json:"total"`
	// Số review trong CỬA SỔ (đã ôn bao nhiêu).
	DoneWindow int `json:"doneWindow"`
	// Tổng số thẻ hiện có, KHÔNG theo cửa sổ (kho học liệu).
	TotalAll int `json:"totalAll"`
	// Số thẻ đã tới hạn (due_at <= now). KHÔNG kéo thẻ `state='new'` — khác hàng đợi ôn `srs.DueCards`, và sự khác biệt đó là CỐ Ý (hành vi v1).
	DueNow   int     `json:"dueNow"`
	Accuracy float64 `json:"accuracy"`
	Streak   int     `json:"streak"`
	// Luôn là "UTC".
	Timezone string `json:"timezone"`
}

type StatsPayload struct {
	Ok    bool       `json:"ok"`
	Stats *Stats     `json:"stats,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type StatusInput struct {
	Status     Status  `json:"status"`
	StatusNote *string `json:"statusNote,omitempty"`
}

// Kết quả tra trọng âm. `fromDict = false` nghĩa là đoán bằng bộ quy tắc hậu tố, UI phải gắn nhãn "ngoại lệ".
type StressLookup struct {
	Term string `json:"term"`
	Ipa  string `json:"ipa"`
	// Pattern in HOA âm tiết có trọng âm, nối bằng "-" (pho-TO-graph).
	Stress    string `json:"stress"`
	Exception bool   `json:"exception"`
	Note      string `json:"note"`
	FromDict  bool   `json:"fromDict"`
}

type StrokeIndexEntry struct {
	Hanzi       string `json:"hanzi"`
	StrokeCount int    `json:"strokeCount"`
}

type StrokeInfo struct {
	Hanzi       string       `json:"hanzi"`
	PinyinMarks string       `json:"pinyinMarks"`
	Level       string       `json:"level"`
	StrokeCount int          `json:"strokeCount"`
	Steps       []StrokeStep `json:"steps"`
}

type StrokePayload struct {
	Ok    bool               `json:"ok"`
	Index []StrokeIndexEntry `json:"index"`
	Info  *StrokeInfo        `json:"info,omitempty"`
	Error *UserError         `json:"error,omitempty"`
}

type StrokeStep struct {
	Order int    `json:"order"`
	Code  string `json:"code"`
	Name  string `json:"name"`
}

type SyncConflictsPayload struct {
	Ok        bool       `json:"ok"`
	Conflicts []Conflict `json:"conflicts"`
	Error     *UserError `json:"error,omitempty"`
}

type SyncStatus struct {
	// Luôn true: merge luôn sẵn sàng, không có cờ tắt/mở (đã bỏ ở v1).
	Enabled  bool   `json:"enabled"`
	Strategy string `json:"strategy"`
	// Rỗng khi chưa sync lần nào.
	LastSyncAt    string `json:"lastSyncAt"`
	ConflictCount int    `json:"conflictCount"`
}

type SyncStatusPayload struct {
	Ok     bool        `json:"ok"`
	Status *SyncStatus `json:"status,omitempty"`
	Error  *UserError  `json:"error,omitempty"`
}

// 1 trục checklist THIEU (A-H) kèm rubric tiếng Việt.
type ThieuAxis struct {
	// Mã trục A..H.
	Code string `json:"code"`
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type ThieuInput struct {
	// Rỗng = ngày UTC hôm nay (YYYY-MM-DD), giữ hành vi v1.
	Session *string `json:"session,omitempty"`
	// Phải đủ 8 trục.
	Scores []ThieuScoreInput `json:"scores"`
	Note   *string           `json:"note,omitempty"`
}

type ThieuScore struct {
	Axis string `json:"axis"`
	// Điểm thang 1-5.
	Value int `json:"value"`
}

type ThieuScoreInput struct {
	Axis  string `json:"axis"`
	Value int    `json:"value"`
}

// 1 buổi chấm checklist — lưu trong `notes` với prefix THIEU|.
type ThieuSession struct {
	ID string `json:"id"`
	// Ngày UTC (YYYY-MM-DD).
	Session string `json:"session"`
	// Điểm 8 trục. Thiếu trục nào = 400 (bản chấm 4/8 trục không có nghĩa checklist).
	Scores    []ThieuScore `json:"scores"`
	Average   float64      `json:"average"`
	Note      string       `json:"note"`
	CreatedAt string       `json:"createdAt"`
}

// Kết quả chấm thanh điệu — quy tắc nằm ở `domain/content.GradeTonePair`.
type ToneGrade struct {
	// Điểm SRS 1-4 theo tỉ lệ trùng: trùng hết = 4, >= 1/2 = 3, …
	Grade int `json:"grade"`
	// Tỉ lệ âm tiết trùng (0-1).
	Score float64 `json:"score"`
	Exact bool    `json:"exact"`
	Hit   int     `json:"hit"`
}

type TopError struct {
	Word  string `json:"word"`
	Count int    `json:"count"`
	// Thẻ sai nhiều nhất gần nhất — để UI bấm "nhảy review". NULL khi lần sai đó không gắn thẻ nào (luyện tự do), HOẶC khi cùng 1 từ sai ở nhiều thẻ khác nhau và không chọn thẻ nào làm đại diện.
	CardID *string `json:"cardId,omitempty"`
	// Mặt trước của thẻ để hiển thị. NULL đi cùng `cardId` null. Chỉ đọc được khi thẻ còn sống (không xoá mềm).
	Front *string `json:"front,omitempty"`
}

type TopErrorCount struct {
	Word  string `json:"word"`
	Count int    `json:"count"`
}

type TopErrorsPayload struct {
	Ok     bool       `json:"ok"`
	Errors []TopError `json:"errors"`
	Error  *UserError `json:"error,omitempty"`
}

type TopicInput struct {
	Title      string   `json:"title"`
	Why        *string  `json:"why,omitempty"`
	Activities []string `json:"activities,omitempty"`
	Position   *int     `json:"position,omitempty"`
	// 0 = bắt buộc, 1 = tham khảo. null = 0 (bắt buộc), khớp DEFAULT của cột.
	IsOptional *int `json:"isOptional,omitempty"`
	// null = để server layout. Ngoài viewBox 0 0 1000 2000 bị từ chối 400 (node ngoài canvas thì M6 không scroll tới được).
	MapX *float64 `json:"mapX,omitempty"`
	MapY *float64 `json:"mapY,omitempty"`
}

type TopicPatch struct {
	Title      *string  `json:"title,omitempty"`
	Why        *string  `json:"why,omitempty"`
	Activities []string `json:"activities,omitempty"`
	Position   *int     `json:"position,omitempty"`
	IsOptional *int     `json:"isOptional,omitempty"`
	MapX       *float64 `json:"mapX,omitempty"`
	MapY       *float64 `json:"mapY,omitempty"`
	// Xoá mapX+mapY (NULL thật, không phải 0) để đưa node về auto-layout. Thắng mọi giá trị mapX/mapY trong cùng patch.
	ClearMap *bool `json:"clearMap,omitempty"`
}

type UpdateBookmarkPayload struct {
	Ok       bool       `json:"ok"`
	Bookmark *Bookmark  `json:"bookmark,omitempty"`
	Error    *UserError `json:"error,omitempty"`
}

type UpdateCardPayload struct {
	Ok    bool       `json:"ok"`
	Card  *Card      `json:"card,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type UpdateMilestonePayload struct {
	Ok        bool       `json:"ok"`
	Milestone *Milestone `json:"milestone,omitempty"`
	Error     *UserError `json:"error,omitempty"`
}

type UpdatePathPayload struct {
	Ok    bool       `json:"ok"`
	Path  *Path      `json:"path,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type UpdateResourcePayload struct {
	Ok       bool       `json:"ok"`
	Resource *Resource  `json:"resource,omitempty"`
	Error    *UserError `json:"error,omitempty"`
}

type UpdateStagePayload struct {
	Ok    bool       `json:"ok"`
	Stage *Stage     `json:"stage,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type UpdateTopicPayload struct {
	Ok    bool       `json:"ok"`
	Topic *Topic     `json:"topic,omitempty"`
	Error *UserError `json:"error,omitempty"`
}

type UpsertDictPayload struct {
	Ok    bool       `json:"ok"`
	Entry *DictEntry `json:"entry,omitempty"`
	// true = chữ mới; false = đã có nên nội dung cũ KHÔNG bị ghi đè (người dùng sửa nghĩa thì import lại không được xoá).
	Created bool       `json:"created"`
	Error   *UserError `json:"error,omitempty"`
}

// Lỗi nghiệp vụ trả về cho client. Message tiếng Việt lấy nguyên văn từ tầng application.
type UserError struct {
	// Thông điệp tiếng Việt, nguyên văn từ application layer.
	Message string `json:"message"`
	// Mã lỗi, map 1-1 sang HTTP status của application (BAD_REQUEST/NOT_FOUND/CONFLICT/NOT_IMPLEMENTED/…).
	Code ErrorCode `json:"code"`
}

// 4 trạng thái kho link. KHÁC `Status` của node roadmap: bookmark không nằm trên đường đi nên không có `not_started`/`skipped`; đọc xong là `DONE`, không còn giá trị thì `ARCHIVED`. CHECK ở DB là backstop.
type BookmarkStatus string

const (
	// Chưa đọc — DEFAULT khi tạo.
	BookmarkStatusToRead BookmarkStatus = "TO_READ"
	// Đang đọc.
	BookmarkStatusReading BookmarkStatus = "READING"
	// Đã đọc xong.
	BookmarkStatusDone BookmarkStatus = "DONE"
	// Cất đi, không đọc nữa.
	BookmarkStatusArchived BookmarkStatus = "ARCHIVED"
)

var AllBookmarkStatus = []BookmarkStatus{
	BookmarkStatusToRead,
	BookmarkStatusReading,
	BookmarkStatusDone,
	BookmarkStatusArchived,
}

func (e BookmarkStatus) IsValid() bool {
	switch e {
	case BookmarkStatusToRead, BookmarkStatusReading, BookmarkStatusDone, BookmarkStatusArchived:
		return true
	}
	return false
}

func (e BookmarkStatus) String() string {
	return string(e)
}

func (e *BookmarkStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookmarkStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookmarkStatus", str)
	}
	return nil
}

func (e BookmarkStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookmarkStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookmarkStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Loại từ sau khi chunking: nội dung (đọc mạnh) hay chức năng (đọc nhẹ).
type ChunkKind string

const (
	ChunkKindContent  ChunkKind = "CONTENT"
	ChunkKindFunction ChunkKind = "FUNCTION"
)

var AllChunkKind = []ChunkKind{
	ChunkKindContent,
	ChunkKindFunction,
}

func (e ChunkKind) IsValid() bool {
	switch e {
	case ChunkKindContent, ChunkKindFunction:
		return true
	}
	return false
}

func (e ChunkKind) String() string {
	return string(e)
}

func (e *ChunkKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChunkKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChunkKind", str)
	}
	return nil
}

func (e ChunkKind) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChunkKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChunkKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Hướng đi của bản đồ: cuộn dọc hay ngang.
type Direction string

const (
	DirectionUp    Direction = "UP"
	DirectionRight Direction = "RIGHT"
)

var AllDirection = []Direction{
	DirectionUp,
	DirectionRight,
}

func (e Direction) IsValid() bool {
	switch e {
	case DirectionUp, DirectionRight:
		return true
	}
	return false
}

func (e Direction) String() string {
	return string(e)
}

func (e *Direction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Direction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Direction", str)
	}
	return nil
}

func (e Direction) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Direction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Direction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ErrorCode string

const (
	ErrorCodeBadRequest ErrorCode = "BAD_REQUEST"
	ErrorCodeNotFound   ErrorCode = "NOT_FOUND"
	ErrorCodeConflict   ErrorCode = "CONFLICT"
	// Tính năng chưa bật / chưa cấu hình (HTTP 501). KHÁC hẳn CONFLICT: 409 là "yêu cầu mâu thuẫn với trạng thái hiện tại", còn 501 là "server chưa có cách phục vụ việc này" — ví dụ `mutation.sync` khi chưa cấu hình nguồn snapshot peer, `/api/backup` trước khi có `pg_dump`. Thêm hằng thứ 5 mà quên `codeForStatus` sẽ rơi về INTERNAL và che message tiếng Việt.
	ErrorCodeNotImplemented ErrorCode = "NOT_IMPLEMENTED"
	ErrorCodeInternal       ErrorCode = "INTERNAL"
)

var AllErrorCode = []ErrorCode{
	ErrorCodeBadRequest,
	ErrorCodeNotFound,
	ErrorCodeConflict,
	ErrorCodeNotImplemented,
	ErrorCodeInternal,
}

func (e ErrorCode) IsValid() bool {
	switch e {
	case ErrorCodeBadRequest, ErrorCodeNotFound, ErrorCodeConflict, ErrorCodeNotImplemented, ErrorCodeInternal:
		return true
	}
	return false
}

func (e ErrorCode) String() string {
	return string(e)
}

func (e *ErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ErrorCode", str)
	}
	return nil
}

func (e ErrorCode) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Trạng thái node suy ra cho bản đồ game: KHÔNG lưu DB, tính từ chuỗi node trước đó trong cùng stage.
type LevelState string

const (
	LevelStateDone    LevelState = "DONE"
	LevelStateCurrent LevelState = "CURRENT"
	LevelStateLocked  LevelState = "LOCKED"
)

var AllLevelState = []LevelState{
	LevelStateDone,
	LevelStateCurrent,
	LevelStateLocked,
}

func (e LevelState) IsValid() bool {
	switch e {
	case LevelStateDone, LevelStateCurrent, LevelStateLocked:
		return true
	}
	return false
}

func (e LevelState) String() string {
	return string(e)
}

func (e *LevelState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LevelState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LevelState", str)
	}
	return nil
}

func (e LevelState) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LevelState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LevelState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 9 loại tài liệu — trùng whitelist `application/roadmap.AllKinds`.
type ResourceKind string

const (
	ResourceKindVideo   ResourceKind = "VIDEO"
	ResourceKindArticle ResourceKind = "ARTICLE"
	ResourceKindTool    ResourceKind = "TOOL"
	ResourceKindApp     ResourceKind = "APP"
	ResourceKindBook    ResourceKind = "BOOK"
	ResourceKindCourse  ResourceKind = "COURSE"
	ResourceKindSite    ResourceKind = "SITE"
	ResourceKindPodcast ResourceKind = "PODCAST"
	ResourceKindChannel ResourceKind = "CHANNEL"
)

var AllResourceKind = []ResourceKind{
	ResourceKindVideo,
	ResourceKindArticle,
	ResourceKindTool,
	ResourceKindApp,
	ResourceKindBook,
	ResourceKindCourse,
	ResourceKindSite,
	ResourceKindPodcast,
	ResourceKindChannel,
}

func (e ResourceKind) IsValid() bool {
	switch e {
	case ResourceKindVideo, ResourceKindArticle, ResourceKindTool, ResourceKindApp, ResourceKindBook, ResourceKindCourse, ResourceKindSite, ResourceKindPodcast, ResourceKindChannel:
		return true
	}
	return false
}

func (e ResourceKind) String() string {
	return string(e)
}

func (e *ResourceKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResourceKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResourceKind", str)
	}
	return nil
}

func (e ResourceKind) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResourceKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResourceKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Bốn trạng thái node roadmap — hợp đồng đóng băng, có CHECK ở DB làm backstop.
type Status string

const (
	StatusNotStarted Status = "NOT_STARTED"
	StatusInProgress Status = "IN_PROGRESS"
	StatusDone       Status = "DONE"
	StatusSkipped    Status = "SKIPPED"
)

var AllStatus = []Status{
	StatusNotStarted,
	StatusInProgress,
	StatusDone,
	StatusSkipped,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusNotStarted, StatusInProgress, StatusDone, StatusSkipped:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 6 loại địa hình của bản đồ — trùng `domain/roadmap.AllTerrains` và CHECK ở migration 00004. Tên ở đây là TÊN HẰNG của domain, đổi sang SCREAMING_SNAKE cho đúng quy ước GraphQL; đổi 1 tên trong 3 nơi này là enum lệch DB (kiểu lỗi `enum Terrain` từng trả `PLAIN` cho 5/6 địa hình).
type Terrain string

const (
	TerrainMeadow  Terrain = "MEADOW"
	TerrainDesert  Terrain = "DESERT"
	TerrainSnow    Terrain = "SNOW"
	TerrainVolcano Terrain = "VOLCANO"
	TerrainOcean   Terrain = "OCEAN"
	TerrainCity    Terrain = "CITY"
)

var AllTerrain = []Terrain{
	TerrainMeadow,
	TerrainDesert,
	TerrainSnow,
	TerrainVolcano,
	TerrainOcean,
	TerrainCity,
}

func (e Terrain) IsValid() bool {
	switch e {
	case TerrainMeadow, TerrainDesert, TerrainSnow, TerrainVolcano, TerrainOcean, TerrainCity:
		return true
	}
	return false
}

func (e Terrain) String() string {
	return string(e)
}

func (e *Terrain) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Terrain(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Terrain", str)
	}
	return nil
}

func (e Terrain) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Terrain) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Terrain) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WordStatus string

const (
	WordStatusOk      WordStatus = "OK"
	WordStatusWrong   WordStatus = "WRONG"
	WordStatusMissing WordStatus = "MISSING"
	WordStatusExtra   WordStatus = "EXTRA"
)

var AllWordStatus = []WordStatus{
	WordStatusOk,
	WordStatusWrong,
	WordStatusMissing,
	WordStatusExtra,
}

func (e WordStatus) IsValid() bool {
	switch e {
	case WordStatusOk, WordStatusWrong, WordStatusMissing, WordStatusExtra:
		return true
	}
	return false
}

func (e WordStatus) String() string {
	return string(e)
}

func (e *WordStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WordStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WordStatus", str)
	}
	return nil
}

func (e WordStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WordStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WordStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
