// Seed dữ liệu từ vựng cho context content. Port NGUYÊN VĂN từ
// api/chinese_hsk.go (hsk1Seed) + api/hsk_seed_l234.go (hsk2/3/4) — dữ liệu
// này là nội dung học thuật, đổi 1 từ là đổi bài học.
//
// Nguồn gốc (giữ nguyên credit như v1):
//   - HSK1: 36 từ, pinyin đối chiếu CC-CEDICT (CC BY-SA 4.0), nghĩa tiếng Việt
//     tự soạn.
//   - HSK 2.0 L2-L4: sinh bởi scripts/seed_hsk.py từ
//     drkameleon/complete-hsk-vocabulary (MIT) + clem109/hsk-vocabulary (MIT);
//     pinyin tham khảo CC-CEDICT.

package contentinfra

// HskEntry là 1 dòng seed từ vựng: Pinyin mang số thanh ("ni3 hao3"), Tone là
// pattern thuần lưu vào cards.tone ("3 3").
type HskEntry struct {
	Hanzi  string
	Pinyin string
	Nghia  string
	Level  string
	Tone   string
}

// hsk1Seed — seed HSK1.
var hsk1Seed = []HskEntry{
	{Hanzi: "你", Pinyin: "ni3", Nghia: "bạn", Level: "HSK1", Tone: "3"},
	{Hanzi: "好", Pinyin: "hao3", Nghia: "tốt/khỏe", Level: "HSK1", Tone: "3"},
	{Hanzi: "你好", Pinyin: "ni3 hao3", Nghia: "xin chào", Level: "HSK1", Tone: "3 3"},
	{Hanzi: "我", Pinyin: "wo3", Nghia: "tôi", Level: "HSK1", Tone: "3"},
	{Hanzi: "你们", Pinyin: "ni3 men5", Nghia: "các bạn", Level: "HSK1", Tone: "3 5"},
	{Hanzi: "他", Pinyin: "ta1", Nghia: "anh ấy", Level: "HSK1", Tone: "1"},
	{Hanzi: "她", Pinyin: "ta1", Nghia: "cô ấy", Level: "HSK1", Tone: "1"},
	{Hanzi: "是", Pinyin: "shi4", Nghia: "là", Level: "HSK1", Tone: "4"},
	{Hanzi: "不", Pinyin: "bu4", Nghia: "không", Level: "HSK1", Tone: "4"},
	{Hanzi: "的", Pinyin: "de5", Nghia: "trợ từ sở hữu (của)", Level: "HSK1", Tone: "5"},
	{Hanzi: "了", Pinyin: "le5", Nghia: "trợ từ hoàn thành (rồi)", Level: "HSK1", Tone: "5"},
	{Hanzi: "吗", Pinyin: "ma5", Nghia: "trợ từ nghi vấn (không)", Level: "HSK1", Tone: "5"},
	{Hanzi: "在", Pinyin: "zai4", Nghia: "ở/tại", Level: "HSK1", Tone: "4"},
	{Hanzi: "有", Pinyin: "you3", Nghia: "có", Level: "HSK1", Tone: "3"},
	{Hanzi: "人", Pinyin: "ren2", Nghia: "người", Level: "HSK1", Tone: "2"},
	{Hanzi: "大", Pinyin: "da4", Nghia: "to/lớn", Level: "HSK1", Tone: "4"},
	{Hanzi: "小", Pinyin: "xiao3", Nghia: "nhỏ", Level: "HSK1", Tone: "3"},
	{Hanzi: "中", Pinyin: "zhong1", Nghia: "giữa/trung", Level: "HSK1", Tone: "1"},
	{Hanzi: "国", Pinyin: "guo2", Nghia: "nước/quốc", Level: "HSK1", Tone: "2"},
	{Hanzi: "中国", Pinyin: "zhong1 guo2", Nghia: "Trung Quốc", Level: "HSK1", Tone: "1 2"},
	{Hanzi: "学习", Pinyin: "xue2 xi2", Nghia: "học tập", Level: "HSK1", Tone: "2 2"},
	{Hanzi: "汉语", Pinyin: "han4 yu3", Nghia: "tiếng Hán", Level: "HSK1", Tone: "4 3"},
	{Hanzi: "老师", Pinyin: "lao3 shi1", Nghia: "thầy/cô giáo", Level: "HSK1", Tone: "3 1"},
	{Hanzi: "学生", Pinyin: "xue2 sheng1", Nghia: "học sinh", Level: "HSK1", Tone: "2 1"},
	{Hanzi: "朋友", Pinyin: "peng2 you3", Nghia: "bạn bè", Level: "HSK1", Tone: "2 3"},
	{Hanzi: "家", Pinyin: "jia1", Nghia: "nhà/gia đình", Level: "HSK1", Tone: "1"},
	{Hanzi: "学校", Pinyin: "xue2 xiao4", Nghia: "trường học", Level: "HSK1", Tone: "2 4"},
	{Hanzi: "水", Pinyin: "shui3", Nghia: "nước", Level: "HSK1", Tone: "3"},
	{Hanzi: "茶", Pinyin: "cha2", Nghia: "trà", Level: "HSK1", Tone: "2"},
	{Hanzi: "米饭", Pinyin: "mi3 fan4", Nghia: "cơm", Level: "HSK1", Tone: "3 4"},
	{Hanzi: "爱", Pinyin: "ai4", Nghia: "yêu", Level: "HSK1", Tone: "4"},
	{Hanzi: "吃", Pinyin: "chi1", Nghia: "ăn", Level: "HSK1", Tone: "1"},
	{Hanzi: "喝", Pinyin: "he1", Nghia: "uống", Level: "HSK1", Tone: "1"},
	{Hanzi: "去", Pinyin: "qu4", Nghia: "đi", Level: "HSK1", Tone: "4"},
	{Hanzi: "来", Pinyin: "lai2", Nghia: "đến", Level: "HSK1", Tone: "2"},
	{Hanzi: "什么", Pinyin: "shen2 me5", Nghia: "cái gì", Level: "HSK1", Tone: "2 5"},
}

// hsk2Seed — seed HSK2.
var hsk2Seed = []HskEntry{
	{Hanzi: "吧", Pinyin: "ba5", Nghia: "trợ từ cuối câu (nhé, nhỉ, nào)", Level: "HSK2", Tone: "5"},
	{Hanzi: "白", Pinyin: "bai2", Nghia: "trắng", Level: "HSK2", Tone: "2"},
	{Hanzi: "百", Pinyin: "bai3", Nghia: "trăm", Level: "HSK2", Tone: "3"},
	{Hanzi: "帮助", Pinyin: "bang1 zhu4", Nghia: "sự giúp đỡ", Level: "HSK2", Tone: "1 4"},
	{Hanzi: "报纸", Pinyin: "bao4 zhi3", Nghia: "báo", Level: "HSK2", Tone: "4 3"},
	{Hanzi: "比", Pinyin: "bi3", Nghia: "so với, hơn (so sánh)", Level: "HSK2", Tone: "3"},
	{Hanzi: "别", Pinyin: "bie2", Nghia: "đừng", Level: "HSK2", Tone: "2"},
	{Hanzi: "长", Pinyin: "chang2", Nghia: "dài", Level: "HSK2", Tone: "2"},
	{Hanzi: "唱歌", Pinyin: "chang4 ge1", Nghia: "hát bài hát", Level: "HSK2", Tone: "4 1"},
	{Hanzi: "出", Pinyin: "chu1", Nghia: "ra", Level: "HSK2", Tone: "1"},
	{Hanzi: "穿", Pinyin: "chuan1", Nghia: "mặc (quần áo)", Level: "HSK2", Tone: "1"},
	{Hanzi: "船", Pinyin: "chuan2", Nghia: "thuyền", Level: "HSK2", Tone: "2"},
	{Hanzi: "次", Pinyin: "ci4", Nghia: "lần, lượt", Level: "HSK2", Tone: "4"},
	{Hanzi: "从", Pinyin: "cong2", Nghia: "từ (nơi chốn, thời gian)", Level: "HSK2", Tone: "2"},
	{Hanzi: "错", Pinyin: "cuo4", Nghia: "sai", Level: "HSK2", Tone: "4"},
	{Hanzi: "打篮球", Pinyin: "da3 lan2 qiu2", Nghia: "chơi bóng rổ", Level: "HSK2", Tone: "3 2 2"},
	{Hanzi: "大家", Pinyin: "da4 jia1", Nghia: "mọi người", Level: "HSK2", Tone: "4 1"},
	{Hanzi: "但是", Pinyin: "dan4 shi4", Nghia: "nhưng", Level: "HSK2", Tone: "4 4"},
	{Hanzi: "到", Pinyin: "dao4", Nghia: "đến, tới", Level: "HSK2", Tone: "4"},
	{Hanzi: "得", Pinyin: "de5", Nghia: "trợ từ (làm... đến nỗi)", Level: "HSK2", Tone: "5"},
	{Hanzi: "弟弟", Pinyin: "di4 di5", Nghia: "em trai", Level: "HSK2", Tone: "4 5"},
	{Hanzi: "第一", Pinyin: "di4 yi1", Nghia: "thứ nhất", Level: "HSK2", Tone: "4 1"},
	{Hanzi: "懂", Pinyin: "dong3", Nghia: "hiểu", Level: "HSK2", Tone: "3"},
	{Hanzi: "房间", Pinyin: "fang2 jian1", Nghia: "phòng", Level: "HSK2", Tone: "2 1"},
	{Hanzi: "非常", Pinyin: "fei1 chang2", Nghia: "rất, vô cùng", Level: "HSK2", Tone: "1 2"},
	{Hanzi: "服务员", Pinyin: "fu2 wu4 yuan2", Nghia: "người phục vụ", Level: "HSK2", Tone: "2 4 2"},
	{Hanzi: "高", Pinyin: "gao1", Nghia: "cao", Level: "HSK2", Tone: "1"},
	{Hanzi: "告诉", Pinyin: "gao4 su5", Nghia: "nói cho biết, bảo", Level: "HSK2", Tone: "4 5"},
	{Hanzi: "哥哥", Pinyin: "ge1 ge5", Nghia: "anh trai", Level: "HSK2", Tone: "1 5"},
	{Hanzi: "给", Pinyin: "gei3", Nghia: "cho, đưa cho", Level: "HSK2", Tone: "3"},
	{Hanzi: "公共汽车", Pinyin: "gong1 gong4 qi4 che1", Nghia: "xe buýt", Level: "HSK2", Tone: "1 4 4 1"},
	{Hanzi: "公斤", Pinyin: "gong1 jin1", Nghia: "ki-lô-gam", Level: "HSK2", Tone: "1 1"},
	{Hanzi: "公司", Pinyin: "gong1 si1", Nghia: "công ty", Level: "HSK2", Tone: "1 1"},
	{Hanzi: "贵", Pinyin: "gui4", Nghia: "đắt", Level: "HSK2", Tone: "4"},
	{Hanzi: "还", Pinyin: "hai2", Nghia: "còn, vẫn (tiếp diễn)", Level: "HSK2", Tone: "2"},
	{Hanzi: "孩子", Pinyin: "hai2 zi5", Nghia: "trẻ em", Level: "HSK2", Tone: "2 5"},
	{Hanzi: "好吃", Pinyin: "hao3 chi1", Nghia: "ngon", Level: "HSK2", Tone: "3 1"},
	{Hanzi: "号", Pinyin: "hao4", Nghia: "số; ngày (trong tháng)", Level: "HSK2", Tone: "4"},
	{Hanzi: "黑", Pinyin: "hei1", Nghia: "đen", Level: "HSK2", Tone: "1"},
	{Hanzi: "红", Pinyin: "hong2", Nghia: "đỏ", Level: "HSK2", Tone: "2"},
	{Hanzi: "欢迎", Pinyin: "huan1 ying2", Nghia: "đón chào", Level: "HSK2", Tone: "1 2"},
	{Hanzi: "回答", Pinyin: "hui2 da2", Nghia: "trả lời", Level: "HSK2", Tone: "2 2"},
	{Hanzi: "机场", Pinyin: "ji1 chang3", Nghia: "sân bay", Level: "HSK2", Tone: "1 3"},
	{Hanzi: "鸡蛋", Pinyin: "ji1 dan4", Nghia: "trứng", Level: "HSK2", Tone: "1 4"},
	{Hanzi: "件", Pinyin: "jian4", Nghia: "cái, chiếc (lượng từ)", Level: "HSK2", Tone: "4"},
	{Hanzi: "教室", Pinyin: "jiao4 shi4", Nghia: "lớp học", Level: "HSK2", Tone: "4 4"},
	{Hanzi: "姐姐", Pinyin: "jie3 jie5", Nghia: "chị gái", Level: "HSK2", Tone: "3 5"},
	{Hanzi: "介绍", Pinyin: "jie4 shao4", Nghia: "giới thiệu", Level: "HSK2", Tone: "4 4"},
	{Hanzi: "进", Pinyin: "jin4", Nghia: "vào", Level: "HSK2", Tone: "4"},
	{Hanzi: "近", Pinyin: "jin4", Nghia: "gần", Level: "HSK2", Tone: "4"},
	{Hanzi: "就", Pinyin: "jiu4", Nghia: "thì, bèn, chính là", Level: "HSK2", Tone: "4"},
	{Hanzi: "觉得", Pinyin: "jue2 de5", Nghia: "nghĩ", Level: "HSK2", Tone: "2 5"},
	{Hanzi: "咖啡", Pinyin: "ka1 fei1", Nghia: "cà phê", Level: "HSK2", Tone: "1 1"},
	{Hanzi: "开始", Pinyin: "kai1 shi3", Nghia: "bắt đầu", Level: "HSK2", Tone: "1 3"},
	{Hanzi: "考试", Pinyin: "kao3 shi4", Nghia: "thi, dự thi", Level: "HSK2", Tone: "3 4"},
	{Hanzi: "可能", Pinyin: "ke3 neng2", Nghia: "có thể, có khả năng", Level: "HSK2", Tone: "3 2"},
	{Hanzi: "可以", Pinyin: "ke3 yi3", Nghia: "có thể, được phép", Level: "HSK2", Tone: "3 3"},
	{Hanzi: "课", Pinyin: "ke4", Nghia: "môn học", Level: "HSK2", Tone: "4"},
	{Hanzi: "快", Pinyin: "kuai4", Nghia: "nhanh", Level: "HSK2", Tone: "4"},
	{Hanzi: "快乐", Pinyin: "kuai4 le4", Nghia: "vui vẻ", Level: "HSK2", Tone: "4 4"},
	{Hanzi: "累", Pinyin: "lei4", Nghia: "mệt", Level: "HSK2", Tone: "4"},
	{Hanzi: "离", Pinyin: "li2", Nghia: "rời khỏi", Level: "HSK2", Tone: "2"},
	{Hanzi: "两", Pinyin: "liang3", Nghia: "hai", Level: "HSK2", Tone: "3"},
	{Hanzi: "路", Pinyin: "lu4", Nghia: "đường", Level: "HSK2", Tone: "4"},
	{Hanzi: "旅游", Pinyin: "lü3 you2", Nghia: "du lịch", Level: "HSK2", Tone: "3 2"},
	{Hanzi: "卖", Pinyin: "mai4", Nghia: "bán", Level: "HSK2", Tone: "4"},
	{Hanzi: "慢", Pinyin: "man4", Nghia: "chậm", Level: "HSK2", Tone: "4"},
	{Hanzi: "忙", Pinyin: "mang2", Nghia: "bận", Level: "HSK2", Tone: "2"},
	{Hanzi: "每", Pinyin: "mei3", Nghia: "mỗi", Level: "HSK2", Tone: "3"},
	{Hanzi: "妹妹", Pinyin: "mei4 mei5", Nghia: "em gái", Level: "HSK2", Tone: "4 5"},
	{Hanzi: "门", Pinyin: "men2", Nghia: "cửa", Level: "HSK2", Tone: "2"},
	{Hanzi: "男人", Pinyin: "nan2 ren2", Nghia: "đàn ông", Level: "HSK2", Tone: "2 2"},
	{Hanzi: "您", Pinyin: "nin2", Nghia: "ngài, bạn (lịch sự)", Level: "HSK2", Tone: "2"},
	{Hanzi: "牛奶", Pinyin: "niu2 nai3", Nghia: "sữa bò", Level: "HSK2", Tone: "2 3"},
	{Hanzi: "女人", Pinyin: "nü3 ren2", Nghia: "phụ nữ", Level: "HSK2", Tone: "3 2"},
	{Hanzi: "旁边", Pinyin: "pang2 bian1", Nghia: "bên cạnh", Level: "HSK2", Tone: "2 1"},
	{Hanzi: "跑步", Pinyin: "pao3 bu4", Nghia: "chạy bộ", Level: "HSK2", Tone: "3 4"},
	{Hanzi: "便宜", Pinyin: "pian2 yi5", Nghia: "rẻ", Level: "HSK2", Tone: "2 5"},
	{Hanzi: "票", Pinyin: "piao4", Nghia: "vé", Level: "HSK2", Tone: "4"},
	{Hanzi: "妻子", Pinyin: "qi1 zi5", Nghia: "vợ", Level: "HSK2", Tone: "1 5"},
	{Hanzi: "起床", Pinyin: "qi3 chuang2", Nghia: "thức dậy", Level: "HSK2", Tone: "3 2"},
	{Hanzi: "千", Pinyin: "qian1", Nghia: "nghìn", Level: "HSK2", Tone: "1"},
	{Hanzi: "晴", Pinyin: "qing2", Nghia: "nắng ráo", Level: "HSK2", Tone: "2"},
	{Hanzi: "去年", Pinyin: "qu4 nian2", Nghia: "năm ngoái", Level: "HSK2", Tone: "4 2"},
	{Hanzi: "让", Pinyin: "rang4", Nghia: "để cho, nhường", Level: "HSK2", Tone: "4"},
	{Hanzi: "上班", Pinyin: "shang4 ban1", Nghia: "đi làm", Level: "HSK2", Tone: "4 1"},
	{Hanzi: "身体", Pinyin: "shen1 ti3", Nghia: "cơ thể", Level: "HSK2", Tone: "1 3"},
	{Hanzi: "生病", Pinyin: "sheng1 bing4", Nghia: "ốm, bị bệnh", Level: "HSK2", Tone: "1 4"},
	{Hanzi: "生日", Pinyin: "sheng1 ri4", Nghia: "sinh nhật", Level: "HSK2", Tone: "1 4"},
	{Hanzi: "时间", Pinyin: "shi2 jian1", Nghia: "thời gian", Level: "HSK2", Tone: "2 1"},
	{Hanzi: "事情", Pinyin: "shi4 qing5", Nghia: "việc", Level: "HSK2", Tone: "4 5"},
	{Hanzi: "手表", Pinyin: "shou3 biao3", Nghia: "đồng hồ đeo tay", Level: "HSK2", Tone: "3 3"},
	{Hanzi: "手机", Pinyin: "shou3 ji1", Nghia: "điện thoại di động", Level: "HSK2", Tone: "3 1"},
	{Hanzi: "送", Pinyin: "song4", Nghia: "tặng; tiễn; đưa", Level: "HSK2", Tone: "4"},
	{Hanzi: "所以", Pinyin: "suo3 yi3", Nghia: "cho nên", Level: "HSK2", Tone: "3 3"},
	{Hanzi: "它", Pinyin: "ta1", Nghia: "nó", Level: "HSK2", Tone: "1"},
	{Hanzi: "踢", Pinyin: "ti1", Nghia: "đá", Level: "HSK2", Tone: "1"},
	{Hanzi: "题", Pinyin: "ti2", Nghia: "đề, câu hỏi", Level: "HSK2", Tone: "2"},
	{Hanzi: "跳舞", Pinyin: "tiao4 wu3", Nghia: "nhảy múa", Level: "HSK2", Tone: "4 3"},
	{Hanzi: "外", Pinyin: "wai4", Nghia: "bên ngoài", Level: "HSK2", Tone: "4"},
	{Hanzi: "完", Pinyin: "wan2", Nghia: "xong", Level: "HSK2", Tone: "2"},
	{Hanzi: "玩", Pinyin: "wan2", Nghia: "chơi", Level: "HSK2", Tone: "2"},
	{Hanzi: "晚上", Pinyin: "wan3 shang5", Nghia: "buổi tối", Level: "HSK2", Tone: "3 5"},
	{Hanzi: "为", Pinyin: "wei4", Nghia: "vì, để, làm (vì)", Level: "HSK2", Tone: "4"},
	{Hanzi: "问", Pinyin: "wen4", Nghia: "hỏi", Level: "HSK2", Tone: "4"},
	{Hanzi: "问题", Pinyin: "wen4 ti2", Nghia: "câu hỏi", Level: "HSK2", Tone: "4 2"},
	{Hanzi: "西瓜", Pinyin: "xi1 gua1", Nghia: "dưa hấu", Level: "HSK2", Tone: "1 1"},
	{Hanzi: "希望", Pinyin: "xi1 wang4", Nghia: "hy vọng", Level: "HSK2", Tone: "1 4"},
	{Hanzi: "洗", Pinyin: "xi3", Nghia: "rửa/giặt", Level: "HSK2", Tone: "3"},
	{Hanzi: "向", Pinyin: "xiang4", Nghia: "hướng về, phía", Level: "HSK2", Tone: "4"},
	{Hanzi: "小时", Pinyin: "xiao3 shi2", Nghia: "giờ", Level: "HSK2", Tone: "3 2"},
	{Hanzi: "笑", Pinyin: "xiao4", Nghia: "cười", Level: "HSK2", Tone: "4"},
	{Hanzi: "新", Pinyin: "xin1", Nghia: "mới", Level: "HSK2", Tone: "1"},
	{Hanzi: "姓", Pinyin: "xing4", Nghia: "họ (tên họ)", Level: "HSK2", Tone: "4"},
	{Hanzi: "休息", Pinyin: "xiu1 xi5", Nghia: "nghỉ ngơi", Level: "HSK2", Tone: "1 5"},
	{Hanzi: "雪", Pinyin: "xue3", Nghia: "tuyết", Level: "HSK2", Tone: "3"},
	{Hanzi: "颜色", Pinyin: "yan2 se4", Nghia: "màu sắc", Level: "HSK2", Tone: "2 4"},
	{Hanzi: "眼睛", Pinyin: "yan3 jing5", Nghia: "mắt", Level: "HSK2", Tone: "3 5"},
	{Hanzi: "羊肉", Pinyin: "yang2 rou4", Nghia: "thịt cừu", Level: "HSK2", Tone: "2 4"},
	{Hanzi: "药", Pinyin: "yao4", Nghia: "thuốc", Level: "HSK2", Tone: "4"},
	{Hanzi: "要", Pinyin: "yao4", Nghia: "muốn, cần, sẽ", Level: "HSK2", Tone: "4"},
	{Hanzi: "也", Pinyin: "ye3", Nghia: "cũng", Level: "HSK2", Tone: "3"},
	{Hanzi: "已经", Pinyin: "yi3 jing1", Nghia: "đã", Level: "HSK2", Tone: "3 1"},
	{Hanzi: "一起", Pinyin: "yi1 qi3", Nghia: "cùng nhau", Level: "HSK2", Tone: "1 3"},
	{Hanzi: "意思", Pinyin: "yi4 si5", Nghia: "ý tưởng", Level: "HSK2", Tone: "4 5"},
	{Hanzi: "阴", Pinyin: "yin1", Nghia: "âm u", Level: "HSK2", Tone: "1"},
	{Hanzi: "因为", Pinyin: "yin1 wei4", Nghia: "vì, bởi vì", Level: "HSK2", Tone: "1 4"},
	{Hanzi: "游泳", Pinyin: "you2 yong3", Nghia: "bơi lội", Level: "HSK2", Tone: "2 3"},
	{Hanzi: "右边", Pinyin: "you4 bian5", Nghia: "bên phải", Level: "HSK2", Tone: "4 5"},
	{Hanzi: "鱼", Pinyin: "yu2", Nghia: "cá", Level: "HSK2", Tone: "2"},
	{Hanzi: "元", Pinyin: "yuan2", Nghia: "đồng (đơn vị tiền tệ)", Level: "HSK2", Tone: "2"},
	{Hanzi: "远", Pinyin: "yuan3", Nghia: "xa", Level: "HSK2", Tone: "3"},
	{Hanzi: "运动", Pinyin: "yun4 dong4", Nghia: "thể thao, vận động", Level: "HSK2", Tone: "4 4"},
	{Hanzi: "再", Pinyin: "zai4", Nghia: "lại, nữa (lần sau)", Level: "HSK2", Tone: "4"},
	{Hanzi: "早上", Pinyin: "zao3 shang5", Nghia: "buổi sáng (sớm)", Level: "HSK2", Tone: "3 5"},
	{Hanzi: "张", Pinyin: "zhang1", Nghia: "tờ, tấm (lượng từ)", Level: "HSK2", Tone: "1"},
	{Hanzi: "丈夫", Pinyin: "zhang4 fu5", Nghia: "chồng", Level: "HSK2", Tone: "4 5"},
	{Hanzi: "找", Pinyin: "zhao3", Nghia: "tìm", Level: "HSK2", Tone: "3"},
	{Hanzi: "着", Pinyin: "zhe5", Nghia: "trợ từ tiếp diễn (đang...)", Level: "HSK2", Tone: "5"},
	{Hanzi: "真", Pinyin: "zhen1", Nghia: "thật sự", Level: "HSK2", Tone: "1"},
	{Hanzi: "正在", Pinyin: "zheng4 zai4", Nghia: "đang (ngay lúc này)", Level: "HSK2", Tone: "4 4"},
	{Hanzi: "知道", Pinyin: "zhi1 dao4", Nghia: "biết", Level: "HSK2", Tone: "1 4"},
	{Hanzi: "准备", Pinyin: "zhun3 bei4", Nghia: "chuẩn bị", Level: "HSK2", Tone: "3 4"},
	{Hanzi: "自行车", Pinyin: "zi4 xing2 che1", Nghia: "xe đạp", Level: "HSK2", Tone: "4 2 1"},
	{Hanzi: "走", Pinyin: "zou3", Nghia: "đi bộ", Level: "HSK2", Tone: "3"},
	{Hanzi: "最", Pinyin: "zui4", Nghia: "nhất", Level: "HSK2", Tone: "4"},
	{Hanzi: "左边", Pinyin: "zuo3 bian5", Nghia: "bên trái", Level: "HSK2", Tone: "3 5"},
}

// hsk3Seed — seed HSK3.
var hsk3Seed = []HskEntry{
	{Hanzi: "阿姨", Pinyin: "a1 yi2", Nghia: "dì, cô (gọi phụ nữ trung niên)", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "啊", Pinyin: "a5", Nghia: "trợ từ cảm thán (a, à)", Level: "HSK3", Tone: "5"},
	{Hanzi: "矮", Pinyin: "ai3", Nghia: "thấp", Level: "HSK3", Tone: "3"},
	{Hanzi: "爱好", Pinyin: "ai4 hao4", Nghia: "thích", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "安静", Pinyin: "an1 jing4", Nghia: "yên tĩnh", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "把", Pinyin: "ba3", Nghia: "giới từ (đem, cầm lấy)", Level: "HSK3", Tone: "3"},
	{Hanzi: "搬", Pinyin: "ban1", Nghia: "chuyển (nhà, đồ)", Level: "HSK3", Tone: "1"},
	{Hanzi: "班", Pinyin: "ban1", Nghia: "lớp; ca (làm việc)", Level: "HSK3", Tone: "1"},
	{Hanzi: "半", Pinyin: "ban4", Nghia: "một nửa", Level: "HSK3", Tone: "4"},
	{Hanzi: "办法", Pinyin: "ban4 fa3", Nghia: "biện pháp", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "办公室", Pinyin: "ban4 gong1 shi4", Nghia: "văn phòng", Level: "HSK3", Tone: "4 1 4"},
	{Hanzi: "帮忙", Pinyin: "bang1 mang2", Nghia: "giúp", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "包", Pinyin: "bao1", Nghia: "gói; túi", Level: "HSK3", Tone: "1"},
	{Hanzi: "饱", Pinyin: "bao3", Nghia: "ăn no", Level: "HSK3", Tone: "3"},
	{Hanzi: "北方", Pinyin: "bei3 fang1", Nghia: "phía bắc", Level: "HSK3", Tone: "3 1"},
	{Hanzi: "被", Pinyin: "bei4", Nghia: "bị, được (câu bị động)", Level: "HSK3", Tone: "4"},
	{Hanzi: "鼻子", Pinyin: "bi2 zi5", Nghia: "mũi", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "比较", Pinyin: "bi3 jiao4", Nghia: "so sánh", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "比赛", Pinyin: "bi3 sai4", Nghia: "cuộc thi", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "必须", Pinyin: "bi4 xu1", Nghia: "phải, bắt buộc", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "变化", Pinyin: "bian4 hua4", Nghia: "đổi/thay đổi", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "表示", Pinyin: "biao3 shi4", Nghia: "bày tỏ", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "表演", Pinyin: "biao3 yan3", Nghia: "biểu diễn", Level: "HSK3", Tone: "3 3"},
	{Hanzi: "别人", Pinyin: "bie2 ren5", Nghia: "người khác", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "宾馆", Pinyin: "bin1 guan3", Nghia: "nhà khách", Level: "HSK3", Tone: "1 3"},
	{Hanzi: "冰箱", Pinyin: "bing1 xiang1", Nghia: "tủ lạnh", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "才", Pinyin: "cai2", Nghia: "tài năng; vừa mới", Level: "HSK3", Tone: "2"},
	{Hanzi: "菜单", Pinyin: "cai4 dan1", Nghia: "thực đơn", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "参加", Pinyin: "can1 jia1", Nghia: "tham gia", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "草", Pinyin: "cao3", Nghia: "cỏ", Level: "HSK3", Tone: "3"},
	{Hanzi: "层", Pinyin: "ceng2", Nghia: "lớp", Level: "HSK3", Tone: "2"},
	{Hanzi: "差", Pinyin: "cha4", Nghia: "kém, thiếu, tệ", Level: "HSK3", Tone: "4"},
	{Hanzi: "超市", Pinyin: "chao1 shi4", Nghia: "siêu thị", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "衬衫", Pinyin: "chen4 shan1", Nghia: "áo sơ mi", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "成绩", Pinyin: "cheng2 ji4", Nghia: "thành tích", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "城市", Pinyin: "cheng2 shi4", Nghia: "thành phố", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "迟到", Pinyin: "chi2 dao4", Nghia: "đến muộn", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "出现", Pinyin: "chu1 xian4", Nghia: "xuất hiện", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "除了", Pinyin: "chu2 le5", Nghia: "ngoài ra", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "厨房", Pinyin: "chu2 fang2", Nghia: "nhà bếp", Level: "HSK3", Tone: "2 2"},
	{Hanzi: "春", Pinyin: "chun1", Nghia: "mùa xuân", Level: "HSK3", Tone: "1"},
	{Hanzi: "词语", Pinyin: "ci2 yu3", Nghia: "từ", Level: "HSK3", Tone: "2 3"},
	{Hanzi: "聪明", Pinyin: "cong1 ming5", Nghia: "thông minh", Level: "HSK3", Tone: "1 5"},
	{Hanzi: "打扫", Pinyin: "da3 sao3", Nghia: "quét dọn", Level: "HSK3", Tone: "3 3"},
	{Hanzi: "打算", Pinyin: "da3 suan4", Nghia: "lên kế hoạch", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "带", Pinyin: "dai4", Nghia: "mang theo, dẫn theo", Level: "HSK3", Tone: "4"},
	{Hanzi: "担心", Pinyin: "dan1 xin1", Nghia: "lo lắng", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "蛋糕", Pinyin: "dan4 gao1", Nghia: "bánh ngọt", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "当然", Pinyin: "dang1 ran2", Nghia: "đương nhiên", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "地", Pinyin: "de5", Nghia: "trợ từ (một cách...)", Level: "HSK3", Tone: "5"},
	{Hanzi: "灯", Pinyin: "deng1", Nghia: "đèn", Level: "HSK3", Tone: "1"},
	{Hanzi: "低", Pinyin: "di1", Nghia: "thấp", Level: "HSK3", Tone: "1"},
	{Hanzi: "地方", Pinyin: "di4 fang5", Nghia: "nơi, chỗ", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "地铁", Pinyin: "di4 tie3", Nghia: "tàu điện ngầm", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "地图", Pinyin: "di4 tu2", Nghia: "bản đồ", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "电梯", Pinyin: "dian4 ti1", Nghia: "thang máy", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "电子", Pinyin: "dian4 zi3", Nghia: "điện tử", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "冬", Pinyin: "dong1", Nghia: "mùa đông", Level: "HSK3", Tone: "1"},
	{Hanzi: "东", Pinyin: "dong1", Nghia: "phía đông", Level: "HSK3", Tone: "1"},
	{Hanzi: "动物", Pinyin: "dong4 wu4", Nghia: "động vật", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "短", Pinyin: "duan3", Nghia: "ngắn", Level: "HSK3", Tone: "3"},
	{Hanzi: "段", Pinyin: "duan4", Nghia: "đoạn", Level: "HSK3", Tone: "4"},
	{Hanzi: "锻炼", Pinyin: "duan4 lian4", Nghia: "rèn luyện (thể dục)", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "多么", Pinyin: "duo1 me5", Nghia: "biết bao", Level: "HSK3", Tone: "1 5"},
	{Hanzi: "饿", Pinyin: "e4", Nghia: "đói", Level: "HSK3", Tone: "4"},
	{Hanzi: "而且", Pinyin: "er2 qie3", Nghia: "hơn nữa, vả lại", Level: "HSK3", Tone: "2 3"},
	{Hanzi: "耳朵", Pinyin: "er3 duo5", Nghia: "tai", Level: "HSK3", Tone: "3 5"},
	{Hanzi: "发烧", Pinyin: "fa1 shao1", Nghia: "sốt", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "发现", Pinyin: "fa1 xian4", Nghia: "tìm thấy", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "方便", Pinyin: "fang1 bian4", Nghia: "tiện lợi", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "放", Pinyin: "fang4", Nghia: "đặt, để; thả", Level: "HSK3", Tone: "4"},
	{Hanzi: "放心", Pinyin: "fang4 xin1", Nghia: "cảm thấy nhẹ nhõm", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "分", Pinyin: "fen1", Nghia: "chia; phút (điểm số)", Level: "HSK3", Tone: "1"},
	{Hanzi: "附近", Pinyin: "fu4 jin4", Nghia: "vùng lân cận", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "复习", Pinyin: "fu4 xi2", Nghia: "ôn tập", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "干净", Pinyin: "gan1 jing4", Nghia: "sạch", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "敢", Pinyin: "gan3", Nghia: "dám", Level: "HSK3", Tone: "3"},
	{Hanzi: "感冒", Pinyin: "gan3 mao4", Nghia: "bị cảm", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "刚才", Pinyin: "gang1 cai2", Nghia: "cách đây chốc lát", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "根据", Pinyin: "gen1 ju4", Nghia: "theo", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "跟", Pinyin: "gen1", Nghia: "và, với, theo (cùng)", Level: "HSK3", Tone: "1"},
	{Hanzi: "更", Pinyin: "geng4", Nghia: "càng, hơn", Level: "HSK3", Tone: "4"},
	{Hanzi: "公园", Pinyin: "gong1 yuan2", Nghia: "công viên", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "故事", Pinyin: "gu4 shi5", Nghia: "câu chuyện", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "刮", Pinyin: "gua1", Nghia: "thổi", Level: "HSK3", Tone: "1"},
	{Hanzi: "关", Pinyin: "guan1", Nghia: "đóng; liên quan", Level: "HSK3", Tone: "1"},
	{Hanzi: "关系", Pinyin: "guan1 xi5", Nghia: "quan hệ", Level: "HSK3", Tone: "1 5"},
	{Hanzi: "关心", Pinyin: "guan1 xin1", Nghia: "quan tâm", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "关于", Pinyin: "guan1 yu2", Nghia: "thuộc về", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "国家", Pinyin: "guo2 jia1", Nghia: "đất nước", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "果汁", Pinyin: "guo3 zhi1", Nghia: "nước ép hoa quả", Level: "HSK3", Tone: "3 1"},
	{Hanzi: "过去", Pinyin: "guo4 qu5", Nghia: "trước đây, đã qua", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "还是", Pinyin: "hai2 shi5", Nghia: "hoặc (câu hỏi); vẫn", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "害怕", Pinyin: "hai4 pa4", Nghia: "sợ hãi", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "河", Pinyin: "he2", Nghia: "sông", Level: "HSK3", Tone: "2"},
	{Hanzi: "黑板", Pinyin: "hei1 ban3", Nghia: "bảng đen", Level: "HSK3", Tone: "1 3"},
	{Hanzi: "护照", Pinyin: "hu4 zhao4", Nghia: "hộ chiếu", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "花", Pinyin: "hua1", Nghia: "hoa", Level: "HSK3", Tone: "1"},
	{Hanzi: "花园", Pinyin: "hua1 yuan2", Nghia: "vườn", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "画", Pinyin: "hua4", Nghia: "vẽ", Level: "HSK3", Tone: "4"},
	{Hanzi: "坏", Pinyin: "huai4", Nghia: "xấu", Level: "HSK3", Tone: "4"},
	{Hanzi: "环境", Pinyin: "huan2 jing4", Nghia: "môi trường", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "换", Pinyin: "huan4", Nghia: "đổi/thay đổi", Level: "HSK3", Tone: "4"},
	{Hanzi: "黄", Pinyin: "huang2", Nghia: "vàng", Level: "HSK3", Tone: "2"},
	{Hanzi: "会议", Pinyin: "hui4 yi4", Nghia: "cuộc họp", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "或者", Pinyin: "huo4 zhe3", Nghia: "hoặc", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "机会", Pinyin: "ji1 hui4", Nghia: "cơ hội", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "几乎", Pinyin: "ji1 hu1", Nghia: "gần như", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "极", Pinyin: "ji2", Nghia: "cực kỳ", Level: "HSK3", Tone: "2"},
	{Hanzi: "记得", Pinyin: "ji4 de5", Nghia: "nhớ", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "季节", Pinyin: "ji4 jie2", Nghia: "mùa", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "检查", Pinyin: "jian3 cha2", Nghia: "kiểm tra", Level: "HSK3", Tone: "3 2"},
	{Hanzi: "简单", Pinyin: "jian3 dan1", Nghia: "đơn giản", Level: "HSK3", Tone: "3 1"},
	{Hanzi: "见面", Pinyin: "jian4 mian4", Nghia: "gặp", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "健康", Pinyin: "jian4 kang1", Nghia: "sức khỏe", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "讲", Pinyin: "jiang3", Nghia: "nói", Level: "HSK3", Tone: "3"},
	{Hanzi: "教", Pinyin: "jiao1", Nghia: "dạy", Level: "HSK3", Tone: "1"},
	{Hanzi: "脚", Pinyin: "jiao3", Nghia: "bàn chân", Level: "HSK3", Tone: "3"},
	{Hanzi: "角", Pinyin: "jiao3", Nghia: "góc", Level: "HSK3", Tone: "3"},
	{Hanzi: "接", Pinyin: "jie1", Nghia: "nhận", Level: "HSK3", Tone: "1"},
	{Hanzi: "街道", Pinyin: "jie1 dao4", Nghia: "phố", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "节目", Pinyin: "jie2 mu4", Nghia: "tiết mục, chương trình", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "节日", Pinyin: "jie2 ri4", Nghia: "kỳ nghỉ", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "结婚", Pinyin: "jie2 hun1", Nghia: "kết hôn", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "结束", Pinyin: "jie2 shu4", Nghia: "kết thúc", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "解决", Pinyin: "jie3 jue2", Nghia: "giải quyết", Level: "HSK3", Tone: "3 2"},
	{Hanzi: "借", Pinyin: "jie4", Nghia: "cho mượn", Level: "HSK3", Tone: "4"},
	{Hanzi: "经常", Pinyin: "jing1 chang2", Nghia: "thường xuyên", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "经过", Pinyin: "jing1 guo4", Nghia: "đi qua; trải qua", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "经理", Pinyin: "jing1 li3", Nghia: "quản lý", Level: "HSK3", Tone: "1 3"},
	{Hanzi: "久", Pinyin: "jiu3", Nghia: "lâu", Level: "HSK3", Tone: "3"},
	{Hanzi: "旧", Pinyin: "jiu4", Nghia: "cũ/già", Level: "HSK3", Tone: "4"},
	{Hanzi: "举行", Pinyin: "ju3 xing2", Nghia: "tổ chức (họp, lễ)", Level: "HSK3", Tone: "3 2"},
	{Hanzi: "句子", Pinyin: "ju4 zi5", Nghia: "câu", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "决定", Pinyin: "jue2 ding4", Nghia: "quyết định", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "渴", Pinyin: "ke3", Nghia: "khát", Level: "HSK3", Tone: "3"},
	{Hanzi: "可爱", Pinyin: "ke3 ai4", Nghia: "đáng yêu", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "刻", Pinyin: "ke4", Nghia: "mười lăm phút", Level: "HSK3", Tone: "4"},
	{Hanzi: "客人", Pinyin: "ke4 ren2", Nghia: "khách thăm", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "空调", Pinyin: "kong1 tiao2", Nghia: "điều hòa", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "口", Pinyin: "kou3", Nghia: "miệng", Level: "HSK3", Tone: "3"},
	{Hanzi: "哭", Pinyin: "ku1", Nghia: "khóc", Level: "HSK3", Tone: "1"},
	{Hanzi: "裤子", Pinyin: "ku4 zi5", Nghia: "quần dài", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "筷子", Pinyin: "kuai4 zi5", Nghia: "đũa", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "蓝", Pinyin: "lan2", Nghia: "xanh da trời", Level: "HSK3", Tone: "2"},
	{Hanzi: "老", Pinyin: "lao3", Nghia: "già; (tiền tố gọi thân mật)", Level: "HSK3", Tone: "3"},
	{Hanzi: "离开", Pinyin: "li2 kai1", Nghia: "rời khỏi", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "礼物", Pinyin: "li3 wu4", Nghia: "quà", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "历史", Pinyin: "li4 shi3", Nghia: "lịch sử", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "脸", Pinyin: "lian3", Nghia: "mặt", Level: "HSK3", Tone: "3"},
	{Hanzi: "练习", Pinyin: "lian4 xi2", Nghia: "luyện tập", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "辆", Pinyin: "liang4", Nghia: "lượng từ (xe cộ)", Level: "HSK3", Tone: "4"},
	{Hanzi: "了解", Pinyin: "liao3 jie3", Nghia: "hiểu", Level: "HSK3", Tone: "3 3"},
	{Hanzi: "邻居", Pinyin: "lin2 ju1", Nghia: "hàng xóm", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "楼", Pinyin: "lou2", Nghia: "tòa nhà, tầng lầu", Level: "HSK3", Tone: "2"},
	{Hanzi: "绿", Pinyin: "lü4", Nghia: "xanh lá", Level: "HSK3", Tone: "4"},
	{Hanzi: "马", Pinyin: "ma3", Nghia: "ngựa", Level: "HSK3", Tone: "3"},
	{Hanzi: "马上", Pinyin: "ma3 shang4", Nghia: "ngay lập tức", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "满意", Pinyin: "man3 yi4", Nghia: "hài lòng", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "帽子", Pinyin: "mao4 zi5", Nghia: "mũ", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "米", Pinyin: "mi3", Nghia: "gạo; mét", Level: "HSK3", Tone: "3"},
	{Hanzi: "面包", Pinyin: "mian4 bao1", Nghia: "bánh mì", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "面条", Pinyin: "mian4 tiao2", Nghia: "mì sợi", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "明白", Pinyin: "ming2 bai5", Nghia: "rõ ràng", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "拿", Pinyin: "na2", Nghia: "cầm, lấy", Level: "HSK3", Tone: "2"},
	{Hanzi: "奶奶", Pinyin: "nai3 nai5", Nghia: "bà", Level: "HSK3", Tone: "3 5"},
	{Hanzi: "南", Pinyin: "nan2", Nghia: "phía nam", Level: "HSK3", Tone: "2"},
	{Hanzi: "难", Pinyin: "nan2", Nghia: "khó", Level: "HSK3", Tone: "2"},
	{Hanzi: "难过", Pinyin: "nan2 guo4", Nghia: "cảm thấy buồn", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "年级", Pinyin: "nian2 ji2", Nghia: "khối lớp", Level: "HSK3", Tone: "2 2"},
	{Hanzi: "年轻", Pinyin: "nian2 qing1", Nghia: "trẻ", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "鸟", Pinyin: "niao3", Nghia: "chim", Level: "HSK3", Tone: "3"},
	{Hanzi: "努力", Pinyin: "nu3 li4", Nghia: "nỗ lực", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "爬山", Pinyin: "pa2 shan1", Nghia: "leo núi", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "盘子", Pinyin: "pan2 zi5", Nghia: "khay", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "胖", Pinyin: "pang4", Nghia: "béo", Level: "HSK3", Tone: "4"},
	{Hanzi: "啤酒", Pinyin: "pi2 jiu3", Nghia: "bia", Level: "HSK3", Tone: "2 3"},
	{Hanzi: "葡萄", Pinyin: "pu2 tao5", Nghia: "nho", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "普通话", Pinyin: "pu3 tong1 hua4", Nghia: "tiếng phổ thông", Level: "HSK3", Tone: "3 1 4"},
	{Hanzi: "骑", Pinyin: "qi2", Nghia: "cưỡi/đi xe", Level: "HSK3", Tone: "2"},
	{Hanzi: "其实", Pinyin: "qi2 shi2", Nghia: "thật ra", Level: "HSK3", Tone: "2 2"},
	{Hanzi: "其他", Pinyin: "qi2 ta1", Nghia: "khác, còn lại", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "奇怪", Pinyin: "qi2 guai4", Nghia: "lạ", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "铅笔", Pinyin: "qian1 bi3", Nghia: "bút chì", Level: "HSK3", Tone: "1 3"},
	{Hanzi: "清楚", Pinyin: "qing1 chu5", Nghia: "rõ ràng", Level: "HSK3", Tone: "1 5"},
	{Hanzi: "秋", Pinyin: "qiu1", Nghia: "mùa thu", Level: "HSK3", Tone: "1"},
	{Hanzi: "裙子", Pinyin: "qun2 zi5", Nghia: "chân váy", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "然后", Pinyin: "ran2 hou4", Nghia: "sau đó", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "热情", Pinyin: "re4 qing2", Nghia: "nồng hậu", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "认为", Pinyin: "ren4 wei2", Nghia: "cho rằng", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "认真", Pinyin: "ren4 zhen1", Nghia: "tận tâm", Level: "HSK3", Tone: "4 1"},
	{Hanzi: "容易", Pinyin: "rong2 yi4", Nghia: "dễ", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "如果", Pinyin: "ru2 guo3", Nghia: "nếu", Level: "HSK3", Tone: "2 3"},
	{Hanzi: "伞", Pinyin: "san3", Nghia: "ô/dù", Level: "HSK3", Tone: "3"},
	{Hanzi: "上网", Pinyin: "shang4 wang3", Nghia: "lên mạng", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "生气", Pinyin: "sheng1 qi4", Nghia: "tức giận", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "声音", Pinyin: "sheng1 yin1", Nghia: "tiếng, giọng", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "使", Pinyin: "shi3", Nghia: "khiến, làm cho", Level: "HSK3", Tone: "3"},
	{Hanzi: "世界", Pinyin: "shi4 jie4", Nghia: "thế giới", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "瘦", Pinyin: "shou4", Nghia: "gầy", Level: "HSK3", Tone: "4"},
	{Hanzi: "舒服", Pinyin: "shu1 fu5", Nghia: "thoải mái", Level: "HSK3", Tone: "1 5"},
	{Hanzi: "叔叔", Pinyin: "shu1 shu5", Nghia: "chú", Level: "HSK3", Tone: "1 5"},
	{Hanzi: "树", Pinyin: "shu4", Nghia: "cây", Level: "HSK3", Tone: "4"},
	{Hanzi: "数学", Pinyin: "shu4 xue2", Nghia: "toán học", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "刷", Pinyin: "shua1", Nghia: "chải/đánh", Level: "HSK3", Tone: "1"},
	{Hanzi: "双", Pinyin: "shuang1", Nghia: "đôi", Level: "HSK3", Tone: "1"},
	{Hanzi: "水平", Pinyin: "shui3 ping2", Nghia: "trình độ", Level: "HSK3", Tone: "3 2"},
	{Hanzi: "司机", Pinyin: "si1 ji1", Nghia: "tài xế", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "虽然", Pinyin: "sui1 ran2", Nghia: "mặc dù", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "太阳", Pinyin: "tai4 yang2", Nghia: "mặt trời", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "糖", Pinyin: "tang2", Nghia: "đường", Level: "HSK3", Tone: "2"},
	{Hanzi: "特别", Pinyin: "te4 bie2", Nghia: "đặc biệt", Level: "HSK3", Tone: "4 2"},
	{Hanzi: "疼", Pinyin: "teng2", Nghia: "đau", Level: "HSK3", Tone: "2"},
	{Hanzi: "提高", Pinyin: "ti2 gao1", Nghia: "nâng cao", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "体育", Pinyin: "ti3 yu4", Nghia: "thể dục thể thao", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "甜", Pinyin: "tian2", Nghia: "ngọt", Level: "HSK3", Tone: "2"},
	{Hanzi: "条", Pinyin: "tiao2", Nghia: "sợi, con (lượng từ vật dài)", Level: "HSK3", Tone: "2"},
	{Hanzi: "同事", Pinyin: "tong2 shi4", Nghia: "đồng nghiệp", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "同意", Pinyin: "tong2 yi4", Nghia: "đồng ý", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "头发", Pinyin: "tou2 fa5", Nghia: "tóc", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "突然", Pinyin: "tu1 ran2", Nghia: "đột ngột", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "图书馆", Pinyin: "tu2 shu1 guan3", Nghia: "thư viện", Level: "HSK3", Tone: "2 1 3"},
	{Hanzi: "腿", Pinyin: "tui3", Nghia: "chân", Level: "HSK3", Tone: "3"},
	{Hanzi: "完成", Pinyin: "wan2 cheng2", Nghia: "hoàn thành", Level: "HSK3", Tone: "2 2"},
	{Hanzi: "碗", Pinyin: "wan3", Nghia: "bát", Level: "HSK3", Tone: "3"},
	{Hanzi: "万", Pinyin: "wan4", Nghia: "vạn", Level: "HSK3", Tone: "4"},
	{Hanzi: "忘记", Pinyin: "wang4 ji4", Nghia: "quên", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "为了", Pinyin: "wei4 le5", Nghia: "để, vì", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "为什么", Pinyin: "wei4 shen2 me5", Nghia: "tại sao", Level: "HSK3", Tone: "4 2 5"},
	{Hanzi: "位", Pinyin: "wei4", Nghia: "chỗ, vị", Level: "HSK3", Tone: "4"},
	{Hanzi: "文化", Pinyin: "wen2 hua4", Nghia: "văn hóa", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "西", Pinyin: "xi1", Nghia: "phía tây", Level: "HSK3", Tone: "1"},
	{Hanzi: "习惯", Pinyin: "xi2 guan4", Nghia: "thói quen", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "洗手间", Pinyin: "xi3 shou3 jian1", Nghia: "nhà vệ sinh", Level: "HSK3", Tone: "3 3 1"},
	{Hanzi: "洗澡", Pinyin: "xi3 zao3", Nghia: "tắm", Level: "HSK3", Tone: "3 3"},
	{Hanzi: "夏", Pinyin: "xia4", Nghia: "mùa hè", Level: "HSK3", Tone: "4"},
	{Hanzi: "先", Pinyin: "xian1", Nghia: "trước", Level: "HSK3", Tone: "1"},
	{Hanzi: "香蕉", Pinyin: "xiang1 jiao1", Nghia: "chuối", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "相同", Pinyin: "xiang1 tong2", Nghia: "giống hệt", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "相信", Pinyin: "xiang1 xin4", Nghia: "tin tưởng", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "像", Pinyin: "xiang4", Nghia: "giống như", Level: "HSK3", Tone: "4"},
	{Hanzi: "小心", Pinyin: "xiao3 xin1", Nghia: "cẩn thận", Level: "HSK3", Tone: "3 1"},
	{Hanzi: "校长", Pinyin: "xiao4 zhang3", Nghia: "hiệu trưởng", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "鞋", Pinyin: "xie2", Nghia: "giày", Level: "HSK3", Tone: "2"},
	{Hanzi: "新闻", Pinyin: "xin1 wen2", Nghia: "tin tức", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "新鲜", Pinyin: "xin1 xian1", Nghia: "tươi", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "信", Pinyin: "xin4", Nghia: "thư", Level: "HSK3", Tone: "4"},
	{Hanzi: "行李箱", Pinyin: "xing2 li5 xiang1", Nghia: "va li", Level: "HSK3", Tone: "2 5 1"},
	{Hanzi: "兴趣", Pinyin: "xing4 qu4", Nghia: "hứng thú", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "熊猫", Pinyin: "xiong2 mao1", Nghia: "gấu trúc", Level: "HSK3", Tone: "2 1"},
	{Hanzi: "需要", Pinyin: "xu1 yao4", Nghia: "cần", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "选择", Pinyin: "xuan3 ze2", Nghia: "chọn", Level: "HSK3", Tone: "3 2"},
	{Hanzi: "眼镜", Pinyin: "yan3 jing4", Nghia: "kính đeo mắt", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "要求", Pinyin: "yao1 qiu2", Nghia: "thỉnh cầu", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "爷爷", Pinyin: "ye2 ye5", Nghia: "ông nội", Level: "HSK3", Tone: "2 5"},
	{Hanzi: "一定", Pinyin: "yi1 ding4", Nghia: "chắc chắn", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "一共", Pinyin: "yi1 gong4", Nghia: "tổng cộng", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "一会儿", Pinyin: "yi1 hui4 r5", Nghia: "một lát", Level: "HSK3", Tone: "1 4 5"},
	{Hanzi: "一样", Pinyin: "yi1 yang4", Nghia: "giống nhau", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "以后", Pinyin: "yi3 hou4", Nghia: "sau này, về sau", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "以前", Pinyin: "yi3 qian2", Nghia: "trước đây", Level: "HSK3", Tone: "3 2"},
	{Hanzi: "以为", Pinyin: "yi3 wei2", Nghia: "cho rằng, tưởng là", Level: "HSK3", Tone: "3 2"},
	{Hanzi: "一般", Pinyin: "yi1 ban1", Nghia: "bình thường, thông thường", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "一边", Pinyin: "yi1 bian1", Nghia: "một bên; vừa... vừa...", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "一直", Pinyin: "yi1 zhi2", Nghia: "thẳng", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "音乐", Pinyin: "yin1 yue4", Nghia: "âm nhạc", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "银行", Pinyin: "yin2 hang2", Nghia: "ngân hàng", Level: "HSK3", Tone: "2 2"},
	{Hanzi: "应该", Pinyin: "ying1 gai1", Nghia: "nên, phải", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "影响", Pinyin: "ying3 xiang3", Nghia: "ảnh hưởng", Level: "HSK3", Tone: "3 3"},
	{Hanzi: "用", Pinyin: "yong4", Nghia: "dùng", Level: "HSK3", Tone: "4"},
	{Hanzi: "游戏", Pinyin: "you2 xi4", Nghia: "trò chơi", Level: "HSK3", Tone: "2 4"},
	{Hanzi: "有名", Pinyin: "you3 ming2", Nghia: "nổi tiếng", Level: "HSK3", Tone: "3 2"},
	{Hanzi: "又", Pinyin: "you4", Nghia: "lại (đã lặp)", Level: "HSK3", Tone: "4"},
	{Hanzi: "遇到", Pinyin: "yu4 dao4", Nghia: "gặp", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "愿意", Pinyin: "yuan4 yi4", Nghia: "đồng ý, muốn, sẵn lòng", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "越", Pinyin: "yue4", Nghia: "vượt qua; (càng... càng...)", Level: "HSK3", Tone: "4"},
	{Hanzi: "月亮", Pinyin: "yue4 liang5", Nghia: "mặt trăng", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "云", Pinyin: "yun2", Nghia: "mây", Level: "HSK3", Tone: "2"},
	{Hanzi: "站", Pinyin: "zhan4", Nghia: "trạm; đứng", Level: "HSK3", Tone: "4"},
	{Hanzi: "着急", Pinyin: "zhao2 ji2", Nghia: "lo lắng", Level: "HSK3", Tone: "2 2"},
	{Hanzi: "照顾", Pinyin: "zhao4 gu5", Nghia: "chăm sóc", Level: "HSK3", Tone: "4 5"},
	{Hanzi: "照片", Pinyin: "zhao4 pian4", Nghia: "ảnh chụp", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "照相机", Pinyin: "zhao4 xiang4 ji1", Nghia: "máy ảnh", Level: "HSK3", Tone: "4 4 1"},
	{Hanzi: "只", Pinyin: "zhi3", Nghia: "chỉ (duy nhất)", Level: "HSK3", Tone: "3"},
	{Hanzi: "终于", Pinyin: "zhong1 yu2", Nghia: "cuối cùng", Level: "HSK3", Tone: "1 2"},
	{Hanzi: "中间", Pinyin: "zhong1 jian1", Nghia: "giữa", Level: "HSK3", Tone: "1 1"},
	{Hanzi: "种", Pinyin: "zhong3", Nghia: "loại; gieo trồng", Level: "HSK3", Tone: "3"},
	{Hanzi: "重要", Pinyin: "zhong4 yao4", Nghia: "quan trọng", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "周末", Pinyin: "zhou1 mo4", Nghia: "cuối tuần", Level: "HSK3", Tone: "1 4"},
	{Hanzi: "主要", Pinyin: "zhu3 yao4", Nghia: "chủ yếu", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "祝", Pinyin: "zhu4", Nghia: "chúc", Level: "HSK3", Tone: "4"},
	{Hanzi: "注意", Pinyin: "zhu4 yi4", Nghia: "chú ý", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "字典", Pinyin: "zi4 dian3", Nghia: "từ điển", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "自己", Pinyin: "zi4 ji3", Nghia: "bản thân, tự mình", Level: "HSK3", Tone: "4 3"},
	{Hanzi: "总是", Pinyin: "zong3 shi4", Nghia: "luôn luôn", Level: "HSK3", Tone: "3 4"},
	{Hanzi: "最近", Pinyin: "zui4 jin4", Nghia: "gần đây", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "作业", Pinyin: "zuo4 ye4", Nghia: "bài tập (về nhà)", Level: "HSK3", Tone: "4 4"},
	{Hanzi: "作用", Pinyin: "zuo4 yong4", Nghia: "tác dụng", Level: "HSK3", Tone: "4 4"},
}

// hsk4Seed — seed HSK4.
var hsk4Seed = []HskEntry{
	{Hanzi: "爱情", Pinyin: "ai4 qing2", Nghia: "tình yêu (nam nữ)", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "安排", Pinyin: "an1 pai2", Nghia: "sắp xếp", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "安全", Pinyin: "an1 quan2", Nghia: "an toàn", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "暗", Pinyin: "an4", Nghia: "tối, u ám", Level: "HSK4", Tone: "4"},
	{Hanzi: "按时", Pinyin: "an4 shi2", Nghia: "đúng giờ", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "按照", Pinyin: "an4 zhao4", Nghia: "theo", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "包括", Pinyin: "bao1 kuo4", Nghia: "bao gồm", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "保护", Pinyin: "bao3 hu4", Nghia: "bảo vệ", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "保证", Pinyin: "bao3 zheng4", Nghia: "bảo đảm", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "抱", Pinyin: "bao4", Nghia: "cầm/nắm", Level: "HSK4", Tone: "4"},
	{Hanzi: "抱歉", Pinyin: "bao4 qian4", Nghia: "là tiếc/xin lỗi", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "报道", Pinyin: "bao4 dao4", Nghia: "báo cáo", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "报名", Pinyin: "bao4 ming2", Nghia: "đăng ký", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "倍", Pinyin: "bei4", Nghia: "gấp (bội số)", Level: "HSK4", Tone: "4"},
	{Hanzi: "本来", Pinyin: "ben3 lai2", Nghia: "vốn có", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "笨", Pinyin: "ben4", Nghia: "ngốc, đần", Level: "HSK4", Tone: "4"},
	{Hanzi: "笔记本", Pinyin: "bi3 ji4 ben3", Nghia: "vở", Level: "HSK4", Tone: "3 4 3"},
	{Hanzi: "毕业", Pinyin: "bi4 ye4", Nghia: "tốt nghiệp", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "遍", Pinyin: "bian4", Nghia: "khắp nơi", Level: "HSK4", Tone: "4"},
	{Hanzi: "标准", Pinyin: "biao1 zhun3", Nghia: "tiêu chuẩn", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "表达", Pinyin: "biao3 da2", Nghia: "bày tỏ", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "表格", Pinyin: "biao3 ge2", Nghia: "biểu mẫu", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "表扬", Pinyin: "biao3 yang2", Nghia: "khen ngợi", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "饼干", Pinyin: "bing3 gan1", Nghia: "bánh quy", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "并且", Pinyin: "bing4 qie3", Nghia: "và", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "博士", Pinyin: "bo2 shi4", Nghia: "tiến sĩ", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "不但", Pinyin: "bu4 dan4", Nghia: "không những", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "不过", Pinyin: "bu4 guo4", Nghia: "chẳng qua, có điều là", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "不得不", Pinyin: "bu4 de2 bu4", Nghia: "đành phải", Level: "HSK4", Tone: "4 2 4"},
	{Hanzi: "不管", Pinyin: "bu4 guan3", Nghia: "bất kể, dù", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "不仅", Pinyin: "bu4 jin3", Nghia: "không chỉ", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "部分", Pinyin: "bu4 fen5", Nghia: "bộ phận", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "擦", Pinyin: "ca1", Nghia: "lau, chùi", Level: "HSK4", Tone: "1"},
	{Hanzi: "猜", Pinyin: "cai1", Nghia: "đoán", Level: "HSK4", Tone: "1"},
	{Hanzi: "材料", Pinyin: "cai2 liao4", Nghia: "tài liệu, nguyên liệu", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "参观", Pinyin: "can1 guan1", Nghia: "tham quan", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "差不多", Pinyin: "cha4 bu5 duo1", Nghia: "gần như, suýt soát", Level: "HSK4", Tone: "4 5 1"},
	{Hanzi: "长城", Pinyin: "chang2 cheng2", Nghia: "Vạn Lý Trường Thành", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "长江", Pinyin: "chang2 jiang1", Nghia: "sông Dương Tử", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "尝", Pinyin: "chang2", Nghia: "nếm thử", Level: "HSK4", Tone: "2"},
	{Hanzi: "场", Pinyin: "chang3", Nghia: "nơi, bãi", Level: "HSK4", Tone: "3"},
	{Hanzi: "超过", Pinyin: "chao1 guo4", Nghia: "vượt quá", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "吵", Pinyin: "chao3", Nghia: "cãi nhau", Level: "HSK4", Tone: "3"},
	{Hanzi: "乘坐", Pinyin: "cheng2 zuo4", Nghia: "cưỡi/đi xe", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "成功", Pinyin: "cheng2 gong1", Nghia: "thành công", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "成熟", Pinyin: "cheng2 shu2", Nghia: "chững chạc", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "成为", Pinyin: "cheng2 wei2", Nghia: "trở thành", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "诚实", Pinyin: "cheng2 shi2", Nghia: "thật thà", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "吃惊", Pinyin: "chi1 jing1", Nghia: "giật mình, kinh ngạc", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "重新", Pinyin: "chong2 xin1", Nghia: "lại", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "抽烟", Pinyin: "chou1 yan1", Nghia: "hút thuốc", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "出差", Pinyin: "chu1 chai1", Nghia: "đi công tác", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "出发", Pinyin: "chu1 fa1", Nghia: "xuất phát", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "出生", Pinyin: "chu1 sheng1", Nghia: "ra đời, sinh ra", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "传真", Pinyin: "chuan2 zhen1", Nghia: "bản fax", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "窗户", Pinyin: "chuang1 hu5", Nghia: "cửa sổ", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "词典", Pinyin: "ci2 dian3", Nghia: "từ điển", Level: "HSK4", Tone: "2 3"},
	{Hanzi: "从来", Pinyin: "cong2 lai2", Nghia: "từ trước tới nay (luôn)", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "粗心", Pinyin: "cu1 xin1", Nghia: "cẩu thả", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "答案", Pinyin: "da2 an4", Nghia: "đáp án", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "打扮", Pinyin: "da3 ban5", Nghia: "ăn diện", Level: "HSK4", Tone: "3 5"},
	{Hanzi: "打扰", Pinyin: "da3 rao3", Nghia: "làm phiền", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "打印", Pinyin: "da3 yin4", Nghia: "in ấn", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "打折", Pinyin: "da3 zhe2", Nghia: "giảm giá", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "打针", Pinyin: "da3 zhen1", Nghia: "tiêm (thuốc)", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "大概", Pinyin: "da4 gai4", Nghia: "khoảng, đại khái", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "大使馆", Pinyin: "da4 shi3 guan3", Nghia: "đại sứ quán", Level: "HSK4", Tone: "4 3 3"},
	{Hanzi: "大约", Pinyin: "da4 yue1", Nghia: "khoảng chừng", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "戴", Pinyin: "dai4", Nghia: "đeo, đội", Level: "HSK4", Tone: "4"},
	{Hanzi: "代表", Pinyin: "dai4 biao3", Nghia: "đại diện, đại biểu", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "代替", Pinyin: "dai4 ti4", Nghia: "thay thế", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "大夫", Pinyin: "dai4 fu5", Nghia: "bác sĩ", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "当", Pinyin: "dang1", Nghia: "làm, đảm nhiệm", Level: "HSK4", Tone: "1"},
	{Hanzi: "当地", Pinyin: "dang1 di4", Nghia: "địa phương, bản địa", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "当时", Pinyin: "dang1 shi2", Nghia: "lúc ấy", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "刀", Pinyin: "dao1", Nghia: "con dao", Level: "HSK4", Tone: "1"},
	{Hanzi: "导游", Pinyin: "dao3 you2", Nghia: "hướng dẫn viên du lịch", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "到处", Pinyin: "dao4 chu4", Nghia: "khắp nơi", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "到底", Pinyin: "dao4 di3", Nghia: "rốt cuộc", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "道歉", Pinyin: "dao4 qian4", Nghia: "xin lỗi", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "得意", Pinyin: "de2 yi4", Nghia: "đắc ý", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "等", Pinyin: "deng3", Nghia: "đợi; hạng", Level: "HSK4", Tone: "3"},
	{Hanzi: "底", Pinyin: "di3", Nghia: "đáy, nền", Level: "HSK4", Tone: "3"},
	{Hanzi: "地球", Pinyin: "di4 qiu2", Nghia: "trái đất", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "地址", Pinyin: "di4 zhi3", Nghia: "địa chỉ", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "掉", Pinyin: "diao4", Nghia: "ngã/rơi", Level: "HSK4", Tone: "4"},
	{Hanzi: "调查", Pinyin: "diao4 cha2", Nghia: "điều tra", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "丢", Pinyin: "diu1", Nghia: "mất", Level: "HSK4", Tone: "1"},
	{Hanzi: "动作", Pinyin: "dong4 zuo4", Nghia: "động tác", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "堵车", Pinyin: "du3 che1", Nghia: "tắc đường", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "肚子", Pinyin: "du4 zi5", Nghia: "bụng", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "断", Pinyin: "duan4", Nghia: "vỡ/gãy", Level: "HSK4", Tone: "4"},
	{Hanzi: "对", Pinyin: "dui4", Nghia: "đúng; đôi; với", Level: "HSK4", Tone: "4"},
	{Hanzi: "对话", Pinyin: "dui4 hua4", Nghia: "đối thoại", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "对面", Pinyin: "dui4 mian4", Nghia: "đối diện", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "顿", Pinyin: "dun4", Nghia: "dừng", Level: "HSK4", Tone: "4"},
	{Hanzi: "朵", Pinyin: "duo3", Nghia: "hoa", Level: "HSK4", Tone: "3"},
	{Hanzi: "而", Pinyin: "er2", Nghia: "mà, nhưng (nối câu)", Level: "HSK4", Tone: "2"},
	{Hanzi: "儿童", Pinyin: "er2 tong2", Nghia: "trẻ em", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "发", Pinyin: "fa1", Nghia: "phát ra", Level: "HSK4", Tone: "1"},
	{Hanzi: "发生", Pinyin: "fa1 sheng1", Nghia: "xảy ra", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "发展", Pinyin: "fa1 zhan3", Nghia: "phát triển", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "法律", Pinyin: "fa3 lü4", Nghia: "pháp luật", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "翻译", Pinyin: "fan1 yi4", Nghia: "biên dịch, phiên dịch", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "烦恼", Pinyin: "fan2 nao3", Nghia: "buồn phiền", Level: "HSK4", Tone: "2 3"},
	{Hanzi: "反对", Pinyin: "fan3 dui4", Nghia: "phản đối", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "反映", Pinyin: "fan3 ying4", Nghia: "phản ánh", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "范围", Pinyin: "fan4 wei2", Nghia: "phạm vi", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "方法", Pinyin: "fang1 fa3", Nghia: "phương pháp", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "方面", Pinyin: "fang1 mian4", Nghia: "mặt, phương diện", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "方向", Pinyin: "fang1 xiang4", Nghia: "hướng", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "访问", Pinyin: "fang3 wen4", Nghia: "thăm (chính thức)", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "放弃", Pinyin: "fang4 qi4", Nghia: "từ bỏ", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "放暑假", Pinyin: "fang4 shu3 jia4", Nghia: "nghỉ hè", Level: "HSK4", Tone: "4 3 4"},
	{Hanzi: "分之", Pinyin: "fen1 zhi1", Nghia: "phần (chỉ phân số)", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "份", Pinyin: "fen4", Nghia: "suất, phần (lượng từ)", Level: "HSK4", Tone: "4"},
	{Hanzi: "风景", Pinyin: "feng1 jing3", Nghia: "phong cảnh", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "丰富", Pinyin: "feng1 fu4", Nghia: "phong phú", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "否则", Pinyin: "fou3 ze2", Nghia: "nếu không", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "符合", Pinyin: "fu2 he2", Nghia: "phù hợp", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "富", Pinyin: "fu4", Nghia: "giàu", Level: "HSK4", Tone: "4"},
	{Hanzi: "负责", Pinyin: "fu4 ze2", Nghia: "phụ trách", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "复印", Pinyin: "fu4 yin4", Nghia: "phô-tô", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "复杂", Pinyin: "fu4 za2", Nghia: "phức tạp", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "父亲", Pinyin: "fu4 qin1", Nghia: "bố", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "改变", Pinyin: "gai3 bian4", Nghia: "đổi/thay đổi", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "干杯", Pinyin: "gan1 bei1", Nghia: "cạn ly", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "干燥", Pinyin: "gan1 zao4", Nghia: "khô hanh", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "感动", Pinyin: "gan3 dong4", Nghia: "cảm động", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "感觉", Pinyin: "gan3 jue2", Nghia: "cảm giác", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "感情", Pinyin: "gan3 qing2", Nghia: "tình cảm", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "感谢", Pinyin: "gan3 xie4", Nghia: "cảm ơn", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "干", Pinyin: "gan4", Nghia: "khô; làm", Level: "HSK4", Tone: "4"},
	{Hanzi: "刚刚", Pinyin: "gang1 gang5", Nghia: "vừa mới", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "高级", Pinyin: "gao1 ji2", Nghia: "cao cấp", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "个子", Pinyin: "ge4 zi5", Nghia: "chiều cao", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "各", Pinyin: "ge4", Nghia: "mỗi", Level: "HSK4", Tone: "4"},
	{Hanzi: "公里", Pinyin: "gong1 li3", Nghia: "ki-lô-mét", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "工具", Pinyin: "gong1 ju4", Nghia: "công cụ", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "工资", Pinyin: "gong1 zi1", Nghia: "tiền lương", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "共同", Pinyin: "gong4 tong2", Nghia: "chung", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "够", Pinyin: "gou4", Nghia: "đủ", Level: "HSK4", Tone: "4"},
	{Hanzi: "购物", Pinyin: "gou4 wu4", Nghia: "mua sắm", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "孤单", Pinyin: "gu1 dan1", Nghia: "cô đơn", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "估计", Pinyin: "gu1 ji4", Nghia: "ước tính", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "鼓励", Pinyin: "gu3 li4", Nghia: "động viên", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "鼓掌", Pinyin: "gu3 zhang3", Nghia: "vỗ tay", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "顾客", Pinyin: "gu4 ke4", Nghia: "khách hàng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "故意", Pinyin: "gu4 yi4", Nghia: "cố ý", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "挂", Pinyin: "gua4", Nghia: "treo", Level: "HSK4", Tone: "4"},
	{Hanzi: "关键", Pinyin: "guan1 jian4", Nghia: "then chốt", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "观众", Pinyin: "guan1 zhong4", Nghia: "khán giả", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "管理", Pinyin: "guan3 li3", Nghia: "quản lý", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "光", Pinyin: "guang1", Nghia: "ánh sáng", Level: "HSK4", Tone: "1"},
	{Hanzi: "广播", Pinyin: "guang3 bo1", Nghia: "phát thanh", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "广告", Pinyin: "guang3 gao4", Nghia: "quảng cáo", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "逛", Pinyin: "guang4", Nghia: "đi dạo", Level: "HSK4", Tone: "4"},
	{Hanzi: "规定", Pinyin: "gui1 ding4", Nghia: "quy định", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "国际", Pinyin: "guo2 ji4", Nghia: "quốc tế", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "果然", Pinyin: "guo3 ran2", Nghia: "quả nhiên", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "过", Pinyin: "guo4", Nghia: "đã từng, qua", Level: "HSK4", Tone: "4"},
	{Hanzi: "过程", Pinyin: "guo4 cheng2", Nghia: "quá trình", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "海洋", Pinyin: "hai3 yang2", Nghia: "đại dương", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "害羞", Pinyin: "hai4 xiu1", Nghia: "ngượng ngùng", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "寒假", Pinyin: "han2 jia4", Nghia: "nghỉ đông", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "汗", Pinyin: "han4", Nghia: "mồ hôi", Level: "HSK4", Tone: "4"},
	{Hanzi: "航班", Pinyin: "hang2 ban1", Nghia: "chuyến bay", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "好处", Pinyin: "hao3 chu5", Nghia: "lợi ích", Level: "HSK4", Tone: "3 5"},
	{Hanzi: "好像", Pinyin: "hao3 xiang4", Nghia: "hình như", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "号码", Pinyin: "hao4 ma3", Nghia: "số", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "合格", Pinyin: "he2 ge2", Nghia: "đạt chuẩn", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "合适", Pinyin: "he2 shi4", Nghia: "phù hợp", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "盒子", Pinyin: "he2 zi5", Nghia: "cái hộp", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "猴子", Pinyin: "hou2 zi5", Nghia: "khỉ", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "厚", Pinyin: "hou4", Nghia: "dày", Level: "HSK4", Tone: "4"},
	{Hanzi: "后悔", Pinyin: "hou4 hui3", Nghia: "hối hận", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "后来", Pinyin: "hou4 lai2", Nghia: "sau này", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "忽然", Pinyin: "hu1 ran2", Nghia: "bỗng nhiên", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "互相", Pinyin: "hu4 xiang1", Nghia: "lẫn nhau", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "护士", Pinyin: "hu4 shi5", Nghia: "y tá", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "怀疑", Pinyin: "huai2 yi2", Nghia: "nghi ngờ", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "回忆", Pinyin: "hui2 yi4", Nghia: "hồi tưởng", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "活动", Pinyin: "huo2 dong4", Nghia: "hoạt động", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "活泼", Pinyin: "huo2 po5", Nghia: "sôi nổi", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "火", Pinyin: "huo3", Nghia: "lửa", Level: "HSK4", Tone: "3"},
	{Hanzi: "获得", Pinyin: "huo4 de2", Nghia: "giành được", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "基础", Pinyin: "ji1 chu3", Nghia: "nền tảng", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "激动", Pinyin: "ji1 dong4", Nghia: "xúc động", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "积极", Pinyin: "ji1 ji2", Nghia: "tích cực", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "积累", Pinyin: "ji1 lei3", Nghia: "tích lũy", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "极其", Pinyin: "ji2 qi2", Nghia: "vô cùng, cực kỳ", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "即使", Pinyin: "ji2 shi3", Nghia: "dù cho, cho dù", Level: "HSK4", Tone: "2 3"},
	{Hanzi: "及时", Pinyin: "ji2 shi2", Nghia: "kịp thời", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "集合", Pinyin: "ji2 he2", Nghia: "tập hợp", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "寄", Pinyin: "ji4", Nghia: "gửi", Level: "HSK4", Tone: "4"},
	{Hanzi: "继续", Pinyin: "ji4 xu4", Nghia: "tiếp tục", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "记者", Pinyin: "ji4 zhe3", Nghia: "phóng viên", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "计划", Pinyin: "ji4 hua4", Nghia: "lên kế hoạch", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "技术", Pinyin: "ji4 shu4", Nghia: "kỹ thuật", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "既然", Pinyin: "ji4 ran2", Nghia: "đã... thì", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "家具", Pinyin: "jia1 ju4", Nghia: "đồ nội thất", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "加班", Pinyin: "jia1 ban1", Nghia: "làm thêm giờ", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "加油站", Pinyin: "jia1 you2 zhan4", Nghia: "trạm xăng", Level: "HSK4", Tone: "1 2 4"},
	{Hanzi: "假", Pinyin: "jia3", Nghia: "giả", Level: "HSK4", Tone: "3"},
	{Hanzi: "价格", Pinyin: "jia4 ge2", Nghia: "giá", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "坚持", Pinyin: "jian1 chi2", Nghia: "kiên trì", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "减肥", Pinyin: "jian3 fei2", Nghia: "giảm cân", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "减少", Pinyin: "jian3 shao3", Nghia: "giảm bớt", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "将来", Pinyin: "jiang1 lai2", Nghia: "trong tương lai", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "奖金", Pinyin: "jiang3 jin1", Nghia: "tiền thưởng", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "降低", Pinyin: "jiang4 di1", Nghia: "hạ xuống", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "交", Pinyin: "jiao1", Nghia: "giao, nộp", Level: "HSK4", Tone: "1"},
	{Hanzi: "交流", Pinyin: "jiao1 liu2", Nghia: "giao lưu, trao đổi", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "交通", Pinyin: "jiao1 tong1", Nghia: "giao thông", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "骄傲", Pinyin: "jiao1 ao4", Nghia: "kiêu ngạo; tự hào", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "饺子", Pinyin: "jiao3 zi5", Nghia: "bánh chẻo", Level: "HSK4", Tone: "3 5"},
	{Hanzi: "教授", Pinyin: "jiao4 shou4", Nghia: "giáo sư", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "教育", Pinyin: "jiao4 yu4", Nghia: "giáo dục", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "接受", Pinyin: "jie1 shou4", Nghia: "tiếp nhận", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "节约", Pinyin: "jie2 yue1", Nghia: "tiết kiệm", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "结果", Pinyin: "jie2 guo3", Nghia: "kết quả", Level: "HSK4", Tone: "2 3"},
	{Hanzi: "解释", Pinyin: "jie3 shi4", Nghia: "giải thích", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "紧张", Pinyin: "jin3 zhang1", Nghia: "hồi hộp", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "尽管", Pinyin: "jin3 guan3", Nghia: "mặc dù, cứ việc", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "进行", Pinyin: "jin4 xing2", Nghia: "tiến hành", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "禁止", Pinyin: "jin4 zhi3", Nghia: "cấm", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "精彩", Pinyin: "jing1 cai3", Nghia: "xuất sắc, đặc sắc", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "精神", Pinyin: "jing1 shen2", Nghia: "tinh thần", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "经济", Pinyin: "jing1 ji4", Nghia: "kinh tế", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "经历", Pinyin: "jing1 li4", Nghia: "trải qua", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "经验", Pinyin: "jing1 yan4", Nghia: "kinh nghiệm", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "京剧", Pinyin: "jing1 ju4", Nghia: "kinh kịch", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "警察", Pinyin: "jing3 cha2", Nghia: "công an", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "竟然", Pinyin: "jing4 ran2", Nghia: "không ngờ", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "竞争", Pinyin: "jing4 zheng1", Nghia: "thi đấu", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "镜子", Pinyin: "jing4 zi5", Nghia: "gương", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "究竟", Pinyin: "jiu1 jing4", Nghia: "rốt cuộc", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "举办", Pinyin: "ju3 ban4", Nghia: "tổ chức", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "拒绝", Pinyin: "ju4 jue2", Nghia: "từ chối", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "距离", Pinyin: "ju4 li2", Nghia: "khoảng cách", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "开玩笑", Pinyin: "kai1 wan2 xiao4", Nghia: "nói đùa", Level: "HSK4", Tone: "1 2 4"},
	{Hanzi: "看法", Pinyin: "kan4 fa3", Nghia: "cách nhìn, quan điểm", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "考虑", Pinyin: "kao3 lü4", Nghia: "cân nhắc", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "棵", Pinyin: "ke1", Nghia: "cây (lượng từ cây cối)", Level: "HSK4", Tone: "1"},
	{Hanzi: "科学", Pinyin: "ke1 xue2", Nghia: "khoa học", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "咳嗽", Pinyin: "ke2 sou5", Nghia: "ho", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "可怜", Pinyin: "ke3 lian2", Nghia: "đáng thương", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "可是", Pinyin: "ke3 shi4", Nghia: "nhưng mà", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "可惜", Pinyin: "ke3 xi1", Nghia: "tiếc quá", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "肯定", Pinyin: "ken3 ding4", Nghia: "chắc chắn", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "空气", Pinyin: "kong1 qi4", Nghia: "không khí", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "恐怕", Pinyin: "kong3 pa4", Nghia: "e rằng, sợ rằng", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "苦", Pinyin: "ku3", Nghia: "đắng", Level: "HSK4", Tone: "3"},
	{Hanzi: "宽", Pinyin: "kuan1", Nghia: "rộng", Level: "HSK4", Tone: "1"},
	{Hanzi: "困", Pinyin: "kun4", Nghia: "buồn ngủ", Level: "HSK4", Tone: "4"},
	{Hanzi: "困难", Pinyin: "kun4 nan5", Nghia: "khó", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "扩大", Pinyin: "kuo4 da4", Nghia: "mở rộng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "拉", Pinyin: "la1", Nghia: "kéo", Level: "HSK4", Tone: "1"},
	{Hanzi: "垃圾桶", Pinyin: "la1 ji1 tong3", Nghia: "thùng rác", Level: "HSK4", Tone: "1 1 3"},
	{Hanzi: "辣", Pinyin: "la4", Nghia: "cay", Level: "HSK4", Tone: "4"},
	{Hanzi: "来不及", Pinyin: "lai2 bu5 ji2", Nghia: "không kịp", Level: "HSK4", Tone: "2 5 2"},
	{Hanzi: "来得及", Pinyin: "lai2 de5 ji2", Nghia: "kịp, còn kịp", Level: "HSK4", Tone: "2 5 2"},
	{Hanzi: "懒", Pinyin: "lan3", Nghia: "lười", Level: "HSK4", Tone: "3"},
	{Hanzi: "浪费", Pinyin: "lang4 fei4", Nghia: "lãng phí", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "浪漫", Pinyin: "lang4 man4", Nghia: "lãng mạn", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "老虎", Pinyin: "lao3 hu3", Nghia: "hổ", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "冷静", Pinyin: "leng3 jing4", Nghia: "bình tĩnh", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "礼貌", Pinyin: "li3 mao4", Nghia: "lễ phép", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "理发", Pinyin: "li3 fa4", Nghia: "cắt tóc", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "理解", Pinyin: "li3 jie3", Nghia: "lĩnh hội", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "理想", Pinyin: "li3 xiang3", Nghia: "lý tưởng", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "厉害", Pinyin: "li4 hai5", Nghia: "giỏi; dữ dội, kinh khủng", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "力气", Pinyin: "li4 qi5", Nghia: "sức lực", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "例如", Pinyin: "li4 ru2", Nghia: "ví dụ như", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "俩", Pinyin: "lia3", Nghia: "hai (khẩu ngữ)", Level: "HSK4", Tone: "3"},
	{Hanzi: "连", Pinyin: "lian2", Nghia: "nối, liền; cả... cũng...", Level: "HSK4", Tone: "2"},
	{Hanzi: "联系", Pinyin: "lian2 xi4", Nghia: "liên hệ", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "凉快", Pinyin: "liang2 kuai5", Nghia: "mát mẻ", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "亮", Pinyin: "liang4", Nghia: "sáng", Level: "HSK4", Tone: "4"},
	{Hanzi: "聊天", Pinyin: "liao2 tian1", Nghia: "tán gẫu", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "另外", Pinyin: "ling4 wai4", Nghia: "ngoài ra, khác", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "留", Pinyin: "liu2", Nghia: "ở lại, giữ lại", Level: "HSK4", Tone: "2"},
	{Hanzi: "留学", Pinyin: "liu2 xue2", Nghia: "du học", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "流泪", Pinyin: "liu2 lei4", Nghia: "rơi lệ", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "流利", Pinyin: "liu2 li4", Nghia: "lưu loát", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "流行", Pinyin: "liu2 xing2", Nghia: "thịnh hành, lan rộng", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "乱", Pinyin: "luan4", Nghia: "lộn xộn", Level: "HSK4", Tone: "4"},
	{Hanzi: "律师", Pinyin: "lü4 shi1", Nghia: "luật sư", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "麻烦", Pinyin: "ma2 fan5", Nghia: "phiền phức", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "马虎", Pinyin: "ma3 hu5", Nghia: "cẩu thả", Level: "HSK4", Tone: "3 5"},
	{Hanzi: "满", Pinyin: "man3", Nghia: "đầy", Level: "HSK4", Tone: "3"},
	{Hanzi: "毛巾", Pinyin: "mao2 jin1", Nghia: "khăn mặt", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "美丽", Pinyin: "mei3 li4", Nghia: "đẹp", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "梦", Pinyin: "meng4", Nghia: "giấc mơ", Level: "HSK4", Tone: "4"},
	{Hanzi: "密码", Pinyin: "mi4 ma3", Nghia: "mật mã", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "免费", Pinyin: "mian3 fei4", Nghia: "miễn phí", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "民族", Pinyin: "min2 zu2", Nghia: "dân tộc", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "母亲", Pinyin: "mu3 qin1", Nghia: "mẹ", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "目的", Pinyin: "mu4 di4", Nghia: "mục đích", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "耐心", Pinyin: "nai4 xin1", Nghia: "kiên nhẫn", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "难道", Pinyin: "nan2 dao4", Nghia: "lẽ nào... (hỏi tu từ)", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "难受", Pinyin: "nan2 shou4", Nghia: "khó chịu", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "内", Pinyin: "nei4", Nghia: "bên trong", Level: "HSK4", Tone: "4"},
	{Hanzi: "内容", Pinyin: "nei4 rong2", Nghia: "nội dung", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "能力", Pinyin: "neng2 li4", Nghia: "năng lực", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "年龄", Pinyin: "nian2 ling2", Nghia: "tuổi", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "农村", Pinyin: "nong2 cun1", Nghia: "nông thôn", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "弄", Pinyin: "nong4", Nghia: "làm", Level: "HSK4", Tone: "4"},
	{Hanzi: "暖和", Pinyin: "nuan3 huo5", Nghia: "ấm", Level: "HSK4", Tone: "3 5"},
	{Hanzi: "偶尔", Pinyin: "ou3 er3", Nghia: "thỉnh thoảng", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "排列", Pinyin: "pai2 lie4", Nghia: "sắp xếp", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "判断", Pinyin: "pan4 duan4", Nghia: "quyết định", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "陪", Pinyin: "pei2", Nghia: "đi cùng", Level: "HSK4", Tone: "2"},
	{Hanzi: "批评", Pinyin: "pi1 ping2", Nghia: "phê bình", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "皮肤", Pinyin: "pi2 fu1", Nghia: "da", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "脾气", Pinyin: "pi2 qi5", Nghia: "tính khí", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "篇", Pinyin: "pian1", Nghia: "bài, thiên (lượng từ bài văn)", Level: "HSK4", Tone: "1"},
	{Hanzi: "骗", Pinyin: "pian4", Nghia: "lừa gạt", Level: "HSK4", Tone: "4"},
	{Hanzi: "乒乓球", Pinyin: "ping1 pang1 qiu2", Nghia: "bóng bàn", Level: "HSK4", Tone: "1 1 2"},
	{Hanzi: "平时", Pinyin: "ping2 shi2", Nghia: "thông thường", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "瓶子", Pinyin: "ping2 zi5", Nghia: "chai", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "破", Pinyin: "po4", Nghia: "vỡ, rách", Level: "HSK4", Tone: "4"},
	{Hanzi: "普遍", Pinyin: "pu3 bian4", Nghia: "phổ biến", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "其次", Pinyin: "qi2 ci4", Nghia: "tiếp theo", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "其中", Pinyin: "qi2 zhong1", Nghia: "trong đó", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "起飞", Pinyin: "qi3 fei1", Nghia: "cất cánh", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "起来", Pinyin: "qi5 lai5", Nghia: "đứng dậy, lên (tiếp diễn)", Level: "HSK4", Tone: "5 5"},
	{Hanzi: "气候", Pinyin: "qi4 hou4", Nghia: "khí hậu", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "千万", Pinyin: "qian1 wan4", Nghia: "mười triệu; nhất định phải", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "签证", Pinyin: "qian1 zheng4", Nghia: "thị thực", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "墙", Pinyin: "qiang2", Nghia: "tường", Level: "HSK4", Tone: "2"},
	{Hanzi: "敲", Pinyin: "qiao1", Nghia: "đánh", Level: "HSK4", Tone: "1"},
	{Hanzi: "桥", Pinyin: "qiao2", Nghia: "cầu", Level: "HSK4", Tone: "2"},
	{Hanzi: "巧克力", Pinyin: "qiao3 ke4 li4", Nghia: "sô-cô-la", Level: "HSK4", Tone: "3 4 4"},
	{Hanzi: "亲戚", Pinyin: "qin1 qi5", Nghia: "họ hàng", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "轻", Pinyin: "qing1", Nghia: "nhẹ", Level: "HSK4", Tone: "1"},
	{Hanzi: "轻松", Pinyin: "qing1 song1", Nghia: "nhẹ nhõm", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "情况", Pinyin: "qing2 kuang4", Nghia: "tình hình", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "请假", Pinyin: "qing3 jia4", Nghia: "xin nghỉ phép", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "请客", Pinyin: "qing3 ke4", Nghia: "mời (ăn uống)", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "穷", Pinyin: "qiong2", Nghia: "nghèo; cùng cực", Level: "HSK4", Tone: "2"},
	{Hanzi: "区别", Pinyin: "qu1 bie2", Nghia: "phân biệt, khác biệt", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "取", Pinyin: "qu3", Nghia: "lấy", Level: "HSK4", Tone: "3"},
	{Hanzi: "全部", Pinyin: "quan2 bu4", Nghia: "toàn bộ", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "缺点", Pinyin: "que1 dian3", Nghia: "điểm yếu", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "缺少", Pinyin: "que1 shao3", Nghia: "thiếu", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "却", Pinyin: "que4", Nghia: "nhưng", Level: "HSK4", Tone: "4"},
	{Hanzi: "确实", Pinyin: "que4 shi2", Nghia: "quả thực", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "群", Pinyin: "qun2", Nghia: "nhóm", Level: "HSK4", Tone: "2"},
	{Hanzi: "然而", Pinyin: "ran2 er2", Nghia: "tuy nhiên", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "热闹", Pinyin: "re4 nao5", Nghia: "nhộn nhịp", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "人民币", Pinyin: "ren2 min2 bi4", Nghia: "nhân dân tệ", Level: "HSK4", Tone: "2 2 4"},
	{Hanzi: "任何", Pinyin: "ren4 he2", Nghia: "bất kỳ", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "任务", Pinyin: "ren4 wu5", Nghia: "nhiệm vụ", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "扔", Pinyin: "reng1", Nghia: "ném", Level: "HSK4", Tone: "1"},
	{Hanzi: "仍然", Pinyin: "reng2 ran2", Nghia: "vẫn", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "日记", Pinyin: "ri4 ji4", Nghia: "nhật ký", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "入口", Pinyin: "ru4 kou3", Nghia: "lối vào", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "软", Pinyin: "ruan3", Nghia: "mềm", Level: "HSK4", Tone: "3"},
	{Hanzi: "散步", Pinyin: "san4 bu4", Nghia: "đi dạo", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "森林", Pinyin: "sen1 lin2", Nghia: "rừng", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "沙发", Pinyin: "sha1 fa1", Nghia: "ghế sofa", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "商量", Pinyin: "shang1 liang5", Nghia: "bàn bạc", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "伤心", Pinyin: "shang1 xin1", Nghia: "đau buồn", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "稍微", Pinyin: "shao1 wei1", Nghia: "một chút", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "社会", Pinyin: "she4 hui4", Nghia: "xã hội", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "深", Pinyin: "shen1", Nghia: "sâu", Level: "HSK4", Tone: "1"},
	{Hanzi: "申请", Pinyin: "shen1 qing3", Nghia: "nộp đơn xin", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "甚至", Pinyin: "shen4 zhi4", Nghia: "thậm chí", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "生活", Pinyin: "sheng1 huo2", Nghia: "cuộc sống", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "生命", Pinyin: "sheng1 ming4", Nghia: "sinh mệnh, sự sống", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "省", Pinyin: "sheng3", Nghia: "tỉnh; tiết kiệm", Level: "HSK4", Tone: "3"},
	{Hanzi: "剩", Pinyin: "sheng4", Nghia: "còn lại", Level: "HSK4", Tone: "4"},
	{Hanzi: "失败", Pinyin: "shi1 bai4", Nghia: "thất bại", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "失望", Pinyin: "shi1 wang4", Nghia: "thất vọng", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "师傅", Pinyin: "shi1 fu5", Nghia: "sư phụ, thợ cả", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "湿润", Pinyin: "shi1 run4", Nghia: "ẩm ướt", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "狮子", Pinyin: "shi1 zi5", Nghia: "sư tử", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "十分", Pinyin: "shi2 fen1", Nghia: "rất, hết sức", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "实际", Pinyin: "shi2 ji4", Nghia: "thực tế", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "实在", Pinyin: "shi2 zai4", Nghia: "thật sự", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "食品", Pinyin: "shi2 pin3", Nghia: "thực phẩm", Level: "HSK4", Tone: "2 3"},
	{Hanzi: "使用", Pinyin: "shi3 yong4", Nghia: "dùng", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "试", Pinyin: "shi4", Nghia: "kiểm tra/thi", Level: "HSK4", Tone: "4"},
	{Hanzi: "市场", Pinyin: "shi4 chang3", Nghia: "chợ", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "世纪", Pinyin: "shi4 ji4", Nghia: "thế kỷ", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "适合", Pinyin: "shi4 he2", Nghia: "vừa vặn", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "适应", Pinyin: "shi4 ying4", Nghia: "thích nghi", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "收", Pinyin: "shou1", Nghia: "nhận", Level: "HSK4", Tone: "1"},
	{Hanzi: "收入", Pinyin: "shou1 ru4", Nghia: "thu nhập", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "收拾", Pinyin: "shou1 shi5", Nghia: "dọn dẹp", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "首都", Pinyin: "shou3 du1", Nghia: "thủ đô", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "首先", Pinyin: "shou3 xian1", Nghia: "thứ nhất", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "受不了", Pinyin: "shou4 bu4 liao3", Nghia: "không chịu nổi", Level: "HSK4", Tone: "4 4 3"},
	{Hanzi: "受到", Pinyin: "shou4 dao4", Nghia: "nhận được", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "售货员", Pinyin: "shou4 huo4 yuan2", Nghia: "người bán hàng", Level: "HSK4", Tone: "4 4 2"},
	{Hanzi: "输", Pinyin: "shu1", Nghia: "mất", Level: "HSK4", Tone: "1"},
	{Hanzi: "熟悉", Pinyin: "shu2 xi1", Nghia: "quen thuộc", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "数量", Pinyin: "shu4 liang4", Nghia: "số lượng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "数字", Pinyin: "shu4 zi4", Nghia: "số từ", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "帅", Pinyin: "shuai4", Nghia: "đẹp trai", Level: "HSK4", Tone: "4"},
	{Hanzi: "顺便", Pinyin: "shun4 bian4", Nghia: "thuận tiện", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "顺利", Pinyin: "shun4 li4", Nghia: "suôn sẻ", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "顺序", Pinyin: "shun4 xu4", Nghia: "trình tự", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "说明", Pinyin: "shuo1 ming2", Nghia: "giải thích", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "硕士", Pinyin: "shuo4 shi4", Nghia: "thạc sĩ", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "死", Pinyin: "si3", Nghia: "chết", Level: "HSK4", Tone: "3"},
	{Hanzi: "速度", Pinyin: "su4 du4", Nghia: "tốc độ", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "塑料袋", Pinyin: "su4 liao4 dai4", Nghia: "túi ni-lông", Level: "HSK4", Tone: "4 4 4"},
	{Hanzi: "酸", Pinyin: "suan1", Nghia: "chua", Level: "HSK4", Tone: "1"},
	{Hanzi: "算", Pinyin: "suan4", Nghia: "tính, coi như", Level: "HSK4", Tone: "4"},
	{Hanzi: "随便", Pinyin: "sui2 bian4", Nghia: "tùy ý, tùy tiện", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "随着", Pinyin: "sui2 zhe5", Nghia: "cùng với", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "孙子", Pinyin: "sun1 zi5", Nghia: "cháu trai", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "所有", Pinyin: "suo3 you3", Nghia: "tất cả", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "抬", Pinyin: "tai2", Nghia: "nhấc lên", Level: "HSK4", Tone: "2"},
	{Hanzi: "台", Pinyin: "tai2", Nghia: "bão", Level: "HSK4", Tone: "2"},
	{Hanzi: "态度", Pinyin: "tai4 du5", Nghia: "thái độ", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "谈", Pinyin: "tan2", Nghia: "nói", Level: "HSK4", Tone: "2"},
	{Hanzi: "弹", Pinyin: "tan2", Nghia: "gảy đàn", Level: "HSK4", Tone: "2"},
	{Hanzi: "汤", Pinyin: "tang1", Nghia: "canh", Level: "HSK4", Tone: "1"},
	{Hanzi: "躺", Pinyin: "tang3", Nghia: "nằm nghỉ", Level: "HSK4", Tone: "3"},
	{Hanzi: "趟", Pinyin: "tang4", Nghia: "lượng từ cho lần", Level: "HSK4", Tone: "4"},
	{Hanzi: "讨论", Pinyin: "tao3 lun4", Nghia: "thảo luận", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "讨厌", Pinyin: "tao3 yan4", Nghia: "không thích", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "特点", Pinyin: "te4 dian3", Nghia: "đặc điểm", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "提供", Pinyin: "ti2 gong1", Nghia: "cung cấp", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "提前", Pinyin: "ti2 qian2", Nghia: "sớm hơn, trước", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "提醒", Pinyin: "ti2 xing3", Nghia: "nhắc nhở", Level: "HSK4", Tone: "2 3"},
	{Hanzi: "填空", Pinyin: "tian2 kong4", Nghia: "điền vào chỗ trống", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "条件", Pinyin: "tiao2 jian4", Nghia: "điều kiện", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "停止", Pinyin: "ting2 zhi3", Nghia: "dừng", Level: "HSK4", Tone: "2 3"},
	{Hanzi: "挺", Pinyin: "ting3", Nghia: "khá, rất; thẳng", Level: "HSK4", Tone: "3"},
	{Hanzi: "通过", Pinyin: "tong1 guo4", Nghia: "thông qua", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "通知", Pinyin: "tong1 zhi1", Nghia: "thông báo", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "同情", Pinyin: "tong2 qing2", Nghia: "thông cảm với", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "推", Pinyin: "tui1", Nghia: "đẩy", Level: "HSK4", Tone: "1"},
	{Hanzi: "推迟", Pinyin: "tui1 chi2", Nghia: "hoãn lại", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "脱", Pinyin: "tuo1", Nghia: "rụng/rơi", Level: "HSK4", Tone: "1"},
	{Hanzi: "袜子", Pinyin: "wa4 zi5", Nghia: "tất", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "完全", Pinyin: "wan2 quan2", Nghia: "hoàn toàn", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "往", Pinyin: "wang3", Nghia: "hướng về", Level: "HSK4", Tone: "3"},
	{Hanzi: "往往", Pinyin: "wang3 wang3", Nghia: "thường thường", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "网球", Pinyin: "wang3 qiu2", Nghia: "quần vợt", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "网站", Pinyin: "wang3 zhan4", Nghia: "trang web", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "危险", Pinyin: "wei1 xian3", Nghia: "nguy hiểm", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "味道", Pinyin: "wei4 dao5", Nghia: "hương vị", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "温度", Pinyin: "wen1 du4", Nghia: "nhiệt độ", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "文章", Pinyin: "wen2 zhang1", Nghia: "bài báo", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "握手", Pinyin: "wo4 shou3", Nghia: "bắt tay", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "污染", Pinyin: "wu1 ran3", Nghia: "ô nhiễm", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "无", Pinyin: "wu2", Nghia: "không, vô", Level: "HSK4", Tone: "2"},
	{Hanzi: "无聊", Pinyin: "wu2 liao2", Nghia: "chán", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "无论", Pinyin: "wu2 lun4", Nghia: "bất luận... gì", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "误会", Pinyin: "wu4 hui4", Nghia: "hiểu lầm", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "西红柿", Pinyin: "xi1 hong2 shi4", Nghia: "cà chua", Level: "HSK4", Tone: "1 2 4"},
	{Hanzi: "吸引", Pinyin: "xi1 yin3", Nghia: "thu hút", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "洗衣机", Pinyin: "xi3 yi1 ji1", Nghia: "máy giặt", Level: "HSK4", Tone: "3 1 1"},
	{Hanzi: "咸", Pinyin: "xian2", Nghia: "mặn", Level: "HSK4", Tone: "2"},
	{Hanzi: "现代", Pinyin: "xian4 dai4", Nghia: "hiện đại", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "羡慕", Pinyin: "xian4 mu4", Nghia: "ghen tị", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "限制", Pinyin: "xian4 zhi4", Nghia: "hạn chế", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "香", Pinyin: "xiang1", Nghia: "thơm", Level: "HSK4", Tone: "1"},
	{Hanzi: "相反", Pinyin: "xiang1 fan3", Nghia: "ngược lại", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "详细", Pinyin: "xiang2 xi4", Nghia: "chi tiết", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "响", Pinyin: "xiang3", Nghia: "tiếng vang", Level: "HSK4", Tone: "3"},
	{Hanzi: "消息", Pinyin: "xiao1 xi5", Nghia: "tin tức", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "小说", Pinyin: "xiao3 shuo1", Nghia: "tiểu thuyết", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "笑话", Pinyin: "xiao4 hua5", Nghia: "trò đùa", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "效果", Pinyin: "xiao4 guo3", Nghia: "hiệu quả", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "心情", Pinyin: "xin1 qing2", Nghia: "tâm trạng", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "辛苦", Pinyin: "xin1 ku3", Nghia: "vất vả", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "信任", Pinyin: "xin4 ren4", Nghia: "tin tưởng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "信心", Pinyin: "xin4 xin1", Nghia: "tự tin", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "信用卡", Pinyin: "xin4 yong4 ka3", Nghia: "thẻ tín dụng", Level: "HSK4", Tone: "4 4 3"},
	{Hanzi: "兴奋", Pinyin: "xing1 fen4", Nghia: "hào hứng", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "行", Pinyin: "xing2", Nghia: "hàng; nghề; được", Level: "HSK4", Tone: "2"},
	{Hanzi: "醒", Pinyin: "xing3", Nghia: "tỉnh dậy", Level: "HSK4", Tone: "3"},
	{Hanzi: "性别", Pinyin: "xing4 bie2", Nghia: "giới tính", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "性格", Pinyin: "xing4 ge2", Nghia: "tính cách", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "幸福", Pinyin: "xing4 fu2", Nghia: "hạnh phúc", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "修", Pinyin: "xiu1", Nghia: "sửa chữa", Level: "HSK4", Tone: "1"},
	{Hanzi: "许多", Pinyin: "xu3 duo1", Nghia: "nhiều", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "血", Pinyin: "xue4", Nghia: "máu", Level: "HSK4", Tone: "4"},
	{Hanzi: "压力", Pinyin: "ya1 li4", Nghia: "áp lực", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "牙膏", Pinyin: "ya2 gao1", Nghia: "kem đánh răng", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "亚洲", Pinyin: "ya4 zhou1", Nghia: "châu Á", Level: "HSK4", Tone: "4 1"},
	{Hanzi: "呀", Pinyin: "ya5", Nghia: "trợ từ cuối câu (nha, nhé)", Level: "HSK4", Tone: "5"},
	{Hanzi: "盐", Pinyin: "yan2", Nghia: "muối", Level: "HSK4", Tone: "2"},
	{Hanzi: "严格", Pinyin: "yan2 ge2", Nghia: "nghiêm khắc", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "严重", Pinyin: "yan2 zhong4", Nghia: "nghiêm trọng", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "研究生", Pinyin: "yan2 jiu1 sheng1", Nghia: "nghiên cứu sinh", Level: "HSK4", Tone: "2 1 1"},
	{Hanzi: "演出", Pinyin: "yan3 chu1", Nghia: "biểu diễn", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "演员", Pinyin: "yan3 yuan2", Nghia: "diễn viên", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "阳光", Pinyin: "yang2 guang1", Nghia: "ánh nắng", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "养成", Pinyin: "yang3 cheng2", Nghia: "bồi dưỡng", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "样子", Pinyin: "yang4 zi5", Nghia: "vẻ ngoài", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "邀请", Pinyin: "yao1 qing3", Nghia: "mời", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "钥匙", Pinyin: "yao4 shi5", Nghia: "chìa khóa", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "也许", Pinyin: "ye3 xu3", Nghia: "có lẽ", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "页", Pinyin: "ye4", Nghia: "trang", Level: "HSK4", Tone: "4"},
	{Hanzi: "叶子", Pinyin: "ye4 zi5", Nghia: "lá", Level: "HSK4", Tone: "4 5"},
	{Hanzi: "一切", Pinyin: "yi1 qie4", Nghia: "tất cả", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "以", Pinyin: "yi3", Nghia: "bằng, lấy (dùng)", Level: "HSK4", Tone: "3"},
	{Hanzi: "亿", Pinyin: "yi4", Nghia: "trăm triệu", Level: "HSK4", Tone: "4"},
	{Hanzi: "意见", Pinyin: "yi4 jian4", Nghia: "ý kiến", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "艺术", Pinyin: "yi4 shu4", Nghia: "nghệ thuật", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "因此", Pinyin: "yin1 ci3", Nghia: "do đó, vì vậy", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "引起", Pinyin: "yin3 qi3", Nghia: "gây ra", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "饮料", Pinyin: "yin3 liao4", Nghia: "đồ uống", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "印象", Pinyin: "yin4 xiang4", Nghia: "ấn tượng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "赢", Pinyin: "ying2", Nghia: "thắng", Level: "HSK4", Tone: "2"},
	{Hanzi: "硬", Pinyin: "ying4", Nghia: "cứng", Level: "HSK4", Tone: "4"},
	{Hanzi: "勇敢", Pinyin: "yong3 gan3", Nghia: "dũng cảm", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "永远", Pinyin: "yong3 yuan3", Nghia: "mãi mãi", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "优点", Pinyin: "you1 dian3", Nghia: "ưu điểm", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "优秀", Pinyin: "you1 xiu4", Nghia: "xuất sắc", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "幽默", Pinyin: "you1 mo4", Nghia: "hài hước", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "由", Pinyin: "you2", Nghia: "do, bởi", Level: "HSK4", Tone: "2"},
	{Hanzi: "由于", Pinyin: "you2 yu2", Nghia: "do, bởi", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "尤其", Pinyin: "you2 qi2", Nghia: "nhất là", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "有趣", Pinyin: "you3 qu4", Nghia: "thú vị", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "友好", Pinyin: "you3 hao3", Nghia: "thân thiện", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "友谊", Pinyin: "you3 yi4", Nghia: "tình bạn", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "愉快", Pinyin: "yu2 kuai4", Nghia: "vui tươi", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "于是", Pinyin: "yu2 shi4", Nghia: "thế là, bèn", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "与", Pinyin: "yu3", Nghia: "và, với (trang trọng)", Level: "HSK4", Tone: "3"},
	{Hanzi: "语法", Pinyin: "yu3 fa3", Nghia: "ngữ pháp", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "语言", Pinyin: "yu3 yan2", Nghia: "ngôn ngữ", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "羽毛球", Pinyin: "yu3 mao2 qiu2", Nghia: "cầu lông", Level: "HSK4", Tone: "3 2 2"},
	{Hanzi: "预习", Pinyin: "yu4 xi2", Nghia: "chuẩn bị bài học", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "圆", Pinyin: "yuan2", Nghia: "hình tròn", Level: "HSK4", Tone: "2"},
	{Hanzi: "原来", Pinyin: "yuan2 lai2", Nghia: "thì ra, vốn dĩ", Level: "HSK4", Tone: "2 2"},
	{Hanzi: "原谅", Pinyin: "yuan2 liang4", Nghia: "tha thứ", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "原因", Pinyin: "yuan2 yin1", Nghia: "nguyên nhân", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "约会", Pinyin: "yue1 hui4", Nghia: "cuộc hẹn", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "阅读", Pinyin: "yue4 du2", Nghia: "đọc", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "允许", Pinyin: "yun3 xu3", Nghia: "cho phép", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "杂志", Pinyin: "za2 zhi4", Nghia: "tạp chí", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "咱们", Pinyin: "zan2 men5", Nghia: "chúng ta (gồm cả người nghe)", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "暂时", Pinyin: "zan4 shi2", Nghia: "tạm thời", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "脏", Pinyin: "zang1", Nghia: "bẩn", Level: "HSK4", Tone: "1"},
	{Hanzi: "责任", Pinyin: "ze2 ren4", Nghia: "trách nhiệm", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "增加", Pinyin: "zeng1 jia1", Nghia: "tăng thêm", Level: "HSK4", Tone: "1 1"},
	{Hanzi: "增长", Pinyin: "zeng1 zhang3", Nghia: "tăng trưởng", Level: "HSK4", Tone: "1 3"},
	{Hanzi: "窄", Pinyin: "zhai3", Nghia: "hẹp", Level: "HSK4", Tone: "3"},
	{Hanzi: "招聘", Pinyin: "zhao1 pin4", Nghia: "tuyển dụng", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "真正", Pinyin: "zhen1 zheng4", Nghia: "thật sự", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "整理", Pinyin: "zheng3 li3", Nghia: "sắp xếp", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "整齐", Pinyin: "zheng3 qi2", Nghia: "ngăn nắp", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "正常", Pinyin: "zheng4 chang2", Nghia: "bình thường", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "正好", Pinyin: "zheng4 hao3", Nghia: "vừa khéo", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "正确", Pinyin: "zheng4 que4", Nghia: "đúng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "正式", Pinyin: "zheng4 shi4", Nghia: "chính thức", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "证明", Pinyin: "zheng4 ming2", Nghia: "bằng chứng", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "之", Pinyin: "zhi1", Nghia: "của (văn ngôn)", Level: "HSK4", Tone: "1"},
	{Hanzi: "支持", Pinyin: "zhi1 chi2", Nghia: "ủng hộ", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "知识", Pinyin: "zhi1 shi5", Nghia: "tri thức", Level: "HSK4", Tone: "1 5"},
	{Hanzi: "直接", Pinyin: "zhi2 jie1", Nghia: "trực tiếp", Level: "HSK4", Tone: "2 1"},
	{Hanzi: "值得", Pinyin: "zhi2 de5", Nghia: "đáng", Level: "HSK4", Tone: "2 5"},
	{Hanzi: "职业", Pinyin: "zhi2 ye4", Nghia: "nghề nghiệp", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "植物", Pinyin: "zhi2 wu4", Nghia: "thực vật", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "指", Pinyin: "zhi3", Nghia: "ngón tay", Level: "HSK4", Tone: "3"},
	{Hanzi: "只好", Pinyin: "zhi3 hao3", Nghia: "đành phải", Level: "HSK4", Tone: "3 3"},
	{Hanzi: "只要", Pinyin: "zhi3 yao4", Nghia: "chỉ cần", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "制造", Pinyin: "zhi4 zao4", Nghia: "sản xuất", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "至少", Pinyin: "zhi4 shao3", Nghia: "ít nhất", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "质量", Pinyin: "zhi4 liang4", Nghia: "chất lượng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "中文", Pinyin: "zhong1 wen2", Nghia: "tiếng Trung", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "重点", Pinyin: "zhong4 dian3", Nghia: "trọng điểm", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "重视", Pinyin: "zhong4 shi4", Nghia: "coi trọng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "周围", Pinyin: "zhou1 wei2", Nghia: "vùng xung quanh", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "猪", Pinyin: "zhu1", Nghia: "lợn", Level: "HSK4", Tone: "1"},
	{Hanzi: "逐渐", Pinyin: "zhu2 jian4", Nghia: "dần dần", Level: "HSK4", Tone: "2 4"},
	{Hanzi: "主动", Pinyin: "zhu3 dong4", Nghia: "chủ động", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "主意", Pinyin: "zhu3 yi5", Nghia: "chủ ý, ý kiến", Level: "HSK4", Tone: "3 5"},
	{Hanzi: "祝贺", Pinyin: "zhu4 he4", Nghia: "chúc mừng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "著名", Pinyin: "zhu4 ming2", Nghia: "nổi tiếng", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "专门", Pinyin: "zhuan1 men2", Nghia: "chuyên (môn)", Level: "HSK4", Tone: "1 2"},
	{Hanzi: "专业", Pinyin: "zhuan1 ye4", Nghia: "chuyên ngành", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "赚", Pinyin: "zhuan4", Nghia: "kiếm (tiền)", Level: "HSK4", Tone: "4"},
	{Hanzi: "撞", Pinyin: "zhuang4", Nghia: "đâm, va", Level: "HSK4", Tone: "4"},
	{Hanzi: "准确", Pinyin: "zhun3 que4", Nghia: "chính xác", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "准时", Pinyin: "zhun3 shi2", Nghia: "đúng giờ", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "仔细", Pinyin: "zi3 xi4", Nghia: "cẩn thận", Level: "HSK4", Tone: "3 4"},
	{Hanzi: "自然", Pinyin: "zi4 ran2", Nghia: "tự nhiên", Level: "HSK4", Tone: "4 2"},
	{Hanzi: "总结", Pinyin: "zong3 jie2", Nghia: "tổng kết", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "租", Pinyin: "zu1", Nghia: "thuê", Level: "HSK4", Tone: "1"},
	{Hanzi: "组成", Pinyin: "zu3 cheng2", Nghia: "tạo thành", Level: "HSK4", Tone: "3 2"},
	{Hanzi: "组织", Pinyin: "zu3 zhi1", Nghia: "tổ chức", Level: "HSK4", Tone: "3 1"},
	{Hanzi: "嘴", Pinyin: "zui3", Nghia: "miệng", Level: "HSK4", Tone: "3"},
	{Hanzi: "最好", Pinyin: "zui4 hao3", Nghia: "tốt nhất", Level: "HSK4", Tone: "4 3"},
	{Hanzi: "最后", Pinyin: "zui4 hou4", Nghia: "cuối cùng", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "尊重", Pinyin: "zun1 zhong4", Nghia: "kính trọng", Level: "HSK4", Tone: "1 4"},
	{Hanzi: "做生意", Pinyin: "zuo4 sheng1 yi4", Nghia: "buôn bán", Level: "HSK4", Tone: "4 1 4"},
	{Hanzi: "座", Pinyin: "zuo4", Nghia: "ngọn, tòa (lượng từ)", Level: "HSK4", Tone: "4"},
	{Hanzi: "座位", Pinyin: "zuo4 wei4", Nghia: "chỗ ngồi", Level: "HSK4", Tone: "4 4"},
	{Hanzi: "作者", Pinyin: "zuo4 zhe3", Nghia: "tác giả", Level: "HSK4", Tone: "4 3"},
}

// HskSeedByLevel trả seed của 1 level HSK. Level lạ trả nil — caller báo 400
// "chưa có seed cho level …" thay vì tự dựng bảng rỗng.
func HskSeedByLevel(level string) []HskEntry {
	switch level {
	case "HSK1":
		return hsk1Seed
	case "HSK2":
		return hsk2Seed
	case "HSK3":
		return hsk3Seed
	case "HSK4":
		return hsk4Seed
	default:
		return nil
	}
}

// HskLevels là tập level có seed, theo thứ tự tăng dần.
var HskLevels = []string{"HSK1", "HSK2", "HSK3", "HSK4"}
