// Seed dữ liệu từ vựng cho context content. Port NGUYÊN VĂN từ
// api/chinese_hsk.go (hsk1Seed) + api/hsk_seed_l234.go (hsk2/3/4) — dữ liệu
// này là nội dung học thuật, đổi 1 từ là đổi bài học.
//
// Nguồn gốc (giữ nguyên credit như v1):
//   - HSK1: 36 từ, pinyin đối chiếu CC-CEDICT (CC BY-SA 4.0), nghĩa tiếng Việt
//     tự soạn.
//   - HSK 2.0 L2-L4: sinh bởi scripts/seed_hsk.py từ
//     drkameleon/complete-hsk-vocabulary (MIT) + clem109/hsk-vocabulary (MIT);
//     pinyin tham khảo CC-CEDICT.
package contentinfra

// HskEntry là 1 dòng seed từ vựng: Pinyin mang số thanh ("ni3 hao3"), Tone là
// pattern thuần lưu vào cards.tone ("3 3").
type HskEntry struct {
	Hanzi  string
	Pinyin string
	Nghia  string
	Level  string
	Tone   string
}

// hsk1Seed — seed HSK1.
var hsk1Seed = []HskEntry{
	{"你", "ni3", "bạn", "HSK1", "3"},
	{"好", "hao3", "tốt/khỏe", "HSK1", "3"},
	{"你好", "ni3 hao3", "xin chào", "HSK1", "3 3"},
	{"我", "wo3", "tôi", "HSK1", "3"},
	{"你们", "ni3 men5", "các bạn", "HSK1", "3 5"},
	{"他", "ta1", "anh ấy", "HSK1", "1"},
	{"她", "ta1", "cô ấy", "HSK1", "1"},
	{"是", "shi4", "là", "HSK1", "4"},
	{"不", "bu4", "không", "HSK1", "4"},
	{"的", "de5", "trợ từ sở hữu (của)", "HSK1", "5"},
	{"了", "le5", "trợ từ hoàn thành (rồi)", "HSK1", "5"},
	{"吗", "ma5", "trợ từ nghi vấn (không)", "HSK1", "5"},
	{"在", "zai4", "ở/tại", "HSK1", "4"},
	{"有", "you3", "có", "HSK1", "3"},
	{"人", "ren2", "người", "HSK1", "2"},
	{"大", "da4", "to/lớn", "HSK1", "4"},
	{"小", "xiao3", "nhỏ", "HSK1", "3"},
	{"中", "zhong1", "giữa/trung", "HSK1", "1"},
	{"国", "guo2", "nước/quốc", "HSK1", "2"},
	{"中国", "zhong1 guo2", "Trung Quốc", "HSK1", "1 2"},
	{"学习", "xue2 xi2", "học tập", "HSK1", "2 2"},
	{"汉语", "han4 yu3", "tiếng Hán", "HSK1", "4 3"},
	{"老师", "lao3 shi1", "thầy/cô giáo", "HSK1", "3 1"},
	{"学生", "xue2 sheng1", "học sinh", "HSK1", "2 1"},
	{"朋友", "peng2 you3", "bạn bè", "HSK1", "2 3"},
	{"家", "jia1", "nhà/gia đình", "HSK1", "1"},
	{"学校", "xue2 xiao4", "trường học", "HSK1", "2 4"},
	{"水", "shui3", "nước", "HSK1", "3"},
	{"茶", "cha2", "trà", "HSK1", "2"},
	{"米饭", "mi3 fan4", "cơm", "HSK1", "3 4"},
	{"爱", "ai4", "yêu", "HSK1", "4"},
	{"吃", "chi1", "ăn", "HSK1", "1"},
	{"喝", "he1", "uống", "HSK1", "1"},
	{"去", "qu4", "đi", "HSK1", "4"},
	{"来", "lai2", "đến", "HSK1", "2"},
	{"什么", "shen2 me5", "cái gì", "HSK1", "2 5"},
}

// hsk2Seed — seed HSK2.
var hsk2Seed = []HskEntry{
	{"吧", "ba5", "trợ từ cuối câu (nhé, nhỉ, nào)", "HSK2", "5"},
	{"白", "bai2", "trắng", "HSK2", "2"},
	{"百", "bai3", "trăm", "HSK2", "3"},
	{"帮助", "bang1 zhu4", "sự giúp đỡ", "HSK2", "1 4"},
	{"报纸", "bao4 zhi3", "báo", "HSK2", "4 3"},
	{"比", "bi3", "so với, hơn (so sánh)", "HSK2", "3"},
	{"别", "bie2", "đừng", "HSK2", "2"},
	{"长", "chang2", "dài", "HSK2", "2"},
	{"唱歌", "chang4 ge1", "hát bài hát", "HSK2", "4 1"},
	{"出", "chu1", "ra", "HSK2", "1"},
	{"穿", "chuan1", "mặc (quần áo)", "HSK2", "1"},
	{"船", "chuan2", "thuyền", "HSK2", "2"},
	{"次", "ci4", "lần, lượt", "HSK2", "4"},
	{"从", "cong2", "từ (nơi chốn, thời gian)", "HSK2", "2"},
	{"错", "cuo4", "sai", "HSK2", "4"},
	{"打篮球", "da3 lan2 qiu2", "chơi bóng rổ", "HSK2", "3 2 2"},
	{"大家", "da4 jia1", "mọi người", "HSK2", "4 1"},
	{"但是", "dan4 shi4", "nhưng", "HSK2", "4 4"},
	{"到", "dao4", "đến, tới", "HSK2", "4"},
	{"得", "de5", "trợ từ (làm... đến nỗi)", "HSK2", "5"},
	{"弟弟", "di4 di5", "em trai", "HSK2", "4 5"},
	{"第一", "di4 yi1", "thứ nhất", "HSK2", "4 1"},
	{"懂", "dong3", "hiểu", "HSK2", "3"},
	{"房间", "fang2 jian1", "phòng", "HSK2", "2 1"},
	{"非常", "fei1 chang2", "rất, vô cùng", "HSK2", "1 2"},
	{"服务员", "fu2 wu4 yuan2", "người phục vụ", "HSK2", "2 4 2"},
	{"高", "gao1", "cao", "HSK2", "1"},
	{"告诉", "gao4 su5", "nói cho biết, bảo", "HSK2", "4 5"},
	{"哥哥", "ge1 ge5", "anh trai", "HSK2", "1 5"},
	{"给", "gei3", "cho, đưa cho", "HSK2", "3"},
	{"公共汽车", "gong1 gong4 qi4 che1", "xe buýt", "HSK2", "1 4 4 1"},
	{"公斤", "gong1 jin1", "ki-lô-gam", "HSK2", "1 1"},
	{"公司", "gong1 si1", "công ty", "HSK2", "1 1"},
	{"贵", "gui4", "đắt", "HSK2", "4"},
	{"还", "hai2", "còn, vẫn (tiếp diễn)", "HSK2", "2"},
	{"孩子", "hai2 zi5", "trẻ em", "HSK2", "2 5"},
	{"好吃", "hao3 chi1", "ngon", "HSK2", "3 1"},
	{"号", "hao4", "số; ngày (trong tháng)", "HSK2", "4"},
	{"黑", "hei1", "đen", "HSK2", "1"},
	{"红", "hong2", "đỏ", "HSK2", "2"},
	{"欢迎", "huan1 ying2", "đón chào", "HSK2", "1 2"},
	{"回答", "hui2 da2", "trả lời", "HSK2", "2 2"},
	{"机场", "ji1 chang3", "sân bay", "HSK2", "1 3"},
	{"鸡蛋", "ji1 dan4", "trứng", "HSK2", "1 4"},
	{"件", "jian4", "cái, chiếc (lượng từ)", "HSK2", "4"},
	{"教室", "jiao4 shi4", "lớp học", "HSK2", "4 4"},
	{"姐姐", "jie3 jie5", "chị gái", "HSK2", "3 5"},
	{"介绍", "jie4 shao4", "giới thiệu", "HSK2", "4 4"},
	{"进", "jin4", "vào", "HSK2", "4"},
	{"近", "jin4", "gần", "HSK2", "4"},
	{"就", "jiu4", "thì, bèn, chính là", "HSK2", "4"},
	{"觉得", "jue2 de5", "nghĩ", "HSK2", "2 5"},
	{"咖啡", "ka1 fei1", "cà phê", "HSK2", "1 1"},
	{"开始", "kai1 shi3", "bắt đầu", "HSK2", "1 3"},
	{"考试", "kao3 shi4", "thi, dự thi", "HSK2", "3 4"},
	{"可能", "ke3 neng2", "có thể, có khả năng", "HSK2", "3 2"},
	{"可以", "ke3 yi3", "có thể, được phép", "HSK2", "3 3"},
	{"课", "ke4", "môn học", "HSK2", "4"},
	{"快", "kuai4", "nhanh", "HSK2", "4"},
	{"快乐", "kuai4 le4", "vui vẻ", "HSK2", "4 4"},
	{"累", "lei4", "mệt", "HSK2", "4"},
	{"离", "li2", "rời khỏi", "HSK2", "2"},
	{"两", "liang3", "hai", "HSK2", "3"},
	{"路", "lu4", "đường", "HSK2", "4"},
	{"旅游", "lü3 you2", "du lịch", "HSK2", "3 2"},
	{"卖", "mai4", "bán", "HSK2", "4"},
	{"慢", "man4", "chậm", "HSK2", "4"},
	{"忙", "mang2", "bận", "HSK2", "2"},
	{"每", "mei3", "mỗi", "HSK2", "3"},
	{"妹妹", "mei4 mei5", "em gái", "HSK2", "4 5"},
	{"门", "men2", "cửa", "HSK2", "2"},
	{"男人", "nan2 ren2", "đàn ông", "HSK2", "2 2"},
	{"您", "nin2", "ngài, bạn (lịch sự)", "HSK2", "2"},
	{"牛奶", "niu2 nai3", "sữa bò", "HSK2", "2 3"},
	{"女人", "nü3 ren2", "phụ nữ", "HSK2", "3 2"},
	{"旁边", "pang2 bian1", "bên cạnh", "HSK2", "2 1"},
	{"跑步", "pao3 bu4", "chạy bộ", "HSK2", "3 4"},
	{"便宜", "pian2 yi5", "rẻ", "HSK2", "2 5"},
	{"票", "piao4", "vé", "HSK2", "4"},
	{"妻子", "qi1 zi5", "vợ", "HSK2", "1 5"},
	{"起床", "qi3 chuang2", "thức dậy", "HSK2", "3 2"},
	{"千", "qian1", "nghìn", "HSK2", "1"},
	{"晴", "qing2", "nắng ráo", "HSK2", "2"},
	{"去年", "qu4 nian2", "năm ngoái", "HSK2", "4 2"},
	{"让", "rang4", "để cho, nhường", "HSK2", "4"},
	{"上班", "shang4 ban1", "đi làm", "HSK2", "4 1"},
	{"身体", "shen1 ti3", "cơ thể", "HSK2", "1 3"},
	{"生病", "sheng1 bing4", "ốm, bị bệnh", "HSK2", "1 4"},
	{"生日", "sheng1 ri4", "sinh nhật", "HSK2", "1 4"},
	{"时间", "shi2 jian1", "thời gian", "HSK2", "2 1"},
	{"事情", "shi4 qing5", "việc", "HSK2", "4 5"},
	{"手表", "shou3 biao3", "đồng hồ đeo tay", "HSK2", "3 3"},
	{"手机", "shou3 ji1", "điện thoại di động", "HSK2", "3 1"},
	{"送", "song4", "tặng; tiễn; đưa", "HSK2", "4"},
	{"所以", "suo3 yi3", "cho nên", "HSK2", "3 3"},
	{"它", "ta1", "nó", "HSK2", "1"},
	{"踢", "ti1", "đá", "HSK2", "1"},
	{"题", "ti2", "đề, câu hỏi", "HSK2", "2"},
	{"跳舞", "tiao4 wu3", "nhảy múa", "HSK2", "4 3"},
	{"外", "wai4", "bên ngoài", "HSK2", "4"},
	{"完", "wan2", "xong", "HSK2", "2"},
	{"玩", "wan2", "chơi", "HSK2", "2"},
	{"晚上", "wan3 shang5", "buổi tối", "HSK2", "3 5"},
	{"为", "wei4", "vì, để, làm (vì)", "HSK2", "4"},
	{"问", "wen4", "hỏi", "HSK2", "4"},
	{"问题", "wen4 ti2", "câu hỏi", "HSK2", "4 2"},
	{"西瓜", "xi1 gua1", "dưa hấu", "HSK2", "1 1"},
	{"希望", "xi1 wang4", "hy vọng", "HSK2", "1 4"},
	{"洗", "xi3", "rửa/giặt", "HSK2", "3"},
	{"向", "xiang4", "hướng về, phía", "HSK2", "4"},
	{"小时", "xiao3 shi2", "giờ", "HSK2", "3 2"},
	{"笑", "xiao4", "cười", "HSK2", "4"},
	{"新", "xin1", "mới", "HSK2", "1"},
	{"姓", "xing4", "họ (tên họ)", "HSK2", "4"},
	{"休息", "xiu1 xi5", "nghỉ ngơi", "HSK2", "1 5"},
	{"雪", "xue3", "tuyết", "HSK2", "3"},
	{"颜色", "yan2 se4", "màu sắc", "HSK2", "2 4"},
	{"眼睛", "yan3 jing5", "mắt", "HSK2", "3 5"},
	{"羊肉", "yang2 rou4", "thịt cừu", "HSK2", "2 4"},
	{"药", "yao4", "thuốc", "HSK2", "4"},
	{"要", "yao4", "muốn, cần, sẽ", "HSK2", "4"},
	{"也", "ye3", "cũng", "HSK2", "3"},
	{"已经", "yi3 jing1", "đã", "HSK2", "3 1"},
	{"一起", "yi1 qi3", "cùng nhau", "HSK2", "1 3"},
	{"意思", "yi4 si5", "ý tưởng", "HSK2", "4 5"},
	{"阴", "yin1", "âm u", "HSK2", "1"},
	{"因为", "yin1 wei4", "vì, bởi vì", "HSK2", "1 4"},
	{"游泳", "you2 yong3", "bơi lội", "HSK2", "2 3"},
	{"右边", "you4 bian5", "bên phải", "HSK2", "4 5"},
	{"鱼", "yu2", "cá", "HSK2", "2"},
	{"元", "yuan2", "đồng (đơn vị tiền tệ)", "HSK2", "2"},
	{"远", "yuan3", "xa", "HSK2", "3"},
	{"运动", "yun4 dong4", "thể thao, vận động", "HSK2", "4 4"},
	{"再", "zai4", "lại, nữa (lần sau)", "HSK2", "4"},
	{"早上", "zao3 shang5", "buổi sáng (sớm)", "HSK2", "3 5"},
	{"张", "zhang1", "tờ, tấm (lượng từ)", "HSK2", "1"},
	{"丈夫", "zhang4 fu5", "chồng", "HSK2", "4 5"},
	{"找", "zhao3", "tìm", "HSK2", "3"},
	{"着", "zhe5", "trợ từ tiếp diễn (đang...)", "HSK2", "5"},
	{"真", "zhen1", "thật sự", "HSK2", "1"},
	{"正在", "zheng4 zai4", "đang (ngay lúc này)", "HSK2", "4 4"},
	{"知道", "zhi1 dao4", "biết", "HSK2", "1 4"},
	{"准备", "zhun3 bei4", "chuẩn bị", "HSK2", "3 4"},
	{"自行车", "zi4 xing2 che1", "xe đạp", "HSK2", "4 2 1"},
	{"走", "zou3", "đi bộ", "HSK2", "3"},
	{"最", "zui4", "nhất", "HSK2", "4"},
	{"左边", "zuo3 bian5", "bên trái", "HSK2", "3 5"},
}

// hsk3Seed — seed HSK3.
var hsk3Seed = []HskEntry{
	{"阿姨", "a1 yi2", "dì, cô (gọi phụ nữ trung niên)", "HSK3", "1 2"},
	{"啊", "a5", "trợ từ cảm thán (a, à)", "HSK3", "5"},
	{"矮", "ai3", "thấp", "HSK3", "3"},
	{"爱好", "ai4 hao4", "thích", "HSK3", "4 4"},
	{"安静", "an1 jing4", "yên tĩnh", "HSK3", "1 4"},
	{"把", "ba3", "giới từ (đem, cầm lấy)", "HSK3", "3"},
	{"搬", "ban1", "chuyển (nhà, đồ)", "HSK3", "1"},
	{"班", "ban1", "lớp; ca (làm việc)", "HSK3", "1"},
	{"半", "ban4", "một nửa", "HSK3", "4"},
	{"办法", "ban4 fa3", "biện pháp", "HSK3", "4 3"},
	{"办公室", "ban4 gong1 shi4", "văn phòng", "HSK3", "4 1 4"},
	{"帮忙", "bang1 mang2", "giúp", "HSK3", "1 2"},
	{"包", "bao1", "gói; túi", "HSK3", "1"},
	{"饱", "bao3", "ăn no", "HSK3", "3"},
	{"北方", "bei3 fang1", "phía bắc", "HSK3", "3 1"},
	{"被", "bei4", "bị, được (câu bị động)", "HSK3", "4"},
	{"鼻子", "bi2 zi5", "mũi", "HSK3", "2 5"},
	{"比较", "bi3 jiao4", "so sánh", "HSK3", "3 4"},
	{"比赛", "bi3 sai4", "cuộc thi", "HSK3", "3 4"},
	{"必须", "bi4 xu1", "phải, bắt buộc", "HSK3", "4 1"},
	{"变化", "bian4 hua4", "đổi/thay đổi", "HSK3", "4 4"},
	{"表示", "biao3 shi4", "bày tỏ", "HSK3", "3 4"},
	{"表演", "biao3 yan3", "biểu diễn", "HSK3", "3 3"},
	{"别人", "bie2 ren5", "người khác", "HSK3", "2 5"},
	{"宾馆", "bin1 guan3", "nhà khách", "HSK3", "1 3"},
	{"冰箱", "bing1 xiang1", "tủ lạnh", "HSK3", "1 1"},
	{"才", "cai2", "tài năng; vừa mới", "HSK3", "2"},
	{"菜单", "cai4 dan1", "thực đơn", "HSK3", "4 1"},
	{"参加", "can1 jia1", "tham gia", "HSK3", "1 1"},
	{"草", "cao3", "cỏ", "HSK3", "3"},
	{"层", "ceng2", "lớp", "HSK3", "2"},
	{"差", "cha4", "kém, thiếu, tệ", "HSK3", "4"},
	{"超市", "chao1 shi4", "siêu thị", "HSK3", "1 4"},
	{"衬衫", "chen4 shan1", "áo sơ mi", "HSK3", "4 1"},
	{"成绩", "cheng2 ji4", "thành tích", "HSK3", "2 4"},
	{"城市", "cheng2 shi4", "thành phố", "HSK3", "2 4"},
	{"迟到", "chi2 dao4", "đến muộn", "HSK3", "2 4"},
	{"出现", "chu1 xian4", "xuất hiện", "HSK3", "1 4"},
	{"除了", "chu2 le5", "ngoài ra", "HSK3", "2 5"},
	{"厨房", "chu2 fang2", "nhà bếp", "HSK3", "2 2"},
	{"春", "chun1", "mùa xuân", "HSK3", "1"},
	{"词语", "ci2 yu3", "từ", "HSK3", "2 3"},
	{"聪明", "cong1 ming5", "thông minh", "HSK3", "1 5"},
	{"打扫", "da3 sao3", "quét dọn", "HSK3", "3 3"},
	{"打算", "da3 suan4", "lên kế hoạch", "HSK3", "3 4"},
	{"带", "dai4", "mang theo, dẫn theo", "HSK3", "4"},
	{"担心", "dan1 xin1", "lo lắng", "HSK3", "1 1"},
	{"蛋糕", "dan4 gao1", "bánh ngọt", "HSK3", "4 1"},
	{"当然", "dang1 ran2", "đương nhiên", "HSK3", "1 2"},
	{"地", "de5", "trợ từ (một cách...)", "HSK3", "5"},
	{"灯", "deng1", "đèn", "HSK3", "1"},
	{"低", "di1", "thấp", "HSK3", "1"},
	{"地方", "di4 fang5", "nơi, chỗ", "HSK3", "4 5"},
	{"地铁", "di4 tie3", "tàu điện ngầm", "HSK3", "4 3"},
	{"地图", "di4 tu2", "bản đồ", "HSK3", "4 2"},
	{"电梯", "dian4 ti1", "thang máy", "HSK3", "4 1"},
	{"电子", "dian4 zi3", "điện tử", "HSK3", "4 3"},
	{"冬", "dong1", "mùa đông", "HSK3", "1"},
	{"东", "dong1", "phía đông", "HSK3", "1"},
	{"动物", "dong4 wu4", "động vật", "HSK3", "4 4"},
	{"短", "duan3", "ngắn", "HSK3", "3"},
	{"段", "duan4", "đoạn", "HSK3", "4"},
	{"锻炼", "duan4 lian4", "rèn luyện (thể dục)", "HSK3", "4 4"},
	{"多么", "duo1 me5", "biết bao", "HSK3", "1 5"},
	{"饿", "e4", "đói", "HSK3", "4"},
	{"而且", "er2 qie3", "hơn nữa, vả lại", "HSK3", "2 3"},
	{"耳朵", "er3 duo5", "tai", "HSK3", "3 5"},
	{"发烧", "fa1 shao1", "sốt", "HSK3", "1 1"},
	{"发现", "fa1 xian4", "tìm thấy", "HSK3", "1 4"},
	{"方便", "fang1 bian4", "tiện lợi", "HSK3", "1 4"},
	{"放", "fang4", "đặt, để; thả", "HSK3", "4"},
	{"放心", "fang4 xin1", "cảm thấy nhẹ nhõm", "HSK3", "4 1"},
	{"分", "fen1", "chia; phút (điểm số)", "HSK3", "1"},
	{"附近", "fu4 jin4", "vùng lân cận", "HSK3", "4 4"},
	{"复习", "fu4 xi2", "ôn tập", "HSK3", "4 2"},
	{"干净", "gan1 jing4", "sạch", "HSK3", "1 4"},
	{"敢", "gan3", "dám", "HSK3", "3"},
	{"感冒", "gan3 mao4", "bị cảm", "HSK3", "3 4"},
	{"刚才", "gang1 cai2", "cách đây chốc lát", "HSK3", "1 2"},
	{"根据", "gen1 ju4", "theo", "HSK3", "1 4"},
	{"跟", "gen1", "và, với, theo (cùng)", "HSK3", "1"},
	{"更", "geng4", "càng, hơn", "HSK3", "4"},
	{"公园", "gong1 yuan2", "công viên", "HSK3", "1 2"},
	{"故事", "gu4 shi5", "câu chuyện", "HSK3", "4 5"},
	{"刮", "gua1", "thổi", "HSK3", "1"},
	{"关", "guan1", "đóng; liên quan", "HSK3", "1"},
	{"关系", "guan1 xi5", "quan hệ", "HSK3", "1 5"},
	{"关心", "guan1 xin1", "quan tâm", "HSK3", "1 1"},
	{"关于", "guan1 yu2", "thuộc về", "HSK3", "1 2"},
	{"国家", "guo2 jia1", "đất nước", "HSK3", "2 1"},
	{"果汁", "guo3 zhi1", "nước ép hoa quả", "HSK3", "3 1"},
	{"过去", "guo4 qu5", "trước đây, đã qua", "HSK3", "4 5"},
	{"还是", "hai2 shi5", "hoặc (câu hỏi); vẫn", "HSK3", "2 5"},
	{"害怕", "hai4 pa4", "sợ hãi", "HSK3", "4 4"},
	{"河", "he2", "sông", "HSK3", "2"},
	{"黑板", "hei1 ban3", "bảng đen", "HSK3", "1 3"},
	{"护照", "hu4 zhao4", "hộ chiếu", "HSK3", "4 4"},
	{"花", "hua1", "hoa", "HSK3", "1"},
	{"花园", "hua1 yuan2", "vườn", "HSK3", "1 2"},
	{"画", "hua4", "vẽ", "HSK3", "4"},
	{"坏", "huai4", "xấu", "HSK3", "4"},
	{"环境", "huan2 jing4", "môi trường", "HSK3", "2 4"},
	{"换", "huan4", "đổi/thay đổi", "HSK3", "4"},
	{"黄", "huang2", "vàng", "HSK3", "2"},
	{"会议", "hui4 yi4", "cuộc họp", "HSK3", "4 4"},
	{"或者", "huo4 zhe3", "hoặc", "HSK3", "4 3"},
	{"机会", "ji1 hui4", "cơ hội", "HSK3", "1 4"},
	{"几乎", "ji1 hu1", "gần như", "HSK3", "1 1"},
	{"极", "ji2", "cực kỳ", "HSK3", "2"},
	{"记得", "ji4 de5", "nhớ", "HSK3", "4 5"},
	{"季节", "ji4 jie2", "mùa", "HSK3", "4 2"},
	{"检查", "jian3 cha2", "kiểm tra", "HSK3", "3 2"},
	{"简单", "jian3 dan1", "đơn giản", "HSK3", "3 1"},
	{"见面", "jian4 mian4", "gặp", "HSK3", "4 4"},
	{"健康", "jian4 kang1", "sức khỏe", "HSK3", "4 1"},
	{"讲", "jiang3", "nói", "HSK3", "3"},
	{"教", "jiao1", "dạy", "HSK3", "1"},
	{"脚", "jiao3", "bàn chân", "HSK3", "3"},
	{"角", "jiao3", "góc", "HSK3", "3"},
	{"接", "jie1", "nhận", "HSK3", "1"},
	{"街道", "jie1 dao4", "phố", "HSK3", "1 4"},
	{"节目", "jie2 mu4", "tiết mục, chương trình", "HSK3", "2 4"},
	{"节日", "jie2 ri4", "kỳ nghỉ", "HSK3", "2 4"},
	{"结婚", "jie2 hun1", "kết hôn", "HSK3", "2 1"},
	{"结束", "jie2 shu4", "kết thúc", "HSK3", "2 4"},
	{"解决", "jie3 jue2", "giải quyết", "HSK3", "3 2"},
	{"借", "jie4", "cho mượn", "HSK3", "4"},
	{"经常", "jing1 chang2", "thường xuyên", "HSK3", "1 2"},
	{"经过", "jing1 guo4", "đi qua; trải qua", "HSK3", "1 4"},
	{"经理", "jing1 li3", "quản lý", "HSK3", "1 3"},
	{"久", "jiu3", "lâu", "HSK3", "3"},
	{"旧", "jiu4", "cũ/già", "HSK3", "4"},
	{"举行", "ju3 xing2", "tổ chức (họp, lễ)", "HSK3", "3 2"},
	{"句子", "ju4 zi5", "câu", "HSK3", "4 5"},
	{"决定", "jue2 ding4", "quyết định", "HSK3", "2 4"},
	{"渴", "ke3", "khát", "HSK3", "3"},
	{"可爱", "ke3 ai4", "đáng yêu", "HSK3", "3 4"},
	{"刻", "ke4", "mười lăm phút", "HSK3", "4"},
	{"客人", "ke4 ren2", "khách thăm", "HSK3", "4 2"},
	{"空调", "kong1 tiao2", "điều hòa", "HSK3", "1 2"},
	{"口", "kou3", "miệng", "HSK3", "3"},
	{"哭", "ku1", "khóc", "HSK3", "1"},
	{"裤子", "ku4 zi5", "quần dài", "HSK3", "4 5"},
	{"筷子", "kuai4 zi5", "đũa", "HSK3", "4 5"},
	{"蓝", "lan2", "xanh da trời", "HSK3", "2"},
	{"老", "lao3", "già; (tiền tố gọi thân mật)", "HSK3", "3"},
	{"离开", "li2 kai1", "rời khỏi", "HSK3", "2 1"},
	{"礼物", "li3 wu4", "quà", "HSK3", "3 4"},
	{"历史", "li4 shi3", "lịch sử", "HSK3", "4 3"},
	{"脸", "lian3", "mặt", "HSK3", "3"},
	{"练习", "lian4 xi2", "luyện tập", "HSK3", "4 2"},
	{"辆", "liang4", "lượng từ (xe cộ)", "HSK3", "4"},
	{"了解", "liao3 jie3", "hiểu", "HSK3", "3 3"},
	{"邻居", "lin2 ju1", "hàng xóm", "HSK3", "2 1"},
	{"楼", "lou2", "tòa nhà, tầng lầu", "HSK3", "2"},
	{"绿", "lü4", "xanh lá", "HSK3", "4"},
	{"马", "ma3", "ngựa", "HSK3", "3"},
	{"马上", "ma3 shang4", "ngay lập tức", "HSK3", "3 4"},
	{"满意", "man3 yi4", "hài lòng", "HSK3", "3 4"},
	{"帽子", "mao4 zi5", "mũ", "HSK3", "4 5"},
	{"米", "mi3", "gạo; mét", "HSK3", "3"},
	{"面包", "mian4 bao1", "bánh mì", "HSK3", "4 1"},
	{"面条", "mian4 tiao2", "mì sợi", "HSK3", "4 2"},
	{"明白", "ming2 bai5", "rõ ràng", "HSK3", "2 5"},
	{"拿", "na2", "cầm, lấy", "HSK3", "2"},
	{"奶奶", "nai3 nai5", "bà", "HSK3", "3 5"},
	{"南", "nan2", "phía nam", "HSK3", "2"},
	{"难", "nan2", "khó", "HSK3", "2"},
	{"难过", "nan2 guo4", "cảm thấy buồn", "HSK3", "2 4"},
	{"年级", "nian2 ji2", "khối lớp", "HSK3", "2 2"},
	{"年轻", "nian2 qing1", "trẻ", "HSK3", "2 1"},
	{"鸟", "niao3", "chim", "HSK3", "3"},
	{"努力", "nu3 li4", "nỗ lực", "HSK3", "3 4"},
	{"爬山", "pa2 shan1", "leo núi", "HSK3", "2 1"},
	{"盘子", "pan2 zi5", "khay", "HSK3", "2 5"},
	{"胖", "pang4", "béo", "HSK3", "4"},
	{"啤酒", "pi2 jiu3", "bia", "HSK3", "2 3"},
	{"葡萄", "pu2 tao5", "nho", "HSK3", "2 5"},
	{"普通话", "pu3 tong1 hua4", "tiếng phổ thông", "HSK3", "3 1 4"},
	{"骑", "qi2", "cưỡi/đi xe", "HSK3", "2"},
	{"其实", "qi2 shi2", "thật ra", "HSK3", "2 2"},
	{"其他", "qi2 ta1", "khác, còn lại", "HSK3", "2 1"},
	{"奇怪", "qi2 guai4", "lạ", "HSK3", "2 4"},
	{"铅笔", "qian1 bi3", "bút chì", "HSK3", "1 3"},
	{"清楚", "qing1 chu5", "rõ ràng", "HSK3", "1 5"},
	{"秋", "qiu1", "mùa thu", "HSK3", "1"},
	{"裙子", "qun2 zi5", "chân váy", "HSK3", "2 5"},
	{"然后", "ran2 hou4", "sau đó", "HSK3", "2 4"},
	{"热情", "re4 qing2", "nồng hậu", "HSK3", "4 2"},
	{"认为", "ren4 wei2", "cho rằng", "HSK3", "4 2"},
	{"认真", "ren4 zhen1", "tận tâm", "HSK3", "4 1"},
	{"容易", "rong2 yi4", "dễ", "HSK3", "2 4"},
	{"如果", "ru2 guo3", "nếu", "HSK3", "2 3"},
	{"伞", "san3", "ô/dù", "HSK3", "3"},
	{"上网", "shang4 wang3", "lên mạng", "HSK3", "4 3"},
	{"生气", "sheng1 qi4", "tức giận", "HSK3", "1 4"},
	{"声音", "sheng1 yin1", "tiếng, giọng", "HSK3", "1 1"},
	{"使", "shi3", "khiến, làm cho", "HSK3", "3"},
	{"世界", "shi4 jie4", "thế giới", "HSK3", "4 4"},
	{"瘦", "shou4", "gầy", "HSK3", "4"},
	{"舒服", "shu1 fu5", "thoải mái", "HSK3", "1 5"},
	{"叔叔", "shu1 shu5", "chú", "HSK3", "1 5"},
	{"树", "shu4", "cây", "HSK3", "4"},
	{"数学", "shu4 xue2", "toán học", "HSK3", "4 2"},
	{"刷", "shua1", "chải/đánh", "HSK3", "1"},
	{"双", "shuang1", "đôi", "HSK3", "1"},
	{"水平", "shui3 ping2", "trình độ", "HSK3", "3 2"},
	{"司机", "si1 ji1", "tài xế", "HSK3", "1 1"},
	{"虽然", "sui1 ran2", "mặc dù", "HSK3", "1 2"},
	{"太阳", "tai4 yang2", "mặt trời", "HSK3", "4 2"},
	{"糖", "tang2", "đường", "HSK3", "2"},
	{"特别", "te4 bie2", "đặc biệt", "HSK3", "4 2"},
	{"疼", "teng2", "đau", "HSK3", "2"},
	{"提高", "ti2 gao1", "nâng cao", "HSK3", "2 1"},
	{"体育", "ti3 yu4", "thể dục thể thao", "HSK3", "3 4"},
	{"甜", "tian2", "ngọt", "HSK3", "2"},
	{"条", "tiao2", "sợi, con (lượng từ vật dài)", "HSK3", "2"},
	{"同事", "tong2 shi4", "đồng nghiệp", "HSK3", "2 4"},
	{"同意", "tong2 yi4", "đồng ý", "HSK3", "2 4"},
	{"头发", "tou2 fa5", "tóc", "HSK3", "2 5"},
	{"突然", "tu1 ran2", "đột ngột", "HSK3", "1 2"},
	{"图书馆", "tu2 shu1 guan3", "thư viện", "HSK3", "2 1 3"},
	{"腿", "tui3", "chân", "HSK3", "3"},
	{"完成", "wan2 cheng2", "hoàn thành", "HSK3", "2 2"},
	{"碗", "wan3", "bát", "HSK3", "3"},
	{"万", "wan4", "vạn", "HSK3", "4"},
	{"忘记", "wang4 ji4", "quên", "HSK3", "4 4"},
	{"为了", "wei4 le5", "để, vì", "HSK3", "4 5"},
	{"为什么", "wei4 shen2 me5", "tại sao", "HSK3", "4 2 5"},
	{"位", "wei4", "chỗ, vị", "HSK3", "4"},
	{"文化", "wen2 hua4", "văn hóa", "HSK3", "2 4"},
	{"西", "xi1", "phía tây", "HSK3", "1"},
	{"习惯", "xi2 guan4", "thói quen", "HSK3", "2 4"},
	{"洗手间", "xi3 shou3 jian1", "nhà vệ sinh", "HSK3", "3 3 1"},
	{"洗澡", "xi3 zao3", "tắm", "HSK3", "3 3"},
	{"夏", "xia4", "mùa hè", "HSK3", "4"},
	{"先", "xian1", "trước", "HSK3", "1"},
	{"香蕉", "xiang1 jiao1", "chuối", "HSK3", "1 1"},
	{"相同", "xiang1 tong2", "giống hệt", "HSK3", "1 2"},
	{"相信", "xiang1 xin4", "tin tưởng", "HSK3", "1 4"},
	{"像", "xiang4", "giống như", "HSK3", "4"},
	{"小心", "xiao3 xin1", "cẩn thận", "HSK3", "3 1"},
	{"校长", "xiao4 zhang3", "hiệu trưởng", "HSK3", "4 3"},
	{"鞋", "xie2", "giày", "HSK3", "2"},
	{"新闻", "xin1 wen2", "tin tức", "HSK3", "1 2"},
	{"新鲜", "xin1 xian1", "tươi", "HSK3", "1 1"},
	{"信", "xin4", "thư", "HSK3", "4"},
	{"行李箱", "xing2 li5 xiang1", "va li", "HSK3", "2 5 1"},
	{"兴趣", "xing4 qu4", "hứng thú", "HSK3", "4 4"},
	{"熊猫", "xiong2 mao1", "gấu trúc", "HSK3", "2 1"},
	{"需要", "xu1 yao4", "cần", "HSK3", "1 4"},
	{"选择", "xuan3 ze2", "chọn", "HSK3", "3 2"},
	{"眼镜", "yan3 jing4", "kính đeo mắt", "HSK3", "3 4"},
	{"要求", "yao1 qiu2", "thỉnh cầu", "HSK3", "1 2"},
	{"爷爷", "ye2 ye5", "ông nội", "HSK3", "2 5"},
	{"一定", "yi1 ding4", "chắc chắn", "HSK3", "1 4"},
	{"一共", "yi1 gong4", "tổng cộng", "HSK3", "1 4"},
	{"一会儿", "yi1 hui4 r5", "một lát", "HSK3", "1 4 5"},
	{"一样", "yi1 yang4", "giống nhau", "HSK3", "1 4"},
	{"以后", "yi3 hou4", "sau này, về sau", "HSK3", "3 4"},
	{"以前", "yi3 qian2", "trước đây", "HSK3", "3 2"},
	{"以为", "yi3 wei2", "cho rằng, tưởng là", "HSK3", "3 2"},
	{"一般", "yi1 ban1", "bình thường, thông thường", "HSK3", "1 1"},
	{"一边", "yi1 bian1", "một bên; vừa... vừa...", "HSK3", "1 1"},
	{"一直", "yi1 zhi2", "thẳng", "HSK3", "1 2"},
	{"音乐", "yin1 yue4", "âm nhạc", "HSK3", "1 4"},
	{"银行", "yin2 hang2", "ngân hàng", "HSK3", "2 2"},
	{"应该", "ying1 gai1", "nên, phải", "HSK3", "1 1"},
	{"影响", "ying3 xiang3", "ảnh hưởng", "HSK3", "3 3"},
	{"用", "yong4", "dùng", "HSK3", "4"},
	{"游戏", "you2 xi4", "trò chơi", "HSK3", "2 4"},
	{"有名", "you3 ming2", "nổi tiếng", "HSK3", "3 2"},
	{"又", "you4", "lại (đã lặp)", "HSK3", "4"},
	{"遇到", "yu4 dao4", "gặp", "HSK3", "4 4"},
	{"愿意", "yuan4 yi4", "đồng ý, muốn, sẵn lòng", "HSK3", "4 4"},
	{"越", "yue4", "vượt qua; (càng... càng...)", "HSK3", "4"},
	{"月亮", "yue4 liang5", "mặt trăng", "HSK3", "4 5"},
	{"云", "yun2", "mây", "HSK3", "2"},
	{"站", "zhan4", "trạm; đứng", "HSK3", "4"},
	{"着急", "zhao2 ji2", "lo lắng", "HSK3", "2 2"},
	{"照顾", "zhao4 gu5", "chăm sóc", "HSK3", "4 5"},
	{"照片", "zhao4 pian4", "ảnh chụp", "HSK3", "4 4"},
	{"照相机", "zhao4 xiang4 ji1", "máy ảnh", "HSK3", "4 4 1"},
	{"只", "zhi3", "chỉ (duy nhất)", "HSK3", "3"},
	{"终于", "zhong1 yu2", "cuối cùng", "HSK3", "1 2"},
	{"中间", "zhong1 jian1", "giữa", "HSK3", "1 1"},
	{"种", "zhong3", "loại; gieo trồng", "HSK3", "3"},
	{"重要", "zhong4 yao4", "quan trọng", "HSK3", "4 4"},
	{"周末", "zhou1 mo4", "cuối tuần", "HSK3", "1 4"},
	{"主要", "zhu3 yao4", "chủ yếu", "HSK3", "3 4"},
	{"祝", "zhu4", "chúc", "HSK3", "4"},
	{"注意", "zhu4 yi4", "chú ý", "HSK3", "4 4"},
	{"字典", "zi4 dian3", "từ điển", "HSK3", "4 3"},
	{"自己", "zi4 ji3", "bản thân, tự mình", "HSK3", "4 3"},
	{"总是", "zong3 shi4", "luôn luôn", "HSK3", "3 4"},
	{"最近", "zui4 jin4", "gần đây", "HSK3", "4 4"},
	{"作业", "zuo4 ye4", "bài tập (về nhà)", "HSK3", "4 4"},
	{"作用", "zuo4 yong4", "tác dụng", "HSK3", "4 4"},
}

// hsk4Seed — seed HSK4.
var hsk4Seed = []HskEntry{
	{"爱情", "ai4 qing2", "tình yêu (nam nữ)", "HSK4", "4 2"},
	{"安排", "an1 pai2", "sắp xếp", "HSK4", "1 2"},
	{"安全", "an1 quan2", "an toàn", "HSK4", "1 2"},
	{"暗", "an4", "tối, u ám", "HSK4", "4"},
	{"按时", "an4 shi2", "đúng giờ", "HSK4", "4 2"},
	{"按照", "an4 zhao4", "theo", "HSK4", "4 4"},
	{"包括", "bao1 kuo4", "bao gồm", "HSK4", "1 4"},
	{"保护", "bao3 hu4", "bảo vệ", "HSK4", "3 4"},
	{"保证", "bao3 zheng4", "bảo đảm", "HSK4", "3 4"},
	{"抱", "bao4", "cầm/nắm", "HSK4", "4"},
	{"抱歉", "bao4 qian4", "là tiếc/xin lỗi", "HSK4", "4 4"},
	{"报道", "bao4 dao4", "báo cáo", "HSK4", "4 4"},
	{"报名", "bao4 ming2", "đăng ký", "HSK4", "4 2"},
	{"倍", "bei4", "gấp (bội số)", "HSK4", "4"},
	{"本来", "ben3 lai2", "vốn có", "HSK4", "3 2"},
	{"笨", "ben4", "ngốc, đần", "HSK4", "4"},
	{"笔记本", "bi3 ji4 ben3", "vở", "HSK4", "3 4 3"},
	{"毕业", "bi4 ye4", "tốt nghiệp", "HSK4", "4 4"},
	{"遍", "bian4", "khắp nơi", "HSK4", "4"},
	{"标准", "biao1 zhun3", "tiêu chuẩn", "HSK4", "1 3"},
	{"表达", "biao3 da2", "bày tỏ", "HSK4", "3 2"},
	{"表格", "biao3 ge2", "biểu mẫu", "HSK4", "3 2"},
	{"表扬", "biao3 yang2", "khen ngợi", "HSK4", "3 2"},
	{"饼干", "bing3 gan1", "bánh quy", "HSK4", "3 1"},
	{"并且", "bing4 qie3", "và", "HSK4", "4 3"},
	{"博士", "bo2 shi4", "tiến sĩ", "HSK4", "2 4"},
	{"不但", "bu4 dan4", "không những", "HSK4", "4 4"},
	{"不过", "bu4 guo4", "chẳng qua, có điều là", "HSK4", "4 4"},
	{"不得不", "bu4 de2 bu4", "đành phải", "HSK4", "4 2 4"},
	{"不管", "bu4 guan3", "bất kể, dù", "HSK4", "4 3"},
	{"不仅", "bu4 jin3", "không chỉ", "HSK4", "4 3"},
	{"部分", "bu4 fen5", "bộ phận", "HSK4", "4 5"},
	{"擦", "ca1", "lau, chùi", "HSK4", "1"},
	{"猜", "cai1", "đoán", "HSK4", "1"},
	{"材料", "cai2 liao4", "tài liệu, nguyên liệu", "HSK4", "2 4"},
	{"参观", "can1 guan1", "tham quan", "HSK4", "1 1"},
	{"差不多", "cha4 bu5 duo1", "gần như, suýt soát", "HSK4", "4 5 1"},
	{"长城", "chang2 cheng2", "Vạn Lý Trường Thành", "HSK4", "2 2"},
	{"长江", "chang2 jiang1", "sông Dương Tử", "HSK4", "2 1"},
	{"尝", "chang2", "nếm thử", "HSK4", "2"},
	{"场", "chang3", "nơi, bãi", "HSK4", "3"},
	{"超过", "chao1 guo4", "vượt quá", "HSK4", "1 4"},
	{"吵", "chao3", "cãi nhau", "HSK4", "3"},
	{"乘坐", "cheng2 zuo4", "cưỡi/đi xe", "HSK4", "2 4"},
	{"成功", "cheng2 gong1", "thành công", "HSK4", "2 1"},
	{"成熟", "cheng2 shu2", "chững chạc", "HSK4", "2 2"},
	{"成为", "cheng2 wei2", "trở thành", "HSK4", "2 2"},
	{"诚实", "cheng2 shi2", "thật thà", "HSK4", "2 2"},
	{"吃惊", "chi1 jing1", "giật mình, kinh ngạc", "HSK4", "1 1"},
	{"重新", "chong2 xin1", "lại", "HSK4", "2 1"},
	{"抽烟", "chou1 yan1", "hút thuốc", "HSK4", "1 1"},
	{"出差", "chu1 chai1", "đi công tác", "HSK4", "1 1"},
	{"出发", "chu1 fa1", "xuất phát", "HSK4", "1 1"},
	{"出生", "chu1 sheng1", "ra đời, sinh ra", "HSK4", "1 1"},
	{"传真", "chuan2 zhen1", "bản fax", "HSK4", "2 1"},
	{"窗户", "chuang1 hu5", "cửa sổ", "HSK4", "1 5"},
	{"词典", "ci2 dian3", "từ điển", "HSK4", "2 3"},
	{"从来", "cong2 lai2", "từ trước tới nay (luôn)", "HSK4", "2 2"},
	{"粗心", "cu1 xin1", "cẩu thả", "HSK4", "1 1"},
	{"答案", "da2 an4", "đáp án", "HSK4", "2 4"},
	{"打扮", "da3 ban5", "ăn diện", "HSK4", "3 5"},
	{"打扰", "da3 rao3", "làm phiền", "HSK4", "3 3"},
	{"打印", "da3 yin4", "in ấn", "HSK4", "3 4"},
	{"打折", "da3 zhe2", "giảm giá", "HSK4", "3 2"},
	{"打针", "da3 zhen1", "tiêm (thuốc)", "HSK4", "3 1"},
	{"大概", "da4 gai4", "khoảng, đại khái", "HSK4", "4 4"},
	{"大使馆", "da4 shi3 guan3", "đại sứ quán", "HSK4", "4 3 3"},
	{"大约", "da4 yue1", "khoảng chừng", "HSK4", "4 1"},
	{"戴", "dai4", "đeo, đội", "HSK4", "4"},
	{"代表", "dai4 biao3", "đại diện, đại biểu", "HSK4", "4 3"},
	{"代替", "dai4 ti4", "thay thế", "HSK4", "4 4"},
	{"大夫", "dai4 fu5", "bác sĩ", "HSK4", "4 5"},
	{"当", "dang1", "làm, đảm nhiệm", "HSK4", "1"},
	{"当地", "dang1 di4", "địa phương, bản địa", "HSK4", "1 4"},
	{"当时", "dang1 shi2", "lúc ấy", "HSK4", "1 2"},
	{"刀", "dao1", "con dao", "HSK4", "1"},
	{"导游", "dao3 you2", "hướng dẫn viên du lịch", "HSK4", "3 2"},
	{"到处", "dao4 chu4", "khắp nơi", "HSK4", "4 4"},
	{"到底", "dao4 di3", "rốt cuộc", "HSK4", "4 3"},
	{"道歉", "dao4 qian4", "xin lỗi", "HSK4", "4 4"},
	{"得意", "de2 yi4", "đắc ý", "HSK4", "2 4"},
	{"等", "deng3", "đợi; hạng", "HSK4", "3"},
	{"底", "di3", "đáy, nền", "HSK4", "3"},
	{"地球", "di4 qiu2", "trái đất", "HSK4", "4 2"},
	{"地址", "di4 zhi3", "địa chỉ", "HSK4", "4 3"},
	{"掉", "diao4", "ngã/rơi", "HSK4", "4"},
	{"调查", "diao4 cha2", "điều tra", "HSK4", "4 2"},
	{"丢", "diu1", "mất", "HSK4", "1"},
	{"动作", "dong4 zuo4", "động tác", "HSK4", "4 4"},
	{"堵车", "du3 che1", "tắc đường", "HSK4", "3 1"},
	{"肚子", "du4 zi5", "bụng", "HSK4", "4 5"},
	{"断", "duan4", "vỡ/gãy", "HSK4", "4"},
	{"对", "dui4", "đúng; đôi; với", "HSK4", "4"},
	{"对话", "dui4 hua4", "đối thoại", "HSK4", "4 4"},
	{"对面", "dui4 mian4", "đối diện", "HSK4", "4 4"},
	{"顿", "dun4", "dừng", "HSK4", "4"},
	{"朵", "duo3", "hoa", "HSK4", "3"},
	{"而", "er2", "mà, nhưng (nối câu)", "HSK4", "2"},
	{"儿童", "er2 tong2", "trẻ em", "HSK4", "2 2"},
	{"发", "fa1", "phát ra", "HSK4", "1"},
	{"发生", "fa1 sheng1", "xảy ra", "HSK4", "1 1"},
	{"发展", "fa1 zhan3", "phát triển", "HSK4", "1 3"},
	{"法律", "fa3 lü4", "pháp luật", "HSK4", "3 4"},
	{"翻译", "fan1 yi4", "biên dịch, phiên dịch", "HSK4", "1 4"},
	{"烦恼", "fan2 nao3", "buồn phiền", "HSK4", "2 3"},
	{"反对", "fan3 dui4", "phản đối", "HSK4", "3 4"},
	{"反映", "fan3 ying4", "phản ánh", "HSK4", "3 4"},
	{"范围", "fan4 wei2", "phạm vi", "HSK4", "4 2"},
	{"方法", "fang1 fa3", "phương pháp", "HSK4", "1 3"},
	{"方面", "fang1 mian4", "mặt, phương diện", "HSK4", "1 4"},
	{"方向", "fang1 xiang4", "hướng", "HSK4", "1 4"},
	{"访问", "fang3 wen4", "thăm (chính thức)", "HSK4", "3 4"},
	{"放弃", "fang4 qi4", "từ bỏ", "HSK4", "4 4"},
	{"放暑假", "fang4 shu3 jia4", "nghỉ hè", "HSK4", "4 3 4"},
	{"分之", "fen1 zhi1", "phần (chỉ phân số)", "HSK4", "1 1"},
	{"份", "fen4", "suất, phần (lượng từ)", "HSK4", "4"},
	{"风景", "feng1 jing3", "phong cảnh", "HSK4", "1 3"},
	{"丰富", "feng1 fu4", "phong phú", "HSK4", "1 4"},
	{"否则", "fou3 ze2", "nếu không", "HSK4", "3 2"},
	{"符合", "fu2 he2", "phù hợp", "HSK4", "2 2"},
	{"富", "fu4", "giàu", "HSK4", "4"},
	{"负责", "fu4 ze2", "phụ trách", "HSK4", "4 2"},
	{"复印", "fu4 yin4", "phô-tô", "HSK4", "4 4"},
	{"复杂", "fu4 za2", "phức tạp", "HSK4", "4 2"},
	{"父亲", "fu4 qin1", "bố", "HSK4", "4 1"},
	{"改变", "gai3 bian4", "đổi/thay đổi", "HSK4", "3 4"},
	{"干杯", "gan1 bei1", "cạn ly", "HSK4", "1 1"},
	{"干燥", "gan1 zao4", "khô hanh", "HSK4", "1 4"},
	{"感动", "gan3 dong4", "cảm động", "HSK4", "3 4"},
	{"感觉", "gan3 jue2", "cảm giác", "HSK4", "3 2"},
	{"感情", "gan3 qing2", "tình cảm", "HSK4", "3 2"},
	{"感谢", "gan3 xie4", "cảm ơn", "HSK4", "3 4"},
	{"干", "gan4", "khô; làm", "HSK4", "4"},
	{"刚刚", "gang1 gang5", "vừa mới", "HSK4", "1 5"},
	{"高级", "gao1 ji2", "cao cấp", "HSK4", "1 2"},
	{"个子", "ge4 zi5", "chiều cao", "HSK4", "4 5"},
	{"各", "ge4", "mỗi", "HSK4", "4"},
	{"公里", "gong1 li3", "ki-lô-mét", "HSK4", "1 3"},
	{"工具", "gong1 ju4", "công cụ", "HSK4", "1 4"},
	{"工资", "gong1 zi1", "tiền lương", "HSK4", "1 1"},
	{"共同", "gong4 tong2", "chung", "HSK4", "4 2"},
	{"够", "gou4", "đủ", "HSK4", "4"},
	{"购物", "gou4 wu4", "mua sắm", "HSK4", "4 4"},
	{"孤单", "gu1 dan1", "cô đơn", "HSK4", "1 1"},
	{"估计", "gu1 ji4", "ước tính", "HSK4", "1 4"},
	{"鼓励", "gu3 li4", "động viên", "HSK4", "3 4"},
	{"鼓掌", "gu3 zhang3", "vỗ tay", "HSK4", "3 3"},
	{"顾客", "gu4 ke4", "khách hàng", "HSK4", "4 4"},
	{"故意", "gu4 yi4", "cố ý", "HSK4", "4 4"},
	{"挂", "gua4", "treo", "HSK4", "4"},
	{"关键", "guan1 jian4", "then chốt", "HSK4", "1 4"},
	{"观众", "guan1 zhong4", "khán giả", "HSK4", "1 4"},
	{"管理", "guan3 li3", "quản lý", "HSK4", "3 3"},
	{"光", "guang1", "ánh sáng", "HSK4", "1"},
	{"广播", "guang3 bo1", "phát thanh", "HSK4", "3 1"},
	{"广告", "guang3 gao4", "quảng cáo", "HSK4", "3 4"},
	{"逛", "guang4", "đi dạo", "HSK4", "4"},
	{"规定", "gui1 ding4", "quy định", "HSK4", "1 4"},
	{"国际", "guo2 ji4", "quốc tế", "HSK4", "2 4"},
	{"果然", "guo3 ran2", "quả nhiên", "HSK4", "3 2"},
	{"过", "guo4", "đã từng, qua", "HSK4", "4"},
	{"过程", "guo4 cheng2", "quá trình", "HSK4", "4 2"},
	{"海洋", "hai3 yang2", "đại dương", "HSK4", "3 2"},
	{"害羞", "hai4 xiu1", "ngượng ngùng", "HSK4", "4 1"},
	{"寒假", "han2 jia4", "nghỉ đông", "HSK4", "2 4"},
	{"汗", "han4", "mồ hôi", "HSK4", "4"},
	{"航班", "hang2 ban1", "chuyến bay", "HSK4", "2 1"},
	{"好处", "hao3 chu5", "lợi ích", "HSK4", "3 5"},
	{"好像", "hao3 xiang4", "hình như", "HSK4", "3 4"},
	{"号码", "hao4 ma3", "số", "HSK4", "4 3"},
	{"合格", "he2 ge2", "đạt chuẩn", "HSK4", "2 2"},
	{"合适", "he2 shi4", "phù hợp", "HSK4", "2 4"},
	{"盒子", "he2 zi5", "cái hộp", "HSK4", "2 5"},
	{"猴子", "hou2 zi5", "khỉ", "HSK4", "2 5"},
	{"厚", "hou4", "dày", "HSK4", "4"},
	{"后悔", "hou4 hui3", "hối hận", "HSK4", "4 3"},
	{"后来", "hou4 lai2", "sau này", "HSK4", "4 2"},
	{"忽然", "hu1 ran2", "bỗng nhiên", "HSK4", "1 2"},
	{"互相", "hu4 xiang1", "lẫn nhau", "HSK4", "4 1"},
	{"护士", "hu4 shi5", "y tá", "HSK4", "4 5"},
	{"怀疑", "huai2 yi2", "nghi ngờ", "HSK4", "2 2"},
	{"回忆", "hui2 yi4", "hồi tưởng", "HSK4", "2 4"},
	{"活动", "huo2 dong4", "hoạt động", "HSK4", "2 4"},
	{"活泼", "huo2 po5", "sôi nổi", "HSK4", "2 5"},
	{"火", "huo3", "lửa", "HSK4", "3"},
	{"获得", "huo4 de2", "giành được", "HSK4", "4 2"},
	{"基础", "ji1 chu3", "nền tảng", "HSK4", "1 3"},
	{"激动", "ji1 dong4", "xúc động", "HSK4", "1 4"},
	{"积极", "ji1 ji2", "tích cực", "HSK4", "1 2"},
	{"积累", "ji1 lei3", "tích lũy", "HSK4", "1 3"},
	{"极其", "ji2 qi2", "vô cùng, cực kỳ", "HSK4", "2 2"},
	{"即使", "ji2 shi3", "dù cho, cho dù", "HSK4", "2 3"},
	{"及时", "ji2 shi2", "kịp thời", "HSK4", "2 2"},
	{"集合", "ji2 he2", "tập hợp", "HSK4", "2 2"},
	{"寄", "ji4", "gửi", "HSK4", "4"},
	{"继续", "ji4 xu4", "tiếp tục", "HSK4", "4 4"},
	{"记者", "ji4 zhe3", "phóng viên", "HSK4", "4 3"},
	{"计划", "ji4 hua4", "lên kế hoạch", "HSK4", "4 4"},
	{"技术", "ji4 shu4", "kỹ thuật", "HSK4", "4 4"},
	{"既然", "ji4 ran2", "đã... thì", "HSK4", "4 2"},
	{"家具", "jia1 ju4", "đồ nội thất", "HSK4", "1 4"},
	{"加班", "jia1 ban1", "làm thêm giờ", "HSK4", "1 1"},
	{"加油站", "jia1 you2 zhan4", "trạm xăng", "HSK4", "1 2 4"},
	{"假", "jia3", "giả", "HSK4", "3"},
	{"价格", "jia4 ge2", "giá", "HSK4", "4 2"},
	{"坚持", "jian1 chi2", "kiên trì", "HSK4", "1 2"},
	{"减肥", "jian3 fei2", "giảm cân", "HSK4", "3 2"},
	{"减少", "jian3 shao3", "giảm bớt", "HSK4", "3 3"},
	{"将来", "jiang1 lai2", "trong tương lai", "HSK4", "1 2"},
	{"奖金", "jiang3 jin1", "tiền thưởng", "HSK4", "3 1"},
	{"降低", "jiang4 di1", "hạ xuống", "HSK4", "4 1"},
	{"交", "jiao1", "giao, nộp", "HSK4", "1"},
	{"交流", "jiao1 liu2", "giao lưu, trao đổi", "HSK4", "1 2"},
	{"交通", "jiao1 tong1", "giao thông", "HSK4", "1 1"},
	{"骄傲", "jiao1 ao4", "kiêu ngạo; tự hào", "HSK4", "1 4"},
	{"饺子", "jiao3 zi5", "bánh chẻo", "HSK4", "3 5"},
	{"教授", "jiao4 shou4", "giáo sư", "HSK4", "4 4"},
	{"教育", "jiao4 yu4", "giáo dục", "HSK4", "4 4"},
	{"接受", "jie1 shou4", "tiếp nhận", "HSK4", "1 4"},
	{"节约", "jie2 yue1", "tiết kiệm", "HSK4", "2 1"},
	{"结果", "jie2 guo3", "kết quả", "HSK4", "2 3"},
	{"解释", "jie3 shi4", "giải thích", "HSK4", "3 4"},
	{"紧张", "jin3 zhang1", "hồi hộp", "HSK4", "3 1"},
	{"尽管", "jin3 guan3", "mặc dù, cứ việc", "HSK4", "3 3"},
	{"进行", "jin4 xing2", "tiến hành", "HSK4", "4 2"},
	{"禁止", "jin4 zhi3", "cấm", "HSK4", "4 3"},
	{"精彩", "jing1 cai3", "xuất sắc, đặc sắc", "HSK4", "1 3"},
	{"精神", "jing1 shen2", "tinh thần", "HSK4", "1 2"},
	{"经济", "jing1 ji4", "kinh tế", "HSK4", "1 4"},
	{"经历", "jing1 li4", "trải qua", "HSK4", "1 4"},
	{"经验", "jing1 yan4", "kinh nghiệm", "HSK4", "1 4"},
	{"京剧", "jing1 ju4", "kinh kịch", "HSK4", "1 4"},
	{"警察", "jing3 cha2", "công an", "HSK4", "3 2"},
	{"竟然", "jing4 ran2", "không ngờ", "HSK4", "4 2"},
	{"竞争", "jing4 zheng1", "thi đấu", "HSK4", "4 1"},
	{"镜子", "jing4 zi5", "gương", "HSK4", "4 5"},
	{"究竟", "jiu1 jing4", "rốt cuộc", "HSK4", "1 4"},
	{"举办", "ju3 ban4", "tổ chức", "HSK4", "3 4"},
	{"拒绝", "ju4 jue2", "từ chối", "HSK4", "4 2"},
	{"距离", "ju4 li2", "khoảng cách", "HSK4", "4 2"},
	{"开玩笑", "kai1 wan2 xiao4", "nói đùa", "HSK4", "1 2 4"},
	{"看法", "kan4 fa3", "cách nhìn, quan điểm", "HSK4", "4 3"},
	{"考虑", "kao3 lü4", "cân nhắc", "HSK4", "3 4"},
	{"棵", "ke1", "cây (lượng từ cây cối)", "HSK4", "1"},
	{"科学", "ke1 xue2", "khoa học", "HSK4", "1 2"},
	{"咳嗽", "ke2 sou5", "ho", "HSK4", "2 5"},
	{"可怜", "ke3 lian2", "đáng thương", "HSK4", "3 2"},
	{"可是", "ke3 shi4", "nhưng mà", "HSK4", "3 4"},
	{"可惜", "ke3 xi1", "tiếc quá", "HSK4", "3 1"},
	{"肯定", "ken3 ding4", "chắc chắn", "HSK4", "3 4"},
	{"空气", "kong1 qi4", "không khí", "HSK4", "1 4"},
	{"恐怕", "kong3 pa4", "e rằng, sợ rằng", "HSK4", "3 4"},
	{"苦", "ku3", "đắng", "HSK4", "3"},
	{"宽", "kuan1", "rộng", "HSK4", "1"},
	{"困", "kun4", "buồn ngủ", "HSK4", "4"},
	{"困难", "kun4 nan5", "khó", "HSK4", "4 5"},
	{"扩大", "kuo4 da4", "mở rộng", "HSK4", "4 4"},
	{"拉", "la1", "kéo", "HSK4", "1"},
	{"垃圾桶", "la1 ji1 tong3", "thùng rác", "HSK4", "1 1 3"},
	{"辣", "la4", "cay", "HSK4", "4"},
	{"来不及", "lai2 bu5 ji2", "không kịp", "HSK4", "2 5 2"},
	{"来得及", "lai2 de5 ji2", "kịp, còn kịp", "HSK4", "2 5 2"},
	{"懒", "lan3", "lười", "HSK4", "3"},
	{"浪费", "lang4 fei4", "lãng phí", "HSK4", "4 4"},
	{"浪漫", "lang4 man4", "lãng mạn", "HSK4", "4 4"},
	{"老虎", "lao3 hu3", "hổ", "HSK4", "3 3"},
	{"冷静", "leng3 jing4", "bình tĩnh", "HSK4", "3 4"},
	{"礼貌", "li3 mao4", "lễ phép", "HSK4", "3 4"},
	{"理发", "li3 fa4", "cắt tóc", "HSK4", "3 4"},
	{"理解", "li3 jie3", "lĩnh hội", "HSK4", "3 3"},
	{"理想", "li3 xiang3", "lý tưởng", "HSK4", "3 3"},
	{"厉害", "li4 hai5", "giỏi; dữ dội, kinh khủng", "HSK4", "4 5"},
	{"力气", "li4 qi5", "sức lực", "HSK4", "4 5"},
	{"例如", "li4 ru2", "ví dụ như", "HSK4", "4 2"},
	{"俩", "lia3", "hai (khẩu ngữ)", "HSK4", "3"},
	{"连", "lian2", "nối, liền; cả... cũng...", "HSK4", "2"},
	{"联系", "lian2 xi4", "liên hệ", "HSK4", "2 4"},
	{"凉快", "liang2 kuai5", "mát mẻ", "HSK4", "2 5"},
	{"亮", "liang4", "sáng", "HSK4", "4"},
	{"聊天", "liao2 tian1", "tán gẫu", "HSK4", "2 1"},
	{"另外", "ling4 wai4", "ngoài ra, khác", "HSK4", "4 4"},
	{"留", "liu2", "ở lại, giữ lại", "HSK4", "2"},
	{"留学", "liu2 xue2", "du học", "HSK4", "2 2"},
	{"流泪", "liu2 lei4", "rơi lệ", "HSK4", "2 4"},
	{"流利", "liu2 li4", "lưu loát", "HSK4", "2 4"},
	{"流行", "liu2 xing2", "thịnh hành, lan rộng", "HSK4", "2 2"},
	{"乱", "luan4", "lộn xộn", "HSK4", "4"},
	{"律师", "lü4 shi1", "luật sư", "HSK4", "4 1"},
	{"麻烦", "ma2 fan5", "phiền phức", "HSK4", "2 5"},
	{"马虎", "ma3 hu5", "cẩu thả", "HSK4", "3 5"},
	{"满", "man3", "đầy", "HSK4", "3"},
	{"毛巾", "mao2 jin1", "khăn mặt", "HSK4", "2 1"},
	{"美丽", "mei3 li4", "đẹp", "HSK4", "3 4"},
	{"梦", "meng4", "giấc mơ", "HSK4", "4"},
	{"密码", "mi4 ma3", "mật mã", "HSK4", "4 3"},
	{"免费", "mian3 fei4", "miễn phí", "HSK4", "3 4"},
	{"民族", "min2 zu2", "dân tộc", "HSK4", "2 2"},
	{"母亲", "mu3 qin1", "mẹ", "HSK4", "3 1"},
	{"目的", "mu4 di4", "mục đích", "HSK4", "4 4"},
	{"耐心", "nai4 xin1", "kiên nhẫn", "HSK4", "4 1"},
	{"难道", "nan2 dao4", "lẽ nào... (hỏi tu từ)", "HSK4", "2 4"},
	{"难受", "nan2 shou4", "khó chịu", "HSK4", "2 4"},
	{"内", "nei4", "bên trong", "HSK4", "4"},
	{"内容", "nei4 rong2", "nội dung", "HSK4", "4 2"},
	{"能力", "neng2 li4", "năng lực", "HSK4", "2 4"},
	{"年龄", "nian2 ling2", "tuổi", "HSK4", "2 2"},
	{"农村", "nong2 cun1", "nông thôn", "HSK4", "2 1"},
	{"弄", "nong4", "làm", "HSK4", "4"},
	{"暖和", "nuan3 huo5", "ấm", "HSK4", "3 5"},
	{"偶尔", "ou3 er3", "thỉnh thoảng", "HSK4", "3 3"},
	{"排列", "pai2 lie4", "sắp xếp", "HSK4", "2 4"},
	{"判断", "pan4 duan4", "quyết định", "HSK4", "4 4"},
	{"陪", "pei2", "đi cùng", "HSK4", "2"},
	{"批评", "pi1 ping2", "phê bình", "HSK4", "1 2"},
	{"皮肤", "pi2 fu1", "da", "HSK4", "2 1"},
	{"脾气", "pi2 qi5", "tính khí", "HSK4", "2 5"},
	{"篇", "pian1", "bài, thiên (lượng từ bài văn)", "HSK4", "1"},
	{"骗", "pian4", "lừa gạt", "HSK4", "4"},
	{"乒乓球", "ping1 pang1 qiu2", "bóng bàn", "HSK4", "1 1 2"},
	{"平时", "ping2 shi2", "thông thường", "HSK4", "2 2"},
	{"瓶子", "ping2 zi5", "chai", "HSK4", "2 5"},
	{"破", "po4", "vỡ, rách", "HSK4", "4"},
	{"普遍", "pu3 bian4", "phổ biến", "HSK4", "3 4"},
	{"其次", "qi2 ci4", "tiếp theo", "HSK4", "2 4"},
	{"其中", "qi2 zhong1", "trong đó", "HSK4", "2 1"},
	{"起飞", "qi3 fei1", "cất cánh", "HSK4", "3 1"},
	{"起来", "qi5 lai5", "đứng dậy, lên (tiếp diễn)", "HSK4", "5 5"},
	{"气候", "qi4 hou4", "khí hậu", "HSK4", "4 4"},
	{"千万", "qian1 wan4", "mười triệu; nhất định phải", "HSK4", "1 4"},
	{"签证", "qian1 zheng4", "thị thực", "HSK4", "1 4"},
	{"墙", "qiang2", "tường", "HSK4", "2"},
	{"敲", "qiao1", "đánh", "HSK4", "1"},
	{"桥", "qiao2", "cầu", "HSK4", "2"},
	{"巧克力", "qiao3 ke4 li4", "sô-cô-la", "HSK4", "3 4 4"},
	{"亲戚", "qin1 qi5", "họ hàng", "HSK4", "1 5"},
	{"轻", "qing1", "nhẹ", "HSK4", "1"},
	{"轻松", "qing1 song1", "nhẹ nhõm", "HSK4", "1 1"},
	{"情况", "qing2 kuang4", "tình hình", "HSK4", "2 4"},
	{"请假", "qing3 jia4", "xin nghỉ phép", "HSK4", "3 4"},
	{"请客", "qing3 ke4", "mời (ăn uống)", "HSK4", "3 4"},
	{"穷", "qiong2", "nghèo; cùng cực", "HSK4", "2"},
	{"区别", "qu1 bie2", "phân biệt, khác biệt", "HSK4", "1 2"},
	{"取", "qu3", "lấy", "HSK4", "3"},
	{"全部", "quan2 bu4", "toàn bộ", "HSK4", "2 4"},
	{"缺点", "que1 dian3", "điểm yếu", "HSK4", "1 3"},
	{"缺少", "que1 shao3", "thiếu", "HSK4", "1 3"},
	{"却", "que4", "nhưng", "HSK4", "4"},
	{"确实", "que4 shi2", "quả thực", "HSK4", "4 2"},
	{"群", "qun2", "nhóm", "HSK4", "2"},
	{"然而", "ran2 er2", "tuy nhiên", "HSK4", "2 2"},
	{"热闹", "re4 nao5", "nhộn nhịp", "HSK4", "4 5"},
	{"人民币", "ren2 min2 bi4", "nhân dân tệ", "HSK4", "2 2 4"},
	{"任何", "ren4 he2", "bất kỳ", "HSK4", "4 2"},
	{"任务", "ren4 wu5", "nhiệm vụ", "HSK4", "4 5"},
	{"扔", "reng1", "ném", "HSK4", "1"},
	{"仍然", "reng2 ran2", "vẫn", "HSK4", "2 2"},
	{"日记", "ri4 ji4", "nhật ký", "HSK4", "4 4"},
	{"入口", "ru4 kou3", "lối vào", "HSK4", "4 3"},
	{"软", "ruan3", "mềm", "HSK4", "3"},
	{"散步", "san4 bu4", "đi dạo", "HSK4", "4 4"},
	{"森林", "sen1 lin2", "rừng", "HSK4", "1 2"},
	{"沙发", "sha1 fa1", "ghế sofa", "HSK4", "1 1"},
	{"商量", "shang1 liang5", "bàn bạc", "HSK4", "1 5"},
	{"伤心", "shang1 xin1", "đau buồn", "HSK4", "1 1"},
	{"稍微", "shao1 wei1", "một chút", "HSK4", "1 1"},
	{"社会", "she4 hui4", "xã hội", "HSK4", "4 4"},
	{"深", "shen1", "sâu", "HSK4", "1"},
	{"申请", "shen1 qing3", "nộp đơn xin", "HSK4", "1 3"},
	{"甚至", "shen4 zhi4", "thậm chí", "HSK4", "4 4"},
	{"生活", "sheng1 huo2", "cuộc sống", "HSK4", "1 2"},
	{"生命", "sheng1 ming4", "sinh mệnh, sự sống", "HSK4", "1 4"},
	{"省", "sheng3", "tỉnh; tiết kiệm", "HSK4", "3"},
	{"剩", "sheng4", "còn lại", "HSK4", "4"},
	{"失败", "shi1 bai4", "thất bại", "HSK4", "1 4"},
	{"失望", "shi1 wang4", "thất vọng", "HSK4", "1 4"},
	{"师傅", "shi1 fu5", "sư phụ, thợ cả", "HSK4", "1 5"},
	{"湿润", "shi1 run4", "ẩm ướt", "HSK4", "1 4"},
	{"狮子", "shi1 zi5", "sư tử", "HSK4", "1 5"},
	{"十分", "shi2 fen1", "rất, hết sức", "HSK4", "2 1"},
	{"实际", "shi2 ji4", "thực tế", "HSK4", "2 4"},
	{"实在", "shi2 zai4", "thật sự", "HSK4", "2 4"},
	{"食品", "shi2 pin3", "thực phẩm", "HSK4", "2 3"},
	{"使用", "shi3 yong4", "dùng", "HSK4", "3 4"},
	{"试", "shi4", "kiểm tra/thi", "HSK4", "4"},
	{"市场", "shi4 chang3", "chợ", "HSK4", "4 3"},
	{"世纪", "shi4 ji4", "thế kỷ", "HSK4", "4 4"},
	{"适合", "shi4 he2", "vừa vặn", "HSK4", "4 2"},
	{"适应", "shi4 ying4", "thích nghi", "HSK4", "4 4"},
	{"收", "shou1", "nhận", "HSK4", "1"},
	{"收入", "shou1 ru4", "thu nhập", "HSK4", "1 4"},
	{"收拾", "shou1 shi5", "dọn dẹp", "HSK4", "1 5"},
	{"首都", "shou3 du1", "thủ đô", "HSK4", "3 1"},
	{"首先", "shou3 xian1", "thứ nhất", "HSK4", "3 1"},
	{"受不了", "shou4 bu4 liao3", "không chịu nổi", "HSK4", "4 4 3"},
	{"受到", "shou4 dao4", "nhận được", "HSK4", "4 4"},
	{"售货员", "shou4 huo4 yuan2", "người bán hàng", "HSK4", "4 4 2"},
	{"输", "shu1", "mất", "HSK4", "1"},
	{"熟悉", "shu2 xi1", "quen thuộc", "HSK4", "2 1"},
	{"数量", "shu4 liang4", "số lượng", "HSK4", "4 4"},
	{"数字", "shu4 zi4", "số từ", "HSK4", "4 4"},
	{"帅", "shuai4", "đẹp trai", "HSK4", "4"},
	{"顺便", "shun4 bian4", "thuận tiện", "HSK4", "4 4"},
	{"顺利", "shun4 li4", "suôn sẻ", "HSK4", "4 4"},
	{"顺序", "shun4 xu4", "trình tự", "HSK4", "4 4"},
	{"说明", "shuo1 ming2", "giải thích", "HSK4", "1 2"},
	{"硕士", "shuo4 shi4", "thạc sĩ", "HSK4", "4 4"},
	{"死", "si3", "chết", "HSK4", "3"},
	{"速度", "su4 du4", "tốc độ", "HSK4", "4 4"},
	{"塑料袋", "su4 liao4 dai4", "túi ni-lông", "HSK4", "4 4 4"},
	{"酸", "suan1", "chua", "HSK4", "1"},
	{"算", "suan4", "tính, coi như", "HSK4", "4"},
	{"随便", "sui2 bian4", "tùy ý, tùy tiện", "HSK4", "2 4"},
	{"随着", "sui2 zhe5", "cùng với", "HSK4", "2 5"},
	{"孙子", "sun1 zi5", "cháu trai", "HSK4", "1 5"},
	{"所有", "suo3 you3", "tất cả", "HSK4", "3 3"},
	{"抬", "tai2", "nhấc lên", "HSK4", "2"},
	{"台", "tai2", "bão", "HSK4", "2"},
	{"态度", "tai4 du5", "thái độ", "HSK4", "4 5"},
	{"谈", "tan2", "nói", "HSK4", "2"},
	{"弹", "tan2", "gảy đàn", "HSK4", "2"},
	{"汤", "tang1", "canh", "HSK4", "1"},
	{"躺", "tang3", "nằm nghỉ", "HSK4", "3"},
	{"趟", "tang4", "lượng từ cho lần", "HSK4", "4"},
	{"讨论", "tao3 lun4", "thảo luận", "HSK4", "3 4"},
	{"讨厌", "tao3 yan4", "không thích", "HSK4", "3 4"},
	{"特点", "te4 dian3", "đặc điểm", "HSK4", "4 3"},
	{"提供", "ti2 gong1", "cung cấp", "HSK4", "2 1"},
	{"提前", "ti2 qian2", "sớm hơn, trước", "HSK4", "2 2"},
	{"提醒", "ti2 xing3", "nhắc nhở", "HSK4", "2 3"},
	{"填空", "tian2 kong4", "điền vào chỗ trống", "HSK4", "2 4"},
	{"条件", "tiao2 jian4", "điều kiện", "HSK4", "2 4"},
	{"停止", "ting2 zhi3", "dừng", "HSK4", "2 3"},
	{"挺", "ting3", "khá, rất; thẳng", "HSK4", "3"},
	{"通过", "tong1 guo4", "thông qua", "HSK4", "1 4"},
	{"通知", "tong1 zhi1", "thông báo", "HSK4", "1 1"},
	{"同情", "tong2 qing2", "thông cảm với", "HSK4", "2 2"},
	{"推", "tui1", "đẩy", "HSK4", "1"},
	{"推迟", "tui1 chi2", "hoãn lại", "HSK4", "1 2"},
	{"脱", "tuo1", "rụng/rơi", "HSK4", "1"},
	{"袜子", "wa4 zi5", "tất", "HSK4", "4 5"},
	{"完全", "wan2 quan2", "hoàn toàn", "HSK4", "2 2"},
	{"往", "wang3", "hướng về", "HSK4", "3"},
	{"往往", "wang3 wang3", "thường thường", "HSK4", "3 3"},
	{"网球", "wang3 qiu2", "quần vợt", "HSK4", "3 2"},
	{"网站", "wang3 zhan4", "trang web", "HSK4", "3 4"},
	{"危险", "wei1 xian3", "nguy hiểm", "HSK4", "1 3"},
	{"味道", "wei4 dao5", "hương vị", "HSK4", "4 5"},
	{"温度", "wen1 du4", "nhiệt độ", "HSK4", "1 4"},
	{"文章", "wen2 zhang1", "bài báo", "HSK4", "2 1"},
	{"握手", "wo4 shou3", "bắt tay", "HSK4", "4 3"},
	{"污染", "wu1 ran3", "ô nhiễm", "HSK4", "1 3"},
	{"无", "wu2", "không, vô", "HSK4", "2"},
	{"无聊", "wu2 liao2", "chán", "HSK4", "2 2"},
	{"无论", "wu2 lun4", "bất luận... gì", "HSK4", "2 4"},
	{"误会", "wu4 hui4", "hiểu lầm", "HSK4", "4 4"},
	{"西红柿", "xi1 hong2 shi4", "cà chua", "HSK4", "1 2 4"},
	{"吸引", "xi1 yin3", "thu hút", "HSK4", "1 3"},
	{"洗衣机", "xi3 yi1 ji1", "máy giặt", "HSK4", "3 1 1"},
	{"咸", "xian2", "mặn", "HSK4", "2"},
	{"现代", "xian4 dai4", "hiện đại", "HSK4", "4 4"},
	{"羡慕", "xian4 mu4", "ghen tị", "HSK4", "4 4"},
	{"限制", "xian4 zhi4", "hạn chế", "HSK4", "4 4"},
	{"香", "xiang1", "thơm", "HSK4", "1"},
	{"相反", "xiang1 fan3", "ngược lại", "HSK4", "1 3"},
	{"详细", "xiang2 xi4", "chi tiết", "HSK4", "2 4"},
	{"响", "xiang3", "tiếng vang", "HSK4", "3"},
	{"消息", "xiao1 xi5", "tin tức", "HSK4", "1 5"},
	{"小说", "xiao3 shuo1", "tiểu thuyết", "HSK4", "3 1"},
	{"笑话", "xiao4 hua5", "trò đùa", "HSK4", "4 5"},
	{"效果", "xiao4 guo3", "hiệu quả", "HSK4", "4 3"},
	{"心情", "xin1 qing2", "tâm trạng", "HSK4", "1 2"},
	{"辛苦", "xin1 ku3", "vất vả", "HSK4", "1 3"},
	{"信任", "xin4 ren4", "tin tưởng", "HSK4", "4 4"},
	{"信心", "xin4 xin1", "tự tin", "HSK4", "4 1"},
	{"信用卡", "xin4 yong4 ka3", "thẻ tín dụng", "HSK4", "4 4 3"},
	{"兴奋", "xing1 fen4", "hào hứng", "HSK4", "1 4"},
	{"行", "xing2", "hàng; nghề; được", "HSK4", "2"},
	{"醒", "xing3", "tỉnh dậy", "HSK4", "3"},
	{"性别", "xing4 bie2", "giới tính", "HSK4", "4 2"},
	{"性格", "xing4 ge2", "tính cách", "HSK4", "4 2"},
	{"幸福", "xing4 fu2", "hạnh phúc", "HSK4", "4 2"},
	{"修", "xiu1", "sửa chữa", "HSK4", "1"},
	{"许多", "xu3 duo1", "nhiều", "HSK4", "3 1"},
	{"血", "xue4", "máu", "HSK4", "4"},
	{"压力", "ya1 li4", "áp lực", "HSK4", "1 4"},
	{"牙膏", "ya2 gao1", "kem đánh răng", "HSK4", "2 1"},
	{"亚洲", "ya4 zhou1", "châu Á", "HSK4", "4 1"},
	{"呀", "ya5", "trợ từ cuối câu (nha, nhé)", "HSK4", "5"},
	{"盐", "yan2", "muối", "HSK4", "2"},
	{"严格", "yan2 ge2", "nghiêm khắc", "HSK4", "2 2"},
	{"严重", "yan2 zhong4", "nghiêm trọng", "HSK4", "2 4"},
	{"研究生", "yan2 jiu1 sheng1", "nghiên cứu sinh", "HSK4", "2 1 1"},
	{"演出", "yan3 chu1", "biểu diễn", "HSK4", "3 1"},
	{"演员", "yan3 yuan2", "diễn viên", "HSK4", "3 2"},
	{"阳光", "yang2 guang1", "ánh nắng", "HSK4", "2 1"},
	{"养成", "yang3 cheng2", "bồi dưỡng", "HSK4", "3 2"},
	{"样子", "yang4 zi5", "vẻ ngoài", "HSK4", "4 5"},
	{"邀请", "yao1 qing3", "mời", "HSK4", "1 3"},
	{"钥匙", "yao4 shi5", "chìa khóa", "HSK4", "4 5"},
	{"也许", "ye3 xu3", "có lẽ", "HSK4", "3 3"},
	{"页", "ye4", "trang", "HSK4", "4"},
	{"叶子", "ye4 zi5", "lá", "HSK4", "4 5"},
	{"一切", "yi1 qie4", "tất cả", "HSK4", "1 4"},
	{"以", "yi3", "bằng, lấy (dùng)", "HSK4", "3"},
	{"亿", "yi4", "trăm triệu", "HSK4", "4"},
	{"意见", "yi4 jian4", "ý kiến", "HSK4", "4 4"},
	{"艺术", "yi4 shu4", "nghệ thuật", "HSK4", "4 4"},
	{"因此", "yin1 ci3", "do đó, vì vậy", "HSK4", "1 3"},
	{"引起", "yin3 qi3", "gây ra", "HSK4", "3 3"},
	{"饮料", "yin3 liao4", "đồ uống", "HSK4", "3 4"},
	{"印象", "yin4 xiang4", "ấn tượng", "HSK4", "4 4"},
	{"赢", "ying2", "thắng", "HSK4", "2"},
	{"硬", "ying4", "cứng", "HSK4", "4"},
	{"勇敢", "yong3 gan3", "dũng cảm", "HSK4", "3 3"},
	{"永远", "yong3 yuan3", "mãi mãi", "HSK4", "3 3"},
	{"优点", "you1 dian3", "ưu điểm", "HSK4", "1 3"},
	{"优秀", "you1 xiu4", "xuất sắc", "HSK4", "1 4"},
	{"幽默", "you1 mo4", "hài hước", "HSK4", "1 4"},
	{"由", "you2", "do, bởi", "HSK4", "2"},
	{"由于", "you2 yu2", "do, bởi", "HSK4", "2 2"},
	{"尤其", "you2 qi2", "nhất là", "HSK4", "2 2"},
	{"有趣", "you3 qu4", "thú vị", "HSK4", "3 4"},
	{"友好", "you3 hao3", "thân thiện", "HSK4", "3 3"},
	{"友谊", "you3 yi4", "tình bạn", "HSK4", "3 4"},
	{"愉快", "yu2 kuai4", "vui tươi", "HSK4", "2 4"},
	{"于是", "yu2 shi4", "thế là, bèn", "HSK4", "2 4"},
	{"与", "yu3", "và, với (trang trọng)", "HSK4", "3"},
	{"语法", "yu3 fa3", "ngữ pháp", "HSK4", "3 3"},
	{"语言", "yu3 yan2", "ngôn ngữ", "HSK4", "3 2"},
	{"羽毛球", "yu3 mao2 qiu2", "cầu lông", "HSK4", "3 2 2"},
	{"预习", "yu4 xi2", "chuẩn bị bài học", "HSK4", "4 2"},
	{"圆", "yuan2", "hình tròn", "HSK4", "2"},
	{"原来", "yuan2 lai2", "thì ra, vốn dĩ", "HSK4", "2 2"},
	{"原谅", "yuan2 liang4", "tha thứ", "HSK4", "2 4"},
	{"原因", "yuan2 yin1", "nguyên nhân", "HSK4", "2 1"},
	{"约会", "yue1 hui4", "cuộc hẹn", "HSK4", "1 4"},
	{"阅读", "yue4 du2", "đọc", "HSK4", "4 2"},
	{"允许", "yun3 xu3", "cho phép", "HSK4", "3 3"},
	{"杂志", "za2 zhi4", "tạp chí", "HSK4", "2 4"},
	{"咱们", "zan2 men5", "chúng ta (gồm cả người nghe)", "HSK4", "2 5"},
	{"暂时", "zan4 shi2", "tạm thời", "HSK4", "4 2"},
	{"脏", "zang1", "bẩn", "HSK4", "1"},
	{"责任", "ze2 ren4", "trách nhiệm", "HSK4", "2 4"},
	{"增加", "zeng1 jia1", "tăng thêm", "HSK4", "1 1"},
	{"增长", "zeng1 zhang3", "tăng trưởng", "HSK4", "1 3"},
	{"窄", "zhai3", "hẹp", "HSK4", "3"},
	{"招聘", "zhao1 pin4", "tuyển dụng", "HSK4", "1 4"},
	{"真正", "zhen1 zheng4", "thật sự", "HSK4", "1 4"},
	{"整理", "zheng3 li3", "sắp xếp", "HSK4", "3 3"},
	{"整齐", "zheng3 qi2", "ngăn nắp", "HSK4", "3 2"},
	{"正常", "zheng4 chang2", "bình thường", "HSK4", "4 2"},
	{"正好", "zheng4 hao3", "vừa khéo", "HSK4", "4 3"},
	{"正确", "zheng4 que4", "đúng", "HSK4", "4 4"},
	{"正式", "zheng4 shi4", "chính thức", "HSK4", "4 4"},
	{"证明", "zheng4 ming2", "bằng chứng", "HSK4", "4 2"},
	{"之", "zhi1", "của (văn ngôn)", "HSK4", "1"},
	{"支持", "zhi1 chi2", "ủng hộ", "HSK4", "1 2"},
	{"知识", "zhi1 shi5", "tri thức", "HSK4", "1 5"},
	{"直接", "zhi2 jie1", "trực tiếp", "HSK4", "2 1"},
	{"值得", "zhi2 de5", "đáng", "HSK4", "2 5"},
	{"职业", "zhi2 ye4", "nghề nghiệp", "HSK4", "2 4"},
	{"植物", "zhi2 wu4", "thực vật", "HSK4", "2 4"},
	{"指", "zhi3", "ngón tay", "HSK4", "3"},
	{"只好", "zhi3 hao3", "đành phải", "HSK4", "3 3"},
	{"只要", "zhi3 yao4", "chỉ cần", "HSK4", "3 4"},
	{"制造", "zhi4 zao4", "sản xuất", "HSK4", "4 4"},
	{"至少", "zhi4 shao3", "ít nhất", "HSK4", "4 3"},
	{"质量", "zhi4 liang4", "chất lượng", "HSK4", "4 4"},
	{"中文", "zhong1 wen2", "tiếng Trung", "HSK4", "1 2"},
	{"重点", "zhong4 dian3", "trọng điểm", "HSK4", "4 3"},
	{"重视", "zhong4 shi4", "coi trọng", "HSK4", "4 4"},
	{"周围", "zhou1 wei2", "vùng xung quanh", "HSK4", "1 2"},
	{"猪", "zhu1", "lợn", "HSK4", "1"},
	{"逐渐", "zhu2 jian4", "dần dần", "HSK4", "2 4"},
	{"主动", "zhu3 dong4", "chủ động", "HSK4", "3 4"},
	{"主意", "zhu3 yi5", "chủ ý, ý kiến", "HSK4", "3 5"},
	{"祝贺", "zhu4 he4", "chúc mừng", "HSK4", "4 4"},
	{"著名", "zhu4 ming2", "nổi tiếng", "HSK4", "4 2"},
	{"专门", "zhuan1 men2", "chuyên (môn)", "HSK4", "1 2"},
	{"专业", "zhuan1 ye4", "chuyên ngành", "HSK4", "1 4"},
	{"赚", "zhuan4", "kiếm (tiền)", "HSK4", "4"},
	{"撞", "zhuang4", "đâm, va", "HSK4", "4"},
	{"准确", "zhun3 que4", "chính xác", "HSK4", "3 4"},
	{"准时", "zhun3 shi2", "đúng giờ", "HSK4", "3 2"},
	{"仔细", "zi3 xi4", "cẩn thận", "HSK4", "3 4"},
	{"自然", "zi4 ran2", "tự nhiên", "HSK4", "4 2"},
	{"总结", "zong3 jie2", "tổng kết", "HSK4", "3 2"},
	{"租", "zu1", "thuê", "HSK4", "1"},
	{"组成", "zu3 cheng2", "tạo thành", "HSK4", "3 2"},
	{"组织", "zu3 zhi1", "tổ chức", "HSK4", "3 1"},
	{"嘴", "zui3", "miệng", "HSK4", "3"},
	{"最好", "zui4 hao3", "tốt nhất", "HSK4", "4 3"},
	{"最后", "zui4 hou4", "cuối cùng", "HSK4", "4 4"},
	{"尊重", "zun1 zhong4", "kính trọng", "HSK4", "1 4"},
	{"做生意", "zuo4 sheng1 yi4", "buôn bán", "HSK4", "4 1 4"},
	{"座", "zuo4", "ngọn, tòa (lượng từ)", "HSK4", "4"},
	{"座位", "zuo4 wei4", "chỗ ngồi", "HSK4", "4 4"},
	{"作者", "zuo4 zhe3", "tác giả", "HSK4", "4 3"},
}

// HskSeedByLevel trả seed của 1 level HSK. Level lạ trả nil — caller báo 400
// "chưa có seed cho level …" thay vì tự dựng bảng rỗng.
func HskSeedByLevel(level string) []HskEntry {
	switch level {
	case "HSK1":
		return hsk1Seed
	case "HSK2":
		return hsk2Seed
	case "HSK3":
		return hsk3Seed
	case "HSK4":
		return hsk4Seed
	default:
		return nil
	}
}

// HskLevels là tập level có seed, theo thứ tự tăng dần.
var HskLevels = []string{"HSK1", "HSK2", "HSK3", "HSK4"}
