#!/usr/bin/env python3
"""T8.1 step 2 — SeedHSK: enrich nghia Viet + doi chieu pinyin roi sinh
api/hsk_seed_l234.go (HSK 2.0 L2-L4: 147+298+598 = 1043 tu unique).

Doc: scripts/hsk_raw/ (fetch_hsk.py tai truoc) -> stdout bao cao + ghi file Go.
Pinyin: drkameleon numeric, doi chieu clem109 (55 tu lay dang doc khac khop,
5 tu tay quyet + 4 tu da am, xem PINYIN_FIX/POLY).
Nghia Viet: nhom tu soan (OVERRIDES + bang VI), goc Anh HSK tu clem109;
KHONG copy dinh nghia CC-CEDICT/MDBG.
"""
import collections
import io
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RAW = HERE / "hsk_raw"
REPO = HERE.parent

# ---- pinyin utils (doi chieu CC-CEDICT) ----
#!/usr/bin/env python3
"""gen.py — phat trien gloss Viet + pinyin cho HSK2/3/4 (thu nghiem trong /tmp)."""
import json, io, re, collections

MARKS={'ā':('a',1),'á':('a',2),'ǎ':('a',3),'à':('a',4),'ē':('e',1),'é':('e',2),'ě':('e',3),'è':('e',4),'ī':('i',1),'í':('i',2),'ǐ':('i',3),'ì':('i',4),'ō':('o',1),'ó':('o',2),'ǒ':('o',3),'ò':('o',4),'ū':('u',1),'ú':('u',2),'ǔ':('u',3),'ù':('u',4),'ǖ':('ü',1),'ǘ':('ü',2),'ǚ':('ü',3),'ǜ':('ü',4),'ü':('ü',5),'ê':('e',5)}
def to_num(s):
    out=[]
    for syl in s.split():
        tone=5; base=''
        for ch in syl:
            if ch in MARKS:
                b,t=MARKS[ch]; base+=b
                if t!=5: tone=t
            else: base+=ch
        out.append(base.lower()+str(tone))
    return ' '.join(out)

def sense(e):
    tr = [t for t in e['translations'] if not t.startswith('CL:')]
    if not tr:
        tr = list(e['translations'])
    s = tr[0]
    # clem109 cat nghia tai ';' lam vo ngoac: noi lai manh tiep theo.
    if s.count('(') != s.count(')') and len(tr) > 1:
        s = s + ', ' + tr[1]
    return s

# ---- pinyin resolution ----
PINYIN_FIX = {'太阳': 'tai4 yang2'}
POLY = {'长': 'chang2', '得': 'de5', '还': 'hai2', '只': 'zhi3'}
def pick_pinyin(hz, level, dr_entry, clem_nums):
    if hz in PINYIN_FIX: return PINYIN_FIX[hz]
    if hz in POLY: return POLY[hz]
    dforms=[' '.join(f['transcriptions']['numeric'].lower().split()) for f in dr_entry['forms']]
    if dforms[0] in clem_nums: return dforms[0]
    for d in dforms[1:]:
        if d in clem_nums: return d
    return dforms[0]

# ---- bang dich EN->VI tu soan (chi tu vung don) ----
# Bang dich EN->VI tu soan cho gloss HSK (T8.1). Chi tu vung don, khong copy dinh nghia.

VI = {
# --- tro tu / lien tu / pho tu (rat it dung map, chu yeu OVERRIDES) ---
'and':'và','or':'hoặc','but':'nhưng','however':'tuy nhiên','although':'mặc dù','though':'mặc dù',
'if':'nếu','because':'vì','therefore':'vì vậy','thus':'do đó','consequently':'do đó','hence':'do đó',
'as':'như','than':'hơn','both':'cả hai','each':'mỗi','every':'mỗi','all':'tất cả','whole':'toàn bộ',
'other':'khác','another':'khác','same':'giống nhau','different':'khác nhau','such':'như vậy',
'very':'rất','really':'thật sự','quite':'khá','almost':'gần như','nearly':'gần như','practically':'gần như',
'just':'vừa','only':'chỉ','also':'cũng','too':'quá','enough':'đủ','already':'đã','still':'vẫn',
'again':'lại','once':'một lần','always':'luôn luôn','often':'thường','sometimes':'thỉnh thoảng',
'occasionally':'thỉnh thoảng','usually':'thường thường','ordinarily':'thông thường','never':'không bao giờ',
'not':'không','no':'không','again ':'lại','more':'hơn','most':'nhất','less':'ít hơn',
'how':'thế nào','what':'gì','why':'tại sao','when':'khi nào','where':'ở đâu','which':'nào',
'very much':'rất nhiều','at once':'ngay lập tức','at last':'cuối cùng',
# --- dai tu ---
'i':'tôi','you':'bạn','he':'anh ấy','she':'cô ấy','it':'nó','we':'chúng tôi','us':'chúng tôi',
'they':'họ','them':'họ','him':'anh ấy','her':'cô ấy','me':'tôi','my':'của tôi','your':'của bạn',
'his':'của anh ấy','our':'của chúng tôi','their':'của họ','oneself':'bản thân','itself':'bản thân nó',
'somebody':'ai đó','someone':'ai đó','something':'điều gì đó','nothing':'không có gì',
'everything':'mọi thứ','anything':'bất cứ điều gì','sb':'ai đó','sth':'điều gì',
# --- dong tu pho bien ---
'be':'là','is':'là','are':'là','was':'đã là','have':'có','has':'có','do':'làm','does':'làm',
'go':'đi','come':'đến','take':'lấy','get':'lấy/nhận','give':'cho','receive':'nhận','send':'gửi',
'make':'làm','do':'làm','use':'dùng','eat':'ăn','drink':'uống','live':'sống','work':'làm việc',
'study':'học','learn':'học','teach':'dạy','read':'đọc','write':'viết','speak':'nói','talk':'nói chuyện',
'tell':'kể/bảo','ask':'hỏi','answer':'trả lời','reply':'trả lời','think':'nghĩ','believe':'tin',
'know':'biết','understand':'hiểu','comprehend':'lĩnh hội','remember':'nhớ','forget':'quên',
'like':'thích','love':'yêu','hate':'ghét','dislike':'không thích','want':'muốn','wish':'chúc/muốn',
'hope':'hy vọng','need':'cần','help':'giúp','try':'thử/cố','begin':'bắt đầu','start':'bắt đầu',
'finish':'xong','complete':'hoàn thành','accomplish':'hoàn thành','stop':'dừng','continue':'tiếp tục',
'change':'đổi/thay đổi','become':'trở thành','turn':'trở thành','grow':'lớn lên','arrive':'đến',
'reach':'đạt tới','leave':'rời khỏi','return':'trở về','come back':'trở về','enter':'vào','exit':'ra',
'open':'mở','close':'đóng','buy':'mua','sell':'bán','pay':'trả tiền','spend':'tiêu','cost':'tốn',
'win':'thắng','lose':'thua/mất','beat':'đánh bại','fight':'đánh nhau','quarrel':'cãi nhau',
'play':'chơi','run':'chạy','walk':'đi bộ','move':'di chuyển','climb':'leo','swim':'bơi','dance':'nhảy múa',
'sing':'hát','draw':'vẽ','paint':'vẽ','write down':'ghi lại','cook':'nấu ăn','wash':'rửa/giặt',
'clean':'dọn sạch','sweep':'quét','brush':'chải/đánh','wear':'mặc','put on':'mặc vào','take off':'cởi ra',
'sit':'ngồi','stand':'đứng','lie':'nằm','sleep':'ngủ','wake':'thức dậy','rest':'nghỉ ngơi',
'laugh':'cười','cry':'khóc','smile':'mỉm cười','shout':'hét','call':'gọi','visit':'thăm',
'meet':'gặp','welcome':'đón chào','invite':'mời','accompany':'đi cùng','follow':'đi theo',
'wait':'đợi','expect':'mong đợi','choose':'chọn','select':'chọn','decide':'quyết định',
'agree':'đồng ý','refuse':'từ chối','oppose':'phản đối','allow':'cho phép','permit':'cho phép',
'forbid':'cấm','prohibit':'cấm','borrow':'mượn','lend':'cho mượn','rent':'thuê','hire':'thuê',
'return sth':'trả lại','keep':'giữ','hold':'cầm/nắm','carry':'mang/vác','bring':'mang đến',
'pick':'hái/nhặt','throw':'ném','push':'đẩy','pull':'kéo','lift':'nhấc lên','hang':'treo',
'fall':'ngã/rơi','drop':'rơi','break':'vỡ/gãy','cut':'cắt','kill':'giết','die':'chết',
'cook rice':'nấu cơm','boil':'đun sôi','burn':'đốt/cháy','rain':'mưa','snow':'tuyết',
'shine':'chiếu sáng','blow':'thổi','flow':'chảy','fly':'bay','drive':'lái xe','ride':'cưỡi/đi xe',
'travel':'đi du lịch','trip':'chuyến đi','guide':'hướng dẫn','miss':'nhớ/lỡ','lose way':'lạc đường',
'find':'tìm thấy','look for':'tìm kiếm','search':'tìm kiếm','lose':'mất','win prize':'trúng thưởng',
'save':'tiết kiệm/cứu','waste':'lãng phí','spend money':'tiêu tiền','earn':'kiếm (tiền)',
'discuss':'thảo luận','explain':'giải thích','introduce':'giới thiệu','describe':'miêu tả',
'express':'bày tỏ','praise':'khen ngợi','criticize':'phê bình','congratulate':'chúc mừng',
'apologize':'xin lỗi','thank':'cảm ơn','complain':'phàn nàn','promise':'hứa','advise':'khuyên',
'suggest':'gợi ý','remind':'nhắc nhở','warn':'cảnh báo','encourage':'động viên','comfort':'an ủi',
'trust':'tin tưởng','doubt':'nghi ngờ','suspect':'nghi ngờ','guess':'đoán','check':'kiểm tra',
'inspect':'kiểm tra','test':'kiểm tra/thi','exam':'kỳ thi','try on':'mặc thử','taste':'nếm thử',
'repair':'sửa chữa','build':'xây dựng','make up':'trang điểm','decorate':'trang trí',
'organize':'tổ chức','arrange':'sắp xếp','prepare':'chuẩn bị','plan':'lên kế hoạch','cancel':'hủy bỏ',
'postpone':'hoãn lại','delay':'trì hoãn','hurry':'vội vàng','waste time':'mất thời gian',
'succeed':'thành công','fail':'thất bại','pass exam':'thi đỗ','graduate':'tốt nghiệp',
'enter school':'nhập học','leave school':'ra trường','work overtime':'làm thêm giờ',
'go to work':'đi làm','get off work':'tan làm','have meeting':'họp','rest day':'ngày nghỉ',
'take photo':'chụp ảnh','watch film':'xem phim','listen':'nghe','watch':'xem','look':'nhìn',
'see':'nhìn thấy','gaze':'ngắm nhìn','smile at':'mỉm cười với','wave':'vẫy tay',
'knock':'gõ cửa','ring':'reo chuông','cough':'ho','sneeze':'hắt hơi','yawn':'ngáp',
'breathe':'thở','smell':'ngửi','taste sweet':'ngọt','feel':'cảm thấy','touch':'sờ/chạm',
'hurt':'đau','ache':'đau nhức','itch':'ngứa','tire':'mệt','rest tired':'nghỉ cho đỡ mệt',
'exercise':'tập thể dục','warm up':'khởi động','compete':'thi đấu','race':'đua',
'swim race':'bơi thi','climb mountain':'leo núi','go hiking':'đi dã ngoại','camp':'cắm trại',
'fish':'câu cá','hunt':'săn bắn','plant':'trồng cây','water':'tưới nước','dig':'đào',
'harvest':'thu hoạch','feed':'cho ăn','raise':'nuôi','grow vegetables':'trồng rau',
# --- tinh tu ---
'good':'tốt','bad':'xấu','big':'to','small':'nhỏ','large':'rộng','long':'dài','short':'ngắn',
'high':'cao','low':'thấp','tall':'cao','far':'xa','near':'gần','new':'mới','old':'cũ/già',
'young':'trẻ','happy':'vui vẻ','sad':'buồn','angry':'tức giận','glad':'vui mừng','sorry':'tiếc/xin lỗi',
'beautiful':'đẹp','pretty':'xinh','handsome':'đẹp trai','ugly':'xấu xí','clean':'sạch',
'dirty':'bẩn','easy':'dễ','difficult':'khó','hard':'cứng/khó','soft':'mềm','hot':'nóng',
'cold':'lạnh','warm':'ấm','cool':'mát','sweet':'ngọt','sour':'chua','bitter':'đắng',
'salty':'mặn','spicy':'cay','delicious':'ngon','tasty':'ngon','hungry':'đói','thirsty':'khát',
'full':'no','tired':'mệt','sleepy':'buồn ngủ','sick':'ốm','ill':'ốm','healthy':'khỏe mạnh',
'strong':'khỏe','weak':'yếu','fat':'béo','thin':'gầy','tall building':'tòa nhà cao',
'fast':'nhanh','slow':'chậm','quick':'nhanh','early':'sớm','late':'muộn','busy':'bận',
'free':'rảnh/miễn phí','idle':'nhàn rỗi','nervous':'hồi hộp','worried':'lo lắng','afraid':'sợ',
'shy':'ngùng','proud':'tự hào','modest':'khiêm tốn','polite':'lịch sự','rude':'thô lỗ',
'honest':'thật thà','kind':'tốt bụng','friendly':'thân thiện','strict':'nghiêm khắc',
'careful':'cẩn thận','careless':'cẩu thả','patient':'kiên nhẫn','impatient':'nóng vội',
'quiet':'yên tĩnh','noisy':'ồn ào','lively':'sôi nổi','lonely':'cô đơn','famous':'nổi tiếng',
'important':'quan trọng','necessary':'cần thiết','possible':'có thể','impossible':'không thể',
'true':'đúng sự thật','false':'sai','right':'đúng','wrong':'sai','correct':'đúng',
'clear':'rõ ràng','vague':'mơ hồ','simple':'đơn giản','complex':'phức tạp','common':'thông thường',
'special':'đặc biệt','ordinary':'bình thường','strange':'lạ','familiar':'quen thuộc',
'convenient':'tiện lợi','inconvenient':'bất tiện','comfortable':'thoải mái','uncomfortable':'khó chịu',
'cheap':'rẻ','expensive':'đắt','rich':'giàu','poor':'nghèo','lucky':'may mắn','unlucky':'không may',
'safe':'an toàn','dangerous':'nguy hiểm','smooth':'thuận lợi','rough':'gồ ghề',
'bright':'sáng','dark':'tối','heavy':'nặng','light':'nhẹ','thick':'dày','thin paper':'mỏng',
'wide':'rộng','narrow':'hẹp','deep':'sâu','shallow':'nông','straight':'thẳng','curved':'cong',
'wet':'ướt','dry':'khô','fresh':'tươi','rotten':'thối','ripe':'chín','raw':'sống',
'red':'đỏ','yellow':'vàng','blue':'xanh da trời','green':'xanh lá','white':'trắng','black':'đen',
'gray':'xám','brown':'nâu','pink':'hồng','orange':'cam','purple':'tím','golden':'vàng óng',
'sunny':'nắng','cloudy':'nhiều mây','windy':'có gió','rainy':'mưa nhiều','snowy':'tuyết nhiều',
'foggy':'sương mù','humid':'ẩm','cold weather':'trời lạnh','hot weather':'trời nóng',
# --- danh tu: nguoi / gia dinh ---
'person':'người','people':'mọi người','man':'đàn ông','woman':'phụ nữ','child':'trẻ em',
'children':'trẻ em','boy':'con trai','girl':'con gái','baby':'em bé','kid':'đứa trẻ',
'father':'bố','mother':'mẹ','parent':'cha mẹ','son':'con trai','daughter':'con gái',
'brother':'anh/chị em trai','sister':'anh/chị em gái','older brother':'anh trai',
'younger brother':'em trai','older sister':'chị gái','younger sister':'em gái',
'husband':'chồng','wife':'vợ','grandfather':'ông','grandmother':'bà','grandma':'bà',
'grandpa':'ông','uncle':'chú/bác','aunt':'cô/dì','cousin':'anh chị em họ',
'nephew':'cháu trai','niece':'cháu gái','family':'gia đình','relative':'họ hàng',
'neighbor':'hàng xóm','friend':'bạn','classmate':'bạn cùng lớp','colleague':'đồng nghiệp',
'teacher':'giáo viên','student':'học sinh','pupil':'học trò','professor':'giáo sư',
'doctor':'bác sĩ','nurse':'y tá','driver':'tài xế','worker':'công nhân','farmer':'nông dân',
'soldier':'bộ đội','police':'công an','reporter':'phóng viên','actor':'diễn viên',
'actress':'diễn viên nữ','singer':'ca sĩ','artist':'họa sĩ/nghệ sĩ','writer':'nhà văn',
'author':'tác giả','cook':'đầu bếp','waiter':'người phục vụ','guide tour':'hướng dẫn viên',
'customer':'khách hàng','guest':'khách','visitor':'khách thăm','passenger':'hành khách',
'boss':'sếp','manager':'quản lý','secretary':'thư ký','employee':'nhân viên',
'athlete':'vận động viên','champion':'nhà vô địch','coach':'huấn luyện viên',
'baby sitter':'người trông trẻ','servant':'người giúp việc','thief':'kẻ trộm',
'stranger':'người lạ','crowd':'đám đông','couple':'cặp đôi','group':'nhóm',
'team':'đội','class':'lớp học','school':'trường học','company':'công ty',
# --- danh tu: co the / suc khoe ---
'body':'cơ thể','head':'đầu','hair':'tóc','face':'mặt','eye':'mắt','ear':'tai',
'nose':'mũi','mouth':'miệng','tooth':'răng','teeth':'răng','tongue':'lưỡi',
'neck':'cổ','shoulder':'vai','arm':'cánh tay','hand':'tay','finger':'ngón tay',
'leg':'chân','foot':'bàn chân','knee':'đầu gối','back':'lưng','belly':'bụng',
'stomach':'dạ dày','heart':'tim','blood':'máu','bone':'xương','skin':'da',
'health':'sức khỏe','illness':'bệnh','disease':'bệnh tật','cold ill':'cảm lạnh',
'fever':'sốt','cough ill':'ho','headache':'đau đầu','toothache':'đau răng',
'medicine':'thuốc','pill':'viên thuốc','doctor visit':'khám bệnh','hospital':'bệnh viện',
'injection':'tiêm thuốc','sweat':'mồ hôi','tear':'nước mắt','sneeze ill':'hắt hơi',
# --- danh tu: an uong ---
'food':'món ăn','meal':'bữa ăn','breakfast':'bữa sáng','lunch':'bữa trưa','dinner':'bữa tối',
'rice':'cơm/gạo','noodle':'mì','bread':'bánh mì','cake':'bánh ngọt','dumpling':'bánh chẻo',
'bun':'bánh bao','porridge':'cháo','soup':'canh','dish':'món ăn','meat':'thịt',
'pork':'thịt lợn','beef':'thịt bò','chicken':'thịt gà','fish food':'cá (món ăn)',
'egg':'trứng','vegetable':'rau','fruit':'hoa quả','apple':'táo','banana':'chuối',
'orange fruit':'cam','watermelon':'dưa hấu','grape':'nho','pear':'lê','peach':'đào',
'strawberry':'dâu tây','vegetables':'rau củ','bean':'đậu','tofu':'đậu phụ',
'milk':'sữa','water':'nước','tea':'trà','coffee':'cà phê','juice':'nước ép',
'beer':'bia','wine':'rượu','sugar':'đường','salt':'muối','oil':'dầu ăn',
'salt and pepper':'muối tiêu','chopsticks':'đũa','bowl':'bát','plate':'đĩa',
'cup':'cốc','bottle':'chai','restaurant':'nhà hàng','menu':'thực đơn',
# --- danh tu: thoi gian ---
'time':'thời gian','year':'năm','month':'tháng','week':'tuần','day':'ngày',
'hour':'giờ','minute':'phút','second':'giây','morning':'buổi sáng','noon':'buổi trưa',
'afternoon':'buổi chiều','evening':'buổi tối','night':'ban đêm','midnight':'nửa đêm',
'today':'hôm nay','tomorrow':'ngày mai','yesterday':'hôm qua','now':'bây giờ',
'later':'sau này','before':'trước đây','after':'sau đó','past':'quá khứ','future':'tương lai',
'spring':'mùa xuân','summer':'mùa hè','autumn':'mùa thu','winter':'mùa đông',
'season':'mùa','holiday':'kỳ nghỉ','vacation':'kỳ nghỉ','weekend':'cuối tuần',
'birthday':'sinh nhật','date':'ngày tháng','calendar':'lịch','clock':'đồng hồ',
'moment':'lúc','while':'trong khi','deadline':'hạn chót','schedule':'lịch trình',
'childhood':'tuổi thơ','youth':'tuổi trẻ','old age':'tuổi già','generation':'thế hệ',
# --- danh tu: noi chon ---
'place':'nơi','home':'nhà','house':'ngôi nhà','room':'phòng','kitchen':'nhà bếp',
'bedroom':'phòng ngủ','bathroom':'nhà tắm','toilet':'nhà vệ sinh','living room':'phòng khách',
'office':'văn phòng','school place':'trường','classroom':'lớp học','library':'thư viện',
'shop':'cửa hàng','market':'chợ','supermarket':'siêu thị','mall':'trung tâm thương mại',
'bank':'ngân hàng','post office':'bưu điện','hospital place':'bệnh viện','pharmacy':'hiệu thuốc',
'hotel':'khách sạn','restaurant place':'quán ăn','cinema':'rạp chiếu phim','theater':'nhà hát',
'museum':'bảo tàng','park':'công viên','zoo':'vườn thú','garden':'vườn','farm':'nông trại',
'station':'nhà ga','airport':'sân bay','bus stop':'bến xe buýt','subway':'tàu điện ngầm',
'street':'phố','road':'đường','bridge':'cầu','square':'quảng trường','city':'thành phố',
'town':'thị trấn','village':'làng','country':'đất nước','nation':'quốc gia','capital':'thủ đô',
'province':'tỉnh','district':'quận/huyện','factory':'nhà máy','gym':'phòng tập',
'pool':'bể bơi','playground':'sân chơi','church':'nhà thờ','temple':'chùa',
'mountain':'núi','river':'sông','lake':'hồ','sea':'biển','ocean':'đại dương','beach':'bãi biển',
'island':'đảo','forest':'rừng','desert':'sa mạc','field':'cánh đồng','sky':'bầu trời',
'sun':'mặt trời','moon':'mặt trăng','star':'ngôi sao','cloud':'mây','rain weather':'mưa',
'snow weather':'tuyết','wind':'gió','fog':'sương mù','earth':'trái đất','world':'thế giới',
'north':'phía bắc','south':'phía nam','east':'phía đông','west':'phía tây',
# --- danh tu: do vat ---
'thing':'đồ vật','book':'sách','newspaper':'báo','magazine':'tạp chí','dictionary':'từ điển',
'notebook':'vở','pen':'bút','pencil':'bút chì','bag':'cặp/túi','box':'hộp','bottle thing':'chai lọ',
'key':'chìa khóa','door':'cửa','window':'cửa sổ','wall':'tường','floor':'sàn nhà',
'table':'bàn','chair':'ghế','sofa':'ghế sofa','bed':'giường','lamp':'đèn','mirror':'gương',
'phone':'điện thoại','computer':'máy tính','tv':'ti-vi','radio':'đài','camera':'máy ảnh',
'photo':'ảnh','picture':'bức tranh','map':'bản đồ','money':'tiền','coin':'đồng xu',
'ticket':'vé','passport':'hộ chiếu','visa':'thị thực','letter':'thư','envelope':'phong bì',
'stamp':'tem','gift':'quà','toy':'đồ chơi','ball':'quả bóng','umbrella':'ô/dù',
'clothes':'quần áo','shirt':'áo sơ mi','pants':'quần','dress':'váy','skirt':'chân váy',
'shoes':'giày','hat':'mũ','scarf':'khăn quàng','gloves':'găng tay','socks':'tất',
'coat':'áo khoác','sweater':'áo len','jacket':'áo khoác ngắn','tie':'cà vạt',
'watch thing':'đồng hồ đeo tay','glasses':'kính','towel':'khăn mặt','soap':'xà phòng',
'toothbrush':'bàn chải','toothpaste':'kem đánh răng','comb':'lược','shampoo':'dầu gội',
'kettle':'ấm nước','thermos':'phích nước','fan':'quạt','heater':'lò sưởi',
'air conditioner':'điều hòa','washing machine':'máy giặt','refrigerator':'tủ lạnh',
'bicycle':'xe đạp','motorbike':'xe máy','car':'ô tô','bus':'xe buýt','train':'tàu hỏa',
'taxi':'taxi','truck':'xe tải','boat':'thuyền','ship':'tàu thủy','airplane':'máy bay',
'basketball':'bóng rổ','football':'bóng đá','table tennis':'bóng bàn','tennis sport':'quần vợt',
'volleyball':'bóng chuyền','swimming pool':'bể bơi','gym place':'phòng tập thể dục',
# --- danh tu: dong vat / thuc vat ---
'animal':'động vật','dog':'chó','cat':'mèo','bird':'chim','fish animal':'cá',
'chicken animal':'gà','duck':'vịt','pig':'lợn','cow':'bò','sheep':'cừu','horse':'ngựa',
'rabbit':'thỏ','mouse':'chuột','tiger':'hổ','lion':'sư tử','bear':'gấu','panda':'gấu trúc',
'monkey':'khỉ','elephant':'voi','snake':'rắn','frog':'ếch','bee':'ong','butterfly':'bướm',
'mosquito':'muỗi','fly insect':'ruồi','ant':'kiến','spider':'nhện','crab':'cua','shrimp':'tôm',
'turtle':'rùa','whale':'cá voi','shark':'cá mập','dolphin':'cá heo',
'tree':'cây','flower':'hoa','grass':'cỏ','leaf':'lá','root':'rễ','branch':'cành',
'bamboo':'tre','rice plant':'lúa','wheat':'lúa mì','corn':'ngô','cotton':'bông',
# --- danh tu tru tuong ---
'idea':'ý tưởng','thought':'suy nghĩ','opinion':'ý kiến','view':'quan điểm',
'question':'câu hỏi','problem':'vấn đề','answer solution':'câu trả lời','result':'kết quả',
'reason':'lý do','cause':'nguyên nhân','effect':'hiệu quả','method':'phương pháp',
'way':'cách','means':'biện pháp','plan abstract':'kế hoạch','decision':'quyết định',
'choice':'lựa chọn','chance':'cơ hội','opportunity':'cơ hội','success':'thành công',
'failure':'thất bại','progress':'tiến bộ','development':'phát triển','change abstract':'thay đổi',
'habit':'thói quen','custom':'phong tục','culture':'văn hóa','history':'lịch sử',
'language':'ngôn ngữ','word':'từ','sentence':'câu','text':'bài văn','article':'bài báo',
'story':'câu chuyện','novel':'tiểu thuyết','poem':'bài thơ','song music':'bài hát',
'music':'âm nhạc','art':'nghệ thuật','science':'khoa học','math':'toán học',
'knowledge':'kiến thức','experience':'kinh nghiệm','skill':'kỹ năng','ability':'khả năng',
'effort':'nỗ lực','courage':'dũng cảm','patience':'kiên nhẫn','confidence':'tự tin',
'feeling':'cảm giác','emotion':'cảm xúc','mood':'tâm trạng','love feeling':'tình yêu',
'friendship':'tình bạn','dream':'giấc mơ','hope feeling':'hy vọng','wish feeling':'điều ước',
'interest':'hứng thú','hobby':'sở thích','game':'trò chơi','sport':'thể thao',
'news':'tin tức','information':'thông tin','message':'tin nhắn','notice':'thông báo',
'advertisement':'quảng cáo','price':'giá','value':'giá trị','quality':'chất lượng',
'rule':'quy tắc','law rule':'pháp luật','duty':'nhiệm vụ','responsibility':'trách nhiệm',
'right correct':'quyền lợi','freedom':'tự do','peace':'hòa bình','war':'chiến tranh',
'nature':'thiên nhiên','environment':'môi trường','weather':'thời tiết','climate':'khí hậu',
'life':'cuộc sống','death':'cái chết','birth':'sinh ra','marriage':'hôn nhân',
'work job':'công việc','job':'việc làm','business':'kinh doanh','trade':'buôn bán',
'money salary':'lương','income':'thu nhập','expense':'chi tiêu','debt':'món nợ',
'meeting':'cuộc họp','party':'bữa tiệc','competition':'cuộc thi','exam test':'kỳ thi',
'lesson':'bài học','course':'khóa học','grade score':'điểm số','mistake':'lỗi sai',
'example':'ví dụ','symbol':'ký hiệu','sign':'biển báo','mark':'dấu vết',
'color':'màu sắc','shape':'hình dạng','size':'kích cỡ','weight':'cân nặng',
'speed':'tốc độ','distance':'khoảng cách','direction':'hướng','position':'vị trí',
'part':'bộ phận','whole thing':'toàn thể','half':'một nửa','pair':'một đôi',
'kind':'loại','type':'kiểu','style':'phong cách','brand':'nhãn hiệu',
# --- dong/tinh tu bo sung ---
'ask way':'hỏi đường','take bus':'đi xe buýt','take taxi':'đi taxi','get on':'lên xe',
'get off':'xuống xe','transfer':'đổi xe','arrive station':'đến bến','buy ticket':'mua vé',
'book ticket':'đặt vé','check in':'làm thủ tục','board plane':'lên máy bay',
'land plane':'hạ cánh','take off plane':'cất cánh','delay flight':'chuyến bay trễ',
'shopping':'mua sắm','bargain':'mặc cả','discount':'giảm giá','cheap price':'giá rẻ',
'pay bill':'thanh toán','change money':'đổi tiền','withdraw':'rút tiền','deposit':'gửi tiền',
'save money':'tiết kiệm tiền','borrow money':'vay tiền','lend money':'cho vay tiền',
'make money':'kiếm tiền','lose money':'mất tiền','rich person':'người giàu',
'take medicine':'uống thuốc','see doctor':'khám bệnh','have fever':'bị sốt',
'catch cold':'bị cảm','have rest':'nghỉ ngơi','get better':'khỏi bệnh',
'take exam':'thi','pass':'đỗ','fail exam':'trượt','study hard':'học chăm',
'review lesson':'ôn bài','do homework':'làm bài tập','attend class':'đi học',
'skip class':'trốn học','graduate school':'tốt nghiệp','find job':'tìm việc',
'quit job':'nghỉ việc','get promotion':'thăng chức','raise salary':'tăng lương',
'start business':'khởi nghiệp','sign contract':'ký hợp đồng','hold meeting':'mở cuộc họp',
'make decision':'ra quyết định','solve problem':'giải quyết vấn đề','face difficulty':'đối mặt khó khăn',
'overcome':'vượt qua','give up':'từ bỏ','insist':'kiên trì','achieve':'đạt được',
'celebrate':'ăn mừng','congratulate success':'chúc mừng thành công',
'say goodbye':'tạm biệt','say hello':'chào hỏi','say thanks':'cảm ơn','say sorry':'xin lỗi',
'make friends':'kết bạn','quarrel friend':'cãi nhau','make up friend':'làm lành',
'get married':'kết hôn','have baby':'sinh con','raise child':'nuôi con',
'move house':'chuyển nhà','rent house':'thuê nhà','buy house':'mua nhà',
'decorate house':'trang trí nhà','clean house':'dọn nhà','cook meal':'nấu cơm',
'wash clothes':'giặt quần áo','do laundry':'giặt giũ','iron clothes':'là quần áo',
'fold clothes':'gấp quần áo','take shower':'tắm','brush teeth':'đánh răng',
'wash face':'rửa mặt','comb hair':'chải đầu','cut hair':'cắt tóc','shave':'cạo râu',
'get up':'thức dậy','go to bed':'đi ngủ','stay up':'thức khuya','oversleep':'ngủ quên',
'have dream':'mơ','snore':'ngáy','take nap':'ngủ trưa','rest eyes':'nhắm mắt nghỉ',
# --- tu vung hoc thuat HSK4 ---
'society':'xã hội','economy':'kinh tế','politics':'chính trị','reform':'cải cách',
'policy':'chính sách','system':'chế độ/hệ thống','standard':'tiêu chuẩn','criterion':'tiêu chí',
'principle':'nguyên tắc','theory':'lý thuyết','practice':'thực tiễn','research':'nghiên cứu',
'survey':'khảo sát','statistics':'thống kê','data':'số liệu','report':'báo cáo',
'speech':'bài phát biểu','debate':'tranh luận','vote':'bỏ phiếu','elect':'bầu cử',
'celebration':'lễ kỷ niệm','ceremony':'nghi lễ','festival':'lễ hội','exhibition':'triển lãm',
'performance':'buổi biểu diễn','competition event':'cuộc thi đấu','match':'trận đấu',
'training':'huấn luyện','drill':'diễn tập','inspect work':'thanh tra','supervise':'giám sát',
'manage':'quản lý','operate':'vận hành','maintain':'bảo trì','protect environment':'bảo vệ môi trường',
'pollute':'ô nhiễm','recycle':'tái chế','conserve':'bảo tồn','develop economy':'phát triển kinh tế',
'invest':'đầu tư','profit':'lợi nhuận','loss':'thua lỗ','budget':'ngân sách',
'advertise':'quảng cáo','promote':'khuyến mãi','brand name':'thương hiệu','market place':'thị trường',
'client':'khách hàng','contract':'hợp đồng','negotiate':'đàm phán','cooperate':'hợp tác',
'establish':'thành lập','expand':'mở rộng','reduce scale':'thu hẹp','close down':'đóng cửa',
'employ':'tuyển dụng','fire':'sa thải','resign':'từ chức','retire':'nghỉ hưu',
'salary pay':'tiền lương','bonus':'tiền thưởng','allowance':'trợ cấp','insurance':'bảo hiểm',
'tax':'thuế','fine':'tiền phạt','fee':'lệ phí','tuition':'học phí','rent fee':'tiền thuê',
'transport':'giao thông','traffic jam':'tắc đường','accident':'tai nạn','safety':'an toàn',
'journey':'hành trình','voyage':'chuyến đi xa','tour':'chuyến tham quan','sightseeing':'ngắm cảnh',
'souvenir':'quà lưu niệm','luggage':'hành lý','backpack':'ba lô','tent':'lều',
'customs':'hải quan','immigration':'xuất nhập cảnh','embassy place':'đại sứ quán',
'translate work':'dịch thuật','interpret':'phiên dịch','publish':'xuất bản','print book':'in ấn',
'broadcast':'phát thanh','televise':'truyền hình','record':'ghi âm','film':'quay phim',
'photograph thing':'chụp ảnh','exhibit':'trưng bày','perform play':'diễn kịch',
'act role':'đóng vai','sing song':'hát','dance performance':'múa','draw picture':'vẽ tranh',
'write novel':'viết tiểu thuyết','compose':'sáng tác','design':'thiết kế','invent':'phát minh',
'discover':'khám phá','explore':'thám hiểm','experiment':'thí nghiệm','observe':'quan sát',
'measure':'đo đạc','calculate':'tính toán','prove':'chứng minh','conclude':'kết luận',
'assume':'giả định','predict':'dự đoán','analyze':'phân tích','compare data':'so sánh',
'summarize':'tổng kết','emphasize':'nhấn mạnh','illustrate':'minh họa','quote':'trích dẫn',
'refer':'tham khảo','consult expert':'tham vấn','recommend':'giới thiệu/tiến cử',
'introduce person':'giới thiệu ai','welcome guest':'đón khách','see off':'tiễn',
'accommodate':'sắp chỗ ở','register':'đăng ký','apply for':'xin/đăng ký',
'approve':'phê duyệt','reject':'bác bỏ','cancel order':'hủy đơn','confirm':'xác nhận',
'inform':'thông báo','notify':'thông tri','announce':'tuyên bố','declare':'tuyên bố',
'propose':'đề xuất','suggest idea':'đề nghị','demand':'yêu cầu','request':'thỉnh cầu',
'order command':'ra lệnh','obey':'tuân theo','violate':'vi phạm','punish':'trừng phạt',
'reward':'khen thưởng','praise work':'biểu dương','criticize work':'phê bình',
'reflect':'phản ánh','mirror':'phản chiếu','influence':'ảnh hưởng','affect':'tác động',
'improve':'cải thiện','worsen':'xấu đi','increase':'tăng lên','decrease':'giảm xuống',
'rise price':'tăng giá','fall price':'giảm giá','fluctuate':'dao động','stable':'ổn định',
'urgent':'khẩn cấp','important matter':'việc quan trọng','trivial':'vặt vãnh',
'complex issue':'vấn đề phức tạp','simple issue':'việc đơn giản','sensitive':'nhạy cảm',
'controversial':'gây tranh cãi','popular':'được yêu thích','fashionable':'hợp mốt',
'traditional':'truyền thống','modern style':'hiện đại','ancient':'cổ đại',
'local custom':'đặc sản địa phương','national':'thuộc quốc gia','international':'quốc tế',
'regional':'thuộc vùng','urban':'thành thị','rural area':'nông thôn','remote':'xa xôi',
'convenient traffic':'giao thông thuận tiện','crowded':'đông đúc','lively street':'nhộn nhịp',
'quiet village':'yên tĩnh','beautiful scenery':'phong cảnh đẹp','famous site':'danh lam thắng cảnh',
'historic':'mang tính lịch sử','cultural':'thuộc văn hóa','artistic':'mang tính nghệ thuật',
'scientific':'mang tính khoa học','technical':'thuộc kỹ thuật','academic':'thuộc học thuật',
'professional':'chuyên nghiệp','amateur':'nghiệp dư','skilled':'lành nghề','experienced':'giàu kinh nghiệm',
'reliable':'đáng tin cậy','responsible':'có trách nhiệm','efficient':'hiệu quả',
'creative':'sáng tạo','diligent':'chăm chỉ','lazy person':'lười biếng','humble':'khiêm tốn',
'arrogant':'kiêu ngạo','generous':'hào phóng','stingy':'keo kiệt','brave person':'dũng cảm',
'cowardly':'nhát gan','optimistic':'lạc quan','pessimistic':'bi quan','romantic person':'lãng mạn',
'humorous':'hài hước','serious':'nghiêm túc','casual':'tùy ý','formal':'trang trọng',
'polite speech':'lịch sự','rude speech':'thô lỗ','sincere':'chân thành','hypocritical':'giả dối',
'frank':'thẳng thắn','tactful':'khéo léo','naive':'ngây thơ','mature':'chững chạc',
'independent':'độc lập','dependent':'phụ thuộc','confident person':'tự tin','shy person':'rụt rè',
'sociable':'hòa đồng','reserved':'kín đáo','talkative':'hay nói','silent':'im lặng',
}

# --- bo sung T8.1 (gioi tu + tu vung HSK2-4 con thieu) ---
VI.update({
'to':'', 'of':'của', 'in':'trong', 'on':'trên', 'at':'lúc', 'out':'ra', 'up':'lên',
'over':'qua', 'through':'qua', 'from':'từ', 'with':'với', 'for':'cho', 'into':'vào',
'about sth':'về việc gì', 'between':'giữa', 'among':'trong số', 'within':'trong vòng',
'without':'không có', 'within reach':'trong tầm với', 'along':'dọc theo', 'across':'băng qua',
'against':'chống lại', 'toward':'hướng tới', 'towards':'hướng tới', 'until':'cho đến khi',
'since':'từ khi', 'while time':'trong khi', 'during':'trong lúc', 'before time':'trước khi',
'after time':'sau khi', 'above':'phía trên', 'below':'phía dưới', 'beside':'bên cạnh',
'besides':'ngoài ra', 'behind':'phía sau', 'beyond':'vượt quá', 'inside':'bên trong',
'outside':'bên ngoài', 'nearby':'gần đây', 'near place':'gần', 'far place':'xa',
'hundred':'trăm', 'thousand':'nghìn', 'ten thousand':'vạn', 'million':'triệu',
'first':'thứ nhất', 'second':'thứ hai', 'third':'thứ ba', 'next':'tiếp theo',
'last':'vừa qua', 'previous':'trước', 'following':'tiếp theo', 'latter':'sau',
'sequence':'trình tự', 'order list':'thứ tự', 'ordinal':'thứ (số thứ tự)',
'number':'số', 'numeral':'số từ', 'digit':'chữ số', 'amount':'số lượng',
'item':'món', 'piece':'miếng', 'pair':'đôi', 'couple item':'cặp',
'song':'bài hát', 'tune':'giai điệu', 'melody':'giai điệu', 'rhythm':'nhịp điệu',
'assistance':'sự giúp đỡ', 'aid':'viện trợ', 'helpful':'hữu ích',
'length':'chiều dài', 'width':'chiều rộng', 'height':'chiều cao', 'depth':'chiều sâu',
'rapid':'nhanh', 'swift':'nhanh', 'slow pace':'chậm', 'gradual':'dần dần',
'gate':'cổng', 'door gate':'cửa', 'entrance':'lối vào', 'exit place':'lối ra',
'subject':'môn học', 'course study':'khóa học', 'lesson study':'bài học',
'major':'chuyên ngành', 'homework':'bài tập về nhà', 'quiz':'kiểm tra ngắn',
'rapid progress':'tiến nhanh', 'kilogram':'ki-lô-gam', 'gram':'gam', 'meter':'mét',
'kilometer':'ki-lô-mét', 'centimeter':'xen-ti-mét', 'liter':'lít', 'yuan money':'đồng (tệ)',
'dollar':'đô la', 'cent':'xu', 'company':'công ty', 'firm':'hãng', 'corporation':'tập đoàn',
'factory place':'nhà máy', 'store':'cửa tiệm', 'shop place':'cửa hàng',
'lateral':'bên cạnh', 'side place':'bên', 'vicinity':'vùng lân cận',
'quickly':'nhanh chóng', 'slowly':'chậm rãi', 'suddenly':'bỗng nhiên',
'advantages':'lợi thế', 'disadvantages':'bất lợi', 'benefit':'lợi ích',
'human':'con người', 'mankind':'nhân loại', 'personnel':'nhân sự',
'affair':'việc', 'matter issue':'việc', 'business affair':'công việc',
'wrist':'cổ tay', 'cell phone':'điện thoại di động', 'deliver':'giao hàng',
'kick':'đá', 'topic':'chủ đề', 'theme':'chủ đề', 'title':'tiêu đề',
'name called':'tên', 'mutton':'thịt cừu', 'overcast':'âm u', 'swimming':'bơi lội',
'monetary':'tiền tệ', 'unit measure':'đơn vị', 'preparation':'sự chuẩn bị',
'left side':'trái', 'right side':'phải', 'maternal':'bên ngoại', 'paternal':'bên nội',
'modal':'tình thái', 'ending':'cuối câu', 'cover':'che phủ', 'till':'đến khi',
'compare':'so sánh', 'comparison':'so sánh', 'contrast':'tương phản',
'guesthouse':'nhà khách', 'icebox':'tủ lạnh', 'refrigerator box':'tủ lạnh',
'participate':'tham gia', 'join':'tham gia', 'layer':'lớp', 'appear':'xuất hiện',
'spring time':'mùa xuân', 'term word':'thuật ngữ', 'acute':'nhạy bén',
'sight':'thị giác', 'hearing sense':'thính giác', 'band music':'ban nhạc',
'anxious':'sốt ruột', 'natural':'tự nhiên', 'elevator':'thang máy',
'electronic':'điện tử', 'beating':'đập', 'drum':'trống', 'brief':'ngắn gọn',
'paragraph':'đoạn văn', 'engage':'tham gia', 'physical':'thuộc cơ thể',
'release':'thả ra', 'relieved':'nhẹ nhõm', 'divide':'chia ra', 'separate':'tách ra',
'moment ago':'cách đây chốc lát', 'ago':'trước', 'public park':'công viên',
'narrative':'chuyện kể', 'pertaining':'thuộc về', 'blackboard':'bảng đen',
'inspection':'kiểm tra', 'angle':'góc', 'program show':'chương trình',
'marry':'kết hôn', 'termination':'kết thúc', 'settle':'giải quyết',
'great':'lớn', 'satisfied':'hài lòng', 'noodles':'mì sợi', 'tray':'khay',
'mandarin':'tiếng phổ thông', 'actually':'thật ra', 'indeed':'quả thực',
'cordial':'nồng hậu', 'conscientious':'tận tâm', 'internet':'mạng',
'mathematics':'toán học', 'chauffeur':'tài xế', 'hurts':'đau', 'strip long':'dải',
'sudden':'đột ngột', 'bathe':'tắm', 'identical':'giống hệt', 'convinced':'tin chắc',
'resemble':'giống như', 'shoe':'giày', 'suitcase':'va li', 'spectacles':'kính đeo mắt',
'surely':'chắc chắn', 'exceed':'vượt quá', 'worry':'lo lắng', 'photograph':'ảnh chụp',
'bore':'khoan', 'layer cake':'lớp', 'temperature':'nhiệt độ', 'achievement':'thành tích',
'care verb':'chăm sóc', 'according':'theo', 'variant':'biến thể', 'classifier':'lượng từ',
'chinese adj':'thuộc Trung Quốc', 'original':'vốn có', 'everywhere':'khắp nơi',
'form paper':'biểu mẫu', 'opposite':'đối diện', 'purpose':'mục đích', 'joke':'trò đùa',
'equivalent':'tương đương', 'shed':'rụng/rơi', 'hit':'đánh', 'any':'bất kỳ',
'times frequency':'lần', 'seat place':'chỗ ngồi', 'loanword':'từ mượn',
'life living':'cuộc sống', 'nature world':'thiên nhiên', 'site':'địa điểm',
'suggestion':'gợi ý', 'surmise':'đoán chừng', 'white color':'trắng',
'newspaper press':'báo', 'length long':'dài', 'sing':'hát', 'boat':'thuyền',
'mistake':'lỗi', 'everyone':'mọi người', 'structural':'thuộc cấu trúc',
'adjective word':'tính từ', 'room place':'phòng', 'unusual':'khác thường',
'bus vehicle':'xe buýt', 'expensive price':'đắt', 'tasty food':'ngon',
'welcome guest':'hoan nghênh', 'airport place':'sân bay', 'chicken food':'thịt gà',
'egg food':'trứng', 'classroom place':'phòng học', 'near place':'gần',
'coffee drink':'cà phê', 'begin start':'bắt đầu', 'exam test':'kỳ thi',
'might':'có lẽ', 'can able':'có thể', 'rapid speed':'nhanh', 'happy feeling':'vui vẻ',
'tired feeling':'mệt', 'road path':'đường', 'sell goods':'bán', 'slow speed':'chậm',
'busy schedule':'bận', 'man male':'đàn ông', 'courteous':'lịch sự', 'milk drink':'sữa',
'woman female':'phụ nữ', 'small size':'nhỏ', 'ticket paper':'vé', 'get out':'ra khỏi',
'bed place':'giường', 'year time':'năm', 'yield give':'nhường', 'ill sick':'ốm',
'birthday day':'sinh nhật', 'watch wrist':'đồng hồ đeo tay', 'therefore':'vì thế',
'dance move':'nhảy múa', 'finish end':'xong', 'toy play':'đồ chơi', 'evening time':'buổi tối',
'question ask':'câu hỏi', 'watermelon fruit':'dưa hấu', 'new thing':'mới',
'rest relax':'nghỉ ngơi', 'snow weather':'tuyết', 'color hue':'màu sắc',
'eye organ':'mắt', 'already done':'đã', 'swimming sport':'bơi', 'far distance':'xa',
'morning time':'buổi sáng', 'open up':'mở ra', 'aspect grammar':'thể (hoàn thành/tiếp diễn)',
'progress advance':'tiến bộ', 'process doing':'quá trình', 'happening':'đang xảy ra',
'bicycle vehicle':'xe đạp', 'left direction':'trái', 'aunt maternal':'dì',
'like love':'thích', 'quiet place':'yên tĩnh', 'team group':'đội', 'half part':'một nửa',
'office work':'văn phòng', 'eat till':'ăn no', 'north direction':'phía bắc',
'quilt blanket':'chăn bông', 'nose organ':'mũi', 'competition event':'cuộc thi',
'people persons':'người ta', 'menu food':'thực đơn', 'grass plant':'cỏ',
'differ':'khác nhau', 'shirt clothing':'áo sơ mi', 'arrive late':'đến muộn',
'late time':'muộn', 'kitchen room':'nhà bếp', 'spring season':'mùa xuân',
'word language':'từ ngữ', 'general term':'từ chung', 'band tie':'dải băng',
'cake food':'bánh ngọt', 'lamp light':'đèn', 'subway train':'tàu điện ngầm',
'map paper':'bản đồ', 'sound noise':'tiếng động', 'east direction':'phía đông',
'hungry feeling':'đói', 'ear organ':'tai', 'illness sick':'bệnh', 'convenient use':'tiện',
'vicinity area':'vùng quanh đây', 'dare do':'dám', 'catch cold':'bị cảm',
'heel foot':'gót chân', 'park place':'công viên', 'blow wind':'thổi',
'wind air':'gió', 'country land':'đất nước', 'juice drink':'nước ép', 'past time':'quá khứ',
'afraid feeling':'sợ', 'passport doc':'hộ chiếu', 'garden place':'vườn hoa',
'bad thing':'xấu', 'yellow color':'vàng', 'opportunity chance':'cơ hội',
'simple easy':'đơn giản', 'health body':'sức khỏe', 'teach instruct':'dạy',
'foot organ':'bàn chân', 'street road':'đường phố', 'holiday day':'ngày lễ',
'dispute argue':'tranh chấp', 'lend borrow':'cho mượn', 'long time':'lâu',
'thirsty feeling':'khát', 'adorable cute':'đáng yêu', 'quarter hour':'mười lăm phút',
'visitor guest':'khách', 'conditioning air':'điều hòa', 'cry weep':'khóc',
'trousers pants':'quần dài', 'blue color':'xanh da trời', 'prefix grammar':'tiền tố',
'surname family':'họ', 'birth born':'sinh', 'children kids':'con cái',
'indicate show':'cho thấy', 'affection love':'yêu mến', 'familiarity close':'thân quen',
'depart leave':'rời đi', 'vehicles cars':'xe cộ', 'neighbor nearby':'hàng xóm',
'story tale':'câu chuyện', 'green color':'xanh lá', 'horse animal':'ngựa',
'hat cap':'mũ', 'rice grain':'gạo', 'bread food':'bánh mì', 'grandma old':'bà',
'south direction':'phía nam', 'sad feeling':'buồn', 'grade school':'khối lớp',
'young age':'trẻ', 'bird animal':'chim', 'effort try':'nỗ lực', 'climb up':'leo',
'fat body':'béo', 'beer drink':'bia', 'grape fruit':'nho', 'actually fact':'trên thực tế',
'strange odd':'lạ', 'lead metal':'chì', 'pencil tool':'bút chì', 'skirt clothing':'váy',
'easy simple':'dễ', 'umbrella rain':'ô', 'angry feeling':'tức giận', 'world earth':'thế giới',
'thin body':'gầy', 'comfortable feel':'thoải mái', 'although conj':'tuy',
'sugar sweet':'đường', 'sweet taste':'ngọt', 'agree yes':'đồng ý', 'library place':'thư viện',
'forget memory':'quên', 'why ask':'tại sao', 'position place':'vị trí', 'culture art':'văn hóa',
'west direction':'phía tây', 'habit custom':'thói quen', 'toilet place':'nhà vệ sinh',
'banana fruit':'chuối', 'true real':'đúng thật', 'college school':'trường cao đẳng',
'fresh food':'tươi', 'letter mail':'thư', 'desire want':'mong muốn', 'panda animal':'gấu trúc',
'need require':'cần', 'while short':'một lát', 'music art':'âm nhạc', 'bank money':'ngân hàng',
'ought should':'nên', 'influence effect':'ảnh hưởng', 'game play':'trò chơi',
'moon night':'mặt trăng', 'cloud sky':'mây', 'worry anxious':'lo âu', 'camera device':'máy ảnh',
'certain animals':'một số loài', 'weekend days':'cuối tuần', 'note paper':'lời nhắn',
'recent time':'gần đây', 'assignment homework':'bài tập', 'romance love':'tình yêu lãng mạn',
'safe secure':'an toàn', 'door entrance':'cửa', 'comprise include':'bao gồm',
'protect guard':'bảo vệ', 'guarantee promise':'bảo đảm', 'sorry regret':'xin lỗi',
'report news':'tường thuật', 'sign up':'đăng ký', 'stupid dumb':'ngốc',
'standard norm':'tiêu chuẩn', 'opinion view':'ý kiến', 'praise compliment':'khen ngợi',
'biscuit cookie':'bánh quy', 'choice select':'lựa chọn', 'wipe clean':'lau chùi',
'guess estimate':'đoán', 'material stuff':'nguyên liệu', 'look around':'tham quan',
'taste food':'nếm', 'large big':'lớn', 'specific particular':'cụ thể', 'surpass exceed':'vượt',
'vehicle car':'xe', 'success win':'thành công', 'mature ripe':'chín chắn',
'honest truthful':'trung thực', 'startled scared':'giật mình', 'smoke cigarette':'hút thuốc',
'cigarette tobacco':'thuốc lá', 'start begin':'khởi hành', 'born birth':'ra đời',
'fax machine':'máy fax', 'window glass':'cửa sổ', 'compound words':'từ ghép',
'answer reply':'câu trả lời', 'disturb bother':'làm phiền', 'print paper':'in ấn',
'discount sale':'giảm giá', 'injection shot':'mũi tiêm', 'roughly about':'khoảng',
'embassy building':'đại sứ quán', 'approximately about':'xấp xỉ', 'wear put':'đeo/mặc',
'glasses eyewear':'kính', 'representative delegate':'đại biểu', 'instead replace':'thay cho',
'local area':'địa phương', 'then time':'lúc đó', 'knife blade':'dao',
'tour trip':'chuyến tham quan', 'guide person':'hướng dẫn viên', 'finally end':'cuối cùng',
'proud self':'tự đắc', 'class rank':'hạng', 'background history':'xuất thân',
'investigation probe':'điều tra', 'movement motion':'động tác', 'jam congestion':'tắc nghẽn',
'belly abdomen':'bụng', 'break snap':'gãy', 'couple pair':'cặp đôi', 'dialog talk':'đối thoại',
'sitting seated':'ngồi', 'send out':'phát ra', 'development growth':'phát triển',
'law legal':'pháp luật', 'translate render':'dịch', 'worried anxiously':'lo lắng',
'against oppose':'phản đối', 'range scope':'phạm vi', 'method way':'phương pháp',
'respect regard':'tôn trọng', 'renounce abandon':'từ bỏ', 'holidays vacation':'nghỉ lễ',
'fraction part':'phân số', 'gifts presents':'quà tặng', 'scenery view':'phong cảnh',
'enrich make':'làm giàu', 'keeping with':'phù hợp với', 'rich wealthy':'giàu có',
'photocopy copy':'phô-tô', 'complicated complex':'phức tạp', 'toast drink':'nâng cốc',
'dry arid':'khô', 'feeling sense':'cảm giác', 'thanks gratitude':'lời cảm ơn',
'trunk body':'thân cây', 'recently lately':'gần đây', 'height tall':'chiều cao',
'tool instrument':'dụng cụ', 'wages pay':'tiền công', 'reach attain':'đạt được',
'shopping buy':'mua sắm', 'lone solitary':'đơn độc', 'estimate assess':'ước tính',
'applaud clap':'vỗ tay', 'client customer':'khách hàng', 'deliberately intentionally':'cố ý',
'suspend hang':'treo lên', 'hook catch':'móc', 'crucial key':'then chốt',
'spectators audience':'khán giả', 'supervise oversee':'giám sát', 'broadcast air':'phát thanh',
'advertise promote':'quảng cáo', 'stroll walk':'đi dạo', 'provision stipulate':'quy định',
'international global':'quốc tế', 'experienced marker':'đã từng', 'marker grammar':'trợ từ',
'course events':'diễn biến', 'ocean sea':'đại dương', 'shy bashful':'rụt rè',
'winter season':'mùa đông', 'vacation break':'kỳ nghỉ', 'perspiration sweat':'mồ hôi',
'scheduled planned':'theo lịch', 'flight plane':'chuyến bay', 'benefit advantage':'lợi ích',
'qualified meet':'đạt chuẩn', 'suitable fit':'phù hợp', 'case instance':'trường hợp',
'monkey animal':'khỉ', 'thick dense':'dày', 'regret remorse':'hối hận',
'afterwards later':'về sau', 'nurse medical':'y tá', 'doubt question':'nghi ngờ',
'recall recollect':'hồi tưởng', 'lively vivid':'sinh động', 'fire flame':'lửa',
'obtain acquire':'giành được', 'base foundation':'nền tảng', 'excite thrill':'kích động',
'active energetic':'năng nổ', 'accumulate gather':'tích lũy', 'gather assemble':'tập hợp',
'live reside':'sinh sống', 'reporter journalist':'phóng viên', 'technology tech':'kỹ thuật',
'since conj':'vì', 'furniture items':'đồ gỗ', 'overtime extra':'làm thêm giờ',
'gas fuel':'xăng', 'fake false':'giả', 'price cost':'giá cả', 'persevere persist':'kiên trì',
'weight body':'cân nặng', 'lessen reduce':'giảm bớt', 'future coming':'tương lai',
'premium bonus':'tiền thưởng', 'hand over':'bàn giao', 'connected linked':'nối liền',
'pride arrogance':'kiêu hãnh', 'dumpling jiaozi':'bánh chẻo', 'educate teach':'giáo dục',
'accept receive':'chấp nhận', 'economize save':'tiết kiệm', 'outcome result':'kết quả',
'explanation clarify':'lời giải thích', 'nervous anxious':'hồi hộp', 'despite spite':'bất chấp',
'brilliant splendid':'rực rỡ', 'spirit mind':'tinh thần', 'economy market':'kinh tế',
'opera performance':'kinh kịch', 'police officer':'cảnh sát', 'unexpectedly sudden':'không ngờ',
'compete rival':'cạnh tranh', 'when said':'khi nói', 'done finished':'đã xong',
'conduct hold':'tổ chức', 'distance far':'khoảng cách', 'way manner':'cách thức',
'looking at':'nhìn vào', 'thing object':'đồ vật', 'trees plants':'cây cối',
'science study':'khoa học', 'cough sick':'ho', 'pitiful pitiable':'đáng thương',
'pity shame':'tiếc', 'sure certain':'chắc chắn', 'fear fright':'sợ hãi',
'bitter taste':'đắng', 'lenient tolerant':'khoan dung', 'sleepy drowsy':'buồn ngủ',
'expand enlarge':'mở rộng', 'pull drag':'kéo', 'rubbish trash':'rác',
'bin container':'thùng', 'hot spicy':'cay nóng', 'lazy idle':'lười',
'romantic love':'lãng mạn', 'tiger animal':'hổ', 'calm composed':'bình tĩnh',
'courtesy politeness':'lễ phép', 'barber haircut':'cắt tóc', 'deal handle':'xử lý',
'strength power':'sức lực', 'example sample':'ví dụ', 'colloquial spoken':'thông tục',
'link connect':'liên kết', 'connection relation':'mối liên hệ', 'nice cold':'mát mẻ',
'chat talk':'trò chuyện', 'additional extra':'thêm', 'message note':'tin nhắn',
'abroad overseas':'nước ngoài', 'tears crying':'nước mắt', 'fluent proficient':'lưu loát',
'spread extend':'lan rộng', 'confusion disorder':'lộn xộn', 'disorder chaos':'rối loạn',
'lawyer attorney':'luật sư', 'inconvenient trouble':'phiền phức', 'towel cloth':'khăn',
'beautiful pretty':'đẹp', 'code secret':'mật mã', 'free charge':'miễn phí',
'nationality ethnic':'dân tộc', 'patient calm':'kiên nhẫn', 'unwell sick':'khó chịu',
'content substance':'nội dung', 'capability ability':'năng lực', 'age years':'tuổi',
'rural countryside':'nông thôn', 'warm cozy':'ấm áp', 'array arrange':'sắp hàng',
'accompany join':'đi cùng', 'criticize blame':'phê bình', 'skin surface':'da',
'character temper':'tính khí', 'sheet paper':'tờ', 'cheat deceive':'lừa gạt',
'table furniture':'bàn', 'bottle container':'chai', 'broken damaged':'hỏng',
'universal general':'phổ biến', 'among between':'trong số', 'off away':'tắt/rời',
'airplane aircraft':'máy bay', 'climate weather':'khí hậu', 'visa stamp':'thị thực',
'bridge crossing':'cây cầu', 'chocolate candy':'sô-cô-la', 'relative kin':'họ hàng',
'relation link':'mối quan hệ', 'gentle mild':'dịu dàng', 'circumstances situation':'hoàn cảnh',
'absence leave':'vắng mặt', 'dinner evening':'bữa tối', 'party gathering':'buổi tiệc',
'exhausted tired':'kiệt sức', 'difference distinction':'điểm khác',
'weak point':'điểm yếu', 'lack shortage':'thiếu', 'group crowd':'nhóm',
'bustling busy':'nhộn nhịp', 'noise sound':'tiếng ồn', 'excitement thrill':'náo nhiệt',
'renminbi currency':'nhân dân tệ', 'rmb money':'đồng nhân dân tệ', 'mission task':'nhiệm vụ',
'throw toss':'ném', 'diary journal':'nhật ký', 'entrance entry':'lối vào',
'soft gentle':'mềm', 'forest woods':'rừng', 'sofa couch':'ghế sofa',
'consult discuss':'bàn bạc', 'grieve mourn':'đau buồn', 'little bit':'một chút',
'bit small':'một ít', 'society community':'xã hội', 'apply submit':'nộp đơn',
'save rescue':'cứu', 'remain stay':'còn lại', 'defeated beaten':'bị đánh bại',
'disappointed let':'thất vọng', 'master expert':'bậc thầy', 'moist damp':'ẩm ướt',
'lion animal':'sư tử', 'into inside':'vào', 'equal same':'bằng nhau',
'parts components':'linh kiện', 'actual real':'thực tế', 'foodstuff provisions':'lương thực',
'test quiz':'bài kiểm tra', 'marketplace market':'chợ', 'century hundred':'thế kỷ',
'fit suit':'vừa vặn', 'adapt adjust':'thích nghi', 'capital city':'thủ đô',
'unbearable intolerable':'không chịu nổi', 'salesperson clerk':'người bán hàng',
'familiar known':'quen thuộc', 'handsome good':'đẹp trai', 'conveniently easily':'thuận tiện',
'smoothly well':'suôn sẻ', 'degree diploma':'học vị', 'die pass':'chết',
'speed velocity':'tốc độ', 'plastic bag':'túi ni-lông', 'bag sack':'túi',
'sour acidic':'chua', 'regard consider':'coi như', 'wishes regards':'lời chúc',
'along with':'cùng với', 'grandson male':'cháu trai', 'lift raise':'nâng lên',
'typhoon storm':'bão', 'manner way':'thái độ', 'pluck string':'gảy đàn',
'string cord':'dây', 'soup broth':'canh', 'recline lie':'nằm nghỉ',
'discuss talk':'thảo luận', 'characteristic trait':'đặc điểm', 'feature point':'đặc trưng',
'offer provide':'cung cấp', 'shift move':'dời lại', 'earlier sooner':'sớm hơn',
'date day':'ngày', 'remind recall':'nhắc nhở', 'fill in':'điền vào',
'job work':'công việc', 'vacancy opening':'chỗ trống', 'condition state':'điều kiện',
'stick adhere':'dán', 'by via':'bằng', 'notify inform':'thông báo',
'sympathize pity':'thông cảm', 'push shove':'đẩy', 'postpone defer':'hoãn lại',
'socks hosiery':'tất', 'often frequent':'hay', 'website site':'trang web',
'danger peril':'nguy hiểm', 'flavor taste':'hương vị', 'shake hands':'bắt tay',
'hands palm':'bàn tay', 'pollution contaminate':'ô nhiễm', 'less fewer':'ít hơn',
'bored weary':'chán', 'misunderstand confuse':'hiểu lầm', 'tomato fruit':'cà chua',
'attract appeal':'thu hút', 'washer machine':'máy giặt', 'salted salty':'mặn',
'modern current':'hiện đại', 'envy jealous':'ghen tị', 'restrict limit':'hạn chế',
'fragrant aromatic':'thơm', 'detailed thorough':'chi tiết', 'echo sound':'tiếng vang',
'novel book':'tiểu thuyết', 'mood frame':'tâm trạng', 'trust confide':'tin tưởng',
'confidence self':'lòng tin', 'credit card':'thẻ tín dụng', 'card paper':'thẻ',
'excited thrilled':'hào hứng', 'wake rouse':'đánh thức', 'gender sex':'giới tính',
'happiness joy':'hạnh phúc', 'many numerous':'nhiều', 'pressure stress':'áp lực',
'toothpaste paste':'kem đánh răng', 'asia continent':'châu Á', 'vowel sound':'nguyên âm',
'salt mineral':'muối', 'strict stern':'nghiêm khắc', 'grave serious':'nghiêm trọng',
'graduate student':'nghiên cứu sinh', 'student pupil':'học viên', 'actor performer':'diễn viên',
'actress female':'nữ diễn viên', 'sunshine sunlight':'ánh nắng', 'cultivate foster':'bồi dưỡng',
'appearance look':'vẻ ngoài', 'invite ask':'mời', 'key lock':'chìa khóa',
'perhaps maybe':'có lẽ', 'page sheet':'trang', 'foliage leaves':'tán lá',
'everything all':'mọi thứ', 'art fine':'nghệ thuật', 'rise ascend':'dâng lên',
'impression mark':'ấn tượng', 'beat defeat':'đánh bại', 'brave courageous':'dũng cảm',
'forever eternal':'mãi mãi', 'merit virtue':'ưu điểm', 'outstanding excellent':'xuất sắc',
'humor comedy':'hài hước', 'follow obey':'làm theo', 'due owed':'đến hạn',
'interesting fun':'thú vị', 'friendly amicable':'thân thiện', 'companionship fellowship':'tình bạn',
'cheerful merry':'vui tươi', 'thereupon whereupon':'do đó', 'grammar rules':'ngữ pháp',
'shuttlecock birdie':'cầu lông', 'prepare ready':'chuẩn bị', 'lesson class':'tiết học',
'circle round':'hình tròn', 'excuse pardon':'tha thứ', 'cause reason':'nguyên nhân',
'appointment date':'cuộc hẹn', 'read peruse':'đọc', 'magazine periodical':'tạp chí',
'speaker talker':'người nói', 'spoken uttered':'được nói', 'temporary transient':'tạm thời',
'dirty filthy':'bẩn', 'narrow tight':'hẹp', 'recruitment hiring':'tuyển dụng',
'genuine real':'thật', 'orderly neat':'ngăn nắp', 'regular steady':'đều đặn',
'formal official':'chính thức', 'proof evidence':'bằng chứng', 'possessive own':'sở hữu',
'favor support':'ủng hộ', 'intellectual mental':'trí thức', 'direct straight':'trực tiếp',
'worth worthy':'đáng', 'occupation profession':'nghề nghiệp', 'botanical plant':'thực vật',
'finger digit':'ngón tay', 'without lacking':'thiếu', 'better improved':'tốt hơn',
'manufacture produce':'sản xuất', 'least smallest':'ít nhất', 'quality grade':'chất lượng',
'attach fasten':'gắn', 'importance significance':'tầm quan trọng', 'surroundings environs':'vùng xung quanh',
'hog pig':'lợn', 'gradually slowly':'dần dần', 'initiative lead':'sáng kiến',
'specialist expert':'chuyên gia', 'specialty field':'chuyên ngành', 'earn gain':'kiếm được',
'accurate exact':'chính xác', 'sum total':'tổng', 'organize arrange':'tổ chức',
'best finest':'tốt nhất', 'final last':'cuối cùng', 'esteem respect':'kính trọng',
'author writer':'tác giả', 'join together':'cùng nhau', 'knowledge learn':'kiến thức',
})

# --- bo sung T8.1 dot 2 (tu don con thieu) ---
VI.update({
'one':'một','two':'hai','three':'ba','ten':'mười','eleven':'mười một','twelve':'mười hai',
'dozen':'tá','score points':'điểm số','grade class':'khối lớp','grade score':'điểm',
'particle':'trợ từ','there':'', 'used verb':'dùng', 'specific':'cụ thể',
'official':'chính thức','voice sound':'giọng nói','program event':'chương trình',
'adorable':'đáng yêu','quarter time':'mười lăm phút','conditioning cool':'điều hòa',
'trousers':'quần dài','depart go':'khởi hành','vehicles cars':'xe cộ',
'sports game':'thể thao','strip band':'dải','main chief':'chính','recent late':'gần đây',
'assignment task':'bài tập','romance love':'tình yêu lãng mạn','comprise consist':'bao gồm',
'protect guard':'bảo vệ','guarantee assure':'bảo đảm','stupid foolish':'ngốc',
'graduation graduate':'tốt nghiệp','wipe rub':'lau','material substance':'chất liệu',
'surpass overtake':'vượt qua','startled frightened':'giật mình','smoke tobacco':'hút thuốc',
'cigarette butt':'thuốc lá','born birthed':'ra đời','fax document':'bản fax',
'disturb interrupt':'làm phiền','print out':'in','roughly around':'khoảng',
'embassy mission':'đại sứ quán','approximately circa':'xấp xỉ','representative agent':'đại diện',
'instead alternate':'thay vào đó','local native':'địa phương','then at':'lúc ấy',
'knife cutter':'dao','finally ultimate':'cuối cùng','background setting':'lai lịch',
'address location':'địa chỉ','investigation inquiry':'điều tra','movement move':'động tác',
'dialog converse':'đối thoại','happen occur':'xảy ra','law statute':'luật',
'translate interpret':'phiên dịch','range extent':'phạm vi','respect honor':'tôn trọng',
'renounce relinquish':'từ bỏ','holidays fest':'ngày lễ','scenery landscape':'phong cảnh',
'enrich enriching':'làm phong phú','charge duty':'phụ trách','complicated intricate':'rắc rối',
'toast cheers':'cạn ly','trunk stem':'thân','recently newly':'mới đây',
'tool implement':'công cụ','wages salary':'tiền lương','lone alone':'cô đơn',
'estimate gauge':'ước lượng','applaud cheer':'vỗ tay','deliberately willfully':'cố tình',
'suspend dangle':'treo lơ lửng','crucial critical':'then chốt','point dot':'điểm',
'spectators viewers':'khán giả','stroll saunter':'tản bộ','provision clause':'điều khoản',
'events happenings':'sự việc','perspiration sweating':'mồ hôi','scheduled slated':'đúng giờ',
'flight fly':'chuyến bay','qualified eligible':'đủ tiêu chuẩn','suitable apt':'thích hợp',
'case instance':'trường hợp','regret rue':'hối tiếc','afterwards afterward':'sau này',
'recall remember':'nhớ lại','obtain get':'đạt được','base basis':'cơ sở',
'excite arouse':'gây xúc động','active lively':'tích cực','accumulate amass':'tích lũy',
'gather collect':'tụ họp','technology technique':'công nghệ','gas vapor':'hơi gas',
'persevere endure':'kiên trì','lessen diminish':'giảm đi','premium award':'tiền thưởng',
'reduce lessen':'hạ xuống','exchange swap':'trao đổi','educate instruct':'giáo dục',
'accept take':'tiếp nhận','economize frugal':'tiết kiệm','outcome upshot':'kết quả',
'explanation account':'giải thích','advance progress':'tiến lên','brilliant bright':'xuất sắc',
'spirit morale':'tinh thần','beijing capital':'Bắc Kinh','opera drama':'kịch',
'conduct direct':'tiến hành','trees timber':'cây','pity sorry':'đáng tiếc',
'sure confident':'chắc chắn','air atmosphere':'không khí','fear dread':'e sợ',
'lenient lax':'rộng lượng','bin can':'thùng','lazy slothful':'lười biếng',
'romantic amorous':'lãng mạn','calm serene':'điềm tĩnh','courtesy etiquette':'phép lịch sự',
'barber cutter':'thợ cắt tóc','deal cope':'xoay xở','strength might':'sức mạnh',
'link join':'nối lại','connection link':'mối nối','nice pleasant':'dễ chịu',
'chat chatter':'tán gẫu','abroad oversea':'nước ngoài','tears weep':'nước mắt',
'fluent fluid':'trôi chảy','spread disseminate':'lan truyền','confusion muddle':'hoang mang',
'disorder disarray':'rối ren','lawyer counsel':'luật sư','code cipher':'mã',
'content matter':'nội dung','capability capacity':'khả năng','age epoch':'tuổi tác',
'array lineup':'dãy','character nature':'tính cách','sheet leaf':'tờ giấy',
'cheat swindle':'lừa đảo','broken shattered':'vỡ','universal worldwide':'phổ quát',
'chocolate cocoa':'sô-cô-la','gentle tender':'nhẹ nhàng','circumstances conditions':'tình hình',
'absence nonattendance':'nghỉ phép','exhausted drained':'kiệt sức','difference gap':'khác biệt',
'lack want':'thiếu thốn','bustling lively':'tấp nập','noise clamor':'ồn ào',
'excitement agitation':'hứng khởi','renminbi yuan':'đồng nhân dân tệ','mission quest':'sứ mệnh',
'diary log':'nhật ký','consult confer':'hội ý','sound tone':'âm thanh',
'band group':'ban nhạc','swing sway':'đung đưa','care concern':'quan tâm',
'chinese china':'Trung Quốc','unit element':'đơn vị','left remaining':'còn lại',
'band strip':'băng','program plan':'kế hoạch','quarter fourth':'một phần tư',
'sports athletics':'môn thể thao','strip ribbon':'ruy băng','main major':'chủ yếu',
'recent fresh':'mới đây','assignment duty':'nhiệm vụ được giao','order sequence':'thứ tự',
'master skilled':'thành thạo','times occurrence':'lượt','seat sit':'ghế ngồi',
'name appellation':'tên gọi','side edge':'cạnh bên','abbr short':'viết tắt',
'main principal':'chủ yếu','note annotation':'ghi chú','recent new':'mới gần đây',
'comprise constitute':'gồm có','protect shield':'che chở','guarantee warrant':'cam kết',
'stupid dull':'khờ','graduation commencement':'lễ tốt nghiệp','biscuit cracker':'bánh bích quy',
'material data':'tài liệu','startled amazed':'kinh ngạc','smoke fume':'khói',
'official formal':'trang trọng','born natal':'được sinh','fax facsimile':'fax',
'print printing':'bản in','roughly roughly':'đại khái','embassy consulate':'sứ quán',
'knife knife':'con dao','finally eventually':'rốt cuộc','background back':'bối cảnh',
'address speech':'bài phát biểu','investigation research':'khảo sát',
'movement campaign':'phong trào','dialog dialogue':'hội thoại','law rule':'điều luật',
'range stove':'phạm vi','respect esteem':'kính nể','holidays holiday':'dịp lễ',
'gifts gift':'quà biếu','scenery scene':'cảnh sắc','charge fee':'phí',
'trunk luggage':'rương','recently recent':'dạo này','tool utensil':'đồ dùng',
'wages wage':'lương bổng','lone lonesome':'lẻ loi','estimate estimation':'dự tính',
'applaud applause':'tràng pháo tay','suspend suspending':'đình chỉ',
'crucial moment':'thời khắc quyết định','point argument':'luận điểm',
'spectators crowd':'đám đông','stroll promenade':'dạo chơi','provision providing':'cung ứng',
'events event':'biến cố','perspiration perspire':'đổ mồ hôi','scheduled timetable':'lên lịch',
'flight flee':'bay','qualified proficient':'thạo việc','suitable convenient':'tiện',
'case crate':'hộp','regret repent':'ăn năn','afterwards after':'hồi sau',
'recall reminisce':'hồi cố','obtain procurement':'thu được','base pedestal':'đế',
'excite excite':'kích thích','active action':'hành động','accumulate accumulation':'tích tụ',
'gather gathering':'hội họp','technology hi':'kỹ nghệ','gas gasoline':'xăng dầu',
'persevere perseverance':'bền bỉ','lessen less':'bớt đi','premium prize':'giải thưởng',
'reduce reduction':'cắt giảm','exchange interchange':'giao lưu','educate education':'dạy dỗ',
'accept acceptance':'chấp thuận','economize economy':'tiết giảm','outcome aftermath':'hậu quả',
'explanation exposition':'thuyết minh','advance advancement':'tiến triển',
'brilliant genius':'tài hoa','spirit ghost':'hồn','conduct behavior':'hành vi',
'trees tree':'cây xanh','pity ruth':'thương hại','sure surely':'quả quyết',
'air aerial':'trên không','fear phobia':'nỗi sợ','lenient gentle':'nhân hậu',
'bin dustbin':'sọt rác','lazy bone':'biếng nhác','romantic novel':'tiểu thuyết tình cảm',
'calm pacific':'êm ả','courtesy court':'lễ nghi','barber shop':'hiệu cắt tóc',
'deal transaction':'thương vụ','strength force':'lực','link linkage':'mắt xích',
'connection junction':'chỗ nối','nice fine':'tốt đẹp','chat chit':'chuyện phiếm',
'abroad foreign':'ngoại quốc','tears tear':'giọt lệ','fluent eloquent':'hùng hồn',
'spread sprawl':'trải rộng','confusion confuse':'lẫn lộn','disorder riot':'náo loạn',
'lawyer pleader':'trạng sư','code encrypt':'mật mã hóa','content contents':'mục lục',
'capability potential':'tiềm năng','age maturity':'trưởng thành','array display':'trưng bày',
'character protagonist':'nhân vật','sheet bedding':'tấm trải','cheat cheat':'gian lận',
'broken interrupt':'gián đoạn','universal cosmos':'vũ trụ','chocolate brown':'nâu sô-cô-la',
'gentle genteel':'thanh lịch','circumstances circumstance':'cảnh ngộ',
'absence absentee':'kẻ vắng mặt','exhausted exhaust':'cạn kiệt','difference differential':'vi phân',
'lack lacking':'khan hiếm','bustling hustle':'hối hả','noise din':'tiếng vang',
'excitement excitation':'kích thích','mission missionary':'truyền giáo',
'diary dairy':'sữa','consult consultant':'cố vấn',
})

# --- single-word fallback (suy tu cum, kiem tay khi review) ---
VI.update({
'abbr': 'viết tắt',
'about': 'về việc gì',
'abroad': 'nước ngoài',
'absence': 'vắng mặt',
'accept': 'chấp nhận',
'accumulate': 'tích lũy',
'accurate': 'chính xác',
'act': 'đóng vai',
'active': 'năng nổ',
'actual': 'thực tế',
'adapt': 'thích nghi',
'additional': 'thêm',
'address': 'địa chỉ',
'adjective': 'tính từ',
'advance': 'tiến lên',
'affection': 'yêu mến',
'afterwards': 'về sau',
'age': 'tuổi',
'air': 'điều hòa',
'appearance': 'vẻ ngoài',
'applaud': 'vỗ tay',
'apply': 'xin/đăng ký',
'appointment': 'cuộc hẹn',
'approximately': 'xấp xỉ',
'array': 'sắp hàng',
'asia': 'châu Á',
'aspect': 'thể (hoàn thành/tiếp diễn)',
'assignment': 'bài tập',
'attach': 'gắn',
'attend': 'đi học',
'attract': 'thu hút',
'background': 'xuất thân',
'band': 'ban nhạc',
'barber': 'cắt tóc',
'base': 'nền tảng',
'beijing': 'Bắc Kinh',
'best': 'tốt nhất',
'better': 'tốt hơn',
'bin': 'thùng',
'biscuit': 'bánh quy',
'bit': 'một ít',
'board': 'lên máy bay',
'bored': 'chán',
'born': 'ra đời',
'botanical': 'thực vật',
'brave': 'dũng cảm',
'brilliant': 'rực rỡ',
'broken': 'hỏng',
'bustling': 'nhộn nhịp',
'by': 'bằng',
'calm': 'bình tĩnh',
'can': 'có thể',
'capability': 'năng lực',
'card': 'thẻ',
'care': 'chăm sóc',
'case': 'trường hợp',
'catch': 'bị cảm',
'cell': 'điện thoại di động',
'century': 'thế kỷ',
'certain': 'một số loài',
'character': 'tính khí',
'characteristic': 'đặc điểm',
'charge': 'phụ trách',
'chat': 'trò chuyện',
'cheat': 'lừa gạt',
'cheerful': 'vui tươi',
'chinese': 'thuộc Trung Quốc',
'chocolate': 'sô-cô-la',
'cigarette': 'thuốc lá',
'circle': 'hình tròn',
'circumstances': 'hoàn cảnh',
'code': 'mật mã',
'college': 'trường cao đẳng',
'colloquial': 'thông tục',
'companionship': 'tình bạn',
'complicated': 'phức tạp',
'compound': 'từ ghép',
'comprise': 'bao gồm',
'condition': 'điều kiện',
'conditioning': 'điều hòa',
'conduct': 'tổ chức',
'confident': 'tự tin',
'confusion': 'lộn xộn',
'connected': 'nối liền',
'connection': 'mối liên hệ',
'consult': 'tham vấn',
'content': 'nội dung',
'conveniently': 'thuận tiện',
'courtesy': 'lễ phép',
'credit': 'thẻ tín dụng',
'crucial': 'then chốt',
'cultivate': 'bồi dưỡng',
'danger': 'nguy hiểm',
'dare': 'dám',
'deal': 'xử lý',
'defeated': 'bị đánh bại',
'degree': 'học vị',
'deliberately': 'cố ý',
'depart': 'rời đi',
'desire': 'mong muốn',
'despite': 'bất chấp',
'detailed': 'chi tiết',
'develop': 'phát triển kinh tế',
'dialog': 'đối thoại',
'diary': 'nhật ký',
'difference': 'điểm khác',
'direct': 'trực tiếp',
'disappointed': 'thất vọng',
'disorder': 'rối loạn',
'dispute': 'tranh chấp',
'disturb': 'làm phiền',
'done': 'đã xong',
'due': 'đến hạn',
'earlier': 'sớm hơn',
'echo': 'tiếng vang',
'economize': 'tiết kiệm',
'educate': 'giáo dục',
'embassy': 'đại sứ quán',
'enrich': 'làm giàu',
'envy': 'ghen tị',
'equal': 'bằng nhau',
'esteem': 'kính trọng',
'estimate': 'ước tính',
'events': 'sự việc',
'exchange': 'trao đổi',
'excite': 'kích động',
'excited': 'hào hứng',
'excitement': 'náo nhiệt',
'excuse': 'tha thứ',
'exhausted': 'kiệt sức',
'explanation': 'lời giải thích',
'fake': 'giả',
'familiarity': 'thân quen',
'favor': 'ủng hộ',
'fax': 'máy fax',
'fear': 'sợ hãi',
'feature': 'đặc trưng',
'fill': 'điền vào',
'final': 'cuối cùng',
'finally': 'cuối cùng',
'fit': 'vừa vặn',
'flavor': 'hương vị',
'flight': 'chuyến bay',
'fluent': 'lưu loát',
'fold': 'gấp quần áo',
'foliage': 'tán lá',
'foodstuff': 'lương thực',
'forever': 'mãi mãi',
'form': 'biểu mẫu',
'fraction': 'phân số',
'fragrant': 'thơm',
'furniture': 'đồ gỗ',
'gas': 'xăng',
'gather': 'tập hợp',
'gender': 'giới tính',
'general': 'từ chung',
'gentle': 'dịu dàng',
'genuine': 'thật',
'gifts': 'quà tặng',
'grade': 'điểm',
'gradually': 'dần dần',
'graduation': 'tốt nghiệp',
'grammar': 'ngữ pháp',
'grandson': 'cháu trai',
'grave': 'nghiêm trọng',
'grieve': 'đau buồn',
'guarantee': 'bảo đảm',
'hands': 'bàn tay',
'happen': 'xảy ra',
'happiness': 'hạnh phúc',
'hearing': 'thính giác',
'heel': 'gót chân',
'hog': 'lợn',
'holidays': 'nghỉ lễ',
'hook': 'móc',
'humor': 'hài hước',
'importance': 'tầm quan trọng',
'impression': 'ấn tượng',
'indicate': 'cho thấy',
'initiative': 'sáng kiến',
'instead': 'thay cho',
'intellectual': 'trí thức',
'interesting': 'thú vị',
'investigation': 'điều tra',
'iron': 'là quần áo',
'jam': 'tắc nghẽn',
'keeping': 'phù hợp với',
'knife': 'dao',
'lack': 'thiếu',
'land': 'hạ cánh',
'law': 'điều luật',
'lawyer': 'luật sư',
'lazy': 'lười biếng',
'lead': 'chì',
'least': 'ít nhất',
'left': 'trái',
'lenient': 'khoan dung',
'lessen': 'giảm bớt',
'link': 'liên kết',
'little': 'một chút',
'living': 'phòng khách',
'local': 'đặc sản địa phương',
'lone': 'đơn độc',
'looking': 'nhìn vào',
'main': 'chính',
'manner': 'thái độ',
'manufacture': 'sản xuất',
'many': 'nhiều',
'marker': 'trợ từ',
'marketplace': 'chợ',
'master': 'bậc thầy',
'material': 'nguyên liệu',
'matter': 'việc',
'merit': 'ưu điểm',
'mission': 'nhiệm vụ',
'misunderstand': 'hiểu lầm',
'modern': 'hiện đại',
'moist': 'ẩm ướt',
'movement': 'động tác',
'name': 'tên',
'nationality': 'dân tộc',
'nice': 'mát mẻ',
'noise': 'tiếng ồn',
'note': 'lời nhắn',
'obtain': 'giành được',
'occupation': 'nghề nghiệp',
'off': 'tắt/rời',
'offer': 'cung cấp',
'older': 'anh trai',
'opera': 'kinh kịch',
'order': 'ra lệnh',
'orderly': 'ngăn nắp',
'ought': 'nên',
'outcome': 'kết quả',
'outstanding': 'xuất sắc',
'overtime': 'làm thêm giờ',
'page': 'trang',
'parts': 'linh kiện',
'perform': 'diễn kịch',
'perhaps': 'có lẽ',
'persevere': 'kiên trì',
'perspiration': 'mồ hôi',
'photocopy': 'phô-tô',
'pitiful': 'đáng thương',
'pity': 'tiếc',
'plastic': 'túi ni-lông',
'pluck': 'gảy đàn',
'point': 'điểm',
'pollution': 'ô nhiễm',
'possessive': 'sở hữu',
'post': 'bưu điện',
'prefix': 'tiền tố',
'premium': 'tiền thưởng',
'pressure': 'áp lực',
'pride': 'kiêu hãnh',
'print': 'in ấn',
'process': 'quá trình',
'program': 'chương trình',
'proof': 'bằng chứng',
'protect': 'bảo vệ môi trường',
'provision': 'quy định',
'public': 'công viên',
'put': 'mặc vào',
'qualified': 'đạt chuẩn',
'quarter': 'mười lăm phút',
'quilt': 'chăn bông',
'quit': 'nghỉ việc',
'range': 'phạm vi',
'recall': 'hồi tưởng',
'recent': 'gần đây',
'recently': 'gần đây',
'recline': 'nằm nghỉ',
'recruitment': 'tuyển dụng',
'reduce': 'thu hẹp',
'regard': 'coi như',
'regret': 'hối hận',
'regular': 'đều đặn',
'relation': 'mối quan hệ',
'remain': 'còn lại',
'renminbi': 'nhân dân tệ',
'renounce': 'từ bỏ',
'representative': 'đại biểu',
'respect': 'tôn trọng',
'restrict': 'hạn chế',
'review': 'ôn bài',
'rise': 'tăng giá',
'rmb': 'đồng nhân dân tệ',
'romance': 'tình yêu lãng mạn',
'romantic': 'lãng mạn',
'roughly': 'khoảng',
'rubbish': 'rác',
'rural': 'nông thôn',
'salary': 'tiền lương',
'salesperson': 'người bán hàng',
'salted': 'mặn',
'say': 'tạm biệt',
'scenery': 'phong cảnh',
'scheduled': 'theo lịch',
'score': 'điểm số',
'seat': 'chỗ ngồi',
'shake': 'bắt tay',
'sheet': 'tờ',
'shift': 'dời lại',
'shuttlecock': 'cầu lông',
'side': 'bên',
'sitting': 'ngồi',
'skip': 'trốn học',
'smoke': 'hút thuốc',
'smoothly': 'suôn sẻ',
'solve': 'giải quyết vấn đề',
'sound': 'tiếng động',
'speaker': 'người nói',
'specialist': 'chuyên gia',
'specialty': 'chuyên ngành',
'spectators': 'khán giả',
'spirit': 'tinh thần',
'spoken': 'được nói',
'sports': 'thể thao',
'spread': 'lan rộng',
'startled': 'giật mình',
'stay': 'thức khuya',
'stick': 'dán',
'strength': 'sức lực',
'string': 'dây',
'strip': 'dải',
'stroll': 'đi dạo',
'stupid': 'ngốc',
'suitable': 'phù hợp',
'sum': 'tổng',
'sunshine': 'ánh nắng',
'sure': 'chắc chắn',
'surname': 'họ',
'surpass': 'vượt',
'surroundings': 'vùng xung quanh',
'suspend': 'treo lên',
'swing': 'đung đưa',
'sympathize': 'thông cảm',
'tears': 'nước mắt',
'technology': 'kỹ thuật',
'temporary': 'tạm thời',
'tennis': 'quần vợt',
'term': 'thuật ngữ',
'thanks': 'lời cảm ơn',
'then': 'lúc đó',
'thereupon': 'do đó',
'times': 'lần',
'toast': 'nâng cốc',
'tomato': 'cà chua',
'tool': 'dụng cụ',
'traffic': 'tắc đường',
'translate': 'dịch thuật',
'trees': 'cây cối',
'trunk': 'thân cây',
'typhoon': 'bão',
'unbearable': 'không chịu nổi',
'unexpectedly': 'không ngờ',
'unit': 'đơn vị',
'universal': 'phổ biến',
'unwell': 'khó chịu',
'used': 'dùng',
'vacancy': 'chỗ trống',
'vehicle': 'xe',
'vehicles': 'xe cộ',
'voice': 'giọng nói',
'vowel': 'nguyên âm',
'wages': 'tiền công',
'washer': 'máy giặt',
'washing': 'máy giặt',
'website': 'trang web',
'wipe': 'lau chùi',
'wishes': 'lời chúc',
'worth': 'đáng',
'yield': 'nhường',
'younger': 'em trai',
'yuan': 'đồng (tệ)',
})

# --- bo sung T8.1 dot 3 ---
VI.update({
'even':'thậm chí','level':'trình độ','president':'hiệu trưởng','option':'cách chọn',
'especially':'nhất là','indicating':'cho thấy','fold':'gấp','weather':'thời tiết',
'glasses':'kính','paint dye':'sơn','courteous polite':'lịch sự','better good':'tốt hơn',
'any better':'tốt hơn','without any':'không có', 'to)':'',
})

# ---- engine dich gloss ----
# -*- coding: utf-8 -*-
"""engine.py — dich sense Anh sang gloss Viet (tu soan), bao leftovers."""
import json, io, re, sys

# Tu rieng cho tung chu Han (Viet tu soan, dua theo nghia HSK). Key: hanzi.
OVERRIDES = {
'吧': 'trợ từ cuối câu (nhé, nhỉ, nào)',
'着': 'trợ từ tiếp diễn (đang...)',
'地': 'trợ từ (một cách...)',
'把': 'giới từ (đem, cầm lấy)',
'被': 'bị, được (câu bị động)',
'比': 'so với, hơn (so sánh)',
'跟': 'và, với, theo (cùng)',
'为': 'vì, để, làm (vì)',
'向': 'hướng về, phía',
'从': 'từ (nơi chốn, thời gian)',
'到': 'đến, tới',
'给': 'cho, đưa cho',
'让': 'để cho, nhường',
'在': 'ở, tại, đang',
'和': 'và, với',
'与': 'và, với (trang trọng)',
'或': 'hoặc',
'而': 'mà, nhưng (nối câu)',
'而且': 'hơn nữa, vả lại',
'但是': 'nhưng',
'可是': 'nhưng mà',
'不过': 'chẳng qua, có điều là',
'不仅': 'không chỉ',
'不但': 'không những',
'与其': 'thà... còn hơn',
'如果': 'nếu',
'即使': 'dù cho, cho dù',
'既然': 'đã... thì',
'尽管': 'mặc dù, cứ việc',
'虽然': 'mặc dù',
'因为': 'vì, bởi vì',
'由于': 'do, bởi',
'所以': 'cho nên',
'因此': 'do đó, vì vậy',
'于是': 'thế là, bèn',
'然后': 'sau đó',
'以后': 'sau này, về sau',
'以前': 'trước đây',
'从来': 'từ trước tới nay (luôn)',
'已经': 'đã',
'正在': 'đang (ngay lúc này)',
'将': 'sẽ',
'要': 'muốn, cần, sẽ',
'会': 'biết, sẽ, có thể',
'可以': 'có thể, được phép',
'可能': 'có thể, có khả năng',
'应该': 'nên, phải',
'必须': 'phải, bắt buộc',
'需要': 'cần',
'愿意': 'đồng ý, muốn, sẵn lòng',
'敢': 'dám',
'能够': 'có thể',
'不能不': 'không thể không',
'不得不': 'đành phải',
'得': 'trợ từ (làm... đến nỗi)',
'只': 'chỉ (duy nhất)',
'就': 'thì, bèn, chính là',
'才': 'mới (chỉ vừa)',
'都': 'đều',
'也': 'cũng',
'再': 'lại, nữa (lần sau)',
'又': 'lại (đã lặp)',
'还': 'còn, vẫn (tiếp diễn)',
'更': 'càng, hơn',
'最': 'nhất',
'非常': 'rất, vô cùng',
'特别': 'đặc biệt',
'十分': 'rất, hết sức',
'有点': 'hơi, có chút',
'极': 'cực kỳ',
'极其': 'vô cùng, cực kỳ',
'几乎': 'gần như',
'差': 'kém, thiếu, tệ',
'差不多': 'gần như, suýt soát',
'一般': 'bình thường, thông thường',
'一样': 'giống nhau',
'一共': 'tổng cộng',
'一切': 'tất cả',
'所有': 'tất cả',
'另外': 'ngoài ra, khác',
'其他': 'khác, còn lại',
'别的': 'khác',
'每个': 'mỗi (cái)',
'大家': 'mọi người',
'自己': 'bản thân, tự mình',
'别人': 'người khác',
'对方': 'đối phương',
'互相': 'lẫn nhau',
'之间': 'giữa (với nhau)',
'其中': 'trong đó',
'什么': 'cái gì',
'怎么': 'thế nào, sao',
'怎么样': 'thế nào, ra sao',
'为什么': 'tại sao',
'多少': 'bao nhiêu',
'几': 'mấy',
'哪': 'nào',
'哪些': 'những... nào',
'谁': 'ai',
'时候': 'lúc, khi',
'地方': 'nơi, chỗ',
'这里': 'ở đây',
'那里': 'ở đó',
'哪里': 'ở đâu',
'这': 'này, đây',
'那': 'kia, đó',
'这些': 'những cái này',
'那些': 'những cái kia',
'这样': 'như thế này',
'那样': 'như thế kia',
'这么': 'như thế này (mức độ)',
'那么': 'như thế kia (mức độ)',
'来': 'đến, lại đây',
'去': 'đi',
'上': 'lên, trên',
'下': 'xuống, dưới',
'进': 'vào',
'出': 'ra',
'回': 'về, trở lại',
'过': 'đã từng, qua',
'起': 'dậy, lên (bắt đầu)',
'起来': 'đứng dậy, lên (tiếp diễn)',
'下去': 'xuống, tiếp tục',
'下来': 'xuống, lại (kết quả)',
'过去': 'trước đây, đã qua',
'起来看': 'trông có vẻ',
'是': 'là',
'有': 'có',
'在乎': 'để tâm, quan tâm',
'行': 'được, ổn (đồng ý)',
'好': 'tốt, được',
'对': 'đúng',
'错': 'sai',
'可以吗': 'được không',
'没关系': 'không sao',
'没问题': 'không vấn đề gì',
'不用谢': 'không cần cảm ơn',
'不客气': 'không có gì',
'对不起': 'xin lỗi',
'谢谢': 'cảm ơn',
'再见': 'tạm biệt',
}

STRIP_PAREN = re.compile(r'\([^)]*\)')
STRIP_BRACKET = re.compile(r'\[[^]]*\]')

def clean(s):
    s = s.strip()
    s = STRIP_BRACKET.sub(' ', s)
    s = STRIP_PAREN.sub(' ', s)
    s = s.split(';')[0]
    s = re.sub(r'\s+', ' ', s).strip()
    return s

# Bo nhan xưng 's, viet tat phu dinh, giu nghia loi.
NORMALIZE = [
    (re.compile(r"cow's", re.I), 'cow'),
    (re.compile(r"person's", re.I), 'person'),
    (re.compile(r"father's", re.I), 'father'),
    (re.compile(r"don't", re.I), 'do not'),
    (re.compile(r"there's", re.I), 'there is'),
    (re.compile(r"'s\b"), ''),
    (re.compile(r"'"), ''),
]

def normalize(s):
    for pat, rep in NORMALIZE:
        s = pat.sub(rep, s)
    return s

def translate(sense):
    s = normalize(clean(sense))
    low = s.lower().strip()
    # bo 'to ' dau dong tu
    m = re.match(r'^to ([a-z].*)$', low)
    verb = False
    if m:
        low = m.group(1); verb = True
    # longest-phrase match truoc
    words = re.findall(r"[a-z']+", low)
    out = []
    unmapped = []
    i = 0
    # thu phrase 3-2-1 tu
    toks = low.replace("'", "").split()
    res = []
    i = 0
    while i < len(toks):
        hit = None
        for L in (4, 3, 2):
            if i + L <= len(toks):
                ph = ' '.join(toks[i:i+L])
                if ph in VI:
                    hit = (L, VI[ph]); break
        if hit is None:
            w = re.sub(r'^[^a-z]+|[^a-z]+$', '', toks[i])
            if w in VI:
                hit = (1, VI[w])
            elif w in ('a', 'an', 'the', ''):
                hit = (1, '')
            elif w in ('etc', 'else'):
                hit = (1, '')
            else:
                unmapped.append(w); hit = (1, None)
        L, vi = hit
        if vi:
            res.append(vi)
        i += L
    gloss = ' '.join(res)
    gloss = re.sub(r'\s+', ' ', gloss).strip()
    return gloss, unmapped, verb

# Ghi de rieng tung chu (Viet tu soan theo nghia HSK).
OVERRIDES.update({
'您': 'ngài, bạn (lịch sự)',
'复习': 'ôn tập',
'关系': 'quan hệ',
'老': 'già; (tiền tố gọi thân mật)',
'楼': 'tòa nhà, tầng lầu',
'种': 'loại; gieo trồng',
'倍': 'gấp (bội số)',
'长江': 'sông Dương Tử',
'分之': 'phần (chỉ phân số)',
'呀': 'trợ từ cuối câu (nha, nhé)',
'无': 'không, vô',
'亿': 'trăm triệu',
'只好': 'đành phải',
'甚至': 'thậm chí',
'咱们': 'chúng ta (gồm cả người nghe)',
'之': 'của (văn ngôn)',
'难道': 'lẽ nào... (hỏi tu từ)',
'尤其': 'nhất là',
'千': 'nghìn',
'姓': 'họ (tên họ)',
'元': 'đồng (đơn vị tiền tệ)',
'左边': 'bên trái',
'右边': 'bên phải',
'带': 'mang theo, dẫn theo',
'冬': 'mùa đông',
'关心': 'quan tâm',
'节目': 'tiết mục, chương trình',
'离开': 'rời khỏi',
'辆': 'lượng từ (xe cộ)',
'年级': 'khối lớp',
'秋': 'mùa thu',
'声音': 'tiếng, giọng',
'体育': 'thể dục thể thao',
'条': 'sợi, con (lượng từ vật dài)',
'为了': 'để, vì',
'一边': 'một bên; vừa... vừa...',
'照顾': 'chăm sóc',
'主要': 'chủ yếu',
'注意': 'chú ý',
'最近': 'gần đây',
'作业': 'bài tập (về nhà)',
'作用': 'tác dụng',
'爱情': 'tình yêu (nam nữ)',
'包括': 'bao gồm',
'保护': 'bảo vệ',
'保证': 'bảo đảm',
'笨': 'ngốc, đần',
'毕业': 'tốt nghiệp',
'表达': 'bày tỏ',
'表格': 'biểu mẫu',
'饼干': 'bánh quy',
'不管': 'bất kể, dù',
'擦': 'lau, chùi',
'材料': 'tài liệu, nguyên liệu',
'超过': 'vượt quá',
'吃惊': 'giật mình, kinh ngạc',
'抽烟': 'hút thuốc',
'出生': 'ra đời, sinh ra',
'传真': 'bản fax',
'打扰': 'làm phiền',
'打印': 'in ấn',
'大概': 'khoảng, đại khái',
'大使馆': 'đại sứ quán',
'大约': 'khoảng chừng',
'代表': 'đại diện, đại biểu',
'代替': 'thay thế',
'当地': 'địa phương, bản địa',
'当时': 'lúc ấy, 당시',
'刀': 'con dao',
'到底': 'rốt cuộc',
'底': 'đáy, nền',
'地址': 'địa chỉ',
'调查': 'điều tra',
'动作': 'động tác',
'对话': 'đối thoại',
'发生': 'xảy ra',
'法律': 'pháp luật',
'翻译': 'biên dịch, phiên dịch',
'范围': 'phạm vi',
'方面': 'mặt, phương diện',
'放弃': 'từ bỏ',
'放暑假': 'nghỉ hè',
'份': 'suất, phần (lượng từ)',
'风景': 'phong cảnh',
'丰富': 'phong phú',
'负责': 'phụ trách',
'复印': 'phô-tô',
'复杂': 'phức tạp',
'干杯': 'cạn ly',
'干燥': 'khô hanh',
'感谢': 'cảm ơn',
'干': 'khô; làm',
'刚刚': 'vừa mới',
'工具': 'công cụ',
'工资': 'tiền lương',
'孤单': 'cô đơn',
'估计': 'ước tính',
'鼓掌': 'vỗ tay',
'故意': 'cố ý',
'挂': 'treo',
'关键': 'then chốt',
'观众': 'khán giả',
'逛': 'đi dạo',
'规定': 'quy định',
'过程': 'quá trình',
'汗': 'mồ hôi',
'航班': 'chuyến bay',
'合格': 'đạt chuẩn',
'合适': 'phù hợp',
'盒子': 'cái hộp',
'后悔': 'hối hận',
'后来': 'sau này',
'回忆': 'hồi tưởng',
'获得': 'giành được',
'基础': 'nền tảng',
'激动': 'xúc động',
'积极': 'tích cực',
'积累': 'tích lũy',
'集合': 'tập hợp',
'技术': 'kỹ thuật',
'家具': 'đồ nội thất',
'加油站': 'trạm xăng',
'假': 'giả',
'坚持': 'kiên trì',
'减少': 'giảm bớt',
'奖金': 'tiền thưởng',
'降低': 'hạ xuống',
'交流': 'giao lưu, trao đổi',
'交通': 'giao thông',
'骄傲': 'kiêu ngạo; tự hào',
'教育': 'giáo dục',
'接受': 'tiếp nhận',
'节约': 'tiết kiệm',
'结果': 'kết quả',
'解释': 'giải thích',
'进行': 'tiến hành',
'精彩': 'xuất sắc, đặc sắc',
'精神': 'tinh thần',
'京剧': 'kinh kịch',
'竟然': 'không ngờ',
'举办': 'tổ chức',
'棵': 'cây (lượng từ cây cối)',
'可怜': 'đáng thương',
'可惜': 'tiếc quá',
'肯定': 'chắc chắn',
'空气': 'không khí',
'恐怕': 'e rằng, sợ rằng',
'宽': 'rộng',
'垃圾桶': 'thùng rác',
'来不及': 'không kịp',
'来得及': 'kịp, còn kịp',
'懒': 'lười',
'浪漫': 'lãng mạn',
'冷静': 'bình tĩnh',
'礼貌': 'lễ phép',
'理发': 'cắt tóc',
'厉害': 'giỏi; dữ dội, kinh khủng',
'力气': 'sức lực',
'俩': 'hai (khẩu ngữ)',
'连': 'nối, liền; cả... cũng...',
'联系': 'liên hệ',
'凉快': 'mát mẻ',
'聊天': 'tán gẫu',
'留学': 'du học',
'流泪': 'rơi lệ',
'流利': 'lưu loát',
'流行': 'thịnh hành, lan rộng',
'乱': 'lộn xộn',
'律师': 'luật sư',
'密码': 'mật mã',
'民族': 'dân tộc',
'难受': 'khó chịu',
'内容': 'nội dung',
'能力': 'năng lực',
'年龄': 'tuổi',
'排列': 'sắp xếp',
'脾气': 'tính khí',
'篇': 'bài, thiên (lượng từ bài văn)',
'骗': 'lừa gạt',
'破': 'vỡ, rách',
'普遍': 'phổ biến',
'千万': 'mười triệu; nhất định phải',
'巧克力': 'sô-cô-la',
'轻松': 'nhẹ nhõm',
'情况': 'tình hình',
'请假': 'xin nghỉ phép',
'穷': 'nghèo; cùng cực',
'区别': 'phân biệt, khác biệt',
'缺少': 'thiếu',
'热闹': 'nhộn nhịp',
'人民币': 'nhân dân tệ',
'任务': 'nhiệm vụ',
'日记': 'nhật ký',
'商量': 'bàn bạc',
})

# Dot fix chat luong (review toan bo gloss 2026-09-24): nghia HSK dung.
OVERRIDES.update({
'别': 'đừng',
'长': 'dài',
'穿': 'mặc (quần áo)',
'次': 'lần, lượt',
'号': 'số; ngày (trong tháng)',
'两': 'hai',
'跑步': 'chạy bộ',
'便宜': 'rẻ',
'起床': 'thức dậy',
'手表': 'đồng hồ đeo tay',
'希望': 'hy vọng',
'一起': 'cùng nhau',
'鱼': 'cá',
'早上': 'buổi sáng (sớm)',
'张': 'tờ, tấm (lượng từ)',
'找': 'tìm',
'牛奶': 'sữa bò',
'去年': 'năm ngoái',
'准备': 'chuẩn bị',
'生病': 'ốm, bị bệnh',
'玩': 'chơi',
'告诉': 'nói cho biết, bảo',
'考试': 'thi, dự thi',
'包': 'gói; túi',
'饱': 'ăn no',
'当然': 'đương nhiên',
'锻炼': 'rèn luyện (thể dục)',
'发烧': 'sốt',
'关': 'đóng; liên quan',
'果汁': 'nước ép hoa quả',
'经常': 'thường xuyên',
'举行': 'tổ chức (họp, lễ)',
'练习': 'luyện tập',
'拿': 'cầm, lấy',
'努力': 'nỗ lực',
'上网': 'lên mạng',
'叔叔': 'chú',
'提高': 'nâng cao',
'相信': 'tin tưởng',
'小心': 'cẩn thận',
'爷爷': 'ông nội',
'一会儿': 'một lát',
'以为': 'cho rằng, tưởng là',
'越': 'vượt qua; (càng... càng...)',
'表演': 'biểu diễn',
'打扫': 'quét dọn',
'季节': 'mùa',
'久': 'lâu',
'双': 'đôi',
'故事': 'câu chuyện',
'短': 'ngắn',
'担心': 'lo lắng',
'才': 'tài năng; vừa mới',
'当时': 'lúc ấy',
'暗': 'tối, u ám',
'按时': 'đúng giờ',
'博士': 'tiến sĩ',
'长城': 'Vạn Lý Trường Thành',
'场': 'nơi, bãi',
'出差': 'đi công tác',
'出发': 'xuất phát',
'打针': 'tiêm (thuốc)',
'戴': 'đeo, đội',
'导游': 'hướng dẫn viên du lịch',
'得意': 'đắc ý',
'等': 'đợi; hạng',
'对': 'đúng; đôi; với',
'反对': 'phản đối',
'符合': 'phù hợp',
'感动': 'cảm động',
'感觉': 'cảm giác',
'感情': 'tình cảm',
'寄': 'gửi',
'交': 'giao, nộp',
'共同': 'chung',
'够': 'đủ',
'光': 'ánh sáng',
'好像': 'hình như',
'寒假': 'nghỉ đông',
'火': 'lửa',
'活动': 'hoạt động',
'经历': 'trải qua',
'究竟': 'rốt cuộc',
'看法': 'cách nhìn, quan điểm',
'考虑': 'cân nhắc',
'满': 'đầy',
'理想': 'lý tưởng',
'例如': 'ví dụ như',
'留': 'ở lại, giữ lại',
'免费': 'miễn phí',
'耐心': 'kiên nhẫn',
'受到': 'nhận được',
'收入': 'thu nhập',
'收拾': 'dọn dẹp',
'熟悉': 'quen thuộc',
'硕士': 'thạc sĩ',
'算': 'tính, coi như',
'随便': 'tùy ý, tùy tiện',
'挺': 'khá, rất; thẳng',
'通过': 'thông qua',
'组成': 'tạo thành',
'支持': 'ủng hộ',
'值得': 'đáng',
'中文': 'tiếng Trung',
'重点': 'trọng điểm',
'重视': 'coi trọng',
'主动': 'chủ động',
'主意': 'chủ ý, ý kiến',
'深': 'sâu',
'请客': 'mời (ăn uống)',
'现代': 'hiện đại',
'行': 'hàng; nghề; được',
'性格': 'tính cách',
'修': 'sửa chữa',
'以': 'bằng, lấy (dùng)',
'引起': 'gây ra',
'饮料': 'đồ uống',
'辛苦': 'vất vả',
'硬': 'cứng',
'由': 'do, bởi',
'增加': 'tăng thêm',
'增长': 'tăng trưởng',
'起飞': 'cất cánh',
'散步': 'đi dạo',
'生命': 'sinh mệnh, sự sống',
'省': 'tỉnh; tiết kiệm',
'失败': 'thất bại',
'烦恼': 'buồn phiền',
})

# Dot fix 2 (review M-source 2026-09-24).
OVERRIDES.update({
'阿姨': 'dì, cô (gọi phụ nữ trung niên)',
'啊': 'trợ từ cảm thán (a, à)',
'搬': 'chuyển (nhà, đồ)',
'班': 'lớp; ca (làm việc)',
'聪明': 'thông minh',
'段': 'đoạn',
'多么': 'biết bao',
'饿': 'đói',
'害怕': 'sợ hãi',
'还是': 'hoặc (câu hỏi); vẫn',
'经过': 'đi qua; trải qua',
'空调': 'điều hòa',
'使': 'khiến, làm cho',
'站': 'trạm; đứng',
'米': 'gạo; mét',
'位': 'chỗ, vị',
'先': 'trước',
'认为': 'cho rằng',
'祝': 'chúc',
'件': 'cái, chiếc (lượng từ)',
'门': 'cửa',
'晴': 'nắng ráo',
'送': 'tặng; tiễn; đưa',
'题': 'đề, câu hỏi',
'运动': 'thể thao, vận động',
'放': 'đặt, để; thả',
'分': 'chia; phút (điểm số)',
'答案': 'đáp án',
'打扮': 'ăn diện',
'打折': 'giảm giá',
'当': 'làm, đảm nhiệm',
'反映': 'phản ánh',
'访问': 'thăm (chính thức)',
'高级': 'cao cấp',
'管理': 'quản lý',
'果然': 'quả nhiên',
'害羞': 'ngượng ngùng',
'及时': 'kịp thời',
'镜子': 'gương',
'开玩笑': 'nói đùa',
'减肥': 'giảm cân',
'辣': 'cay',
'麻烦': 'phiền phức',
'申请': 'nộp đơn xin',
'师傅': 'sư phụ, thợ cả',
'食品': 'thực phẩm',
'填空': 'điền vào chỗ trống',
'提前': 'sớm hơn, trước',
'通知': 'thông báo',
'完全': 'hoàn toàn',
'往': 'hướng về',
'往往': 'thường thường',
'无论': 'bất luận... gì',
'相反': 'ngược lại',
'效果': 'hiệu quả',
'醒': 'tỉnh dậy',
'演出': 'biểu diễn',
'演员': 'diễn viên',
'叶子': 'lá',
'意见': 'ý kiến',
'赢': 'thắng',
'原来': 'thì ra, vốn dĩ',
'只要': 'chỉ cần',
'至少': 'ít nhất',
'总结': 'tổng kết',
'座': 'ngọn, tòa (lượng từ)',
'做生意': 'buôn bán',
'撞': 'đâm, va',
'准时': 'đúng giờ',
'自然': 'tự nhiên',
'专门': 'chuyên (môn)',
'真正': 'thật sự',
'正常': 'bình thường',
'正好': 'vừa khéo',
'正式': 'chính thức',
'知识': 'tri thức',
})

OVERRIDES.update({'旅游': 'du lịch'})

def main():
    clem_by, drk = {}, {}
    for n in (2, 3, 4):
        cl = json.loads((RAW / "clem109" / ("hsk-vocab-json/hsk-level-%d.json" % n)).read_text(encoding="utf-8"))
        d = collections.defaultdict(list)
        for e in cl:
            d[e["hanzi"]].append(to_num(e["pinyin"]))
        clem_by[n] = d
        drk[n] = {e["simplified"]: e for e in
                  json.loads((RAW / ("drk-old-%d.json" % n)).read_text(encoding="utf-8"))}
    seen, rows = set(), []
    for n in (2, 3, 4):
        cl = json.loads((RAW / "clem109" / ("hsk-vocab-json/hsk-level-%d.json" % n)).read_text(encoding="utf-8"))
        for e in cl:
            if e["hanzi"] in seen:
                continue
            seen.add(e["hanzi"])
            s = sense(e)
            py = pick_pinyin(e["hanzi"], n, drk[n][e["hanzi"]], clem_by[n][e["hanzi"]])
            g = OVERRIDES.get(e["hanzi"])
            if g is None:
                g, un, _ = translate(s)
                assert not un and g, (n, e["hanzi"], s, un)
            tone = " ".join(ch for ch in py if ch.isdigit())
            assert len(py.split()) == len(tone.split()), (n, e["hanzi"], py)
            assert tone and all(c in "12345" for c in tone.split()), (n, e["hanzi"], tone)
            rows.append((n, e["hanzi"], py, tone, g))
    counts = collections.Counter(n for n, _, _, _, _ in rows)
    assert dict(counts) == {2: 147, 3: 298, 4: 598}, dict(counts)

    def gs(s):
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    levels = collections.defaultdict(list)
    for (n, hz, py, tone, g) in rows:
        levels[n].append((hz, py, g, tone))
    dest = REPO / "api" / "hsk_seed_l234.go"
    with io.open(dest, "w", encoding="utf-8") as f:
        f.write("package main\n\n")
        f.write("// T8.1 — seed HSK 2.0 L2-L4 (1043 tu unique theo hanzi+level).\n")
        f.write("// Sinh boi scripts/seed_hsk.py — khong sua tay (sua script roi chay lai).\n")
        f.write("// Nguon: drkameleon/complete-hsk-vocabulary (MIT, Copyright (c) 2026 Yanis Zafir\u00f3pulos);\n")
        f.write("// doi chieu clem109/hsk-vocabulary (MIT, Copyright (c) 2018 Clement Venard);\n")
        f.write("// pinyin tham khao CC-CEDICT (CC BY-SA 4.0), nghia Viet nhom tu soan.\n\n")
        for n in (2, 3, 4):
            f.write("// hsk%dSeed: %d tu HSK%d.\n" % (n, len(levels[n]), n))
            f.write("var hsk%dSeed = []HskEntry{\n" % n)
            for (hz, py, g, tone) in levels[n]:
                f.write("\t{%s, %s, %s, \"HSK%d\", %s},\n" % (gs(hz), gs(py), gs(g), n, gs(tone)))
            f.write("}\n\n")
        f.write("// hskSeedByLevel tra seed theo level (HSK1 nam trong chinese_hsk.go — giu 36 tu).\n")
        f.write("func hskSeedByLevel(level string) []HskEntry {\n")
        f.write('\tswitch level {\n\tcase "HSK2":\n\t\treturn hsk2Seed\n')
        f.write('\tcase "HSK3":\n\t\treturn hsk3Seed\n\tcase "HSK4":\n\t\treturn hsk4Seed\n')
        f.write("\tdefault:\n\t\treturn nil\n\t}\n}\n")
    print("SeedHSK OK: %d entries -> %s" % (len(rows), dest))


if __name__ == "__main__":
    sys.exit(main())
