package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"langapp/internal/transport/graphql/generated"
	"langapp/internal/transport/graphql/model"
)

// Stages is the resolver for the stages field.
func (r *pathResolver) Stages(ctx context.Context, obj *model.Path) ([]model.Stage, error) {
	views, err := r.loaders(ctx).LoadStages(ctx, parseID(obj.ID))
	if err != nil {
		return nil, err
	}
	out := make([]model.Stage, 0, len(views))
	for _, sv := range views {
		out = append(out, stageView(sv.Stage))
	}
	return out, nil
}

// Progress is the resolver for the progress field.
func (r *pathResolver) Progress(ctx context.Context, obj *model.Path) (*model.Progress, error) {
	prog, err := r.loaders(ctx).LoadProgress(ctx, parseID(obj.ID))
	if err != nil {
		return nil, err
	}
	return progressView(prog), nil
}

// Topics is the resolver for the topics field.
func (r *stageResolver) Topics(ctx context.Context, obj *model.Stage) ([]model.Topic, error) {
	views, err := stageTopics(ctx, r.loaders(ctx), parseID(obj.PathID), parseID(obj.ID))
	if err != nil {
		return nil, err
	}
	out := make([]model.Topic, 0, len(views))
	for _, sv := range views {
		for _, tv := range sv.Topics {
			out = append(out, topicView(tv.Topic))
		}
	}
	return out, nil
}

// Milestones is the resolver for the milestones field.
func (r *stageResolver) Milestones(ctx context.Context, obj *model.Stage) ([]model.Milestone, error) {
	views, err := stageTopics(ctx, r.loaders(ctx), parseID(obj.PathID), parseID(obj.ID))
	if err != nil {
		return nil, err
	}
	out := []model.Milestone{}
	// `stageTopics` lọc theo stageID nên trả ≤1 StageView. Vòng lặp thay vì
	// index trực tiếp để hàm này không phụ thuộc vào việc hàm kia có lọc hay
	// không — lệch 1 chỗ là 500 cho cả cây.
	for _, sv := range views {
		for _, m := range sv.Milestones {
			out = append(out, milestoneView(m))
		}
	}
	return out, nil
}

// Deck is the resolver for the deck field.
func (r *stageResolver) Deck(ctx context.Context, obj *model.Stage) (*model.DeckRef, error) {
	if obj.DeckID == nil {
		return nil, nil
	}
	ref, err := r.loaders(ctx).LoadDeck(ctx, parseID(*obj.DeckID))
	if err != nil {
		return nil, err
	}
	return deckRefView(ref), nil
}

// activityList tách cột `activities` (JSON array string) thành mảng —
// `decodeActivities` giải thích vì sao JSON hỏng không được làm hỏng cả cây.
func (r *topicResolver) ActivityList(ctx context.Context, obj *model.Topic) ([]string, error) {
	return decodeActivities(obj.Activities), nil
}

// Level đọc bảng bên cạnh do `stageTopics` điền — xem `Loaders.topicMeta`.
// KHÔNG tính ở đây: luật thuộc `domain/roadmap.LevelStates`, đã chạy 1 lần cho
// cả stage trong application service. Tính lần thứ hai ở resolver là 2 bản luật
// trôi khỏi nhau — loại bug đã xảy ra ở M2 khi ghép layout theo chỉ số thay vì
// theo id.
func (r *topicResolver) Level(ctx context.Context, obj *model.Topic) (model.LevelState, error) {
	meta := r.loaders(ctx).TopicMeta(parseID(obj.ID))
	return levelOf(string(meta.Level)), nil
}

// Point is the resolver for the point field.
func (r *topicResolver) Point(ctx context.Context, obj *model.Topic) (*model.MapPoint, error) {
	p := r.loaders(ctx).TopicMeta(parseID(obj.ID)).Point
	return &model.MapPoint{X: p.X, Y: p.Y}, nil
}

// MapPinned is the resolver for the mapPinned field.
func (r *topicResolver) MapPinned(ctx context.Context, obj *model.Topic) (bool, error) {
	return r.loaders(ctx).TopicMeta(parseID(obj.ID)).MapPinned, nil
}

// Resources is the resolver for the resources field.
func (r *topicResolver) Resources(ctx context.Context, obj *model.Topic) ([]model.Resource, error) {
	rows, err := r.loaders(ctx).LoadResources(ctx, parseID(obj.ID))
	if err != nil {
		return nil, err
	}
	out := make([]model.Resource, 0, len(rows))
	for _, res := range rows {
		out = append(out, resourceView(res))
	}
	return out, nil
}

// Path returns generated.PathResolver implementation.
func (r *Resolver) Path() generated.PathResolver { return &pathResolver{r} }

// Stage returns generated.StageResolver implementation.
func (r *Resolver) Stage() generated.StageResolver { return &stageResolver{r} }

// Topic returns generated.TopicResolver implementation.
func (r *Resolver) Topic() generated.TopicResolver { return &topicResolver{r} }

type (
	pathResolver  struct{ *Resolver }
	stageResolver struct{ *Resolver }
	topicResolver struct{ *Resolver }
)
