package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	roadmapapp "langapp/internal/application/roadmap"
	srsapp "langapp/internal/application/srs"
	"langapp/internal/transport/graphql/generated"
	"langapp/internal/transport/graphql/model"
)

// CreateDeck is the resolver for the createDeck field.
func (r *mutationResolver) CreateDeck(ctx context.Context, name string, lang *string) (*model.CreateDeckPayload, error) {
	d, err := r.SRS.CreateDeck(ctx, name, derefOr(lang, ""))
	if err != nil {
		return &model.CreateDeckPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := deckView(d)
	return &model.CreateDeckPayload{Ok: true, Deck: &out}, nil
}

// DeleteDeck is the resolver for the deleteDeck field.
func (r *mutationResolver) DeleteDeck(ctx context.Context, id string) (*model.DeleteDeckPayload, error) {
	if err := r.SRS.DeleteDeck(ctx, parseID(id)); err != nil {
		return &model.DeleteDeckPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DeleteDeckPayload{Ok: true}, nil
}

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, deckID string, input model.CardInput) (*model.CreateCardPayload, error) {
	c, err := r.SRS.CreateCard(ctx, parseID(deckID), srsapp.CardInput{
		Front: input.Front, Back: input.Back, Pinyin: input.Pinyin,
	})
	if err != nil {
		return &model.CreateCardPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := cardView(c)
	return &model.CreateCardPayload{Ok: true, Card: &out}, nil
}

// UpdateCard is the resolver for the updateCard field.
func (r *mutationResolver) UpdateCard(ctx context.Context, id string, patch model.CardPatch) (*model.UpdateCardPayload, error) {
	c, err := r.SRS.UpdateCard(ctx, parseID(id), srsapp.CardPatch{
		Front: patch.Front, Back: patch.Back, Pinyin: patch.Pinyin,
	})
	if err != nil {
		return &model.UpdateCardPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := cardView(c)
	return &model.UpdateCardPayload{Ok: true, Card: &out}, nil
}

// DeleteCard is the resolver for the deleteCard field.
func (r *mutationResolver) DeleteCard(ctx context.Context, id string) (*model.DeleteCardPayload, error) {
	if err := r.SRS.DeleteCard(ctx, parseID(id)); err != nil {
		return &model.DeleteCardPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DeleteCardPayload{Ok: true}, nil
}

// RecordReview is the resolver for the recordReview field.
func (r *mutationResolver) RecordReview(ctx context.Context, input model.ReviewInput) (*model.RecordReviewPayload, error) {
	res, err := r.SRS.RecordReview(ctx, srsapp.ReviewInput{
		CardID: parseID(input.CardID), Grade: input.Grade,
	})
	if err != nil {
		return &model.RecordReviewPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.RecordReviewPayload{Ok: true, Review: reviewView(res)}, nil
}

// SetCardTone chỉ GHI tone đã chấm. Bước chấm là `content.gradeTone` — 2 use case
// của 2 context, tách bạch để client có thể chấm thử mà không ghi (drill).
func (r *mutationResolver) SetCardTone(ctx context.Context, id string, tone *string) (*model.SetCardTonePayload, error) {
	c, err := r.SRS.SetCardTone(ctx, parseID(id), tone)
	if err != nil {
		return &model.SetCardTonePayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := cardView(c)
	return &model.SetCardTonePayload{Ok: true, Card: &out}, nil
}

// ImportHsk is the resolver for the importHSK field.
func (r *mutationResolver) ImportHsk(ctx context.Context, input *model.ImportHSKInput) (*model.ImportHSKPayload, error) {
	in := contentImportInput{}
	if input != nil {
		in = contentImportInput{Level: derefOr(input.Level, ""), Deck: derefOr(input.Deck, "")}
	}
	res, err := r.Content.ImportHSK(ctx, in.toApp())
	if err != nil {
		return &model.ImportHSKPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.ImportHSKPayload{Ok: true, Result: importResultView(res)}, nil
}

// SeedEnglish is the resolver for the seedEnglish field.
func (r *mutationResolver) SeedEnglish(ctx context.Context) (*model.SeedEnglishPayload, error) {
	res, err := r.Content.SeedEnglish(ctx)
	if err != nil {
		return &model.SeedEnglishPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.SeedEnglishPayload{Ok: true, Result: &model.EnglishSeedResult{
		EnDict: res.EnDict, PvoAdded: res.PVOAdded, TmrndAdded: res.TMRNDAdded,
	}}, nil
}

// UpsertDictEntry is the resolver for the upsertDictEntry field.
func (r *mutationResolver) UpsertDictEntry(ctx context.Context, input model.DictEntryInput) (*model.UpsertDictPayload, error) {
	entry, created, err := r.Content.UpsertDictEntry(ctx, contentZHEntry(input))
	if err != nil {
		return &model.UpsertDictPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.UpsertDictPayload{
		Ok:      true,
		Created: created,
		Entry:   &model.DictEntry{Hanzi: entry.Hanzi, Pinyin: entry.Pinyin, Nghia: entry.Nghia},
	}, nil
}

// SetTone là CHẤM rồi GHI trong 1 lần gọi: `content` chấm (bảng thang điệu),
// `srs` ghi vào `cards.tone`. Đây là đường 1 bước cho client; `gradeTone` +
// `setCardTone` là đường 2 bước cho UI muốn chấm thử trước khi lưu.
func (r *mutationResolver) SetTone(ctx context.Context, cardID string, tone string) (*model.SetTonePayload, error) {
	written, err := r.Content.SetTone(ctx, parseID(cardID), tone)
	if err != nil {
		return &model.SetTonePayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.SetTonePayload{Ok: true, CardID: cardID, Tone: &written}, nil
}

// AppendThieu is the resolver for the appendThieu field.
func (r *mutationResolver) AppendThieu(ctx context.Context, input model.ThieuInput) (*model.AppendThieuPayload, error) {
	in := contentThieuInput{Session: derefOr(input.Session, ""), Note: derefOr(input.Note, ""), Scores: map[string]int{}}
	for _, s := range input.Scores {
		in.Scores[s.Axis] = s.Value
	}
	session, err := r.Content.AppendThieu(ctx, in.toApp())
	if err != nil {
		return &model.AppendThieuPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := thieuSessionView(session)
	return &model.AppendThieuPayload{Ok: true, Session: &out}, nil
}

// CreatePath is the resolver for the createPath field.
func (r *mutationResolver) CreatePath(ctx context.Context, input model.PathInput) (*model.CreatePathPayload, error) {
	p, err := r.Roadmap.CreatePath(ctx, roadmapapp.PathInput{
		Slug:     input.Slug,
		Title:    input.Title,
		Overview: derefOr(input.Overview, ""),
		Language: derefOr(input.Language, ""),
	})
	if err != nil {
		return &model.CreatePathPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := pathView(p)
	return &model.CreatePathPayload{Ok: true, Path: &out}, nil
}

// UpdatePath is the resolver for the updatePath field.
func (r *mutationResolver) UpdatePath(ctx context.Context, slug string, patch model.PathPatch) (*model.UpdatePathPayload, error) {
	p, err := r.Roadmap.UpdatePath(ctx, slug, roadmapapp.PathPatch{
		Title: patch.Title, Overview: patch.Overview, Language: patch.Language,
	})
	if err != nil {
		return &model.UpdatePathPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := pathView(p)
	return &model.UpdatePathPayload{Ok: true, Path: &out}, nil
}

// DeletePath is the resolver for the deletePath field.
func (r *mutationResolver) DeletePath(ctx context.Context, slug string) (*model.DeletePathPayload, error) {
	if err := r.Roadmap.DeletePath(ctx, slug); err != nil {
		return &model.DeletePathPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DeletePathPayload{Ok: true}, nil
}

// CreateStage is the resolver for the createStage field.
func (r *mutationResolver) CreateStage(ctx context.Context, pathSlug string, input model.StageInput) (*model.CreateStagePayload, error) {
	// terrain/direction KHÔNG gửi = để lấy DEFAULT của cột. `terrainText`
	// trả "" cho MEADOW vì đó là DEFAULT — gửi "meadow" cho mọi stage sẽ thêm
	// dữ liệu vô nghĩa vào lịch sử merge. Giá trị KHÔNG map được thì 400, không
	// rơi về DEFAULT (xem `terrainText`).
	terrain, err := terrainText(input.Terrain)
	if err != nil {
		return &model.CreateStagePayload{Ok: false, Error: toUserError(err)}, nil
	}
	direction, err := directionText(input.Direction)
	if err != nil {
		return &model.CreateStagePayload{Ok: false, Error: toUserError(err)}, nil
	}
	in := roadmapapp.StageInput{
		Slug: input.Slug, Title: input.Title, Goal: derefOr(input.Goal, ""),
		Position: input.Position, DurationWeeks: input.DurationWeeks,
		DeckID:    parseIDPtr(input.DeckID),
		Terrain:   terrain,
		Direction: direction,
	}
	if input.Status != nil {
		v := statusText(*input.Status)
		in.Status = &v
	}

	st, err := r.Roadmap.CreateStage(ctx, pathSlug, in)
	if err != nil {
		return &model.CreateStagePayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := stageView(st)
	return &model.CreateStagePayload{Ok: true, Stage: &out}, nil
}

// UpdateStage is the resolver for the updateStage field.
func (r *mutationResolver) UpdateStage(ctx context.Context, id string, patch model.StagePatch) (*model.UpdateStagePayload, error) {
	p := roadmapapp.StagePatch{
		Title: patch.Title, Goal: patch.Goal, Position: patch.Position,
		DurationWeeks: patch.DurationWeeks, DeckID: parseIDPtr(patch.DeckID),
	}
	// `terrain`/`direction` nil = KHÔNG đụng; enum không có giá trị "unset"
	// nên "không gửi" chính là nil của input. Giá trị gửi lên mà `switch` không
	// map được ⇒ 400, KHÔNG rơi về DEFAULT (xem `terrainText`).
	if patch.Terrain != nil {
		v, err := terrainText(patch.Terrain)
		if err != nil {
			return &model.UpdateStagePayload{Ok: false, Error: toUserError(err)}, nil
		}
		p.Terrain = &v
	}
	if patch.Direction != nil {
		v, err := directionText(patch.Direction)
		if err != nil {
			return &model.UpdateStagePayload{Ok: false, Error: toUserError(err)}, nil
		}
		p.Direction = &v
	}
	st, err := r.Roadmap.UpdateStage(ctx, parseID(id), p)
	if err != nil {
		return &model.UpdateStagePayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := stageView(st)
	return &model.UpdateStagePayload{Ok: true, Stage: &out}, nil
}

// DeleteStage is the resolver for the deleteStage field.
func (r *mutationResolver) DeleteStage(ctx context.Context, id string) (*model.DeleteStagePayload, error) {
	if err := r.Roadmap.DeleteStage(ctx, parseID(id)); err != nil {
		return &model.DeleteStagePayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DeleteStagePayload{Ok: true}, nil
}

// SetStageStatus is the resolver for the setStageStatus field.
func (r *mutationResolver) SetStageStatus(ctx context.Context, id string, input model.StatusInput) (*model.SetStageStatusPayload, error) {
	status := statusText(input.Status)
	note := derefOr(input.StatusNote, "")
	st, err := r.Roadmap.SetStageStatus(ctx, parseID(id), &status, &note)
	if err != nil {
		return &model.SetStageStatusPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := stageView(st)
	return &model.SetStageStatusPayload{Ok: true, Stage: &out}, nil
}

// CreateTopic is the resolver for the createTopic field.
func (r *mutationResolver) CreateTopic(ctx context.Context, stageID string, input model.TopicInput) (*model.CreateTopicPayload, error) {
	t, err := r.Roadmap.CreateTopic(ctx, parseID(stageID), roadmapapp.TopicInput{
		Title: input.Title, Why: derefOr(input.Why, ""),
		Activities: orEmpty(input.Activities), Position: input.Position,
		IsOptional: input.IsOptional, MapX: input.MapX, MapY: input.MapY,
	})
	if err != nil {
		return &model.CreateTopicPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := topicView(t)
	return &model.CreateTopicPayload{Ok: true, Topic: &out}, nil
}

// UpdateTopic is the resolver for the updateTopic field.
func (r *mutationResolver) UpdateTopic(ctx context.Context, id string, patch model.TopicPatch) (*model.UpdateTopicPayload, error) {
	p := roadmapapp.TopicPatch{
		Title: patch.Title, Why: patch.Why, Position: patch.Position,
		IsOptional: patch.IsOptional, MapX: patch.MapX, MapY: patch.MapY,
		ClearMap: patch.ClearMap != nil && *patch.ClearMap,
	}
	// `activities` là `[]string` không phải `[]string?` vì `*[]string` của
	// application phân biệt "không gửi" với "gửi mảng rỗng" — cần giữ nguyên
	// để `UpdateTopic` không coi patch không đổi activities là xoá sạch.
	if patch.Activities != nil {
		v := patch.Activities
		p.Activities = &v
	}
	t, err := r.Roadmap.UpdateTopic(ctx, parseID(id), p)
	if err != nil {
		return &model.UpdateTopicPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := topicView(t)
	return &model.UpdateTopicPayload{Ok: true, Topic: &out}, nil
}

// DeleteTopic is the resolver for the deleteTopic field.
func (r *mutationResolver) DeleteTopic(ctx context.Context, id string) (*model.DeleteTopicPayload, error) {
	if err := r.Roadmap.DeleteTopic(ctx, parseID(id)); err != nil {
		return &model.DeleteTopicPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DeleteTopicPayload{Ok: true}, nil
}

// SetTopicStatus is the resolver for the setTopicStatus field.
func (r *mutationResolver) SetTopicStatus(ctx context.Context, id string, input model.StatusInput) (*model.SetTopicStatusPayload, error) {
	status := statusText(input.Status)
	note := derefOr(input.StatusNote, "")
	t, err := r.Roadmap.SetTopicStatus(ctx, parseID(id), &status, &note)
	if err != nil {
		return &model.SetTopicStatusPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := topicView(t)
	return &model.SetTopicStatusPayload{Ok: true, Topic: &out}, nil
}

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, topicID string, input model.ResourceInput) (*model.CreateResourcePayload, error) {
	res, err := r.Roadmap.CreateResource(ctx, parseID(topicID), roadmapapp.ResourceInput{
		Title: input.Title, URL: input.URL, Kind: resourceKindText(input.Kind),
		Note: derefOr(input.Note, ""), Position: input.Position,
	})
	if err != nil {
		return &model.CreateResourcePayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := resourceView(res)
	return &model.CreateResourcePayload{Ok: true, Resource: &out}, nil
}

// UpdateResource is the resolver for the updateResource field.
func (r *mutationResolver) UpdateResource(ctx context.Context, id string, patch model.ResourcePatch) (*model.UpdateResourcePayload, error) {
	p := roadmapapp.ResourcePatch{
		Title: patch.Title, URL: patch.URL, Note: patch.Note, Position: patch.Position,
		// `clearUrl` là `Boolean` có default false trong schema ⇒ model sinh ra
		// `*bool`; `false` phải giữ nguyên nghĩa "không xoá link".
		ClearURL: patch.ClearURL != nil && *patch.ClearURL,
	}
	if patch.Kind != nil {
		v := resourceKindText(patch.Kind)
		p.Kind = &v
	}
	res, err := r.Roadmap.UpdateResource(ctx, parseID(id), p)
	if err != nil {
		return &model.UpdateResourcePayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := resourceView(res)
	return &model.UpdateResourcePayload{Ok: true, Resource: &out}, nil
}

// DeleteResource is the resolver for the deleteResource field.
func (r *mutationResolver) DeleteResource(ctx context.Context, id string) (*model.DeleteResourcePayload, error) {
	if err := r.Roadmap.DeleteResource(ctx, parseID(id)); err != nil {
		return &model.DeleteResourcePayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DeleteResourcePayload{Ok: true}, nil
}

// CreateMilestone is the resolver for the createMilestone field.
func (r *mutationResolver) CreateMilestone(ctx context.Context, stageID string, input model.MilestoneInput) (*model.CreateMilestonePayload, error) {
	m, err := r.Roadmap.CreateMilestone(ctx, parseID(stageID), roadmapapp.MilestoneInput{
		Text: input.Text, Position: input.Position,
	})
	if err != nil {
		return &model.CreateMilestonePayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := milestoneView(m)
	return &model.CreateMilestonePayload{Ok: true, Milestone: &out}, nil
}

// UpdateMilestone is the resolver for the updateMilestone field.
func (r *mutationResolver) UpdateMilestone(ctx context.Context, id string, patch model.MilestonePatch) (*model.UpdateMilestonePayload, error) {
	m, err := r.Roadmap.UpdateMilestone(ctx, parseID(id), roadmapapp.MilestonePatch{
		Text: patch.Text, Position: patch.Position,
	})
	if err != nil {
		return &model.UpdateMilestonePayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := milestoneView(m)
	return &model.UpdateMilestonePayload{Ok: true, Milestone: &out}, nil
}

// DeleteMilestone is the resolver for the deleteMilestone field.
func (r *mutationResolver) DeleteMilestone(ctx context.Context, id string) (*model.DeleteMilestonePayload, error) {
	if err := r.Roadmap.DeleteMilestone(ctx, parseID(id)); err != nil {
		return &model.DeleteMilestonePayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DeleteMilestonePayload{Ok: true}, nil
}

// CreateBookmark is the resolver for the createBookmark field.
func (r *mutationResolver) CreateBookmark(ctx context.Context, input model.BookmarkInput) (*model.CreateBookmarkPayload, error) {
	// `status` không gửi → `bookmarkStatusText(nil)` trả `""` → `ValidateBookmarkStatus("")`
	// gán DEFAULT `to_read` ở tầng application. Không gán sẵn `TO_READ` ở đây
	// được vì khi đó `nil` (không gửi) và giá trị lạ sẽ cùng đi qua 1 nhánh.
	status, err := bookmarkStatusText(input.Status)
	if err != nil {
		return &model.CreateBookmarkPayload{Ok: false, Error: toUserError(err)}, nil
	}
	// `tags: null` và `tags: []` cho cùng kết quả ở CreateBookmark (mảng rỗng
	// không giữ tag nào) — khác `updateBookmark`, xem chỗ đó.
	b, err := r.Roadmap.CreateBookmark(ctx, roadmapapp.BookmarkInput{
		Title: input.Title, URL: input.URL, Note: derefOr(input.Note, ""),
		Tags: input.Tags, Status: status,
	})
	if err != nil {
		return &model.CreateBookmarkPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := bookmarkView(b)
	return &model.CreateBookmarkPayload{Ok: true, Bookmark: &out}, nil
}

// UpdateBookmark is the resolver for the updateBookmark field.
func (r *mutationResolver) UpdateBookmark(ctx context.Context, id string, patch model.BookmarkPatch) (*model.UpdateBookmarkPayload, error) {
	patchIn := roadmapapp.BookmarkPatch{
		Title: patch.Title, URL: patch.URL, Note: patch.Note,
		ClearURL: patch.ClearURL != nil && *patch.ClearURL,
	}
	// `tags: []` và "không gửi tags" là 2 thứ khác nhau — client gửi mảng rỗng
	// là muốn XOÁ hết tag, nên phải giữ con trỏ xuống tầng application (null
	// trong JSON → `nil` ở đây, xem `UpdateTopic` với `activities`).
	if patch.Tags != nil {
		v := patch.Tags
		patchIn.Tags = &v
	}
	b, err := r.Roadmap.UpdateBookmark(ctx, parseID(id), patchIn)
	if err != nil {
		return &model.UpdateBookmarkPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := bookmarkView(b)
	return &model.UpdateBookmarkPayload{Ok: true, Bookmark: &out}, nil
}

// DeleteBookmark is the resolver for the deleteBookmark field.
func (r *mutationResolver) DeleteBookmark(ctx context.Context, id string) (*model.DeleteBookmarkPayload, error) {
	if err := r.Roadmap.DeleteBookmark(ctx, parseID(id)); err != nil {
		return &model.DeleteBookmarkPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DeleteBookmarkPayload{Ok: true}, nil
}

// SetBookmarkStatus is the resolver for the setBookmarkStatus field.
func (r *mutationResolver) SetBookmarkStatus(ctx context.Context, id string, status model.BookmarkStatus) (*model.SetBookmarkStatusPayload, error) {
	// `status` là tham số BẮT BUỘC (`BookmarkStatus!`) nên không có nhánh
	// `nil` — nhưng `bookmarkStatusText` vẫn phải trả lỗi cho giá trị lạ
	// thay vì rơi về `to_read`, xem lý do ở `convert.go`.
	text, err := bookmarkStatusText(&status)
	if err != nil {
		return &model.SetBookmarkStatusPayload{Ok: false, Error: toUserError(err)}, nil
	}
	b, err := r.Roadmap.SetBookmarkStatus(ctx, parseID(id), text)
	if err != nil {
		return &model.SetBookmarkStatusPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := bookmarkView(b)
	return &model.SetBookmarkStatusPayload{Ok: true, Bookmark: &out}, nil
}

// RecordShadowProgress is the resolver for the recordShadowProgress field.
func (r *mutationResolver) RecordShadowProgress(ctx context.Context, input model.ShadowProgressInput) (*model.ShadowProgressPayload, error) {
	p, err := r.Practice.RecordShadowProgress(ctx, parseID(input.CardID), input.Loops, input.Rate)
	if err != nil {
		return &model.ShadowProgressPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := shadowView(p)
	return &model.ShadowProgressPayload{Ok: true, Progress: &out}, nil
}

// AppendError is the resolver for the appendError field.
func (r *mutationResolver) AppendError(ctx context.Context, input model.AppendErrorInput) (*model.AppendErrorPayload, error) {
	e, err := r.Practice.AppendError(ctx, parseIDPtr(input.CardID), input.Expected, input.Transcript, orEmpty(input.Wrong))
	if err != nil {
		return &model.AppendErrorPayload{Ok: false, Error: toUserError(err)}, nil
	}
	views := errorEntryViews([]practiceErrorEntry{e})
	out := views[0]
	return &model.AppendErrorPayload{Ok: true, Entry: &out}, nil
}

// MarkErrorResolved is the resolver for the markErrorResolved field.
func (r *mutationResolver) MarkErrorResolved(ctx context.Context, errorID string) (*model.MarkErrorResolvedPayload, error) {
	noteID, err := r.Practice.MarkErrorResolved(ctx, parseID(errorID))
	if err != nil {
		return &model.MarkErrorResolvedPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.MarkErrorResolvedPayload{Ok: true, NoteID: idOf(noteID)}, nil
}

// Sync là mutation DUY NHẤT không theo mẫu payload `ok` + `error` — nó trả
// thẳng `MergeResult` vốn ĐÃ có sẵn cả `ok` lẫn `error` trong schema, vì
// `application/sync.MergeResult` mang `Warnings` + `Conflicts` mà client cần
// đọc cả khi merge LỖI (conflict phát sinh rồi rollback thì client vẫn phải
// biết). Bọc thêm 1 payload sẽ phải nhân bản 4 field.
func (r *mutationResolver) Sync(ctx context.Context) (*model.MergeResult, error) {
	// `r.Sync` là chính method này (mutationResolver có method `Sync`), nên
	// phải chỉ định `r.Resolver` để với tới service. Ghi rõ ở đây vì
	// `r.Sync.Sync(ctx)` nghe rất hợp lý rồi fail khi biên dịch.
	res, err := r.Resolver.Sync.Sync(ctx)
	return mergeResultView(res, err), nil
}

// Decks is the resolver for the decks field.
func (r *queryResolver) Decks(ctx context.Context) ([]model.Deck, error) {
	rows, err := r.SRS.ListDecks(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Deck, 0, len(rows))
	for _, d := range rows {
		out = append(out, deckView(d))
	}
	return out, nil
}

// Deck trả null (không phải lỗi) khi id không tồn tại: `deck(id:)` với id
// client tự dán là tình huống bình thường, và ép 404 ở đây biến câu hỏi
// thành lỗi cho 1 UI chỉ cần biết "không có".
func (r *queryResolver) Deck(ctx context.Context, id string) (*model.Deck, error) {
	rows, err := r.SRS.ListDecks(ctx)
	if err != nil {
		return nil, err
	}
	want := parseID(id)
	for _, d := range rows {
		if d.ID == want {
			out := deckView(d)
			return &out, nil
		}
	}
	return nil, nil
}

// Cards is the resolver for the cards field.
func (r *queryResolver) Cards(ctx context.Context, deckID string) ([]model.Card, error) {
	rows, err := r.SRS.ListCards(ctx, parseID(deckID))
	if err != nil {
		return nil, err
	}
	out := make([]model.Card, 0, len(rows))
	for _, c := range rows {
		out = append(out, cardView(c))
	}
	return out, nil
}

// DueCards is the resolver for the dueCards field.
func (r *queryResolver) DueCards(ctx context.Context, deckID string) ([]model.Card, error) {
	rows, err := r.SRS.DueCards(ctx, parseID(deckID))
	if err != nil {
		return nil, err
	}
	out := make([]model.Card, 0, len(rows))
	for _, c := range rows {
		out = append(out, cardView(c))
	}
	return out, nil
}

// DictSearch is the resolver for the dictSearch field.
func (r *queryResolver) DictSearch(ctx context.Context, q string, limit *int) ([]model.DictEntry, error) {
	rows, err := r.Content.SearchDict(ctx, q, limitOr(limit, contentDefaultLimit))
	if err != nil {
		return nil, err
	}
	return dictViews(rows), nil
}

// EnglishSearch is the resolver for the englishSearch field.
func (r *queryResolver) EnglishSearch(ctx context.Context, q string, limit *int) ([]model.EnglishEntry, error) {
	rows, err := r.Content.SearchEnglish(ctx, q, limitOr(limit, contentDefaultLimit))
	if err != nil {
		return nil, err
	}
	return enViews(rows), nil
}

// Stress trả kết quả luôn (kể cả khi từ không có trong dict) vì
// `LookupStress` có nhánn fallback quy tắc hậu tố — "không biết" là 1 kết quả
// hợp lệ, không phải lỗi. `fromDict = false` là thứ client dùng để gắn nhãn.
func (r *queryResolver) Stress(ctx context.Context, word string) (*model.StressLookup, error) {
	res, err := r.Content.LookupStress(ctx, word)
	if err != nil {
		return nil, err
	}
	return &model.StressLookup{
		Term:      res.Term,
		Ipa:       res.IPA,
		Stress:    res.Stress,
		Exception: res.Exception,
		Note:      res.Note,
		FromDict:  res.Source == contentSourceDict,
	}, nil
}

// Strokes is the resolver for the strokes field.
func (r *queryResolver) Strokes(ctx context.Context, level string, hanzi *string) (*model.StrokePayload, error) {
	h := ""
	if hanzi != nil {
		h = *hanzi
	}
	index, info, err := r.Content.GetStrokes(ctx, level, h)
	if err != nil {
		return &model.StrokePayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := &model.StrokePayload{Ok: true, Index: strokeIndexViews(index)}
	// `info` zero khi `hanzi` rỗng (chỉ xin index) hoặc khi chữ không có dữ
	// liệu — use case đã trả 404 trong trường hợp sau.
	if info.Hanzi != "" {
		out.Info = strokeInfoView(info)
	}
	return out, nil
}

// Chunk is the resolver for the chunk field.
func (r *queryResolver) Chunk(ctx context.Context, sentence string) (*model.ChunkPayload, error) {
	chunks, err := r.Content.Chunk(ctx, sentence)
	if err != nil {
		return &model.ChunkPayload{Ok: false, Error: toUserError(err)}, nil
	}
	out := &model.ChunkPayload{Ok: true, Chunks: make([]model.Chunk, 0, len(chunks))}
	for _, c := range chunks {
		out.Chunks = append(out.Chunks, model.Chunk{Text: c.Text, Kind: chunkKindOf(c.Kind)})
	}
	return out, nil
}

// GradeTone is the resolver for the gradeTone field.
func (r *queryResolver) GradeTone(ctx context.Context, expected string, answered string) (*model.GradeTonePayload, error) {
	res, err := r.Content.GradeTonePair(expected, answered)
	if err != nil {
		return &model.GradeTonePayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.GradeTonePayload{Ok: true, Grade: &model.ToneGrade{
		Grade: res.Grade,
		Score: res.Score,
		Exact: res.Exact,
		Hit:   res.Hit,
	}}, nil
}

// ThieuAxes is the resolver for the thieuAxes field.
func (r *queryResolver) ThieuAxes(ctx context.Context) ([]model.ThieuAxis, error) {
	return thieuAxesView(r.Content.ListThieuAxes()), nil
}

// ThieuSessions is the resolver for the thieuSessions field.
func (r *queryResolver) ThieuSessions(ctx context.Context) ([]model.ThieuSession, error) {
	rows, err := r.Content.ListThieu(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.ThieuSession, 0, len(rows))
	for _, s := range rows {
		out = append(out, thieuSessionView(s))
	}
	return out, nil
}

// ReaderArticles is the resolver for the readerArticles field.
func (r *queryResolver) ReaderArticles(ctx context.Context, level *string, id *string) ([]model.ReaderArticle, error) {
	rows, err := r.Content.GetReaderArticles(ctx, derefOr(level, ""), derefOr(id, ""))
	if err != nil {
		return nil, err
	}
	return readerArticleViews(rows), nil
}

// Paths is the resolver for the paths field.
func (r *queryResolver) Paths(ctx context.Context) ([]model.PathSummary, error) {
	rows, err := r.Roadmap.ListPaths(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.PathSummary, 0, len(rows))
	for _, p := range rows {
		pv := pathView(p.Path)
		out = append(out, model.PathSummary{Path: &pv, Summary: summaryView(p.Progress)})
	}
	return out, nil
}

// Path trả null khi slug không tồn tại. 404 chỉ dành cho mutation: query trả
// null là câu trả lời hợp lệ, còn mutation hỏng là hành động hỏng.
func (r *queryResolver) Path(ctx context.Context, slug string) (*model.Path, error) {
	p, err := r.Roadmap.PathBySlug(ctx, slug)
	if err != nil {
		return nil, nil
	}
	out := pathView(p)
	return &out, nil
}

// PathProgress is the resolver for the pathProgress field.
func (r *queryResolver) PathProgress(ctx context.Context, slug string, since *string) (*model.PathProgressPayload, error) {
	t, err := parseSince(derefOr(since, ""))
	if err != nil {
		return &model.PathProgressPayload{Ok: false, Error: toUserError(errBadRequest(err))}, nil
	}
	prog, err := r.Roadmap.Progress(ctx, slug, t)
	if err != nil {
		return &model.PathProgressPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.PathProgressPayload{Ok: true, Progress: progressView(prog)}, nil
}

// Stage/Topic/Resource/Milestone trả null khi id không tồn tại — xem `Path`.
// Cả 4 đi qua use case `…ByID` của application (M4 thêm), KHÔNG dựng cả cây rồi
// lọc: dựng cây để lấy 1 node là O(cây) I/O cho 1 việc O(1).
func (r *queryResolver) Stage(ctx context.Context, id string) (*model.Stage, error) {
	st, err := r.Roadmap.StageByID(ctx, parseID(id))
	if err != nil {
		return nil, nil
	}
	out := stageView(st)
	return &out, nil
}

// Topic đi qua `TopicByID` của application, vốn đã trả kèm layout + LevelState
// của CẢ stage. Resolver ghi luôn layout vào bảng bên cạnh của loader để
// `Topic.level` / `Topic.point` đọc lại được mà không query thêm — cùng cơ chế
// với `Stage.topics` (xem `Loaders.topicMeta`).
func (r *queryResolver) Topic(ctx context.Context, id string) (*model.Topic, error) {
	tv, err := r.Roadmap.TopicByID(ctx, parseID(id))
	if err != nil {
		return nil, nil
	}
	r.loaders(ctx).rememberTopic([]roadmapapp.TopicView{tv})
	out := topicView(tv.Topic)
	return &out, nil
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, id string) (*model.Resource, error) {
	res, err := r.Roadmap.ResourceByID(ctx, parseID(id))
	if err != nil {
		return nil, nil
	}
	out := resourceView(res)
	return &out, nil
}

// Milestone is the resolver for the milestone field.
func (r *queryResolver) Milestone(ctx context.Context, id string) (*model.Milestone, error) {
	m, err := r.Roadmap.MilestoneByID(ctx, parseID(id))
	if err != nil {
		return nil, nil
	}
	out := milestoneView(m)
	return &out, nil
}

// Bookmark trả null (không phải lỗi) khi id không tồn tại — cùng lý do với
// `deck(id:)`: client tự dán id là tình huống bình thường.
func (r *queryResolver) Bookmark(ctx context.Context, id string) (*model.Bookmark, error) {
	b, err := r.Roadmap.BookmarkByID(ctx, parseID(id))
	if err != nil {
		return nil, nil
	}
	out := bookmarkView(b)
	return &out, nil
}

// Bookmarks trả kho link theo bộ lọc. `status`/`tag` rỗng = không lọc.
//
// KHÔNG bọc payload `ok`+`error` như `Query.stats`: lọc sai không thể xảy ra
// từ GraphQL — `status` là enum nên gqlgen tự chặn giá trị lạ, còn `tag` chỉ có
// 1 quy tắc là quá dài. Lỗi còn lại là lỗi hệ thống, và trả null + error
// GraphQL là đúng (giống `Query.paths`).
func (r *queryResolver) Bookmarks(ctx context.Context, status *model.BookmarkStatus, tag *string) ([]model.Bookmark, error) {
	filter := roadmapapp.BookmarkFilter{Tag: derefOr(tag, "")}
	if status != nil {
		// `TO_READ` phải ghi tường minh `"to_read"` chứ không rút về `""`:
		// `""` ở `BookmarkFilter` nghĩa là KHÔNG lọc, nên gộp 2 thứ đó thì
		// lọc `status: TO_READ` trả về toàn bộ kho link — sai lặng.
		text, err := bookmarkStatusText(status)
		if err != nil {
			return nil, err
		}
		filter.Status = text
	}
	rows, err := r.Roadmap.ListBookmarks(ctx, filter)
	if err != nil {
		return nil, err
	}
	out := make([]model.Bookmark, 0, len(rows))
	for _, b := range rows {
		out = append(out, bookmarkView(b))
	}
	return out, nil
}

// ShadowProgress is the resolver for the shadowProgress field.
func (r *queryResolver) ShadowProgress(ctx context.Context, cardID string) (*model.ShadowProgress, error) {
	p, err := r.Practice.GetShadowProgress(ctx, parseID(cardID))
	if err != nil {
		return nil, err
	}
	sv := shadowView(p)
	return &sv, nil
}

// Errors is the resolver for the errors field.
func (r *queryResolver) Errors(ctx context.Context, cardID *string, limit *int) ([]model.ErrorEntry, error) {
	var card *int64
	if cardID != nil {
		v := parseID(*cardID)
		card = &v
	}
	rows, err := r.Practice.ListErrors(ctx, card, limitOr(limit, practiceDefaultErrorLimit))
	if err != nil {
		return nil, err
	}
	return errorEntryViews(rows), nil
}

// TopErrors is the resolver for the topErrors field.
func (r *queryResolver) TopErrors(ctx context.Context, limit *int) ([]model.TopErrorCount, error) {
	rows, err := r.Practice.TopErrors(ctx, limitOr(limit, practiceDefaultErrorLimit))
	if err != nil {
		return nil, err
	}
	return topErrorViews(rows), nil
}

// ErrorSuggestions is the resolver for the errorSuggestions field.
func (r *queryResolver) ErrorSuggestions(ctx context.Context, limit *int) ([]model.CardErrorCount, error) {
	rows, err := r.Practice.SuggestErrorsFromErrors(ctx, limitOr(limit, practiceDefaultErrorLimit))
	if err != nil {
		return nil, err
	}
	return cardErrorViews(rows), nil
}

// Diff is the resolver for the diff field.
func (r *queryResolver) Diff(ctx context.Context, sample string, transcript string) (*model.DiffPayload, error) {
	res, err := r.Practice.DiffAgainstSample(sample, transcript)
	if err != nil {
		return &model.DiffPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.DiffPayload{Ok: true, Result: diffView(res)}, nil
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context, rangeArg *string) (*model.StatsPayload, error) {
	s, err := r.Insight.Stats(ctx, derefOr(rangeArg, ""))
	if err != nil {
		return &model.StatsPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.StatsPayload{Ok: true, Stats: statsView(s)}, nil
}

// Streak không nhận tham số `now`: client không được chọn mốc. `ComputeStreak`
// nhận `now` để test được, nhưng nếu lộ ra ngoài thì 1 máy lệch giờ sẽ tự
// báo streak ảo. Mốc luôn là UTC hôm nay của server.
func (r *queryResolver) Streak(ctx context.Context) (int, error) {
	return r.Insight.ComputeStreak(ctx, nowUTC())
}

// InsightTopErrors is the resolver for the insightTopErrors field.
func (r *queryResolver) InsightTopErrors(ctx context.Context, limit *int) (*model.TopErrorsPayload, error) {
	rows, err := r.Insight.TopErrors(ctx, limitOr(limit, insightDefaultTopErrors))
	if err != nil {
		return &model.TopErrorsPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.TopErrorsPayload{Ok: true, Errors: insightTopErrorViews(rows)}, nil
}

// ProgressOverRange is the resolver for the progressOverRange field.
func (r *queryResolver) ProgressOverRange(ctx context.Context, since string) (*model.ProgressResultPayload, error) {
	res, err := r.Insight.ProgressOverRange(ctx, since)
	if err != nil {
		return &model.ProgressResultPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.ProgressResultPayload{Ok: true, Result: &model.ProgressResult{
		Since:     res.Since,
		Completed: res.Completed,
	}}, nil
}

// SyncStatus is the resolver for the syncStatus field.
func (r *queryResolver) SyncStatus(ctx context.Context) (*model.SyncStatusPayload, error) {
	s, err := r.Sync.Status(ctx)
	if err != nil {
		return &model.SyncStatusPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.SyncStatusPayload{Ok: true, Status: syncStatusView(s)}, nil
}

// SyncConflicts is the resolver for the syncConflicts field.
func (r *queryResolver) SyncConflicts(ctx context.Context, limit *int) (*model.SyncConflictsPayload, error) {
	rows, err := r.Sync.Conflicts(ctx, limitOr(limit, syncDefaultConflictLimit))
	if err != nil {
		return &model.SyncConflictsPayload{Ok: false, Error: toUserError(err)}, nil
	}
	return &model.SyncConflictsPayload{Ok: true, Conflicts: conflictViews(rows)}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
