// audio.proto — hợp đồng giữa app chính (internal/infrastructure/audio) và tiến
// trình `services/audio-service` (Piper TTS + Whisper sidecar).
//
// Vì sao gRPC ở đây mà không phải interface trong 1 process: Piper là binary
// ngoài (Python wheel 752MB) và Whisper là sidecar 8GB. Chúng đã là 2 tiến
// trình riêng trong v1; M4 chỉ đổi cách app nói chuyện với chúng từ
// `os/exec` + HTTP client sang 1 giao thức có version, có timeout, có
// healthcheck và có ranh giới service thật (STACK-V2-PLAN §2).
//
// Sinh code: `go generate ./proto/...` (xem buf.gen.yaml). KHÔNG sửa tay file
// `.pb.go` — chạy lại buf là bản tái lập được.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: audio/v1/audio.proto

package audiopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Audio_Synthesize_FullMethodName       = "/audio.v1.Audio/Synthesize"
	Audio_Transcribe_FullMethodName       = "/audio.v1.Audio/Transcribe"
	Audio_StreamSynthesize_FullMethodName = "/audio.v1.Audio/StreamSynthesize"
)

// AudioClient is the client API for Audio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioClient interface {
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error)
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
	StreamSynthesize(ctx context.Context, in *StreamSynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
}

type audioClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioClient(cc grpc.ClientConnInterface) AudioClient {
	return &audioClient{cc}
}

func (c *audioClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesizeResponse)
	err := c.cc.Invoke(ctx, Audio_Synthesize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, Audio_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioClient) StreamSynthesize(ctx context.Context, in *StreamSynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Audio_ServiceDesc.Streams[0], Audio_StreamSynthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSynthesizeRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Audio_StreamSynthesizeClient = grpc.ServerStreamingClient[Chunk]

// AudioServer is the server API for Audio service.
// All implementations should embed UnimplementedAudioServer
// for forward compatibility.
type AudioServer interface {
	Synthesize(context.Context, *SynthesizeRequest) (*SynthesizeResponse, error)
	Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error)
	StreamSynthesize(*StreamSynthesizeRequest, grpc.ServerStreamingServer[Chunk]) error
}

// UnimplementedAudioServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioServer struct{}

func (UnimplementedAudioServer) Synthesize(context.Context, *SynthesizeRequest) (*SynthesizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedAudioServer) Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedAudioServer) StreamSynthesize(*StreamSynthesizeRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method StreamSynthesize not implemented")
}
func (UnimplementedAudioServer) testEmbeddedByValue() {}

// UnsafeAudioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServer will
// result in compilation errors.
type UnsafeAudioServer interface {
	mustEmbedUnimplementedAudioServer()
}

func RegisterAudioServer(s grpc.ServiceRegistrar, srv AudioServer) {
	// If the following call panics, it indicates UnimplementedAudioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Audio_ServiceDesc, srv)
}

func _Audio_Synthesize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServer).Synthesize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Audio_Synthesize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServer).Synthesize(ctx, req.(*SynthesizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Audio_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Audio_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServer).Transcribe(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Audio_StreamSynthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioServer).StreamSynthesize(m, &grpc.GenericServerStream[StreamSynthesizeRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Audio_StreamSynthesizeServer = grpc.ServerStreamingServer[Chunk]

// Audio_ServiceDesc is the grpc.ServiceDesc for Audio service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Audio_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.v1.Audio",
	HandlerType: (*AudioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Synthesize",
			Handler:    _Audio_Synthesize_Handler,
		},
		{
			MethodName: "Transcribe",
			Handler:    _Audio_Transcribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSynthesize",
			Handler:       _Audio_StreamSynthesize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "audio/v1/audio.proto",
}
