// audio.proto — hợp đồng giữa app chính (internal/infrastructure/audio) và tiến
// trình `services/audio-service` (Piper TTS + Whisper sidecar).
//
// Vì sao gRPC ở đây mà không phải interface trong 1 process: Piper là binary
// ngoài (Python wheel 752MB) và Whisper là sidecar 8GB. Chúng đã là 2 tiến
// trình riêng trong v1; M4 chỉ đổi cách app nói chuyện với chúng từ
// `os/exec` + HTTP client sang 1 giao thức có version, có timeout, có
// healthcheck và có ranh giới service thật (STACK-V2-PLAN §2).
//
// Sinh code: `go generate ./proto/...` (xem buf.gen.yaml). KHÔNG sửa tay file
// `.pb.go` — chạy lại buf là bản tái lập được.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: audio/v1/audio.proto

package audiopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SynthesizeRequest yêu cầu đọc 1 đoạn văn bản.
// `lang` là gợi ý chọn voice (zh/en) — server bỏ qua lang và dùng voice mặc
// định khi không khớp, KHÔNG phải lỗi (giữ hành vi v1 của PiperTTSEngine).
type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_audio_v1_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_v1_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_audio_v1_audio_proto_rawDescGZIP(), []int{0}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// SynthesizeResponse trả WAV bytes trong `audio` (không base64) vì gRPC
// chịu được binary thô; base64 ở đây là +33% payload vô nghĩa.
type SynthesizeResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Audio       []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	ContentType string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Engine là tên engine thật sự xử lý ("piper" | "stub"), để app gắn header
	// X-Engine mà không phải tự suy ra.
	Engine        string `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	Real          bool   `protobuf:"varint,4,opt,name=real,proto3" json:"real,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResponse) Reset() {
	*x = SynthesizeResponse{}
	mi := &file_audio_v1_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResponse) ProtoMessage() {}

func (x *SynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_v1_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_audio_v1_audio_proto_rawDescGZIP(), []int{1}
}

func (x *SynthesizeResponse) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *SynthesizeResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SynthesizeResponse) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *SynthesizeResponse) GetReal() bool {
	if x != nil {
		return x.Real
	}
	return false
}

// TranscribeRequest mang audio thô + tên/kiểu để engine đoán định dạng
// (wav vs m4a vs webm).
type TranscribeRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Audio       []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Filename    string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Lang là gợi ý ("zh"/"en"); rỗng = để engine tự nhận dạng.
	Lang          string `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_audio_v1_audio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_v1_audio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_audio_v1_audio_proto_rawDescGZIP(), []int{2}
}

func (x *TranscribeRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *TranscribeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TranscribeRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TranscribeRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// WordTimestamp là 1 từ kèm mốc thời gian. Mọi trường optional vì Whisper
// sidecar có lúc trả, có lúc không (v1 cũng vậy).
type WordTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Start         *float64               `protobuf:"fixed64,2,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *float64               `protobuf:"fixed64,3,opt,name=end,proto3,oneof" json:"end,omitempty"`
	Confidence    *float64               `protobuf:"fixed64,4,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordTimestamp) Reset() {
	*x = WordTimestamp{}
	mi := &file_audio_v1_audio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordTimestamp) ProtoMessage() {}

func (x *WordTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_audio_v1_audio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordTimestamp.ProtoReflect.Descriptor instead.
func (*WordTimestamp) Descriptor() ([]byte, []int) {
	return file_audio_v1_audio_proto_rawDescGZIP(), []int{3}
}

func (x *WordTimestamp) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordTimestamp) GetStart() float64 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *WordTimestamp) GetEnd() float64 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

func (x *WordTimestamp) GetConfidence() float64 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

type TranscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Words         []*WordTimestamp       `protobuf:"bytes,3,rep,name=words,proto3" json:"words,omitempty"`
	Confidence    *float64               `protobuf:"fixed64,4,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Engine        string                 `protobuf:"bytes,5,opt,name=engine,proto3" json:"engine,omitempty"`
	Real          bool                   `protobuf:"varint,6,opt,name=real,proto3" json:"real,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_audio_v1_audio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_v1_audio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_audio_v1_audio_proto_rawDescGZIP(), []int{4}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeResponse) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *TranscribeResponse) GetWords() []*WordTimestamp {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *TranscribeResponse) GetConfidence() float64 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *TranscribeResponse) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *TranscribeResponse) GetReal() bool {
	if x != nil {
		return x.Real
	}
	return false
}

// StreamSynthesizeRequest giống SynthesizeRequest — có riêng để client
// chọn đường streaming (STACK-V2-PLAN §3: GraphQL không có streaming binary).
type StreamSynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSynthesizeRequest) Reset() {
	*x = StreamSynthesizeRequest{}
	mi := &file_audio_v1_audio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSynthesizeRequest) ProtoMessage() {}

func (x *StreamSynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_v1_audio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSynthesizeRequest.ProtoReflect.Descriptor instead.
func (*StreamSynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_audio_v1_audio_proto_rawDescGZIP(), []int{5}
}

func (x *StreamSynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StreamSynthesizeRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// Chunk là 1 mảnh WAV. `last = true` ở mảnh cuối để client biết đã hết.
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_audio_v1_audio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_audio_v1_audio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_audio_v1_audio_proto_rawDescGZIP(), []int{6}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

var File_audio_v1_audio_proto protoreflect.FileDescriptor

const file_audio_v1_audio_proto_rawDesc = "" +
	"\n" +
	"\x14audio/v1/audio.proto\x12\baudio.v1\";\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"y\n" +
	"\x12SynthesizeResponse\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\x12\x12\n" +
	"\x04real\x18\x04 \x01(\bR\x04real\"|\n" +
	"\x11TranscribeRequest\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04lang\x18\x04 \x01(\tR\x04lang\"\x9b\x01\n" +
	"\rWordTimestamp\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x19\n" +
	"\x05start\x18\x02 \x01(\x01H\x00R\x05start\x88\x01\x01\x12\x15\n" +
	"\x03end\x18\x03 \x01(\x01H\x01R\x03end\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01H\x02R\n" +
	"confidence\x88\x01\x01B\b\n" +
	"\x06_startB\x06\n" +
	"\x04_endB\r\n" +
	"\v_confidence\"\xcb\x01\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12-\n" +
	"\x05words\x18\x03 \x03(\v2\x17.audio.v1.WordTimestampR\x05words\x12#\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01H\x00R\n" +
	"confidence\x88\x01\x01\x12\x16\n" +
	"\x06engine\x18\x05 \x01(\tR\x06engine\x12\x12\n" +
	"\x04real\x18\x06 \x01(\bR\x04realB\r\n" +
	"\v_confidence\"A\n" +
	"\x17StreamSynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"/\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x02 \x01(\bR\x04last2\xe3\x01\n" +
	"\x05Audio\x12G\n" +
	"\n" +
	"Synthesize\x12\x1b.audio.v1.SynthesizeRequest\x1a\x1c.audio.v1.SynthesizeResponse\x12G\n" +
	"\n" +
	"Transcribe\x12\x1b.audio.v1.TranscribeRequest\x1a\x1c.audio.v1.TranscribeResponse\x12H\n" +
	"\x10StreamSynthesize\x12!.audio.v1.StreamSynthesizeRequest\x1a\x0f.audio.v1.Chunk0\x01B Z\x1elangapp/proto/audio/v1;audiopbb\x06proto3"

var (
	file_audio_v1_audio_proto_rawDescOnce sync.Once
	file_audio_v1_audio_proto_rawDescData []byte
)

func file_audio_v1_audio_proto_rawDescGZIP() []byte {
	file_audio_v1_audio_proto_rawDescOnce.Do(func() {
		file_audio_v1_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_v1_audio_proto_rawDesc), len(file_audio_v1_audio_proto_rawDesc)))
	})
	return file_audio_v1_audio_proto_rawDescData
}

var file_audio_v1_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_audio_v1_audio_proto_goTypes = []any{
	(*SynthesizeRequest)(nil),       // 0: audio.v1.SynthesizeRequest
	(*SynthesizeResponse)(nil),      // 1: audio.v1.SynthesizeResponse
	(*TranscribeRequest)(nil),       // 2: audio.v1.TranscribeRequest
	(*WordTimestamp)(nil),           // 3: audio.v1.WordTimestamp
	(*TranscribeResponse)(nil),      // 4: audio.v1.TranscribeResponse
	(*StreamSynthesizeRequest)(nil), // 5: audio.v1.StreamSynthesizeRequest
	(*Chunk)(nil),                   // 6: audio.v1.Chunk
}
var file_audio_v1_audio_proto_depIdxs = []int32{
	3, // 0: audio.v1.TranscribeResponse.words:type_name -> audio.v1.WordTimestamp
	0, // 1: audio.v1.Audio.Synthesize:input_type -> audio.v1.SynthesizeRequest
	2, // 2: audio.v1.Audio.Transcribe:input_type -> audio.v1.TranscribeRequest
	5, // 3: audio.v1.Audio.StreamSynthesize:input_type -> audio.v1.StreamSynthesizeRequest
	1, // 4: audio.v1.Audio.Synthesize:output_type -> audio.v1.SynthesizeResponse
	4, // 5: audio.v1.Audio.Transcribe:output_type -> audio.v1.TranscribeResponse
	6, // 6: audio.v1.Audio.StreamSynthesize:output_type -> audio.v1.Chunk
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_audio_v1_audio_proto_init() }
func file_audio_v1_audio_proto_init() {
	if File_audio_v1_audio_proto != nil {
		return
	}
	file_audio_v1_audio_proto_msgTypes[3].OneofWrappers = []any{}
	file_audio_v1_audio_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_v1_audio_proto_rawDesc), len(file_audio_v1_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_v1_audio_proto_goTypes,
		DependencyIndexes: file_audio_v1_audio_proto_depIdxs,
		MessageInfos:      file_audio_v1_audio_proto_msgTypes,
	}.Build()
	File_audio_v1_audio_proto = out.File
	file_audio_v1_audio_proto_goTypes = nil
	file_audio_v1_audio_proto_depIdxs = nil
}
